### ISSUE TITLE
Add beer then remove still tap???

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#100]
I added a beer to my beers then deleted it and then I went to the my taps page and tapped a new beer and in the dropdown that beer was stil an option as a beer I could tap

**Comment by EmDubeu** [comment]
Skemp45 - Thadius mentioned you could set me up with some install
instructions so I could help out with some testing. I have all the hardware
setup with Noobs ready. Just need you'alls awesome code.

Emdubeu (Mike)

On Wed, Feb 5, 2014 at 1:33 PM, Skemp45 notifications@github.com wrote:

> I added a beer to my beers then deleted it and then I went to the my taps
> page and tapped a new beer and in the dropdown that beer was stil an option
> as a beer I could tap
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/100
> .

## 

Mike Wright

**Comment by thadius856** [comment]
Yerp. Can you give him at least view on /byo/?

**Comment by JayUnt** [comment]
bug fixed and committed
