### ISSUE TITLE
HBT Thread: Stay or Go?

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#101]
We need to talk about the direction of this project and where we want it to go with regards to HBT. 

I reached out to the owner, TxBrew, for their official stance on affiliate links. His response was that we can't have any affiliate links on our website if we link to it.

I asked him for clarification on if a Donate button would be acceptable. Here's his response:

> You cannot solicit the community in any way without being involved in the Sponsor programs. 
> 
> If you would like more information please let me know. Many, many sponsors find it quite lucrative. 
> 
> Thanks!

I have to assume the Sponsor Membership costs more than the Lifetime Membership ($150) and has a shorter duration. I accidentally inquired about their advertising prices instead, and the answer was that single banner ad was $150/mo with a two month minimum. That should give you an ballpark of how much it's going to cost. Clearly, this is way out of our ballpark.

We're at the point where we need to decide if we want to:
1. Continue a project thread on HBT without donations or referrals of any sort.
2. Remove our thread on HBT and add a donate button to the website.

As much as it pains me to say it, I'm personally leaning towards #2 because HBT on gets us more eyeballs. We could easily do the same with SEO and word of mouth.

What do you guys think? I'm not going to make any changes without the majority in support.

**Comment by kerber** [comment]
It might just be because I don't have hosting costs tied up in it, but I don't see the need for any referral links or 'solicitation' besides a donate button somewhere on our site. If people want to donate, that's great. They just don't want us going into threads and talking about our project and donations here and there. I would think we'd be perfectly fine just keeping the project thread active, as long as we don't ask for donations or talk about them.

Right now, we're getting a lot of traction from HBT and, once the eyeballs make it to our site, they can see the donate button on their own.

**Comment by kerber** [comment]
If we want to link to the hardware or such from the site, let's just link and not use referrals. I doubt they are going to net enough for the project to constitute the loss of views.

**Comment by thadius856** [comment]
I removed referrals in Day 2. We had at least 1 purchase of ~$100, so that
would have been 4-6%. Amazon flogged the dog and ate the referral though.

**Comment by thadius856** [comment]
> They just don't want us going into threads and talking about our project and donations here and there.

I would think that's the case, but I don't interpret the above that way. Here's what I sent:

> Tx,
> 
> We removed the affiliate links. We're just linking to a tutorial with plain links to Amazon. We're giving away everything for free and we don't sell anything.
> 
> Several members here are asking us to put up a donate link on our website. Is that kosher for us to do, or will we have to remove our threads here to do so?
> 
> Thad

I can inquire again if you're still thinking that's what they meant.

**Comment by EmDubeu** [comment]
Remove the thread on HBT and add a donate button to the website.

On Wed, Feb 5, 2014 at 6:05 PM, thadius856 notifications@github.com wrote:

> They just don't want us going into threads and talking about our project
> and donations here and there.
> 
> I would think that's the case, but I don't interpret the above that way.
> Here's what I sent:
> 
> Tx,
> 
> We removed the affiliate links. We're just linking to a tutorial with
> plain links to Amazon. We're giving away everything for free and we don't
> sell anything.
> 
> Several members here are asking us to put up a donate link on our website.
> Is that kosher for us to do, or will we have to remove our threads here to
> do so?
> 
> Thad
> 
> I can inquire again if you're still thinking that's what they meant.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/101#issuecomment-34285144
> .

## 

Mike Wright

**Comment by kerber** [comment]
It's unclear as to whether he means that the donate button is solicitation or whether he doesn't want us making a big deal about donating on HBT. I guess I don't know the guy well enough to know whether he's just being really draconian or just unclear - especially with something as harmless as a donate button.

**Comment by thadius856** [comment]
Sent PM for clarification. We'll see.

**Comment by Skemp45** [comment]
Ok,

So here is what I have wanted from day 1 with this project, for all home brewers to enjoy and use and HBT is the best place for them to find it. I am not worried about domain and hosting fees as it's not much as I said $30 at most per year no big deal. But if txbrew says it's cool let's add the donate button because the more hardware we an afford the better program we can make and the better experience for out end users.

**Comment by kerber** [comment]
I agree with Skemp.

**Comment by Boombrewer** [comment]
I agree with Skemp too.

**Comment by JayUnt** [comment]
As long as Skemp doesn't mind the hosting and domain, lets stay on HBT.

**Comment by Skemp45** [comment]
Yeah, I have no problem eating the cost of domain and hosting. FOR SCIENCE!!!!!

**Comment by thadius856** [comment]
The official response is in.

Sent:

```
We're nothing trying to ask for donations on your site. The question is: can we have a donate button on our website (assuming we don't direct users here to the button)?

Also, can you clue us into sponsor rates?
```

Received:

```
I understood your question. If you add a donate button you are soliciting the community, and that requires a sponsor membership. UIt has to be that way or everyone with a pet project would ask for money. 

If you'll send me your full name and email address I would be happy to have some info sent out. 

Thanks!
```

**Comment by mtnbound** [comment]
Based on the response, it sounds like we're all in agreement. Stay on HBT, and ditch the Donate button. I'll be happy to chip in for the domain and hosting if needed.

**Comment by kerber** [comment]
From what I can tell, the HBT thread still links to a page with referral links. [This post](http://www.homebrewtalk.com/f51/initial-release-raspberrypints-digital-taplist-solution-456809/#post5866692) links to [this RPints page](http://raspberrypints.com/site/byo/preparation/) which has links.

**Comment by thadius856** [comment]
Those are vanilla links. I removed our referral ID from them.
