### ISSUE TITLE
Beer Tab Style Drop down menu repetitive

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#106]
![image](https://f.cloud.github.com/assets/6321429/2099824/337aeec6-8f41-11e3-87ba-42deb28a5d82.png)

This is with the latest code just pulled down this morning (in one big zip so everything is new as Joe would be getting it)

**Comment by Boombrewer** [comment]
@Thad, for some reason I can't add labels anymore when I create a new issue.  I know you wanted these listed as bugs - I swear I'm not being lazy.

**Comment by thadius856** [comment]
Ah. Remind me to fix your permissions  tonight.

**Comment by Skemp45** [comment]
Added the labels for you

**Comment by thadius856** [comment]
I'm a little confused. What does the title have to do with this issue?

**Comment by Boombrewer** [comment]
Nothing.  Wrong picture.
![image](https://f.cloud.github.com/assets/6321429/2105947/a70b6328-8f98-11e3-806a-512955726fba.png)

That should help.  My mistake.

**Comment by JayUnt** [comment]
Did you drop your raspberrypints scheme before rerunning the new stuff? It's possible the table didn't get emptied and then you re-inserted the test data again.

**Comment by thadius856** [comment]
Oh, I see the problem. I think. It's pulling `category` instead of `name` from beerStyles table.

Each category has several styles. That's kinda the point of the hierarchy.

**Comment by thadius856** [comment]
admin/beer_form.php, Line 91 is the troublemaker.

```
                    <?php echo $htmlHelper->ToSelectList("beerStyleId", $beerStyleList, "name", "id", $beer->get_beerStyleId(), "Select One"); ?>
```

**Comment by Boombrewer** [comment]
Fixed.  Just loaded the latest update.

![image](https://f.cloud.github.com/assets/6321429/2110924/7a7faa5e-900a-11e3-8e30-2b31e3c5bb0e.png)

**Comment by jkurl** [comment]
Boombrewer,

Send me a email at klinklotus@gmail.com so I can get you my address for
those cards.
