### ISSUE TITLE
IRC Channel - Now Exists!

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#108]
Sorry for taking a while.

Anybody interested communicating via IRC is welcome to join me on irchighway, #raspberrypints.

**Comment by thadius856** [comment]
I saw Jkurl and Jerry pop into the channel while I was asleep. Sry, guys.

Seems I wasn't clear above. Details:

Server: irc.irchighway.net
Channel: #raspberrypints

**Comment by thadius856** [comment]
We really need to keep on-topic in these issues... we keep veering off and it's hard to find the proper issue later.

Edit: Removed off-topic posts.

**Comment by thadius856** [comment]
Sorry I haven't been in IRC the last couple days.

Definitely in tonight, if anybody wants to talk.

**Comment by Skemp45** [comment]
Please see https://github.com/RaspberryPints/RaspberryPints/wiki/IRC-Channel

**Comment by thadius856** [comment]
In IRC right now, if anybody needs to talk.

Added it to my Startup folder and configured on-connect, so should be in there most times when I'm not at work.
