### ISSUE TITLE
No kegs in tap drop down list

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#109]
I installed the new code tonight and did not install any test data, so I started with a blank database.

I added a beer, added a keg, but when I went to add a beer to a tap, no kegs showed up in the list.

I always add the test data, so I'm not sure if I'm just missing something.

**Comment by thadius856** [comment]
What was the keg's status?

**Comment by mtnbound** [comment]
Serving, and the active flag was set to 1 in the DB. I was too tired to debug it last night, so I thought I would create it in case someone else had time to take a look.

**Comment by thadius856** [comment]
Unless something changed, we purposely hid serving kegs from the list so
you couldnt put the same keg on multiple taps accidentally.

**Comment by mtnbound** [comment]
You're right. the statement going to the DB is:
SELECT \* FROM kegs WHERE active = 1 AND kegStatusCode != 'SERVING' AND kegStatusCode != 'SANITIZED' AND kegStatusCode != 'NEEDS_CLEANING' AND kegStatusCode != 'NEEDS_PARTS' AND kegStatusCode != 'NEEDS_REPAIRS' AND kegStatusCode != 'FLOODED' ORDER BY label

So you're not showing almost every status. Any reason why? I don't really need keg status tracking, so can I just leave it to some generic status and not mess with it?

**Comment by thadius856** [comment]
We were discussing removing all except serving, needs repairs, needs parts.

**Comment by thadius856** [comment]
I suppose alternatively we could add a "Do Not Track" status?

**Comment by mtnbound** [comment]
That might be the best way. We've talked about making this really customizable, and this would be a good way to do it. that way, if someone wants that they can keep it, and if not they can turn it off.

It would be simple to just check for the option before the SQL statement, and remove the where clause if it's not being used. I might get a chance to look at it today.

I'm traveling for work starting tomorrow morning, so I won't be able to work too much on this after today until Tue, unless I get bored in the hotel.

**Comment by mtnbound** [comment]
I'll close this since it's not a bug, and open an enhancement issue for the configuration.
