### ISSUE TITLE
Page Header Not V-Aligned

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#11]
During the CSV->SQL conversion/CSS cleanup, some items lost proper alignment.

In particular, the page header is no longer v-aligned. See screenshot: 

![untitled](https://f.cloud.github.com/assets/6320180/1866148/ebf0eb48-7828-11e3-9822-7faf3289dd29.png)

**Comment by Skemp45** [comment]
So you are just looking to drop this lower? as if the bottom of your screen shot was the base for all 3 headers?

**Comment by thadius856** [comment]
Yep, drop lower.

The left and right elements appear to be vertically centered. Was hoping for something similar here.

**Comment by Skemp45** [comment]
![taplist](https://f.cloud.github.com/assets/6318869/1875071/cf34bd14-78e5-11e3-820a-0487517083ed.png)

**Comment by Skemp45** [comment]
Mine is not displaying the same, this may be because Mine is month day year time instead of day of week month day year

**Comment by thadius856** [comment]
Hrm. Odd. My date/time moved up to the corner to match yours. o.O

Trying to snag a deal on Dell Outlets. Be with you shortly.

**Comment by Skemp45** [comment]
Thoughts on this Thad?

**Comment by thadius856** [comment]
Sure thing. I had a deal alert set for a Dell U3014 monitor. Deal alert went off, I refreshed the page like mad hoping for one, ended up buying 3. Wooooot! :) Normally $1200 ea, paid $656 +tax ea.

**Comment by thadius856** [comment]
Hehe. No, but really, no idea why this is like it.

I'm guessing the header div should be set to display: table; the "Beers on Tap" section set to display:table-row; and then a new sub div created with display:table-cell; vertical-align: middle;

Just a guess.

**Comment by Skemp45** [comment]
height:100px; which it did not need to be set to so I changed it to height:50px; and then added some padding from the top   padding-top:50px; and boom 
![titlefix](https://f.cloud.github.com/assets/6318869/1885264/b146ebf0-79c7-11e3-83e0-78bf87b46e6a.png)

**Comment by Skemp45** [comment]
just need to work on the dashed borders but that is being addressed in #13

**Comment by Skemp45** [comment]
I will create a pull request after #25 is resolved and I can grab those files and make my changes

**Comment by JayUnt** [comment]
Not too beat a dead horse, but of you are going to make the header a display: table-cell, why not make the whole thing just a table. We would be having any of these border issues or width issues of we use a table.

If you guys want, after I do the keg image, I can convert it to a table so you guys could see how much cleaner with less code it would be with a table. If not, I'll drop it and not mention it again.

**Comment by Skemp45** [comment]
If you want to put it all in a table in your fork I say why not, lets see how it looks/works and if its better we should use it. I am all for making it easier and more efficient
