### ISSUE TITLE
Add Seltzer Water to Style pulldown when adding a new beer

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#110]
Need to add a Seltzer Water option to the Style pulldown when adding a new beer.

**Comment by thadius856** [comment]
Ok, we'll add it do now as a stop gap.

Really we should move towards a list of non-beer beverage types with a
separate table/page.

Good place to brainstorm here. I'll get it started:

Beer
Wine
Kombucha
Tea
Coffee
Water
Juice
Drink

What else?

**Comment by JayUnt** [comment]
How were you thinking we would allow them to add a non-beer drink to a tap?  Would they have to put a "beer recipe" in for the soda or would there be a different section?  Would the tap have a "tap a beer" and a "tap a soda" button?  Or would we just mix the non-beers and the sodas everywhere?

If we are going to mix them everywhere, i would suggest we just put the non-beer styles in the beerStyles table with a category of 'Non-alcoholic' or something like that.  Thats what i was initially thinking about them. The user would add a recipe for a soda, not fill out the ibu, og, fg. But fill the srm with a color (like red for fruit punch).  Then when they go to tap a keg, they just select the fruit punch "beer" from the list.

**Comment by Skemp45** [comment]
Yeah, Jason I like your thinking here. if set to Non Alcoholic then remove field for ibu og fg

**Comment by thadius856** [comment]
I've added Seltzer Water, plus all of the above, to the beerStyles table.

They're prefixed with an underscore, so they should fall to the bottom of the dropdown list.

I did not add a method for hiding the values on the front page yet.

**Comment by thadius856** [comment]
Note, this really feels like a bandaid.

**Comment by JayUnt** [comment]
To make it less of a bandaid, we can rename beers to drinks.  We can also rename beerStyles to drink styles.  When creating a drink, we could only show a type dropdown at first (beer, kimbucha, soda, juice, seltzer).  After they select that, we then show the appropriate fields for that type.  But in the end, they are stored in the same database.  

Or we just have a flag in the style table for alcoholic vs non-alcoholic, which would determine which form to show. But the idea is to show only the style and then show the rest of the form after they select a value.

**Comment by thadius856** [comment]
Agree, ideally only the applicable fields should show if you pick a type from the dropdown.

Beyond my skillage, tho.

**Comment by JayUnt** [comment]
I'm assuming this is a version 2 feature, right?  If not, ilk work I it sooner.

**Comment by thadius856** [comment]
I think having the option in the list is a v1 feature. I already did it.

We can probably wait til v2 for the special dropdown form building.
