### ISSUE TITLE
Saving Preferences

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#111]
Is anyone else having an issue with saving the preferences? I'm getting an error on line 13 and 14 of the update_columns.php page. It looks like it's saving, but I didn't know if it was causing issues down the line.

Also, just so we don't have merge issues. Line 72 of the personalize.php page needs the full <?php tag.

I'm running on my WAMP testing environment with display errors on.

**Comment by sevlabs** [comment]
This same thing happened to me last week and it turned out to be a setup issue. After I dropped the raspberrypints DB and did a clean install it started saving my preferences correctly.

**Comment by mtnbound** [comment]
hmm. Thought I did that, but I'll try again to make sure.

I found it by adding a new configuration value, so I thought I blew it up, but it seemed to exist in the master branch as well.

**Comment by Skemp45** [comment]
fixed the <? tag on line 72 nice catch

**Comment by thadius856** [comment]
Been turning columns on and off all night successfully.

Anybody able to reproduce?

**Comment by Boombrewer** [comment]
It worked fine for me all last night and I was actively trying to break it and my display.  Everything saved fine (except the apostrophe).

**Comment by mtnbound** [comment]
It's not that it doesn't save, but when I turn my error handling on it displays an error on save_columns.php on line 13 and 14. Just wanted to make sure it wasn't breaking something else.

Sent from Yahoo Mail on Android

**Comment by thadius856** [comment]
Here's those lines.

```
$name=$_POST['id'];
$config_Value=$_POST['configValue'];
```

I don't have any clue about them, tbh.

**Comment by thadius856** [comment]
Nobody seems to see anything wrong with those lines.

Closing as non-issue.
