### ISSUE TITLE
Show ABV image column doesn't apply to empty taps

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#112]
When I change the preference to not show the ABV column, and I have an open tap, the graphic still shows.

Environment: WAMP
Browser: Firefox

**Comment by Skemp45** [comment]
Screen shot

**Comment by sevlabs** [comment]
I was able to replicate this error. I'll work on fixing this.

![2014-02-07_140832](https://f.cloud.github.com/assets/6545107/2113322/6fcf2e4c-902b-11e3-883a-3a0e3269113b.jpg)

**Comment by Skemp45** [comment]
ok, ty

**Comment by thadius856** [comment]
> When I change the preference to not show the ABV column,

I assume you meant to say when you try to turn off the ABV image?

**Comment by thadius856** [comment]
There's 2 problems going on here.

One is `index.php` line 191:

```
<?php if(($config[ConfigNames::ShowAbvCol]) && ($config[ConfigNames::ShowAbvImage])){ ?>
```

`ShowAbvImage` doesn't exist. `ShowAbvImg` does.

When I fix that, the image stays and we get breakage like there's div hanging open somewhere.

Will keep digging.

**Comment by thadius856** [comment]
Looks like `ShowAbvImage` does exist, but only because it's bandaided in `config_names.php`.

Fixing and will push to `develop` branch momentarily.

The bigger issue above still exists.

**Comment by sevlabs** [comment]
Not sure what you mean by bandaided in config_names.php. Are all of the other configuration items in config_names.php bandaids as well? I was planning to review this over the weekend but I won't if you are working on it. (only to avoid duplicate efforts)

**Comment by thadius856** [comment]
No, you misunderstand me. The line in `config_names.php` looked like:

`const ShowAbvImage = 'showAbvImg';`

Somebody (may or may not be you) had fixed the naming convention on one side, but not the other.

So I changed `ShowAbvImage` to `ShowAbvImg` and updated `index.php` to reflect that.

**Comment by thadius856** [comment]
I tried to fix this issue, but my mind is having trouble wrapping around why the image is still drawing. I added debug code and tried to pinpoint it, but it defeated me.

By all means, go ahead. I don't plan to revisit this one today.

**Comment by sevlabs** [comment]
I updated index.php to resolve the ABV image showing on empty tap issue. I also updated styles.css to center the SRM, IBU, and KEG data elements. I will try to upload these updates to the development branch momentarily.

![2014-02-09_125026](https://f.cloud.github.com/assets/6545107/2120482/982a8a58-91b6-11e3-899a-efe397fa08da.jpg)

**Comment by thadius856** [comment]
Schweet! :)

**Comment by thadius856** [comment]
Tested. Closing as fixed.
