### ISSUE TITLE
Admin Logo Link No Worky

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#113]
I added a Admin Logo. Now when I click on the logo in the left navigation panel it takes me to "192.168.0.252" and not "192.168.0.252/index.php.

I changed the logo to something else, and the same problem occurred. 

In the end, it would be good to provide an option to remove logo as there is only an option to add a logo.

Added a Admin Logo:
![image](https://f.cloud.github.com/assets/6434553/2112578/cbb0d874-9020-11e3-97ec-5634d0fa3319.png)

Clicking on this logo results in whammy...
![image](https://f.cloud.github.com/assets/6434553/2112587/e541d0ae-9020-11e3-820f-760b8bd75479.png)

**Comment by Skemp45** [comment]
```
<div class="user">
    <a href="../index.php"><img src="img/logo.png" width="120" height="120" class="hoverimg" alt="Avatar" /></a>
</div>
```

Fixed the redirect option so it grabs the index.
