### ISSUE TITLE
Adding Taplist Logo results in error

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#114]
When I attempt to add a Taplist logo from the admin panel, I get sent to the following url and it gives me an error:

Url: http://192.168.0.252/admin/update_logo.php

Error message: Sorry, there was a problem uploading your file.

**Comment by EmDubeu** [comment]
Is there a size requirement for the logo? If so, there should be some comments about the size.

**Comment by EmDubeu** [comment]
It would also be nice to have an option to remove a logo.

**Comment by Skemp45** [comment]
How big was the logo

**Comment by Skemp45** [comment]
if ($uploaded_size > 350000) 
is the limit

**Comment by Skemp45** [comment]
I guess We can remove file size.....

**Comment by EmDubeu** [comment]
86 kb.

**Comment by Boombrewer** [comment]
I had a similar problem with both the Admin and the Tap logo uploads.
I tried both a 7kb jpeg and a 161kb png.

**Comment by thadius856** [comment]
I'm having issues with it, too. But different.

I can upload, but it looks like it's just a plain page refresh. Have to Hard Refresh (Ctrl+F5) to see the new logo.

Any way we can force a hard refresh automatically?

Edit: Mine's a 48.5kb PNG with transparency, btw.

**Comment by thadius856** [comment]
Have you guys tried chmod'ing the image & parent folder? Good change it's a permissions issue.

**Comment by EmDubeu** [comment]
"Have you guys tried chmod'ing the image & parent folder? Good change it's a permissions issue." 

instructions on how to do this?

**Comment by thadius856** [comment]
Make the error happen again.

Either at the Pi itself of through a SSH session (such as PuTTy):

```
sudo chmod -R 777 /var/www
```

Try again afterwards.

**Comment by EmDubeu** [comment]
Bam! That worked.

On Sat, Feb 8, 2014 at 7:32 PM, thadius856 notifications@github.com wrote:

> Make the error happen again.
> 
> Either at the Pi itself of through a SSH session (such as PuTTy):?
> 
> sudo chmod -R 777 /var/www
> 
> Try again afterwards.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/114#issuecomment-34564416
> .

## 

Mike Wright

**Comment by thadius856** [comment]
Boom,

Any inputs?

**Comment by jkurl** [comment]
Thad my plan tomorrow is to go through the install instructions provide you
a write up and then start in on the raspberry pints interface. Not sure
where you want me to send my feedback to?

**Comment by thadius856** [comment]
Please post your comments in issue #71 .

**Comment by jkurl** [comment]
Roger will do.

**Comment by Boombrewer** [comment]
So are you saying to copy the image to the /var/www folder first, change permissions, and then try to upload the image?

**Comment by thadius856** [comment]
Negative. I uploaded from my Windows workstation using the website.

What I'm say is:
1. Try it the way you have been. If it fails, note it.
2. Run `chmod -R 777 /var/www`
3. Try again.

**Comment by thadius856** [comment]
Still getting the error?

**Comment by Boombrewer** [comment]
Nope.  Its updating now.  But the admin page seems slow to change.  Its kind of weird but I think its just Chrome.  Looks and works great on the Pi.

**Comment by EmDubeu** [comment]
Chrome is slow for me too. Lags serious ass with Chromium on the pi.

**Comment by thadius856** [comment]
To be expected. The video overhead alone at 1080p is pretty stressful on
this diminutive hardware.

Thats why I chose Chromium. So I could develop on Chrome remotely and know
it would look the same.

**Comment by Skemp45** [comment]
ok so is the actual issue fixed for Adding Taplist Logo results in error? can we close?

**Comment by Boombrewer** [comment]
I would say we can close this.  I've gotten them all to update but I know there were others getting the error as well.  Not sure if its completely worked out.

**Comment by thadius856** [comment]
Em, can you confirm this works?

**Comment by jkurl** [comment]
I was not able to get mine to work didn't have to much time to further
test.

**Comment by EmDubeu** [comment]
i'm testing it... stand by...

On Mon, Feb 10, 2014 at 5:27 PM, thadius856 notifications@github.comwrote:

> Em, can you confirm this works?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/114#issuecomment-34718059
> .

## 

Mike Wright

**Comment by EmDubeu** [comment]
Jerry - what are the rights on your /var/www folder?

On Mon, Feb 10, 2014 at 5:34 PM, Jerry Livingston
notifications@github.comwrote:

> I was not able to get mine to work didn't have to much time to further
> test.
> 
> On Monday, February 10, 2014, thadius856 notifications@github.com wrote:
> 
> > Em, can you confirm this works?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/RaspberryPints/RaspberryPints/issues/114#issuecomment-34718059
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/114#issuecomment-34718442
> .

## 

Mike Wright

**Comment by jkurl** [comment]
Good question. I know admin and includes are 777. I will be home in a few
mins. I will SFTP in and Check it.

**Comment by jkurl** [comment]
I just changed the permission and gave the www folder all 777 for everything and I was able to change the admin logo and tap list logo as well.

**Comment by thadius856** [comment]
Closing as resolved. Somebody please check that we're chmoding the whole directory in the setup instructions.

**Comment by jkurl** [comment]
I know when I did the install yesterday the chmod was for the Admin and
Includes folder only.

**Comment by EmDubeu** [comment]
permissions are almost 90% of the problem.  By the way,  did you know that
73 % of all percentages are made up?   Anywho,  it looks like we need to
chmod some shit. I'm not sure where the chmod 777 needs to be placed in the
install routine.  Thoughts anyone?

**Comment by jkurl** [comment]
i am looking in the install instructions now. we have chmod of 777 for the
entire folder is the master.zip is downloaded to the pi but if you use
windows to move the files it just has Admin and Includes folder only
getting the chmod of 777.

**Comment by Boombrewer** [comment]
I've been chmod'ing the whole folder after transferring the files.  That's probably the best bet instead of the 'right click' admin and includes.  Besides that its much easier to just chmod on the pi.  (that just doesn't sound right)
