### ISSUE TITLE
Header Text Needs Length Parameters

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#115]
I added my brewery name to the Header Text field in the Admin section. If the Header Text is too long, it messes up the Taplist display.

Header Text: Hump Day Brewery Hump Day Brewery Hump Day Brewery Hump Day Brewery Hump Day Brewery Hump Day Brewery Hump Day Brewery Hump Day Brewery 

Taplist:

![image](https://f.cloud.github.com/assets/6434553/2112681/fe788a80-9021-11e3-97a2-af8e35c8c370.png)

**Comment by Skemp45** [comment]
Interesting brewery name

**Comment by Skemp45** [comment]
What length do we want it set to?

**Comment by thadius856** [comment]
Does this really need to be addressed? It's pretty obvious when you bork it up.

How about just specify a max-height?

**Comment by thadius856** [comment]
Just about broke my keyboard doing it (HULK SMAAAASSSHHHHH) but I figured this one out and added it.

By default, it will truncate to 20 characters (that's what fits on my test bed). I added a box to `personalize.php` to allow the user to set it at whatever they like.

Committing to `develop` branch momentarily.

**Comment by thadius856** [comment]
Closing as fixed.
