### ISSUE TITLE
Password in /var/www/includes config.php is in cleartext

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#116]
Shouldn't we hide/encrypt the mysql localhost password for 'beers' in the config.php file in the the /var/www/includes directory?

**Comment by Skemp45** [comment]
I dont see why that would be necessary no different than  wordpress, joomla, or drupal config files

**Comment by EmDubeu** [comment]
Got it. I'm not a programmer, so I wasn't sure if this was typical.

**Comment by Skemp45** [comment]
:+1:
