### ISSUE TITLE
Branches and Versioning

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#117]
We're less than 2 weeks from release now. We need to get our branching and versioning under control ASAP. I'm about to implement some new branches and provide a write-up on how to use them, but I need to know...

...are all of our branches up to date? Looks to me like Install and ModifyAbvImage have both been merged into the master. Mind if I delete them now?

**Comment by thadius856** [comment]
Everybody that wants to develop needs to check out these two articles:

http://nvie.com/posts/a-successful-git-branching-model/
https://www.atlassian.com/git/workflows#!workflow-gitflow

Take a few minutes to soak it all in. It's very important this makes sense to you. You may have to read it several times. It's ok, I'll wait...

..

..

..

..

..

Got it? Ok, good.

Now print the first image from the first article and put it somewhere you can reference it easily.

Here's what we'll take away from this.
- If you want to work on the project, edit the `develop` branch.
- If you want to add a feature, branch off the `develop` branch and to a branch named `feature-yourfeaturename`. When you complete your feature and have tested it, merge your feature branch back into `develop`.
- When we want to release a new version, we'll create a new `release` branch. After testing it out, we'll merge it into both `master` (to push it out to the world!) and into `develop` (so we can keep developing onward).
- If a user reports a bug that's easy to fix, we'll branch off the `master` into a `hotfix-yourhotfixname` branch. When done, merge it back into both `master` and `develop`.

We won't use the maintenance branches described in the second article.

**Comment by sevlabs** [comment]
It's OK to delete ModifyAbvImage

**Comment by sevlabs** [comment]
So when I create a new branch and clone the repository to my local machine, do I source the master branch (as indicated in the other how-to  #85) or the development branch? From this latest post it seems I should clone the development branch but I just wanted to confirm. 

I'm planning to create a new branch called "feature-DisplayOptions" to work on the ABV graphic fix and will also include toggling the graphics on/off for the other taplist items as well.

**Comment by thadius856** [comment]
For features, branch off `develop`.

We only branch off `master` after a public release and for hotfixes.

Edit: Second thought, we'd only branch of `master` for hotfixes. For releases, `release` (and probably `develop`) branches already are up-to-date.

**Comment by sevlabs** [comment]
How do I tell TortoiseGit to create a local clone of the "develop" branch? I tried this and it failed:

![2014-02-08_222037](https://f.cloud.github.com/assets/6545107/2119022/2c553238-9139-11e3-91fc-18fabf7846c0.jpg)

**Comment by thadius856** [comment]
Create the branch using `TortoiseGit` -> `Create Branch`.

Switch to it using 'TortoiseGit`->`Switch/Checkout`. Commit something.
That creates the local branch.

To push it to remote, just use `TortoiseGit` -> `Push`. It'll automagically
crate a new branch on GH.

**Comment by sevlabs** [comment]
In order to get the 'TortoiseGit' --> 'Create Branch' option to show I had to clone the master first then go back and select 'Create Branch' on the local folder. Hopefully this is correct, but let me know if not. Thanks.

**Comment by thadius856** [comment]
Yes, you have to clone the master first.

Sounds like you want `develop` in a second folder. If so, that's okay. Only thing that it may require you to do is to specify which branch to use when Pushing. Be sure to select the right branches. The "..." button is your best friend the first time or two.

I usually just run all branches from a single folder and Checkout/Switch Branches between them.

**Comment by sevlabs** [comment]
I think I'm back in business now. Thanks for the help.

**Comment by thadius856** [comment]
Np. If you have questions, please let me know.

**Comment by thadius856** [comment]
Seven, I was wrong. There's an easier way. I'll post it in teh tutorial momentarily.

**Comment by sevlabs** [comment]
I pushed my updates just now and it looks like they went straight into the develop branch.

**Comment by thadius856** [comment]
That's fine. You probably forgot to switch to your feature branch and push it to remote.

If you ever are at a point where you want to work on a branch that you don't have locally but is on the server (perhaps you want to test Joe's `feature-xml` branch) you can add it locally in one easy step:

http://joelabrahamsson.com/remote-branches-with-tortoisegit/

See the `Fetching the remote branch` section.

**Comment by sevlabs** [comment]
Thanks man, I'll wrap my head around this GitHub thing some day.

thadius856 wrote:

**Comment by thadius856** [comment]
None of us knew git when we started. Don't worry, you'll get there.

**Comment by sevlabs** [comment]
Do I need to create a pull request for the develop branch now that I pushed my changes there?

**Comment by thadius856** [comment]
Nope. We're developing in `develop` now, so everybody should be testing
`develop`, not `master`.

By codebase lockdown day (13th), we'll merge any remaining `feature-`
branches into `develop`.

On codebase lockdwon day, we'll clone `develop` to `release`.

We'll apply bugfixes to `release` until release day.

On release day, we'll merge `release` into `master` and create a GitHub
Release for v1.0.0.x. We'll then merge `master` back to `develop` and keep
working on `develop`.

**Comment by Skemp45** [comment]
Closing and linking to this from the wiki
