### ISSUE TITLE
Header Text doesn't accept apostrophe

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#118]
![image](https://f.cloud.github.com/assets/6321429/2116533/82cac590-908c-11e3-8e76-54deb9e08916.png)

The above entry results in a page with nothing more than ERROR
I tried every other character I could find on my keyboard and this was the only one that gave an error.

I guess I could always just change the name?

**Comment by Boombrewer** [comment]
This may be related to #105, but you guys who are much smarter at this than me need to make that call.

**Comment by thadius856** [comment]
Sorta related.

I _think_ the problem is the `'` is getting injected into the SQL and throwing off the column count.

Any input, SQL gods?

**Comment by EmDubeu** [comment]
Apostrophe in a beer name has problems, too.

![image](https://f.cloud.github.com/assets/6434553/2119096/dafd439c-9144-11e3-9e9d-81a55dd04df0.png)

**Comment by Skemp45** [comment]
humm the header text is not an issue for me.... 
![apo](https://f.cloud.github.com/assets/6318869/2126370/01b04d1e-9261-11e3-9423-f8f9e9524c55.png)

![apo2](https://f.cloud.github.com/assets/6318869/2126371/054df296-9261-11e3-9acd-f61b773fdfe3.png)

**Comment by thadius856** [comment]
Did you update it using the panel, or manual SQL update?

The aprostraphe errors out the submit form for me.

I'm assuming the ' is breaking the an UPDATE with values ( ' ', ' ', ' ');
etc.

**Comment by thadius856** [comment]
![untitled](https://f.cloud.github.com/assets/6320180/2126406/6c01226a-9261-11e3-90cb-098511db1ce6.png)

**Comment by Skemp45** [comment]
I used the admin panel, but yeah, an Apostrophe means something special in MySQL

**Comment by Skemp45** [comment]
ok im not duplicating but will troubleshoot we need to add  mysql_escape_string()

**Comment by thadius856** [comment]
> Apostrophe in a beer name has problems, too.

This was addressed in a recent update. Should be fixed now. If still broken for you, download most recent zip and overwrite your `admin/includes/html_helper.php` with the new one.

![untitled](https://f.cloud.github.com/assets/6320180/2126431/d5931652-9261-11e3-9f0f-870714f9bb97.png)

![untitled](https://f.cloud.github.com/assets/6320180/2126434/dd1ea6b6-9261-11e3-9d79-b9c6ed4ae51c.png)

**Comment by thadius856** [comment]
Anybody dare test with SQL injection? Perhaps some testing of DROP is in order?

**Comment by Skemp45** [comment]
Derp, I had magic quotes on which automagicly escaped for me. shut it off and got the error, try this do drunk\'n does that work?

**Comment by Boombrewer** [comment]
Yep.  Worked like a champ.  Would it be easier to just add this as a FAQ or change the code?  How many people is this actually going to affect?

**Comment by JayUnt** [comment]
Skemp,  just so you know. In the /admin/includes/functions.php there is an encode() function.  It pretty just uses the php htmlentitites function to encode the characters, but we should use this function to encode all strings for the db.  That way if we change the way we want to encrypt, we only have to do it in one spot.

**Comment by Skemp45** [comment]
Nice I can use that then :)

**Comment by Skemp45** [comment]
@thadius856  can you explain what you are trying to do here?

```
    <p><b>Truncate To:</b> (# characters)</p>
<form method="post" action="update_header_text_trunclen.php">
<input type="text" class="smallbox" value="<?php echo $headerTextTruncLen['configValue']; ?>" name="header_text_trunclen"> &nbsp
<input type="submit" class="btn" name="Submit" value="Submit">
</form>
```

**Comment by Skemp45** [comment]
I just dont understand why we are creating 2 forms for header text or what the idea is behind it.

I have a fixed file to allow for apostrophes but dont want to update until I understand whats you are trying to do

**Comment by Skemp45** [comment]
Ok, I figured out how to work around what you had, looks like you didn't change update_header_text.php which is what needed changed. I updated in the development branch. So this issue is now fixed. 
changed 

```
$header_text=$_POST['header_text'];
```

To 

```
$header_text=encode($_POST['header_text']);
```

and added require_once 'includes/functions.php'; so that encode would work

**Comment by Skemp45** [comment]
As soon as I understand what the story with the truncate is we will close issue

**Comment by thadius856** [comment]
I have no idea what you're talking about. I didn't code that chunk. I only
changed the box size class.

**Comment by Skemp45** [comment]
ok no worried then brother, I think i will close this as the issue is resolved :D YAYYYY another one bites the dust

**Comment by thadius856** [comment]
Oh, the truncate.

There was a bug issue open about needing to limit the length of the text
there, otherwise it will wrap to multiple lines and sit over the top of the
taplist.
