### ISSUE TITLE
Tap Form not auto-filling from Beer Form

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#120]
![image](https://f.cloud.github.com/assets/6321429/2116566/4a5638b4-908e-11e3-9718-61d37b8c63f3.png)

I honestly can't remember which direction you guys were going with this, but I thought the Tap Form was supposed to auto-fill SRM, IBU, OG, and FG from the Beer Form inputs when the beer was selected?  I'm pretty sure a previous version did this.

If I'm mistaken, please promptly delete this.

**Comment by thadius856** [comment]
You are correct. It should auto-fill.

However, I cannot reproduce this. It's working well in both Chrome and Chromium.

Looks like maybe you're using Safari. Can you try another browser?

**Comment by Boombrewer** [comment]
I was using Chrome on my laptop.  I just tried Chrome on my iPad.  Same thing.  I'll try some other stuff in a little bit.

**Comment by Boombrewer** [comment]
I've tried re-starting Chrome, using a different platform, tried if on Chromium on the Pi, still the same.  But the weird thing is that my logos showed up this morning (after I got error messages last night).

Confused = this guy.

**Comment by Boombrewer** [comment]
Operator error or bad install.  Either way - Closed.

**Comment by thadius856** [comment]
So it works now?

**Comment by Boombrewer** [comment]
Yeah, I think I just had a bad install or something.  I just nuked it and re-installed everything about 20 minutes ago.

**Comment by DanielRedOak** [comment]
This happened to me just now.  I pulled up the console in Chrome and it was a syntax error coming through from the notes field of one of the beers I added.  The issue was that I had a new line/line feed in the description causing issues.  Removed that and made sure the notes field was a single line and everything works again.
