### ISSUE TITLE
Installer: Hide Step 2 / Step 3 when "Clear Data" Selected

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#122]
In the Installer, when selecting "Clear Data", only Step 1 is required (admin password).

Filling out Step 2 and Step 3 does nothing. So why not hide these steps to prevent confusion?

**Comment by thadius856** [comment]
While we're at it, can we make the page force a reload when we land on it using the browser's Back and Forward buttons?

When you perform a Clear Data, then press the browser's Back button, it still displays "Upgrade" and "Clear Data". When you refresh the page, they both disappear as they should.

**Comment by mtnbound** [comment]
I just pushed to the install branch new code that takes care of this. As for as the forced refresh, that's probably a little more of an issue. I'll take a look at it, although I'm not sure how often that will happen in the real course of use.

I'm traveling so I don't have my Pi, and I'm not sure how Chromium will behave vs. my test setup.

**Comment by thadius856** [comment]
Chromium so far has behaved exactly the same as Chrome for me.

**Comment by Skemp45** [comment]
ok, 1.5 days of scripting left you guys finished with this? if so lets close it if not lets finish it up!!!! ITS GO TIME

**Comment by mtnbound** [comment]
Yes, this is done.

**Comment by mtnbound** [comment]
I think I pushed it to the "Install branch" You can delete that branch after it's merged.

**Comment by Skemp45** [comment]
@thadius856 if you want to push when you can then mark this as complete. I am really trying to clean up these issues today as we are coming too close to the end with this many issues open

**Comment by thadius856** [comment]
Hrm? You want me to merge `Install` into `develop`?

Ok, easy enough.

**Comment by thadius856** [comment]
If I didn't pick the correct blocks in the when resolving the merge conflicts, let me know and re-open.

Otherwise, closing as completed.
