### ISSUE TITLE
HBT Forum Signatures

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#124]
If you're interested in putting your name/title in your HBT sig, here's the code I used:

```
[b]Thadius Miller[/b], Project Manager -> [thread=456809]RaspberryPints[/thread]
```

If anybody has something more snazzy, let me know. This one's rather plain.

**Comment by JayUnt** [comment]
Should all of these "HOW TO!" and "No Action Needed" items go into the wiki instead?

**Comment by Skemp45** [comment]
Mise well

**Comment by Skemp45** [comment]
Example:
https://github.com/RaspberryPints/RaspberryPints/wiki/HBT-Signature

**Comment by Skemp45** [comment]
Closing this issue. The wiki is the way to go. if we disagree these can be re opened but it is getting to be too many non issues in the issues section
