### ISSUE TITLE
Styling Help Please: beer_list.php

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#126]
I need minor help finishing styling beer_list.php. I'll push the newest version to `develop` momentarily.

I want the table on this page to have plain headers (no background image, no underline). For the life of me, I can't figure out where it's inheriting from! I've tried hard refreshes. Chrome doesn't want show the inheritance anywhere in the DOM when I Inspect Element.

I'm probably just tired and missing something obvious. Anybody?

![untitled](https://f.cloud.github.com/assets/6320180/2118026/5dd9fd4c-90ef-11e3-82a9-dd7df4e727a3.png)

Btw, yes, that's sample data so I could determine cell heights and widths. I'll be hiding it before release.

**Comment by mcangeli** [comment]
What is in the style.css file for H3??

Scratch that. 

You've got the row set to intborder for the class ( <tr class="intborder"> )

Is the style in there? (I haven't looked at the style.css sheet yet...)

Also, you're calling the cells as th (which would specify header correct?) so that would be the default styling... change the th to td for the cells in that row and it _should_ get rid of that.

**Comment by thadius856** [comment]
I don't really want to change _every_ `th` on all pages, but I tried just to see if I could do it (if I could, I'd just create a new class). Problem is, I tried changing `th` in both `admin/styles.css` and `admin/styles/layout.css` and there was zero change. Even tried `!important;` with no luck.

I mass-searched every file in the repo for "text-decoration" and "underline". One result came up, but it was for hyperlinks. _sigh_

**Comment by mcangeli** [comment]
The code in TH is bolded by default. It may be underlined if its a link as well...

http://www.w3schools.com/TAGS/tag_th.asp

I bet there is also default shading to the headers (think like in excel)

**Comment by mcangeli** [comment]
Yea, I just tested it.

I changed the <th> to <td> for the name and style row and made the td for the notes a th and the shading and formating changed.

**Comment by thadius856** [comment]
Thing is, I'm pretty sure _I_ put the damn underline there when I was styling a previous page.

Just can't remember how I did it so that I can undo it. >.<

**Comment by mcangeli** [comment]
Yar. Also, there's a section in the layout.css file in the admin section.

admin/styles/layout.css

th {background: #E0E0E0 url(../img/bg_th.png) repeat-x top; text-shadow: 1px 1px 1px #fff; font-size: 14px; text-decoration: underline;}

**Comment by thadius856** [comment]
Boom. There it is.

I swear I looked through that file 20 times. Ugh.

Wonder why my searches didn't pick it up.

**Comment by mcangeli** [comment]
There were 41 th's in that file... :)

Sometimes you just need a fresh set of Eyes.

**Comment by Skemp45** [comment]
Yeah let's stay out of the style.css unless we want global changes
