### ISSUE TITLE
Admin - Adding a new keg with a Label # that already exists.

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#127]
Should you be able to add a new keg with a label that is already in use?

![image](https://f.cloud.github.com/assets/6434553/2119102/7653bca4-9145-11e3-94b5-5482975d9c5c.png)

![image](https://f.cloud.github.com/assets/6434553/2119101/61e9e43c-9145-11e3-91bc-58a28d794f61.png)

**Comment by thadius856** [comment]
Probably not. Labels should be unique, not duplicated.

**Comment by thadius856** [comment]
On second though, yes, yes you probably should be able to.

The keg already has a unique ID that we're not displaying.

If Joe Bob wants to put the same label on 5 kegs, I don't see any reason to stop him.
