### ISSUE TITLE
Forgotten Password Screen - kegerFace?

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#128]
When you click the Forgotten Password link on the Admin login screen, you get a KegerFace screen.
![image](https://f.cloud.github.com/assets/6434553/2119108/42700734-9146-11e3-8a31-904293058dd8.png)

![image](https://f.cloud.github.com/assets/6434553/2119109/550d329a-9146-11e3-8d3f-cb5aed6f9217.png)

**Comment by thadius856** [comment]
Fixed. Changed both the name and the color.
