### ISSUE TITLE
DB cleanse instructions

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#129]
Are there Update Instructions when we need to update our test systems with new source code? It might be helpful for those of us who are not super savvy with database administration. There may be other folks following the HBT thread and have loaded some of the raspberrypi master zip files and won't have a clean final product.

**Comment by thadius856** [comment]
Good idea. Are you willing to write them?

To nuke the database:

```
Navigate to http://your.ip.goes.here/phpMyAdmin. Log in.
Click 'Databases'.
Check the box next to `raspberrypints`.
Click the 'Drop' button. Click 'Yes' when asked to confirm.
```

Alternatively, using command line only (note the _double_ dashes and semi-colon):

```
mysql --user=your_username --password=your_password
DROP DATABASE IF EXISTS raspberrypints;
```

And then remove the files:

```
sudo rm -R /var/www/*
```

**Comment by Boombrewer** [comment]
@thadius856, If I just pull down a new zip and try the install process without deleting anything, will it test the update functionality?  I'd like to see if I can just update the new files and leave my data in there to see how it reacts but I'm not sure how to go about that the right way.

**Comment by thadius856** [comment]
In the future, yes. Right now, no.

We're constantly doing things that change the schema. So right now, doing that will jack up your install so fast it ain't even funny.

In the future, we'll only modify the schema in major releases, so users will be able to update to a minor release within the same major release by copying right over their existing install (when upgrading within the same release). For major releases, we'll 

Remember, versions goes Major.Minor.Hotfix.Build!

Examples:

Joe has 1.0.0.546
The most recent release is 1.0.3.555
Joe can copy the new files right over his old files. Doing so will grant him 3 new hotfixes.

Joe has 1.0.3.555
The most recent release is 1.1.1.604
Joe can copy the new files right over his old files. Doing so will grant him 1 new feature set, plus a hotfix.

Joe has 1.1.1.604
The most recent release is 2.0.0.1004
Joe must apply a v1.1->v2.0 SQL patch, then he can copy the files over his old ones.

**Comment by thadius856** [comment]
So the short answer is: until we lock down the schema (the cutoff for schema updates is 11:59pm PST 13 Feb 2014!), you're best of blowing away your database each time you apply a new version. 

Alternatively, you can look at the changes made to `schema.sql` between your version and the newest version, and apply those changes manually in phpMyAdmin.

**Comment by Boombrewer** [comment]
^^^^hmmm...  likely above my skill level.  I'll just nuke it each time and re-enter my data.  That's usually how I find bugs anyway (which is my job).  I'm just starting to memorize OGs, FGs, and SRM levels of my beers.  On the up side, my 'tasting comments' are getting more entertaining each time.  : )

**Comment by thadius856** [comment]
You're welcome to create a copy of `test_data.sql`, enter your info into it, and keep it on your desktop. 

Each time you blow away and reload the files, just copy your test_data over it, then run the installer and it'll load YOUR beers instead of mine.

**Comment by EmDubeu** [comment]
Here's what I did when I cleaned up my db and installed a new rpints version:

To load a new update:
1.  Clean up database:
         a. Go to raspberry Pi terminal and type: mysql --user=your_username --password=your_password
         b. and do this: DROP DATABASE IF EXISTS raspberrypints;
         c. Then, clean up www folder, type: sudo rm -R /var/www/*
2.  Open WinSCP window
         a. Clear the /var/www contents
         b. Copy the new build from the left window to right window in the /var/www folder
         c. If you want to load your own test data instead of the default test_data.sql, delete the sql/test_data.sql file and copy over your own test_data.sql file.
3.  Set folder permissions:
         a. On the WinSCP window, on the right panel, select "admin" and "includes" folders. 
         b. Right click and go to properties. Set the box "octal" to 0777. 
         c. Check the box "set group, owner, and permissions recursively"
         d. Click ok
4.  Install Rpints software:
         a. Navigate to http://YOUR_IP_HERE/install
         b. Populate fields as you did in the original install
5.  Verify your RaspberryPints install:
         a. Open the taplist http://YOUR_IP_HERE/index.php
         b. Open admin http://YOUR_IP_HERE/admin/index.php

**Comment by Skemp45** [comment]
see page in wiki https://github.com/RaspberryPints/RaspberryPints/wiki/DB-cleanse-instructions
