### ISSUE TITLE
Too Much Cell Padding in Most Divs

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#13]
During the CSV->SQL conversion/CSS cleanup, some items lost proper alignment.

In particular, most divs regained padding. This causes the rows to become spread apart and the borders to not meet. See screenshot: 

![untitled](https://f.cloud.github.com/assets/6320180/1866164/4e85556e-7829-11e3-80bc-4e054efca54a.png)

**Comment by Skemp45** [comment]
![taplistupdate](https://f.cloud.github.com/assets/6318869/1868426/a700a73a-7869-11e3-82b6-2c5ebe0132dc.png)
This look better? I kind of feel like we need a small gap at the top

**Comment by Skemp45** [comment]
![taplist](https://f.cloud.github.com/assets/6318869/1868442/13710f68-786a-11e3-9745-0c1bd8c44e39.png)
for example, what do you guys think?

**Comment by JayUnt** [comment]
I know im a bit late to this ticket, this project is going so fast ive lost track of where we are,  I think to really fix this issue, the we should swap the background shading of the even and odd rows.  So tap 1 would have the darker background and 2 would have the lighter background.  That way its truly alternating rows.

**Comment by thadius856** [comment]
Kemp,

Very much like what you did. Looking at my Pi, looks like I committed your changes last night.

Jay,

Sounds good, man. If you swap the colors, please remove the gap between the header row and 1st beer, as it will no longer serve a purpose. Re-open/close this ticket one you're done so we know if you did it or not.

**Comment by Skemp45** [comment]
So I made the changes above as That is a GREAT suggestion but that brings a new issue..... OF COURSE lol/
The border for the tap column goes all the way to the top where as all the other titles cut off and have like a 5px gap. also the borders are not lining up.

![borderlineup](https://f.cloud.github.com/assets/6318869/1882476/9fe6a3c4-7976-11e3-8a9d-6bfc79bc6b41.png)

**Comment by thadius856** [comment]
Hrrrrrm. I'll dig into this a bit later tonight.

**Comment by Skemp45** [comment]
SO........ I walked away had a couple 61 minute ipas and BOOM

![taplist](https://f.cloud.github.com/assets/6318869/1885451/bba0b0a8-79cd-11e3-8f10-e611731b1a1c.png)
