### ISSUE TITLE
Package Installation Instructions

### ISSUE THREAD

**Issue by EmDubeu** [RaspberryPints/RaspberryPints#130]
With a completely fresh SD card, I went through the Noobs and Rpints install again just to ensure the install instructions would work. 

My only problem was under the Package Installation instructions, specifically the LAMP portion. After fully completing the install I tried to open http://my_ip_address//phpmyadmin and I got a 404 message. PhpMyadmin not installed. So I did a sudo apt-get install phpmyadmin and tried the  http://my_ip_address//phpmyadmin again. It worked. 

So, my question is this: is the command "sudo apt-get install apache2 php5 mysql-client mysql-server php5-mysql" in the Package Installation instructions supposed to install phpmyadmin?

**Comment by thadius856** [comment]
Nope. Boom report that a couple house ago in #71.

Will add to the instructions momentarily.

Closing as duplicate.

**Comment by thadius856** [comment]
Page is Lock for Editing by Wekim.

Go ahead and just tack it on the end of that command. ;)

**Comment by EmDubeu** [comment]
I out! Sorry.

**Comment by thadius856** [comment]
No worries. Go ahead and tack it on the end.

**Comment by EmDubeu** [comment]
Updated the Package Installation instructions with the full LAMP (phpmyadmin)

changed the install to this: sudo apt-get install apache2 php5 mysql-client mysql-server php5-mysql phpmyadmin
