### ISSUE TITLE
Version as option?

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#132]
Is there a reason we have version as a enable and disable option. Its because the show on admin option is set to 1 on the schema.sql if we dont want this change it to 0

![onoff](https://f.cloud.github.com/assets/6318869/2126279/2e05dfba-9260-11e3-879a-f4142f7cb78a.png)

**Comment by Skemp45** [comment]
I am just going to fix this because it  should not be there

**Comment by Skemp45** [comment]
commit 2fe6414f95c446bb5e940617d459d1c28234f174

**Comment by thadius856** [comment]
It was already fixed.

Please make edits on develop branch. We should be touching master unless
we're creating a public release or publishing a hotfix.
