### ISSUE TITLE
Make  new "Your logo here" image

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#133]
http://zookeeperbrewing.com/admin/img/logo.png

this image seems to be low quality I will create a new one

**Comment by Skemp45** [comment]
![logo](https://f.cloud.github.com/assets/6318869/2127859/a38928ec-9273-11e3-9b2a-30722eef54d6.png)
This ok?

**Comment by Skemp45** [comment]
instead of 
![logoold](https://f.cloud.github.com/assets/6318869/2127882/c63416c2-9273-11e3-9618-ee8cf6600d85.png)

**Comment by jkurl** [comment]
Shawn,

```
What is the max size for the logo? Mine gave me a error last night but
```

I did try to upload from my iPad.

Jerry

**Comment by Skemp45** [comment]
350k

**Comment by Skemp45** [comment]
actually that does not seem to be in affect, i just did a 1mb file. How big was yours?

**Comment by Skemp45** [comment]
maybe you guys need to increase your servers default upload limit??

in your php.ini do 
upload_max_filesize = 50M

**Comment by jkurl** [comment]
I will give it a try from my laptop. Not quite sure what the size. Wanted
to test it real quick and see how doing it from a tablet worked

**Comment by jkurl** [comment]
what folder is the php.ini in so i can edit it. I downloaded another image and it is on 8K on disc so it should load it.

my admin logo won't load either it just refreshes the page but doesn't give a error like taplist does. i changed the size on the pic so it would be under the 350K incase mine was still set to that lower limit.

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/img/logo.png

can someone upload this and replace the current logo.png in /img

**Comment by Skemp45** [comment]
Please also upload to /admin/img and replace that logo.png

**Comment by Skemp45** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Bump on this so I can close this. I have not been on my home computer to complete this.

**Comment by Skemp45** [comment]
once done issue can be closed

**Comment by thadius856** [comment]
This is done for the `develop` branch.

30fab9dd095528b1b275857f3dd3f148ff2cdb8c

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/admin/img/logo.png

^^^This Logo needs to be uploaded in place of these two following logos. 
img/logo.png
admin/img/logo.png
this did not get updated in the merge

**Comment by thadius856** [comment]
I can definitely see the change on mine and in the commit link above.

Are you sure you downloaded the develop branch?

**Comment by thadius856** [comment]
Dude, I can definitely see it on yours too. Hard refresh.

**Comment by Skemp45** [comment]
hrmmm Maybe I am doing something wrong lol. here is where I was looking
 https://github.com/RaspberryPints/RaspberryPints/blob/master/img/logo.png

**Comment by thadius856** [comment]
Thats the master branch.

Go to main page, click Branches, click develop.

Now you can download the zip of it.

**Comment by Skemp45** [comment]
:D right on

**Comment by Skemp45** [comment]
I STAND CORRECTED CLOSING
