### ISSUE TITLE
Auto refresh or push refresh?

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#134]
I'm not even sure if this is required as of yet or if you guys have already addressed this...

So after I make some changes via the admin (on my laptop), the only way I know of to see those changes reflected on the display is to (on the pi) exit full screen mode and refresh the page.

1) would it be easier to configure the OS to automatically refresh the page after X minutes?  Seems like overkill considering a majority of the use is a 'digital chaulkboard' that doesn't get changed that often.

2) command a 'refresh' after certain save or submit buttons are clicked?  this seems more appropriate since its only happening when changes are occurring.

I know this will need to be addressed anyways and likely in a different way when the flow sensors portion gets developed since it will be changing more often.  If you guys have already addressed this, I'm sorry.

**Comment by EmDubeu** [comment]
I noticed the same thing. For example:
1. Make a change to the SG or FG in the taplist in the admin screen.
2. Open my_ip/index.php and the gravity is the old value.
3. Manually refresh the my_ip/index.php screen and the updated gravity is
   shown.

On Mon, Feb 10, 2014 at 12:15 PM, Boombrewer notifications@github.comwrote:

> I'm not even sure if this is required as of yet or if you guys have
> already addressed this...
> 
> So after I make some changes via the admin (on my laptop), the only way I
> know of to see those changes reflected on the display is to (on the pi)
> exit full screen mode and refresh the page.
> 
> 1) would it be easier to configure the OS to automatically refresh the
> page after X minutes? Seems like overkill considering a majority of the use
> is a 'digital chaulkboard' that doesn't get changed that often.
> 
> 2) command a 'refresh' after certain save or submit buttons are clicked?
> this seems more appropriate since its only happening when changes are
> occurring.
> 
> I know this will need to be addressed anyways and likely in a different
> way when the flow sensors portion gets developed since it will be changing
> more often. If you guys have already addressed this, I'm sorry.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/134
> .

## 

Mike Wright

**Comment by Skemp45** [comment]
Well we might have to make the page auto refresh to update the keg lvl column. Might take care of the issue.

**Comment by jkurl** [comment]
Boombrewer is you have a mouse or one the keyboard/track pas combos you can
right and select refresh but yes having to manually refresh when putting
stuff in is kind of a pain. When I first set mine up I got one in to make
sure it displayed correctly and then went back in and added in the rest.

**Comment by thadius856** [comment]
Why are y'all exiting full screen? Just hit F5.

My impression was that we were moving to updating the SQL view, refreshing
with jQuery. Seems we have the dependencies in place already, just haven't
implemented them yet.

With the code cut looming (3 days) this will probably have to wait for v2+.

**Comment by Skemp45** [comment]
YEs I agree v2

We need to start clearing these issues out of the issues section.

**Comment by Boombrewer** [comment]
So should we switch this label to Enhancement V2 or just put the F5 trick in the FAQ. Honestly, I did a search for the hot keys and didn't find F5 so we might just be safe with a FAQ entry and save the coding effort. My .02.

**Comment by thadius856** [comment]
F5 is the universal hotkey for refresh in just about every browser for the last 15+ years. :)

I second a FAQ entry.

**Comment by Boombrewer** [comment]
Learned me something new today...  speaking of FAQ, we should probably make some progress on that behemoth.  Who's working it?  (not to de-rail this thread).

**Comment by thadius856** [comment]
I saw Ray had added a bunch to it. But anybody can. Feel free to add at-will.

Just try to keep to three basic guidelines:
1. Keep the tone professional and third-person. Avoid writing "you" in a directive statement.
2. Be mindful of spelling and grammar.
3. If you can't think of at least three items to put in a category or list, it probably doesn't need to be one.

**Comment by mcangeli** [comment]
In the mean time, add:

< meta http-equiv="refresh" content="600" >

(Remove the spaces between the < meta and " > 

to the head section in index.php to refresh the page every 10 minutes (the content portion is in seconds)

**Comment by mtnbound** [comment]
Did we add the refresh meta tag to the release? I was testing today, and the screen wasn't refreshing after changing the data. I know we didn't move to AJAX until V2, but just wondering about the meta tag

**Comment by thadius856** [comment]
If it works, yes.

If it's buggy, no. :P

**Comment by mtnbound** [comment]
It should work no problem. I had added it to my local Pi version, and it was working fine.

**Comment by thadius856** [comment]
Sounds good. Dump it on `rc-v1.0.0.x`, or create a pull request against that branch.

**Comment by kerber** [comment]
I'm just going to leave this here.... http://socket.io/

**Comment by kerber** [comment]
I see three options.
1. The page refreshes on a set interval. This means that the entire page has to refetch data from mysql and rerender every time.
2. We just use jquery's ajax and do long polling, refreshing the data in the page on a set interval. Still requires refetching data from mysql.
3. We use [websockets](http://socket.io/) to:
- Have the server push all data to the page only when it's updated (possibly complex)
- If a more complex update happens, like a beer being updated, the server pushes a message telling the page to do a full refresh. If a simple event happens, like a pour, the server just pushes that to the page and it updated the relevant data.

I'm inclined to # 3, as it's the most dynamic, but it depends on what everyone is most comfortable with.

**Comment by JayUnt** [comment]
Ive never used websockets before, but the faster the front end can refresh the better.

Would there need to be two web servers then? a node server and the apache.

**Comment by kerber** [comment]
Yeah, you run a node server on another port. It might end up being a little intensive for the RPi. I'm not sure how viable that option is with all the GUI running on the pi, though. It might be worth a test.

**Comment by JayUnt** [comment]
Yeah.  My biggest concern is getting the end user to setup another server
and it just might be too much for them.  I was originally thinking about
just polling the backend every x mins (which could be configurably in the
admin) and if there is activity, we could reduce the time, until there is
no more activity.  That polling could just do a page refresh if there was
any new pours or tap changes or whatever, or it could even make the changed
manually.  like if the amount left in the keg changes, we could animate the
keg amount getting smaller.

On Wed, Feb 19, 2014 at 7:54 PM, Kerber notifications@github.com wrote:

> Yeah, you run a node server on another port. It might end up being a
> little intensive for the RPi. I'm not sure how viable that option is with
> all the GUI running on the pi, though. It might be worth a test.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/134#issuecomment-35571358
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
> like if the amount left in the keg changes, we could animate the
> keg amount getting smaller.

Gonna be a pretty short animation (2 px at most) unless you're pulling quarts off a 3-gallon keg. ;)

**Comment by kerber** [comment]
You're totally right, JayUnt. Ajax long polling would probably be a great path for us.

**Comment by mcangeli** [comment]
http://raspberrypints.com/suggestion/page-auto-refresh/

Is the index.php page set with a meta refresh for the time being?

**Comment by thadius856** [comment]
I don't believe so.

Would be pretty easy to toss an extra config table value and wrap a meta refresh in an if statement.

If you decide to implement it, please do so on the feature-more_customization_options branch, since I've already started tearing into the db.

**Comment by JayUnt** [comment]
@Kerber and I have been looking into the 3 methods he posted above.  If we go one of the latter 2 options, it will be built into the flow sensor branch, since the new API that is being built for it, will push the notifications.  If we go with the set jquery interval, it can be done anywhere.

**Comment by thadius856** [comment]
Understood. Was answering the question asked.

**Comment by JayUnt** [comment]
I just didn't want multiple groups working on the same thing without each other knowing. If anyone else wants to look into the long-polling and websockets, let us know.  That way we can all discuss it together.

**Comment by mcangeli** [comment]
I think the quick temporary fix is to use the meta refresh route.

Once things like Temp and Pours are active and working, then the ajax long polling method would be ideal for updating the temps and keg levels as little of the other information would change. It may be a combination of the two actually. Ajax long polling to update the keg levels and then a separate method for refreshing the whole page when a new keg is tapped.

I think the biggest thing prompting this request at the moment is that the changes are being made in the admin section (logo, header, etc) on a separate machine and then the kiosk is not updating with the new logo, heading or beer added right away.

**Comment by Skemp45** [comment]
Opening a new issue for this with a summry of comments
