### ISSUE TITLE
Submit a bug

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#135]
Can someone please submit a bug from the bug form so I can see if it is properly importing into the bug tracking system

**Comment by thadius856** [comment]
Submitted.

Noticed a few typos on the form and confirmation pages.

**Comment by Skemp45** [comment]
DOH, lets get those fixed

**Comment by Skemp45** [comment]
OK......... SO. 
in order for users to be able to send us bugs and suggestions from within their panel we will need them to have an SMTP server on the pi because your bug requests are not getting sent out by the form mailer because there is no SMTP server. 

Option 1: Add the steps to install an SMTP server with the install instructions.

Option 2: Have the report bug and Feedback buttons link to a page on our website For example (http://raspberrypints.com/someform) and they will fill it out here. 

Thoughts?

**Comment by Skemp45** [comment]
http://rpi.tnet.com/project/faqs/smtp 

Good link explaining how to install SMTP

**Comment by JayUnt** [comment]
I like option 2 better.  Odds are they will have issues trying to install SMTP and then have to submit a bug, but then can't.  Less we put on them, the less they can break things.

**Comment by JayUnt** [comment]
Can we just use a wordpress issue tracking plugin?  or what about using issues in github? can we setup a different branch or something to allow anons to setup issues there.

**Comment by Skemp45** [comment]
hahahaha Talk about a catch 22. I need to report a bug about not being bale to report  a bug hahahahha

**Comment by Skemp45** [comment]
Yeah I am sure we can, have any in mind

**Comment by JayUnt** [comment]
Ive never used one before.  But Really Simple Issue Tracker seems to have the most downloads from the list

http://wordpress.org/plugins/tags/bug-tracker.
http://wordpress.org/plugins/really-simple-issue-tracker/

**Comment by jkurl** [comment]
The less people have to install and do things on their pi the easier it
will be and less chance of them either corrupting their install or worse
corrupting their SD card. Chances if that are small but as a technician I
try to make things as user friendly as I can and so easy a caveman can do
it. Sorry had to work that lame ass joke in.

**Comment by Boombrewer** [comment]
Option 2 with a link to the web page sounds the best to me and the easiest to implement in the short time before release.

**Comment by JayUnt** [comment]
And also if we have to make changes to the form, its on our site so we can make it whenever we want.  And not have to wait until a new release goes out.

**Comment by Skemp45** [comment]
Hahaha, I agree at this point. No point in having them host the file anyway. We will just do like contact form 7 or another contact form on the WordPress and just link to it.

**Comment by JayUnt** [comment]
Yeah contact form 7 will work. Then we can just add it as an issue into
GitHub

**Comment by Skemp45** [comment]
Yeah that works for me. one less tool to manage

**Comment by Skemp45** [comment]
OK, 
ALL DONE IN DEV BRANCH

installed contact form 7
updated left_bar.php to make buttons link to form on website
removed formailer.php, feeback.php, and report_bug.php as they are no longer needed.

**Comment by Skemp45** [comment]
the contact form submits to support@raspberrypints.com which just forward to thad, jay, and myself and we can then add them here in github

**Comment by Skemp45** [comment]
As soon as I get some Sounds good's and right on man's I will close issue

**Comment by JayUnt** [comment]
i didn't test it, but You Da Man!

**Comment by thadius856** [comment]
Not tested, but same.

Sorry, still at work.

**Comment by Skemp45** [comment]
We should be good on this closing
