### ISSUE TITLE
Password Rest (Not Working)

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#136]
So the password reset built into the admin, sends the password in plain text, which would work even through its not the most secure. BUT because we MD5 encrypt the password, it sends you the MD5 Hash code which is useless. 

We can either make a form where they fill in the info and it updates the database or have a walk through on how to change through DB and then in v2 have the form.

**Comment by JayUnt** [comment]
I know its going to be more work for now, but i think keeping the end users out of the db is the best way to go.  But if there is not enough time to build/test, just go with the instructions.  Maybe we should write an update script that changes the password to admin, and then they can just run that.

**Comment by Skemp45** [comment]
That would work. Someone want to throw the script together

**Comment by thadius856** [comment]
If we have /var/www as 777, could a user outside the network run the script
to reset a password maliciously?

**Comment by Skemp45** [comment]
I have been meaning to talk to you guys about 777/ Why are we running wide open perms? we should be able to run 705's

**Comment by sevlabs** [comment]
Setting anything to 777 will come back around as a security risk at some point.

**Comment by Skemp45** [comment]
:+1:  ^

**Comment by thadius856** [comment]
Seriously, we discussed this in length in like 5 different issues.

We keptnhaving problems with the installer failing, the logos not
uploading, the admin panel not saving things, and other quirky issues.

I'm not attached to 777, but every time it was asked what we need, nobody
volunteered 705 or any other number. Are you sure 705 across the board is
what we need?

**Comment by sevlabs** [comment]
Sorry, I'm late to this 777 party. I can research this issue but I'll probably need to acquire a Rpi so I can replicate the (Unix?) file structure in question. I probably won't be able to complete this by launch date.

Maybe try 755 for now and see if that works? Unix nerds (like me) are sure to have a field day when they find 777 permissions on a networked system.

**Comment by Skemp45** [comment]
with 1.5 days left to finish the scripting on this Monster  let me get some quick replys on the logic you guys want on the password reset. I was thinking this. 

user goes to forgot password page >> puts in email >> emailed a link to reset password >> goes to link inputs new password submits it >> this updates database.

We will have to make the link from the email create a session and have the reset page check for that session so people cant visit password reset file directly

**Comment by jkurl** [comment]
Shawn,

```
As a user I think that would be the best route. I don't really care for
```

systems that have a security question but I understand the need to a 2 step
validation. With most people they aren't going to make this system be
available outside their own network.

When I have been testing it on my mac I have saved the user name and
password in my keychain so I don't have to enter it in. Several reason to
doing this one being lazy and two quicker access to the system.

Another question is what if they forget their user name?

**Comment by Skemp45** [comment]
forgot username works, they hit the forgot user button out in email and it emails it to them

**Comment by Skemp45** [comment]
ERRRRRRRRRRRRRRRRRRRRRRRRRRRRR issue. With having it send a password reset email to their email they would need to have an SMTP server installed....... same with sending username. I have it working now where when they go to forgot password they can put in email and new password and it just updates it. but if anyone knows your email they can reset it if they want. IDEAS on this????

**Comment by jkurl** [comment]
Shawn

  How hard would it to be to code a form into admin panel w/ the security
questions and have it reset right then again if they know your security
question answers they can change your password.

Jerry

**Comment by Skemp45** [comment]
I was just thinking that myself. Might be our only option 
![login](https://f.cloud.github.com/assets/6318869/2152456/4f25e77a-9419-11e3-8a02-3974116f4882.png)

**Comment by jkurl** [comment]
I like that. Looks slick and neat. Your the man shawn

**Comment by Boombrewer** [comment]
Also guys, let's take a step back and really thing about this.  Its not like we're housing bank information in this thing.  If someone wants to hack my RPints and rearrange things, will I be pissed and will it take me some time to fix - yes.  But in the big scheme of things, I could nuke the SD card and start over from the very beginning and be out less time than it takes me to brew an all grain batch of beer.

IMHO, I'm really only keeping my wife out of it so she doesn't get click happy and muck things up.  Or am I missing a larger security threat that just isn't even on my radar?

**Comment by Skemp45** [comment]
Well. Here is what I will do. for v1 we will make it the basic put in email and new password and it will update it. in v2 as an increased security update we will have it check security questions. Sound good?

**Comment by Boombrewer** [comment]
Sounds great to me.  As a tertiary option, we add in a FAQ that if you're absentminded enough to forget your most important and treasured username/password, here's directions to nuke your folder and re-install from scratch. ; ) 

Sometimes stupidity should be painful.

(Skemp, I'm just busting your balls man - you're doing a great job. Thanks)

**Comment by Skemp45** [comment]
I committed  a change to the dev branch. created sendpassword.php this sends the new password into the database and md5 encrypts it. I also updated email_to.php which is the page with the password reset form on it. I will also work on changing the forgot my username page. for the FORGOT USERNAME page do we want to have it echo the username or just let them reset it?

**Comment by thadius856** [comment]
Echo.

Maybe add a "Change username" function to v2 once logged in.

**Comment by JayUnt** [comment]
We should also add that secret password question/answer to the install screen when they create the user.  That way its required to set, as opposed to hoping they go to that screen to set it.

Could be v2 though.  If any bugs are sent about this, we can just tell them how to update it right through the db.

**Comment by thadius856** [comment]
Second.

**Comment by Skemp45** [comment]
email_tou.php was updated so now all you do is put in your email and it echos your username. password reset and getting your username are now done and ready for v1 release YAYYYYYY

**Comment by Skemp45** [comment]
![forgot user](https://f.cloud.github.com/assets/6318869/2161404/e40fc1ec-94c5-11e3-9d50-b3715f216adb.png)
![user](https://f.cloud.github.com/assets/6318869/2161405/e82128d4-94c5-11e3-9ca2-3866416edaf3.png)

**Comment by Skemp45** [comment]
Let me know what you guys think before I close this issue and consider it done

**Comment by EmDubeu** [comment]
I like it. I will test it tonight.

On Thu, Feb 13, 2014 at 9:50 AM, Skemp45 notifications@github.com wrote:

> Let me know what you guys think before I close this issue and consider it
> done
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/136#issuecomment-35005452
> .

## 

Mike Wright

**Comment by jkurl** [comment]
This should make it easy. Nice job shawn

**Comment by Skemp45** [comment]
Issue is fixed for v1 release
