### ISSUE TITLE
mb_strlen() error

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#137]
It looks like mb_strlen() was added to index.php. The problem is that mb_strlen() is not enabled with php by default.  So we either need to find a different function, or add instructions to enabling it.

**Comment by thadius856** [comment]
Was enabled on the Pi when I installed the LAMP stack. So were short php
tags.

Sounds like we need an entry in the FAQ, "What do I need to do to run this
on something other than a Pi?" or some such.

**Comment by mcangeli** [comment]
This was posted on the php page for mb_strlen

"If you find yourself without the mb string functions and can't easily change it, a quick hack replacement for mb_strlen for utf8 characters is to use a a PCRE regex with utf8 turned on.

$strlen = preg_match_all("/.{1}/us",$utf8string,$dummy);

This is basically an ugly hack which counts all single character matches, and I'd expect it to be painfully slow on large strings."

That would work if mb_strlen isn't available...

**Comment by thadius856** [comment]
strlen() would work if it never encountered extended Unicode characters.

**Comment by mcangeli** [comment]
Yea, the page said that mb_strlen was preferred...

I think though, that if you install via apt-get on a debian based system it comes enabled by default.

**Comment by thadius856** [comment]
Anybody have an objection to just adding a blurb to the install instructions and calling it good?

"Note: If you are not installing this on a Raspberry Pi, you need to ensure that you [enable short php tags] and [mb_strlen()]."     Of course, where [blah] is a link to some external article.

We even already have an "nbox" type for this in our WordPress theme and these users will be in the vast minority.

**Comment by JayUnt** [comment]
That works.  If there is enough confusion with it, we could show them how
to enable it. But for now just telling them its needed and they can google
it works for me.

On Wed, Feb 12, 2014 at 8:22 PM, thadius856 notifications@github.comwrote:

> Anybody have an objection to just adding a blurb to the install
> instructions and calling it good?
> 
> "Note: If you are not installing this on a Raspberry Pi, you need to
> ensure that you [enable short php tags] and [mb_strlen()]." Of course,
> where [blah] is a link to some external article.
> 
> We even already have an "nbox" type for this in our WordPress theme and
> these users will be in the vast minority.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/137#issuecomment-34939033
> .

## 

Jason Unterman

**Comment by mcangeli** [comment]
I think that works. Could even post a good php.ini file for download.

**Comment by Skemp45** [comment]
Here is the php.ini I run.

```
upload_max_filesize = 150M
post_max_size = 50M
expose_php = Off
register_globals = off
allow_url_fopen = off
max_execution_time = 500
magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
```

**Comment by Skemp45** [comment]
ok, where are we at with this? lets do what we need to to close this up

**Comment by Skemp45** [comment]
posted in the byo issue #71 what needs to be added to documentation so we can close this issue and the byo issue once done

**Comment by thadius856** [comment]
Added. Closing as completed.
