### ISSUE TITLE
Added Option to not track keg status

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#141]
I just added an option to a new branch under the development branch to not track Keg Status. Hopefully I used the branching in the manner you were hoping for Thad.

Also, I didn't want to mess with the personalize.php page, but technically "Track Keg Status" is not a show/hide column option. I was just going to add a new "Configuration" section under the show/hide, but since it's written as a while loop, there will need to be something (possibly a new column) to tell the code which section to put it under.

The categorization of the configs are not critical for V1, but I thought I would mention it, since it doesn't really fit in that personalize section.

Hopefully that makes sense :) It's been a long day!

**Comment by mtnbound** [comment]
Forgot to mention that we'll need to add a new row in the config table called "kegStatus" and display of "Track Keg Status?"

**Comment by Skemp45** [comment]
@mtnbound  looks like you are actively on. can you do what I am asking in #133 please. I am not on my home pc.

**Comment by mtnbound** [comment]
Done. I added it to the "keg tracking option" branch off the develop branch

**Comment by Skemp45** [comment]
any chance you can also push the logo to the dev branch?

**Comment by Skemp45** [comment]
because we prolly wont to the keg tracking option till v2 but the logo will be v1

**Comment by mtnbound** [comment]
I have a feeling users might complain if they have to constantly update the keg status. Since it's done it might be worth adding it to V1. Just a thought...

**Comment by Skemp45** [comment]
is it all done and functional? we just have a deadline of 1.5 days to stop scripting so I was trying to not add new features this close to the end?

**Comment by Skemp45** [comment]
but if its fully functional then I guess why not

**Comment by thadius856** [comment]
Is it fully functional? Is it tested? Is it ready for primetime?

**Comment by thadius856** [comment]
> I just added an option to a new branch under the development branch to not track Keg Status. Hopefully I used the branching in the manner you were hoping for Thad.

Btw, yes, you did everything right except the name.

In the future, let's try to keep to "feature-xxxxxx" where xxxxxx is the name of the feature we're working on. That'll keep it clear that it's a feature branch, and split off of `develop`.

**Comment by mtnbound** [comment]
It was developer tested, yes. It should still go through regular beta testing, but I ran quite a few scenarios through it for sure.

**Comment by thadius856** [comment]
Well, we still have 8 days, so I'll merge it in if you're confident we can work em out in time.

**Comment by EmDubeu** [comment]
I'll load and test.
