### ISSUE TITLE
Take Site Live

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#142]
I feel like sometime today or maybe this weekend we should take our website live just for a few hours to check how everything works and functions so far

**Comment by jkurl** [comment]
Shawn I think that is a good idea. I was gonna say can we still block the
masses but why not let them test it a little if they are paying attention.

**Comment by EmDubeu** [comment]
Great idea.

On Thu, Feb 13, 2014 at 8:20 AM, Jerry Livingston
notifications@github.comwrote:

> Shawn I think that is a good idea. I was gonna say can we still block the
> masses but why not let them test it a little if they are paying attention.
> 
> On Thursday, February 13, 2014, Skemp45 notifications@github.com wrote:
> 
> > I feel like sometime today or maybe this weekend we should take our
> > website live just for a few hours to check how everything works and
> > functions so far
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/RaspberryPints/RaspberryPints/issues/142>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/142#issuecomment-34995056
> .

## 

Mike Wright

**Comment by thadius856** [comment]
...can we still block the masses? Or hide the menu bars so they can't find
the page unless they know the filename?

**Comment by Skemp45** [comment]
Yeah I can remove the menu so that can't find the pages

**Comment by jkurl** [comment]
guys I just sent out a e-mail to the brew club I am a member of so this
should get you guys some more exposure.  This club is a really great bunch
and every now and then Jamil makes it to our meeting so I am hoping he
maybe on our mailing list.  this could be some good exposure for you guys.
 Just don't pull it like Flappy bird was if people become addicted to their
tap list. I wanted to say thanks to you guys for letting help out with
testing and putting up w/ my non-coding skills.  you guys rock.

V/r,
Jerry

**Comment by Skemp45** [comment]
Thank you for your help too Jerry, we all had a hugs part is all of this, Could not have asked for a better bunch of people to work with.

**Comment by mcangeli** [comment]
IF you're using wordpress you should be able to set it to maintenance mode where only the admins can see the live site.

**Comment by Skemp45** [comment]
Yeah, normally I would but we are using a plugin that allows users to view one page, the parts page but for some reason it lets even logged in admins to only see the parts page :/ meh

**Comment by thadius856** [comment]
I'm going to post our parts list on HBT and notify them that we're taking the site down in advance of the launch.

@Skemp45 can you please remove that single-page plugin and put the site in maintenance mode? thx!

**Comment by thadius856** [comment]
@mcangeli, please post your desired WP username/email so I can get you set up with access.

Even if you don't plan on contributing to the site itself, I'd like for you to be able to fix a typo or errant character, should you stumble upon one.

**Comment by sevlabs** [comment]
I've been slammed with work these past few days but I will have some free time this weekend. If there's anything critical that I can help with let me know!

**Comment by thadius856** [comment]
Nothing critical. Just keep eyes out for writing that seems pre-production,
less than professional, confusing, unclear, missing details, or outdated.

That applies to the admin panel, website, etc. etc.

**Comment by mcangeli** [comment]
Username: mcangeli

Pick a password and email me: mcangeli at gmail.com

**Comment by thadius856** [comment]
Sent.

**Comment by thadius856** [comment]
Login to the WordPress admin panel.

Not seeing you in the users list, though.

**Comment by mtnbound** [comment]
Thad: Just a quick note that the links to Amazon didn't copy to your HBT post. I know we weren't doing this referral thing, but there is a lot of "view this item on Amazon" text with no links. Don't want you to get 100 questions about it on the HBT thread :)

Not sure it matters, but just wanted to let you know.

**Comment by Skemp45** [comment]
@thadius856 and everyone else. 

You can all now view the website if you have an active user. To everyone else it just says coming soon.

**Comment by EmDubeu** [comment]
I still see coming soon. :(

**Comment by EmDubeu** [comment]
never mind. i fixed it.

On Fri, Feb 14, 2014 at 8:42 AM, Mike Wright emdubeu@gmail.com wrote:

> I still see coming soon. :(
> On Feb 14, 2014 8:10 AM, "Skemp45" notifications@github.com wrote:
> 
> > @thadius856 https://github.com/thadius856 and everyone else.
> > 
> > You can all now view the website if you have an active user. To everyone
> > else it just says coming soon.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/142#issuecomment-35097277
> > .

## 

Mike Wright

**Comment by jkurl** [comment]
I am looking through the site now. Looks good so far. I am about the head
to the airport and fly Thad's way for a week w/ the family. Not sure how
Thursday is gonna work when this is released. I am sure the questions will
be blowing up on HBT.

**Comment by jkurl** [comment]
Found that SD Association downloads takes you to the RPi downloads page I
know the tool is on the same page as the downloads but wouldn't we want to
directly link to the SD formatting tool?

**Comment by jkurl** [comment]
Guys the support email was from me as a test. Sorry to banging out 500
emails but I am trying to do this and wrap stuff up for my upcoming
deployment.

**Comment by sevlabs** [comment]
I still can't access the live site. Sad face.

**Comment by thadius856** [comment]
Seven, send me your email.

**Comment by Skemp45** [comment]
this has been done and we are working on site, issues closed

**Comment by EmDubeu** [comment]
Hey guys, what was the name of the WP plugin we used for maintenance?

On Mon, Feb 17, 2014 at 5:09 AM, Skemp45 notifications@github.com wrote:

> Closed #142 https://github.com/RaspberryPints/RaspberryPints/issues/142.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/142
> .

## 

Mike Wright

**Comment by thadius856** [comment]
The one that worked was Hide My Site.
