### ISSUE TITLE
Valentines Day message To users

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#143]
I wanted to let subscribers know we are aware of them and get them excited for the release date. Also figured I could wish them a happy valentines day. Here is what I wrote. Look ok?

**Comment by Skemp45** [comment]
Happy Valentine’s Day from your Raspberry Pints team.

Hello everyone, we would just like to take a second and thank each and every one of you for your support and suggestions over the last month. This project would not be what it is if it was not for your kind words, suggestions, the want for the program, and the overall enthusiasm for the project. We have been busting tail these last few weeks with the deadline coming quickly upon us. We hope you spend much time with your significant others and friends this Valentine’s Day because, a few short days after (February 20th) you will be like a hobbit in a cave testing and playing with the program. We encourage your participation after the first release as well, we are expecting many suggestions for updates and changes and this is the only way we can make Raspberry Pints the best it can be. At any time you can post on the Home Brew Talk thread or drop us a line at Support@raspberrypints.com.  Lastly we really hope you enjoy Raspberry Pints and that it meets all of your expectations.

**Comment by Skemp45** [comment]
Sorry, idk why its formatting like that in here

**Comment by EmDubeu** [comment]
Like it. No suggested edits.

On Thu, Feb 13, 2014 at 10:39 AM, Skemp45 notifications@github.com wrote:

> I wanted to let subscribers know we are aware of them and get them excited
> for the release date. Also figured I could wish them a happy valentines
> day. Here is what I wrote. Look ok?
> 
> ```
>                 Happy Valentine's Day from your Raspberry Pints team.
> ```
> 
> Hello everyone, we would just like to take a second and thank each and every one of you for your support and suggestions over the last month. This project would not be what it is if it was not for your kind words, suggestions, the want for the program, and the overall enthusiasm for the project. We have been busting tail these last few weeks with the deadline coming quickly upon us. We hope you spend much time with your significant others and friends this Valentine's Day because, a few short days after (February 20th) you will be like a hobbit in a cave testing and playing with the program. We encourage your participation after the first release as well, we are expecting many suggestions for updates and changes and this is the only way we can make Raspberry Pints the best it can be. At any time you can post on the Home Brew Talk thread or drop us a line at Support@raspberrypints.com.  Lastly we really hope you enjoy Raspberry Pints and that it meets all of your expectations.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/143
> .

## 

Mike Wright

**Comment by Skemp45** [comment]
![hopletter](https://f.cloud.github.com/assets/6318869/2163491/d0787a74-94df-11e3-9385-2e50132d7321.png)
Added a little flare

**Comment by EmDubeu** [comment]
damn fine addition.

On Thu, Feb 13, 2014 at 10:51 AM, Skemp45 notifications@github.com wrote:

> [image: hopletter]https://f.cloud.github.com/assets/6318869/2163491/d0787a74-94df-11e3-9385-2e50132d7321.png
> Added a little flare
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/143#issuecomment-35011766
> .

## 

Mike Wright

**Comment by jkurl** [comment]
Rock on shawn that new addition makes me want to go out and have a few
awesome beers

**Comment by Skemp45** [comment]
:+1:

**Comment by thadius856** [comment]
Typo in the the program name. We have no space! :P

Otherwise, looks great.

Its formatting pre because you indented the first line with multiple spaces.

**Comment by mcangeli** [comment]
Looks good.

**Comment by Skemp45** [comment]
Message was sent to 96 people!!!!!!!!!
