### ISSUE TITLE
redirect to /install if not configured

### ISSUE THREAD

**Issue by tssgery** [RaspberryPints/RaspberryPints#147]
I know v1.0.0 is not out yet, but I have been playing with it a little. I'd suggest that you redirect users to the /install url if the app is not yet configured. 

The easiest way I know of to do that is to test for the existance of the includes/config.php file and, if not found send a redirect. This can be done by placing the following lines as the first lines of /index.php

```
<?php
        if (!file_exists(__DIR__.'/includes/config.php')) {
           header('Location: /install', true, 303);
           die();
        }
?>
```

**Comment by JayUnt** [comment]
Agreed.

And with the next version, we should check that the database is setup for
the code base. If the database is a version/versions behind, redirect then
to the install page to run the update scripts.

**Comment by mtnbound** [comment]
I actually do the version checking now. I check that the code version and the DB version is the same. If it's different, I give them the "Upgrade" option.

One other thing I was thinking of doing for V2, it putting a API on the website that just returns the current released version. On the admin screen, we can check that the installed version is the same as the latest version. I couldn't see a way to call Git to get the latest version, so I figured it would be very easy to just add it to a raspberrypints.com API.

**Comment by JayUnt** [comment]
Yeah, oh saw the upgrade in the install. But we should force them to the
install page if an upgrade is available.

And telling they there is a code upgrade is a good idea.

**Comment by JayUnt** [comment]
And by "if upgrade is available" i mean, if they upgraded their code but not the database. I think if they know there is a new version of the app, but don't want to install any of it, let them stay behind.

**Comment by mtnbound** [comment]
I agree. Force redirect if the code and DB are different, but notify if new version is available.

**Comment by thadius856** [comment]
> <?php
>         if (!file_exists(**DIR**.'/includes/config.php')) {
>            header('Location: /install', true, 303);
>            die();
>         }
> ?>

I tried adding this. It blanked the page, and didn't redirect to `install`.

Not seeing any syntax errors myself...

**Comment by tssgery** [comment]
I tested that on my debian lamp instance and it redirected perfectly with chrome. Firefox and other browsers should work fine as well.Those lines should be the first lines in the file; with no blank lines before them.

When I ran it from the cli ("php5 index.php"), you won't get any output or errors if it works. Did you try that?

**Comment by tssgery** [comment]
If it's easier, I can test again tomorrow and send a pull request with the changes

**Comment by tssgery** [comment]
I had a few minutes so retested and submitted a pull request.

Pull request #148 contains the proper code; it has been tested on a debian 7 lamp system with php5

**Comment by thadius856** [comment]
Closed pull request.

Create pull request against `rc-1.0.0.x` branch instead of `master`.

**Comment by tssgery** [comment]
I had done it in master so it could be tested before pushing to rc-1.0.0.x, but can do rc-1.0.0.x directly as well. Pull request #149 submitted

**Comment by thadius856** [comment]
Accepted and merged in. Pulled to my local folder.

Yup, blanking...

**Comment by tssgery** [comment]
I tested it right before I submitted. when you run php from the cli, do you get any errors?

Alternatively, what environment are you testing with? I can try to recreate your environment

**Comment by thadius856** [comment]
Environment? The Pi, LAMP.

**Comment by thadius856** [comment]
Also, explain "php from the cli"?

**Comment by thadius856** [comment]
Nvm, I get what you mean.

`PHP Parse error: syntax error, unexpected '<' in /var/www/index.php on line 8`

**Comment by tssgery** [comment]
hmmm. Interesting. You may have a different version of php than I do. This should be easy to address though. you should be able to remove line 6 ("?>") and line 8 ("<?php") so that my additions are placed within the original php block.

**Comment by tssgery** [comment]
If that doesn't work, let me know what software you have running on your pi. Did you download a prebuilt LAMP SD card image, or did you install apache2/php/mysql yourself? I can follow those same steps and test in the same environment

**Comment by thadius856** [comment]
Packages we installed (after aft-get update/upgrade):

apache2 php5 mysql-client mysql-server php5-mysql phpmyadmin
chromium-browser ttf-mscorefonts-installer x11-xserver-utils unclutter

**Comment by tssgery** [comment]
Raspian Wheezy? or a different image?

**Comment by thadius856** [comment]
Yes, correct. From NOOBS v1.3.4 in my case.

**Comment by tssgery** [comment]
I am not sure what is going on as I just installed Raspian Wheezy NOOBS from scratch and the RaspberryPints rc-1.0.0.x branch seems to work fine for me. Here is what I did after installing Raspian:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install apache2 php5 mysql-client mysql-server \ 
                     php5-mysql phpmyadmin chromium-browser \
                     ttf-mscorefonts-installer x11-xserver-utils unclutter
cd /var
sudo rm -rf www
git clone -b rc-1.0.0.x https://github.com/RaspberryPints/RaspberryPints.git /var/www
```

After that, I went to another machine, opened both firefox and chrome and validated they both redirected to the /install uri

**Comment by thadius856** [comment]
Hrm. Nuked everything I had, reloaded it all, and everything works now.

Tested deleting config.php, and the redirect was successful.

**Comment by thadius856** [comment]
Only problem now is that we're trying to import schema again, when it already exists. Of course, this creates errors.

So either we need to add a lot of "IF NOT EXIST" statements to the schema, or we need to make the schema a checkbox to select/deselect, or (best yet) check if the schema is already there and skip if so.

**Comment by tssgery** [comment]
correct on the re-import of the schema; The current install will try to reimport schema if the config.php file gets removed. 

I'm not sure if it'd be best to skip creation if the schema already exists or allow the user to select a checkbox that says something like "delete database if it already exists". Both have their pros and cons.

I would suggest that a separate github issue is opened to tracked the issue though; it's really not related to the redirect function.

**Comment by Skemp45** [comment]
is this resolved for v1 release?

**Comment by thadius856** [comment]
The basic redirect is, yes.

**Comment by mtnbound** [comment]
Just a comment on this. When I was testing the install code, I was having problems with this redirect.

Since I use Apache virtual directories, it was taking me to the main "localhost/install" rather than my virtual directory "localhost/rp/install"

The second issue is that apparently index.php is not a default page on my virtual directory WAMP setup, so I was being redirected to a directory listing. The redirect is to the /install directory not the /install/index.php file.

Not sure it's any big deal at all since not too many people are using WAMP virtual directories, but just thinking we might want to standardize on the way we redirect so we can account for any setup.

Just thought I would mention it.

**Comment by tssgery** [comment]
yeah, I think you're right.

It would be good to change the redirect to allow virtual directories and to specify the php file to load explicitly.

I don't have a mechanism handy to test it out but I _think_ if you modify line 3 of /index.php to say...

```
header('Location: install/index.php', true, 303);
```

It should resolve both problems?

**Comment by Skemp45** [comment]
was this updated?

**Comment by tssgery** [comment]
I didn't update it as I don't have an environment handy to test it. I can set one up but it won't be real quick as work is very hectic this week.

**Comment by mcangeli** [comment]
It was working the other day when I did a reinstall of my PI

**Comment by tssgery** [comment]
I just double checked and the change to /index.php above...

```
header('Location: install/index.php', true, 303);
```

Address both problems. 

Pull request #209 address this

**Comment by thadius856** [comment]
Pull request completed. Closing.
