### ISSUE TITLE
Website feature page

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#151]
I was noodling around the site and noticed we've still got a few future features listed on the features page. The following should be removed:
- Beers poured from each keg
- Amount left in each keg

**Comment by thadius856** [comment]
I noticed this too. This was on my list of things to take care of this weekend, but honestly, I haven't had the drive.

Burning out a little bit on documentation and Joe-proofing. It's far-and-away the largest part of my time on this project. :\

**Comment by kerber** [comment]
If you don't mind giving me access, I can take a fresh look. I've got some free time tomorrow.

**Comment by thadius856** [comment]
Email address, please.

**Comment by kerber** [comment]
I did a pretty thorough click-through. I found a few broken links and what not, but they're all dealt with now.

**Comment by Skemp45** [comment]
Closing as resolved if we come across more issues on site please open a new issue
