### ISSUE TITLE
update site url

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#152]
Once we are ready to take site live I will need to update the site url. it is currently raspberyrpints.com/site and I will move it to raspberrypints.com so when linking to things make sure you link for the future not how it is currently. 

**_FOR EXAMPLE**_
I need to update the report a bug and make a suggestion links in the admin panel go to our form on the website. the url is currently- http://raspberrypints.com/site/report-bug-make-a-suggestion/. I am going to update the script to reflect http://raspberrypints.com/report-bug-make-a-suggestion/

**Comment by kerber** [comment]
I don't believe the links within the pages update dynamically. Any link to another page will need to be updated.

**Comment by thadius856** [comment]
They don't? Hrm...

**Comment by kerber** [comment]
Maybe they do, but I had to update most of the links on the bottom of the guide pages. They were still pointing to what the links for the pages used to be before being renamed.

**Comment by Skemp45** [comment]
I can handle the updates. I have a tool to replace all

**Comment by kerber** [comment]
Right on. Sounds good!

**Comment by Skemp45** [comment]
#flawless
