### ISSUE TITLE
Admin panel - coming soon

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#153]
How does everyone feel about all the 'coming soon' buttons in the Admin panel left bar? I'm inclined to think that this actually diminishes all the work that's been done and sets expectations really really high. Maybe I'm crazy (almost certainly am), but I like to err on the side of caution when it comes to dropping info on new functionality.

**Comment by thadius856** [comment]
Those buttons were added so I could get a feel for the spacing and page length. It's filler text.

Feel free to comment.

**Comment by kerber** [comment]
That makes total sense. I think it would be good to remove them before release. I know it's last minute, but I think it's going to cause a lot of buzz around things we aren't ready to address.

**Comment by jkurl** [comment]
I agree with Kerber. It has already happened in the HBT thread.

**Comment by thadius856** [comment]
Dooooo eeet.

**Comment by kerber** [comment]
I'm at work without access to my git, but I can make the changes directly from github, if you don't mind me making them directly to dev.

**Comment by thadius856** [comment]
Would prefer to the rc branch, but direct is fine.

**Comment by Skemp45** [comment]
Nice work, much cleaner

**Comment by Skemp45** [comment]
alright, we have 2.5 days until release, no more new add-ons at this point, just troubleshooting bugs and cleaning things up. Lets do this people. I know we are all a little burnt out after a month plus of non stop scripting and working this project but we are so close and lets not disappoint.

**Comment by kerber** [comment]
I didn't merge the changes into the RC. I'll leave that to someone who knows what the hell they are doing.

**Comment by kerber** [comment]
Ok. I put in a pull request from develop to rc-1.0.0. Can someone make a double check and merge if they don't find any issues?

**Comment by Skemp45** [comment]
@kerber resolved in issue #154 closing this issue, if issues arise we can reopen

**Comment by kerber** [comment]
The pull request is still open.

**Comment by Skemp45** [comment]
Yeah, but assuming that gets done we are all good on this

**Comment by thadius856** [comment]
Pull request merged in and closed.
