### ISSUE TITLE
Facebook page? 

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#155]
What do you guys think about creating a Facebook page for RaspberryPints? I feel like it can help the project spread more virally, but I don't know if it just adds another place for us to check for people's issues. We can have a generic message for anyone who posts an issue, sending them to the bug form on the site.

**Comment by Skemp45** [comment]
Social media is good :D it also gives us a place to receive praises

**Comment by thadius856** [comment]
I log in like once per year, so you dont want me running it.

**Comment by kerber** [comment]
I'm fairly active, so I wouldn't mind modding it.

**Comment by Skemp45** [comment]
same here

**Comment by Skemp45** [comment]
https://www.facebook.com/pages/RaspberryPints/1458042767747445

**Comment by Skemp45** [comment]
like it then send a message so I can add you guys as admins please

**Comment by jkurl** [comment]
Shawn,

  I don't have a FB account so I am out of that one.

Jerry

**Comment by jkurl** [comment]
What about creating a support team for Rpints. I am not coding anything
just testing. By creating this team we could collect the issue and offer
solutions and if it is a issue that needs correcting in code the support
team could open the issues in GitHub and close them as we'll. this would
leave more time for cranking out bugs by Thad, shawn and the rest of the
coding team. What does everyone think about this?

**Comment by Skemp45** [comment]
is there any rule against posting our Facebook page in the HBT thread?

**Comment by Skemp45** [comment]
@jkurl It would be awesome to have a support team but that would take up alot of time and resources. with us giving this away for free thats alot of stuff we are giving them. Also then if we do that people will expect us to troubleshoot their issues and we cant always deliver on that

**Comment by jkurl** [comment]
I can see that. I was looking for ways to take the pressure off of you guys
that are coding and doing the large bulk of the work.

**Comment by Skemp45** [comment]
Issue is fixed, closing now
