### ISSUE TITLE
Offer a script that installs pre-reqs and sets up Raspberry Pints

### ISSUE THREAD

**Issue by tssgery** [RaspberryPints/RaspberryPints#157]
I've developed a rudimentary script that configures a new Raspbian image for RP usage and then downloads Raspberry Pints, setting up phpMyAdmin and getting it to the stage a user could get to the /install page. I've tested this with NOOBS 1.3.4

I have put this script in my RaspberryPints fork, on the master branch, so you can have a look at it and decide if/where you want it: https://github.com/tssgery/RaspberryPints/tree/master/util

Feel free to not utilize this if it doesn't make sense. I wrote it for my testing purposes and thought it might be generally helpful.

**Comment by jkurl** [comment]
Guys at this point w/ the launch happening in a few days I think any new
code or possible additions should wait till version 2 or 1.5. Shawn is
trying to clear issues out and adding this in at the last minute could
complicate things and overwhelm the team with support issues. I have seen
way to many last minute inclusions derail many a projects in my time and I
would hate to see the something happen here.

**Comment by tssgery** [comment]
I don't disagree :+1: 

Just saying that this script is available when/if people want it.

**Comment by jkurl** [comment]
Eric I am a big fan of scripts just a little late in the game. Can you send
me a quick write up on it. I plan on wiping my pi and will test it from
scratch. That way it can be tested ahead of time and if the team wants to
use it the bugs can be found well before v2 come outs.

**Comment by tssgery** [comment]
Instructions and an overview are at the head of the script; the link is in the first comment. let me know if you have questions.

**Comment by Skemp45** [comment]
this is awesome, we will add this to v2 FOR SURE

**Comment by kerber** [comment]
I just checked it out. Solid script, man! Good form, too.

**Comment by tssgery** [comment]
Thanks for the feedback, let me know if you think of anything else that needs to be added/checked

**Comment by thadius856** [comment]
Looks pretty solid. You seem to have already anticipated quite a few cases.

BRANCH should probably be master though. :)

**Comment by tssgery** [comment]
The script is setup to pull and install the release candidate. Will that be released from 'master' or from 'rc-1.0.0.x'?

**Comment by thadius856** [comment]
On release day, `rc-1.0.0.x` will be merged into `master`. From there, a Release will be created.

Not sure how GitHub's Release feature is supported in git, if it all.

**Comment by thadius856** [comment]
However, master and the Release should always be done together, never apart, and always within minutes of each other.

**Comment by tssgery** [comment]
If master always contains the latest release, it's a trivial change to make.

That does have some implication on upgrades/updates being applied but I'm sure you can handle it (for example, once 2.0.0 gets released and merged to 'master', anyone running from a git tree could 'git pull' and get the 2.0 code with a 1.0 database schema). 

I'll make the BRANCH name change to the script in my repo.

**Comment by thadius856** [comment]
Oh boy. Hrmmm...

Perhaps it would be better to wget a release zip, and manually update it each release?

Ex:
https://github.com/RaspberryPints/RaspberryPints/archive/0.5.0.275-beta.zip
https://github.com/RaspberryPints/RaspberryPints/archive/0.9.0.0.zip

Tar's are available with the different extension, in case you prefer untar to unzip, but then we lose the functionality of git.

**Comment by tssgery** [comment]
You really have two options that I can think of:

1) Go with what your current branching model and make sure that you handle any database upgrade logic (i.e. have a php include file that checks the database version and upgrades it if necessary). This isn't a high throughput application with terabytes if data so the slight hit of checking the database version on a page refresh will be negligible.

2) Change your branching model to have a branch per version (like you do now) but cut any release zips or instruct users to pull from a specific branch. Within that release, keep the database schema consistent to avoid issues. in this model, 'master' is not really used much. This means that when users want to upgrade, it's more manual work as they need to move branches and apply database upgrades anyway.

I would REALLY keep the ability to have users directly pull the code with git. Don't force them to pull a compressed archive. Linux users haven't dealt with zip/tar file releases for years.

Given the two options above, number 1 is the better choice and not really much more work than number 2. You have to handle any database upgrade logic somewhere anyway and Linux users are very used to rolling upgrades as changes are committed to git repositories.

**Comment by jkurl** [comment]
Nice explanation Eric. When I was building android from source a quick repo
sync and the new additions were added w/ out pulling a compressed file.
Would be a whole lot easier to roll in the updates and lots less headache

**Comment by mcangeli** [comment]
I was slowly working on this as well. There's a simple way to do a bash script that will install everything and grab the repo so that all that has to be done is launching a browser and going to the local host.

**Comment by Skemp45** [comment]
@mcangeli You cool with this as v2 or are you done with this?

**Comment by Boombrewer** [comment]
@mcangeli Don't forget to include the install of an init.d file to start the flow monitor python script.

**Comment by Skemp45** [comment]
You should be able to import it or start it at the beginning of the python script. I will look at it

**Comment by mcangeli** [comment]
There are some changes to the original script above that would need to be made in order to use this with the flow meter branch, but its simply adding the extra packages for apt-get to install.
