### ISSUE TITLE
Website Main Image

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#160]
We need to update the main image on the front of our website. It is the old style background and different keg, ibu, and srm images.
![mainpage](https://f.cloud.github.com/assets/6318869/2207284/bee8a4f0-9971-11e3-9665-9373d354a800.png)

**Comment by thadius856** [comment]
Done.

![untitled](https://f.cloud.github.com/assets/6320180/2207627/e87ea5ea-9975-11e3-8920-d63dfc693792.png)

**Comment by Skemp45** [comment]
Awesome
