### ISSUE TITLE
Site Was Visible

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#164]
Heads-up. Looks like the site has been visible, if you knew the right URLs to view.

Guess what gave it away? 404 pages.

I've installed Hide My Site addon and turned on password protection. The password isn't really important, as our admin logins override it. However, if you need to, feel free to change it. Just don't make it anything guessable.

**Comment by jkurl** [comment]
That took care of the HBT app as well. Password screens pops up.

**Comment by Skemp45** [comment]
:o THE HELL lol thanks for fixing Thad

**Comment by Skemp45** [comment]
closing as resolved. nice work Thad
