### ISSUE TITLE
Updating Contributors Page

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#165]
I am changing the contributors section where it says "Special Thanks To:" to "Assistant Contributors". I was debating between "Junior Contributors" or "Project Assistants" but I think that Assistant Contributor has the best ring to it and most accurately portrays what we are trying to give credit for. 

After reviewing, I can see how "Special Thanks To" could be slightly insulting or belittling to the time and effort that was put in by these guys. It is the same type of phrasing that would be used to say "A Special Thanks to our Sponsors" or basically a virtual pat on the back, which could be seen as being slightly ungrateful...etc., etc. 

I am also adding @SevenXXX to the "Assistant Contributors" as it appears that somehow throughout the merging process his label did not get added into the final version. 

If you recall, he is the one that created the disable ABV image option; so of course we would want to give credit for that. 

If anyone has any input or additional opinions on the wording of this section let me know by 12 noon tomorrow 2/20/14 so that it can be added to the final version.

**Comment by EmDubeu** [comment]
Assistant Contributor sounds fine to me.

**Comment by thadius856** [comment]
Sounds great to me.

Thanks for tackling this. Seven pointed out to me last night that he fell
off the list. I suspect others have as well.

Definitely clears up my evening a no for the release.

**Comment by Skemp45** [comment]
Yeah I think something happened with all the merging that was going on and somehow his name dropped but he is added back on now :D

**Comment by Skemp45** [comment]
Glad we are all good, closing as resolved
