### ISSUE TITLE
Delete or chmod 000 to Install

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#166]
We need to decide what we want to do to the install folder once installed. 

My suggestion is remove it. and already have wrote this option by using if file exsists. 

```
     <?php
    if (file_exists("../install")) {
       ?><div class="error status"><span> <?php print "For security reasons, please delete, move or rename the install directory before you use your tap list"; ?> </span></div><?php
    }
?> 
```

**Comment by Skemp45** [comment]
![add](https://f.cloud.github.com/assets/6318869/2195847/5ffa61e8-98a6-11e3-8217-53ebb6e3002d.png)

**Comment by mtnbound** [comment]
I like the way the Skemp implemented this. That way if a user (mostly devs) wants to keep the folder for clearing data, etc, they can keep it. 

Most should and will delete.

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task
