### ISSUE TITLE
VERY IMPORTANT READ!!!!!!!!!

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#167]
At 6 PM tonight, drop what you are doing and crack a beer and join me in celebrating all the hard work we all have done in the past month and a half.

WHOS EXCITED????

**Comment by Boombrewer** [comment]
I'm down for that!  Just wish I could've done more of the heavily lifting.

Just to say it again - you guys did an amazing job!

**Comment by thadius856** [comment]
Yerp, I'm down. Will be in the IRC channel too.

**Comment by jkurl** [comment]
Man I saw you message pop up on my phone and I thought it said you were
down and in the ER.

**Comment by Skemp45** [comment]
:| that would not be good. I will jump in the IRC at release time

**Comment by Skemp45** [comment]
OH YEAH, just puttogetehr the new list of subscribers, I will check for new ones before I send out tonight but we are at 180!!!!!

**Comment by EmDubeu** [comment]
Yea... Baby...

On Thu, Feb 20, 2014 at 9:21 AM, Skemp45 notifications@github.com wrote:

> OH YEAH, just puttogetehr the new list of subscribers, I will check for
> new ones before I send out tonight but we are at 180!!!!!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/167#issuecomment-35645738
> .

## 

Mike Wright

**Comment by JayUnt** [comment]
Is this 6pm PST or EST?

Ill be down for PST, but i cant at EST.

**Comment by Skemp45** [comment]
5 hours 51 minutes from right now so what ever time that makes it for you ;) im horrible at time conversion

**Comment by Skemp45** [comment]
Here is the IRC meet up info in case you lost it
https://github.com/RaspberryPints/RaspberryPints/wiki/IRC-Channel

**Comment by Boombrewer** [comment]
@Skemp45 I thought you moved all the information stuff to the Wiki on Github?  When I click on it, it only shows the link to the website.  Is it a permission thing or am I just lost?

**Comment by Skemp45** [comment]
the link about to the irc info?

**Comment by Boombrewer** [comment]
All the stuff that was in the issues section that was just for information purposes and not really issues.  You commented in all of them saying they were moving over to the wiki section to clean up the issues section but I don't see anything in the wiki.

**Comment by Skemp45** [comment]
https://github.com/RaspberryPints/RaspberryPints/wiki/_pages

**Comment by Boombrewer** [comment]
Thanks.

boy am I an idiot some times.  It would have helped if I had clicked on the pages tab.  : (

**Comment by Skemp45** [comment]
haha no worries

**Comment by Skemp45** [comment]
doing this now
