### ISSUE TITLE
Website Admin roles

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#168]
Ok, now that we are going to release this to the world we really should limit down the number of users on our website that have admin perms. Right now we have 10 people with admin rights. We can leave them all but drop some to Author or Editor. 
If you NEED admin rights please post below so I know who to leave!

**Comment by Boombrewer** [comment]
I'd be happy to help out where I can but feel free to kill my access if you have enough help already.

**Comment by Skemp45** [comment]
I have no problem leaving you  on as a editor so you can still make changes etc. Its just having 10 Admins stresses me out lol.

**Comment by jkurl** [comment]
If you have me as an admin drop me to editor. I don't need admin access.

**Comment by mtnbound** [comment]
You can drop me as admin as well, if I'm listed. Happy to update content, but don't need admin for sure.

**Comment by Skemp45** [comment]
ok, list your username as well please :D

**Comment by jkurl** [comment]
Klinklotus is my username

**Comment by Skemp45** [comment]
ty

**Comment by thadius856** [comment]
I was going to post this tonight, but you beat me to it.

Once the password wall drops, no need for 10 admins.

**Comment by Skemp45** [comment]
I reduced all non staffers to editors which is one lvl below admin for security purposes. you can still make content changes just not structure changes like plugins etc.

**Comment by JayUnt** [comment]
Since ive never made a change to the wordpress site, you can drop me down too.  If i need a change, ill just let you guys know.

**Comment by Skemp45** [comment]
All taken care of
