### ISSUE TITLE
MAKE A RELEASE 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#169]
LETS DO THIS

@thadius856 Will you go ahead and delete the other 2 releases Beta and Testing Release Functionality and make a v1 release and then in 1 hour and 38 minutes its go time

**Comment by jkurl** [comment]
They are already wanting it released. I told them 6pm PST. The timer had
less than an hr a few mins ago.

**Comment by Skemp45** [comment]
how much time should it have?
I will adjust quick

**Comment by jkurl** [comment]
2.5 hrs. It is 3:30 here on the west coast. Isn't it releasing at 6PM PST

**Comment by Skemp45** [comment]
Yeah
how does it look now

**Comment by jkurl** [comment]
It shows 3 hrs and 22 mins. Close. Adjust it back by an hour

**Comment by Skemp45** [comment]
ok i just did

**Comment by jkurl** [comment]
Awesome job shawn. Looks good.

**Comment by thadius856** [comment]
Still at work. If it's 20 minutes out, I won't be home. If it's 1 hr 20
mins out, I will be.

Let me know what you need me to do.

**Comment by jkurl** [comment]
The release should be in 1hr and 15mins out

**Comment by Skemp45** [comment]
yeah its 505 PST and we want to release at 6PST so you have 45 min and all we need to do is make a release for v1 from the rc-1.0.0.x branch

**Comment by thadius856** [comment]
I'll make a release just as soon as I finish wiping... ;)

**Comment by Skemp45** [comment]
Closed and released right on time nice work
