### ISSUE TITLE
Update to Bootstrap?

### ISSUE THREAD

**Issue by paulcanning** [RaspberryPints/RaspberryPints#170]
Just a recommendation to use Bootstrap in order to give a responsive user experience.

Plus it looks pretty too.

**Comment by thadius856** [comment]
Not familiar. Can you give more info?

**Comment by JayUnt** [comment]
thanks  for the suggestion, well see if we can using bootstrap will clean up the site.

@thadius856  He is talking about twitter bootstrap, which is a css/js library to help with responsive design and just some neat js features.
http://getbootstrap.com/

**Comment by paulcanning** [comment]
Is is this closed as in "we're going to do it" or closed as in "we are not going to do it" ?

**Comment by Skemp45** [comment]
At this time I do not think this will be the best route to take the front end of the site, this is something we can revisit but with no advancement on this and the current avenue we are taking RaspberryPints I do not think bootstrap will be the best option
