### ISSUE TITLE
Launch Day: The Hotwash

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#173]
Now that we're publicly released, it's time to do a hotwash. That is, take a look at how things went, where we did well, and where we can improve for next time.

Confused? Read this: http://emilms.fema.gov/IS921/921_Toolkit/downloads/NPPD_HotWash.pdf

This is the time to have your say!

Consider the following:
- Building the feature list
- Setting the cutoff date
- Branching
- Versioning
- Creating the release
- Public communication (including social media)
- etc etc.

So. What went well? What didn't? What would you change if you'd had the foresight to know what you know now?

**Comment by Boombrewer** [comment]
I think the release went really well.  We had a couple small details missing from the install instructions but they got corrected quickly.

I think the communication with the public could be better as far as what to expect - features list and what-not.  I completely understand locking down the website but once we locked down the features we were including in V1 and what we were putting off till V2, we could've put that out there so everyone knew what to expect.  I know a lot of things were covered in the HBT thread, but that gets daunting when it reaches huge numbers of posts.

All-in-all, I think it went about as good as it could've gone.  I was on the HBT thread pretty late and there were more successes than problems.  And judging by the number of people who were pulling it down at the opening, it was obviously highly anticipated.  Solid work gentlemen.

**Comment by Skemp45** [comment]
Consider the following:

```
----Building the feature list----
```

we need to do a better job this time selecting our feature list and STICKING TO IT. to make sure we release on time we need to make sure that we do not add features half way through the project. 

```
----Setting the cutoff date----
```

We did a good job settign a reasonable cut of date Good job all

```
----Branching----
```

This was handled well after @thadius856 built the branching how to

```
----Versioning----
```

We will see how this is handled going forward.

```
----Creating the release----
```

@thadius856 Very nice job getting this set and you grabbed the right branch it was Perfect

```
----Public communication (including social media)----
```

This speaks for itself, because of the sheer ammount of traffic we got right on release. We have been  1 3 5 and 6 on reddits homebrewing sub redit all week. We started the Facebook page and I created a twitter and the facebook is starting to boom and we are getting user participation. Nice work all. lets keep this up

**Comment by thadius856** [comment]
**Building the feature list**

I think this went well. Though we didn't stick to what we had planned, we knew where we wanted to go generally. As long as we footstomp that feature lists are a guide for our development, and not a promise to our users, I think we'll be fine.

**Setting the cutoff date**

I feel like we might have pushed it out a little far. I found myself about 10 days from the cutoff without any new features to work on because I didn't want to bloat the feature list.

**Branching**

We had a couple stumbles, but nothing irreversible. The good thing is, if you don't feel comfortable with full-fledged branching of the origin, you can always clone a branch to your own account and create a pull request back.

**Versioning**

Think we're doing good here. We just need to remember to update it each release.

**Creating the release**

Some bumps here. Can't seem to figure out how to delete old releases. The official documentation seems to indicate it's possible, but I can't find the button they describe. Anybody else able to try to delete 0.5.0.0-beta and 0.9.0.0 releases?

**Public communication (including social media)**

Was not expecting to see us on Reddit. Some of the negativity there threw me for a loop, but I think I maintained by cool. HBT is a mess, full of "Written on my iPhone!" posts with typos and no pictures describing what they're talking about, but there's nothing we can do about that.

**Comment by Skemp45** [comment]
I saw the negativity but your right, keep your cool. there are so many TROLLS out there and all they are waiting for is for you to fight back then they go off. :D @thadius856 I saw on HBT you said you were going to release hotfix for version 1.0.1. Please let me know when you release it so I can blast it out on social media

**Comment by thadius856** [comment]
Roger dodger.

**Comment by jkurl** [comment]
Guys,

   sorry this is coming in late.  I got back to work today and found out I had training all week for a new program coming online for casualty response so I just now got time to write this up.  I want to say thank you again for letting helping you out(in my limited ways).

V/r,
Jerry

Building the feature list
  This was a pretty smooth release and while there was a bit of confusion of what was going to be used for the flow meter hardware, the group did a great job keep the confusion to minimum.  giving them a preview of what could be coming down the pipe would not hurt as long as key words like this is a possible feature and it is still in the development stages. Please do not commit to any hardware until we test out what will work and what the best route in all aspects of this project for the end user.

Setting the cutoff date
    This seem to be a moving target and things were being added at the last minute with very small amounts of time to test it.  put a hard target for a release date that is realistic and a coding cutoff date for current features. this could be a week before the release and focus on squashing bugs.

Versioning
  This needs to happen so everyone knows what the current release is. sticking to versioning like 1.10 maybe even go out to 1.101 but keep it simple.

Creating the release
  a good option for this would be to create a release 72hrs out, then 48hrs and finally a 24hr release to test any last minute fixes and locate bugs not  previously discovered.  A last minute release could have been something that caused this project to fail. I know yo all have full time lives but organizing your releases will give you more time to focus on potential failures in the project.

Public communication (including social media)
  This was executed very well. hitting numerous social media outlets helped bring more exposure but having numerous outlets leads to even more work of keeping up with not just improvements but answering support related question of general FAQs. I know I mentioned a support team to help with this stuff and still believe one is needed.  There are about to be more complex features that will  be coming down the pipe and opening it up to the community could bring on a whole new set of features that take a lot of time to develop and provide support. I know this is not a business but the route you guys are heading is pushing this to a larger scale project and the potential to be displayed in business. why would someone pay for some other the other services that cost a lot when they can use your feature rich taplist that is free.

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task
