### ISSUE TITLE
Not Receiving Emails :(

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#175]
@Skemp45, I'm not receiving any emails at thad@raspberrypints.com

Did we break something?

Jay has a few support emails, and I haven't seen a single one yet.

**Comment by jkurl** [comment]
Is admins the only one suppose to get emails or is admins and editors
suppose to get them as we'll.

**Comment by Skemp45** [comment]
thad, you should be getting them jay and myself have been getting them and replying. I will send you a test now. reply back if you get it

**Comment by JayUnt** [comment]
Skemp,

I put the the bugs/enhancements into github.  I also replyed to the people
who sent the emails. If you did too, we sent them two emails which is not
horrible, but not really a good thing.  We should coordinate who is in
charge of replying to the emails and putting them into github.

On Sat, Feb 22, 2014 at 4:36 AM, Skemp45 notifications@github.com wrote:

> thad, you should be getting them jay and myself have been getting them and
> replying. I will send you a test now. reply back if you get it
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/175#issuecomment-35798781
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Skemp, I got your test. But haven't been getting the bug ones.

**Comment by Skemp45** [comment]
I will review today

**Comment by Skemp45** [comment]
@jayunt if you want to handle the emails and moving the issues to GitHub that's fine

**Comment by JayUnt** [comment]
Sounds good.  Take some of this off of your plate, since you have a lot of stuff you are doing.

**Comment by Skemp45** [comment]
Thanks @JayUnt. and @thadius856 DURRRRRRRRRRRR I had your cc in as thad@raspberypints.com, I missed an r lol. fixed now

**Comment by Skemp45** [comment]
Closing

**Comment by thadius856** [comment]
Hurr durr. :P
