### ISSUE TITLE
Adding new Keg requires input in a non required field

### ISSUE THREAD

**Issue by dlgreenwald** [RaspberryPints/RaspberryPints#176]
When attempting to add a new keg with no detail the page silently fails to add the keg to the keg list.  Dropping in a debug statement after the write shows that the save does not check to see if it was successful.  In this case the problem is that "Invalid query: Incorrect decimal value: '' for column 'weight' at row 1".  The result is that the input fails unless you put a valid number in the field.  It's also not validated by the javascript, like the first item is.

**Comment by Skemp45** [comment]
Fixed in hotfix1
