### ISSUE TITLE
Beer details must be reentered when tapping a keg

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#177]
From: Sean Power (Arglesnaf on HBT) sean@seanjpower.com
Subject: Beer details must be reentered when tapping a keg

Message Body:
I read the rational for this in git hub, but it is not great for Commercial Beers, Soda, Seltzer et al.

**Comment by JayUnt** [comment]
I guess when we make a non-beer category, we should also make a commercial beer category.  This way the user can put in the abv and thats it.  They dont know the og, fg and all of that info.

**Comment by EmDubeu** [comment]
Good point.  If the user enters a value in the OG and FG fields, then
calculate the abv. Right?

**Comment by Skemp45** [comment]
Yeah, lets go ahead and do that as alot of people using this might tap a keg of something and not know original readings. This also makes the product scalable to non homebrewers.

**Comment by thadius856** [comment]
I think I recommended this like a month ago. ;)

Perhaps we need to keep these separate from table `beers`?

**Comment by Skemp45** [comment]
opening new issue with direct problem
