### ISSUE TITLE
If you have an error tapping a keg, its status is switched to serving

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#178]
From: Sean Power (Arglesnaf on HBT) sean@seanjpower.com
Subject: If you have an error tapping a keg, its status is switched to serving

Message Body:
If you do no enter all the data on the tapping a keg screen, the keg is not added to the tap, but the keg status is still set to serving.

**Comment by thadius856** [comment]
Indeed a bug, if it happens.

**Comment by thadius856** [comment]
Unable to reproduce. Steps taken:

Added an extra tap on "My Taps".
Clicked "Tap a Keg"
Selected a beer from the dropdown and a keg that's ready to be tapped.
Deleted the shown IBU value.
Attempted to submit the form.

The form recognizes that there is missing data and refuses to submit. Checked the status of the keg, and it is unchanged.

**Comment by JayUnt** [comment]
I will email Sean back and ask him which fields he did not enter.

**Comment by Skemp45** [comment]
Yeah I could not duplicate either.

**Comment by Skemp45** [comment]
any update? can we close? We have had no other reports of this

**Comment by JayUnt** [comment]
I want able to reproduce either.
