### ISSUE TITLE
Tap # Column Not Centered

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#18]
During the CSV->SQL conversion/CSS cleanup, some items lost proper alignment.

In particular, the tap # column is not centered (vertically not horizontally). Extraneous hr tag in column header. Suggest also applying CSS trick to beautify number (ex: http://labs.kaliko.com/2012/04/circled-number-with-pure-css.html). See screeshot:

![untitled](https://f.cloud.github.com/assets/6320180/1866595/11316820-7837-11e3-9ada-ac417d445c9d.png)

**Comment by Skemp45** [comment]
http://labs.kaliko.com/2012/04/circled-number-with-pure-css.html seems to be a dead link for me, I removed the HR and # from the tap column and it looks much better. Going to try to get that link to load so I can see what you are wanting.

**Comment by Skemp45** [comment]
Here, I got the link to load and this is what they look like, any color suggestions? Also I need someone else to put their eyes on the centering of the numbers vertically, see if you can get it to listen. I cant seem to get it centered exactly center!

![tapwithcircle](https://f.cloud.github.com/assets/6318869/1868747/1c4ac042-7870-11e3-953e-3bc5f36cf384.png)

**Comment by thadius856** [comment]
Hey cool, images load in email even though GitHub is blocked here. Go
figure.

Looks pretty nice. The top gap doesn't bother me particularly. Though the
closeness of the text from one row to the next makes for hard reading.

The numbers look great. I expect we could add that color setting to the
Admin page eventually to let users pick what they like. As for a default, I
trust your judgment on colors. Right now the bg and font color are a little
close to each other, at least apparently on this crummy 5-year-old TN
panel. My faux-8-bit panels at home may be easier to read, or maybe not.

Thad

**Comment by Skemp45** [comment]
Ok, whats the status on this? are we happy with the current look of the tap column? 

![tapside](https://f.cloud.github.com/assets/6318869/1874870/9c5990ca-78dd-11e3-8765-c9fe45d4f1e8.png)

**Comment by thadius856** [comment]
I like what you're seeing, but I'm not seeing it on the most recent commit. Downloaded approx ~30 mins ago.

![untitled](https://f.cloud.github.com/assets/6320180/1874886/e567a77a-78dd-11e3-983d-c25bc70edf05.png)

Perhaps it got lost in the merge? :\ Ugh, this has a learning curve. 

Vertical Centering still appears to be off in your screenshot.

Maybe go a few shades darker with the BG color, or alpha 50%.

**Comment by thadius856** [comment]
Here's what I'm seeing in the CSS:

```
.TapNum {
text-align: center;
float: left;
height: 50px; 
width:50px;
}
```

**Comment by Skemp45** [comment]
ok, so I dont mess this up again...... how should I push my css sheet

**Comment by thadius856** [comment]
Go to the front page of the Master branch.

Click the word "Fork" in the upper-right hand corner.

Make your edits.

Click "Compare and Review" or "Create Pull Request" when done with your fork. It's usually a green button.

**Comment by Skemp45** [comment]
#22 here ya go

**Comment by thadius856** [comment]
Merged. Closing as resolved.
