### ISSUE TITLE
Keg select on tap admin screen

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#180]
From: Brandon brandon@whatisboom.com
Subject: Keg select on tap admin screen

Message Body:
The select is not populated with <options> corresponding to my kegs that have been entered. I can insert options with values that equal my keg id's and it validates/works.

**Comment by thadius856** [comment]
I'm having a hard time understanding what this user is trying to describe.

Can somebody with a better grasp of the problem clue me in?

**Comment by JayUnt** [comment]
I think the keg dropdown doesn't have anything in it. He added the options directly in the html and it works for him. That's what I think he is saying. I'm guessing it's a keg status issue, for them not showing. I haven't had a chance to look into it though.

**Comment by JayUnt** [comment]
OK this has to be that he added a keg that is with status SERVING.  and then went to the tap form and it wasnt showing up.  The fix is really the clarification of the statuses.

I think we should get rid of SERVING, and add READY_TO_SERVE and ON_TAP.  We can make it so the only way for it to be ON_TAP is when you add a keg to a tap through the admin.  We do not allow the user to set this status.  This should make it less confusing to the user.

Thoughts?

I am going to email the guy back and tell him to change the status from SERVING to PRIMARY and then he should be able to add it to a tap.

**Comment by thadius856** [comment]
I think ON_TAP is still ambiguous. How about TAPPED?

READY_TO_SERVE? I don't have any feelings either way about this one. _shrug_

**Comment by Skemp45** [comment]
Agree with taking the choice out of the users hands. Make it alot cleaner and easier to allow the on tap top handle the status of the kegs. I like On Tap and Ready To Serve

**Comment by Skemp45** [comment]
Old thread see no current value, if there is valuable info please add as a new issue with a descriptive title
