### ISSUE TITLE
keg form is requiring too many fields

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#184]
Since we don't have a way to push db changes yet, this will have to wait until we do.

But we need to make most of the properties of the keg table nullable.  All of the fields are not null, even though they shouldn't be.  The only ones that should be not null are:
- id
- label
- kegTypeId
- kegStatusCode
- active
- createdDate
- modifiedDate

After we make these alters, we can revert the keg form back to not require the changed ones that were made for #183.

**Comment by JayUnt** [comment]
Im working on this bug inside the feature-flow_monitor release, since i'm already working in that branch.

**Comment by Skemp45** [comment]
Closing, if not already done please reopen under issues
