### ISSUE TITLE
The default apache page just doesn't seem to go away. 

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#185]
Support email from Bryan Hargrave, bryandhargrave@gmail.com.  Im not really sure what command he is talking about.    If no one knows, i will email him and ask which he is referring to.

```
The default apache page just doesn't seem to go away. You know, the
"It works!" page. I can edit my list of taps and kegs and beers and
blah blah... but that page just won't go away no matter how many times
I send the command. Can I manually replace it in Raspbian somewhere?
```

Can we automatically look and delete the default index file in our install script?

**Comment by mcangeli** [comment]
Should be possible to.

It looks like 
unlink ( _ DIR _"/index.html");
(remove the spaces between the _ and DIR)

Would do the trick.
I haven't tested this yet though as my pi is offline...

**Comment by mcangeli** [comment]
Just tested this on a different server and unlink deleted the file I specified in the parenthesis

**Comment by JayUnt** [comment]
I haven't worked on any of the the install stuff, so if whoever did, wants to add it, that would be great. (That looks like too many commas for one sentence...)

**Comment by Skemp45** [comment]
![commachameleon_fullpic_artwork](https://f.cloud.github.com/assets/6318869/2240560/cef970d2-9c9a-11e3-8267-49883b41ebaa.jpg)

**Comment by Skemp45** [comment]
@mtnbound You were head on install, can you add this?

**Comment by mtnbound** [comment]
Sure, no problem. I'll just delete it at the end.

**Comment by thadius856** [comment]
@mtnbound While you're in there, can you take a look at #181?

**Comment by mtnbound** [comment]
What branch are we working in now? Do you want me to clone the release, or the hotfix branch?

**Comment by thadius856** [comment]
Hotfix-v1.0.1

You can push directly to it, or edit directly on the site, or send a pull request. Whatever is easiest for you.

**Comment by mtnbound** [comment]
Should be completed. Pushed to Hotfix branch

**Comment by thadius856** [comment]
Can you guys publish hotfix branch today?

And post in the HBT thread afterwards.

**Comment by Skemp45** [comment]
@thadius856 I will try, whats the release name supposed to be?
1.0.1?

**Comment by Skemp45** [comment]
And whats the detailed report on what has been updated

**Comment by Skemp45** [comment]
- Test
- test2

**Comment by thadius856** [comment]
@Skemp45 I put all of my notes into the hotfix milestone, except maybe CSS
cleanup. And yes 1.0.1.xxx.

**Comment by Skemp45** [comment]
https://github.com/RaspberryPints/RaspberryPints/releases

**Comment by Skemp45** [comment]
tested the hell out of this and it seems to all be in order. made a release. blasted on social media and HBT also emailed out update

**Comment by Skemp45** [comment]
I also figured out how to remove the 2 test releases
