### ISSUE TITLE
Georgia typo in style.css

### ISSUE THREAD

**Issue by shepikoff** [RaspberryPints/RaspberryPints#186]
Line 7: font: 1.5em Gerorgia, arial, verdana, sans-serif;

Can get rid of all the other Georgia font family assignments further down.

**Comment by thadius856** [comment]
Nice catch.

Fixed the typo, removed all of the Georgia font callouts except for on table h2{} and table h3{}.

No idea why, but when I try to remove Georgia on those, h2 and h3 end up the same size, but suddenly bold. Go figure.

**Comment by shepikoff** [comment]
The table h2 and table h3 issue is caused by the browser default style. There are no user defined font-weights for each. This can be addressed by adding font-weight properties for the standard h# tags and then using table h# tag to override and adjust those properties. Also, further in after removing the redundant "Georgia" tags, we should now use just font-size unless there are plans to collapse all font properties into shorthand.

**Comment by thadius856** [comment]
> Also, further in after removing the redundant "Georgia" tags, we should now use just font-size unless there are plans to collapse all font properties into shorthand.

I think I moved this direction. Let me know if you meant something other than what I did in the commit above.

> This can be addressed by adding font-weight properties for the standard h# tags and then using table h# tag to override and adjust those properties. 

Can you demonstrate? I'd love to fiddle today, but I have to get milling and doughing in soon to finish before dark.

**Comment by shepikoff** [comment]
Yeah, you got the font-size corrected, I missed it. Let's say we moved all the table h1 {} properties into h1 {} as:

```
h1 {
    color: #FFFFFF;
    display: block;
    font-size: 1.5em;
    font-weight: bold;
    margin: 0;
    opacity:1;
    }
```

Now we don't have to use table h1 {} until we need to override the global h1 properties. Cheers! Got my batch done yesterday.

**Comment by thadius856** [comment]
Nice. Applied this change. Will commit and push momentarily.

If you (or anybody else reading this) feel inclined to cleanup the CSS, please feel free to send a pull request. I'm stretched a few too many ways at the moment to go through a full cleanup again. :\
