### ISSUE TITLE
Install instructions wrong. 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#187]
We tell them to delete the default apache index, which is index.html but we say DELETE INDEX.PHP!!!!!!!!! FIRE LASERSSSSSSSSSSSSSSSS
![index](https://f.cloud.github.com/assets/6318869/2240484/55479dcc-9c95-11e3-981b-35f05e962206.png)
Fixing

**Comment by Skemp45** [comment]
Fixed

**Comment by thadius856** [comment]
Until we add it to the Install script...

**Comment by Skemp45** [comment]
;) right
