### ISSUE TITLE
The More You Know!!

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#188]
Just wanted to keep you all updated, Here are some stats from the websites performance. 
Feb 20th (Release Day)- 222 unique visitors. 
Feb 21st- 2,165 UNIQUE VISITORS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Feb 22nd- 1,226 UNIQUE Visitors!!!!!!!!!!!
And today so far at 7am pst we have had 146 unique visitors. 
11,864 page views. 
These numbers are outstanding and we need to be PROUD of this. I could not believe it when I saw this.

**Comment by thadius856** [comment]
Wow. Nice. :)

**Comment by kerber** [comment]
Excellent!
