### ISSUE TITLE
More simple flow monitoring

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#190]
Hey everyone,
I decided to run some tests today to see what the Alamode is capable of doing on it's own. I set aside the Centipede board and made another version of the Arduino code that reads from the flow sensors directly. I'm testing with 3 flow sensors, each at @ 1000 pulses/second. I'm getting 100% precision.

The MCP23017 route does offer a lot more expandability, but it's not needed for those who only care about keg levels for <12 kegs. This will give users another option at $25 less.

I've written this version to speak the same protocol for pours, so that it doesn't require any special measures in higher level code.

**Comment by thadius856** [comment]
Cool!

**Comment by kerber** [comment]
Right now it's looking like V2 will only really have flow monitoring as a hardware addition. Maybe we should stow the Centipede until we need it. That way, it can be a $25 upgrade that will allow certain new features, instead of another $25 and added complexity now.

**Comment by thadius856** [comment]
That's fine. Question, though.

> I've written this version to speak the same protocol for pours, so that it doesn't require any special measures in higher level code.

To be clear, how much code would we have to change later to add support for the Centipede?

**Comment by kerber** [comment]
The Arduino code would be the only change needed, and that would have to happen to add new features. Since we're not storing and data or settings on the Arduino layer, we don't have to worry about losing people's settings by updating all that code.

I'd just have to add my high-speed MCP23017 read code back into it.

**Comment by thadius856** [comment]
Sounds good, man. I might recommend leaving it in there, commented. I know I have trouble remembering what I ate for breakfast yesterday...

...no, wait. I remember. I never eat breakfast. :P

**Comment by kerber** [comment]
I'll probably just keep the separate version. There's enough separate changes that I don't want to keep it cluttering up the code.

**Comment by Boombrewer** [comment]
Nice work man!  That's great news.  And <12 keg limit even takes care of Thad.  I don't think there are too many homebrewers out there with 12 kegs or more.

**Comment by mcangeli** [comment]
I got the alamode and centipede the other day and put them together. Now I'm having issues with the pi again (the SD card slot is a bitch).

Kerber, have you diagrammed or documented anywhere how you're hooking the flowmeters up??

**Comment by thadius856** [comment]
Don't forget future use of solenoids, RFID readers, motion sensors, etc.

I could easily fill 25 GPIO pins if I had the code support for the hardware.

Wanna get really crazy? Temp sensors on each keg or in the line.

**Comment by kerber** [comment]
The SF800 should be wired up as follows with the red pin = pin1, the center  = pin2, and so on.
- Pin1 : ground
- Pin2 : data (use pullup resistor)
- Pin3 : 5v

**Comment by Boombrewer** [comment]
In the Arduino code, line 18 is "pinmode(13, OUTPUT);"
What is pin 13 used for?  I couldn't find anything in the code.

**Comment by kerber** [comment]
That line can be removed. Pin 13 corresponds to the on-board LED and was used for debugging purposes.

**Comment by Boombrewer** [comment]
So I see flow_monitor.py is writing data to a log file (which is does not create).  Was the plan to have the MCV framework utilize the log file to update the front end?  Is anyone currently working on this?

Also, is anyone against or have an opinion on having the python script update the MySQL db table 'pours' based on 'tapId'?  I just want to have an idea which path to devote my energy towards.

**Comment by mcangeli** [comment]
Kerber and I had a lengthy discussion about that. 

The feeling was that the python was only going to pass along the info from the flow meters to another php script that would then update the db.

I've got a version of this working that I will pass along.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:06/09/2014  12:34 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] More simple flow monitoring (#190) </div><div>
</div>So I see flow_monitor.py is writing data to a log file (which is does not create). Was the plan to have the MCV framework utilize the log file to update the front end? Is anyone currently working on this?

Also, is anyone against or have an opinion on having the python script update the MySQL db table 'pours' based on 'tapId'? I just want to have an idea which path to devote my energy towards.

**Comment by Boombrewer** [comment]
That would be awesome.  I was interested in how we were setting this us.  Do you have it working on the new MCV framework or on the old files?

**Comment by mcangeli** [comment]
The new mvc.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:06/09/2014  9:29 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] More simple flow monitoring (#190) </div><div>
</div>That would be awesome. I was interested in how we were setting this us. Do you have it working on the new MCV framework or on the old files?

**Comment by Boombrewer** [comment]
You just took a lot off my plate.  Thanks.  Know anything about serial communications between arduino and python?  I need it to go both directions periodically (like every minute or so).

**Comment by Boombrewer** [comment]
@mcangeli can I get that script from you?  It didn't look like it was uploaded anywhere.

Thanks.

**Comment by mcangeli** [comment]
I have to see if I can find it. The laptop I was doing development on is no
more and I'm not sure if my pi is still online at the moment....

I thought I had uploaded it to one of my repositories, but it doesn't look
like I did.

**Comment by mcangeli** [comment]
Boombrewer, I got the Pi back on line today. Will try and upload the two scripts I'm using as well as instructions on how to use them some time this weekend.

**Comment by mcangeli** [comment]
@Boombrewer https://drive.google.com/folderview?id=0B51uISJSIyOWa0t2WFBxRUFpYTA&usp=sharing

**Comment by Boombrewer** [comment]
@mcangeli Thanks man.  Hopefully I'll get a chance to implement them this week.

**Comment by mcangeli** [comment]
There are some parts that deal with the untappd stuff I had been working on... you should be able to comment that part out and it should work.

The python script looks for the utcheckin.php script to update the database and refresh the display monitor.

**Comment by Skemp45** [comment]
Old thread see no current value, if there is valuable info please add as a new issue with a descriptive title
