### ISSUE TITLE
Changing Logos/Background Fudges Permissions

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#192]
When you change the logos or background, it messes up the file permissions. I get:

-rw-r--r-- 1 www-data www-data  840952 Feb 22 17:42 background.jpg
-rw-r--r-- 1 www-data www-data  49727 Feb 22 16:42 logo.png

Then WinSCP throws angry errors at me because it can't update the ownership to match what's on the local side.

Any way to fix this?

**Comment by Skemp45** [comment]
Im not getting this. My perms are staying the same.....

**Comment by thadius856** [comment]
Odd. I'm definitely getting this. Also on admin/config.php as well.
