### ISSUE TITLE
Themes and Customization 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#193]
I have started playing around with different themes for the admin panel. thoughts?

They select what color admin panel they want 
![themecolor](https://f.cloud.github.com/assets/6318869/2241381/c31b260a-9cce-11e3-8a6f-af43ebab7a74.png)

Then this updates the database do the proper css style sheet.

![dbtheme](https://f.cloud.github.com/assets/6318869/2241382/d6ffad3a-9cce-11e3-991e-36a92ac008ce.png)

and we do the same thing we did with the 4k monitor option

**Comment by Skemp45** [comment]
![greentheme](https://f.cloud.github.com/assets/6318869/2241423/e4f5bafe-9cd0-11e3-80cc-bd04664910ef.png)

**Comment by Skemp45** [comment]
![redtheme](https://f.cloud.github.com/assets/6318869/2241424/eb111406-9cd0-11e3-94a8-9326c47879b9.png)

**Comment by thadius856** [comment]
Sounds like a plan, Stan.

We should probably avoid "xxxThemeColor" for the frontend, as it may entail different layouts and boarders and etc. "xxxThemeNumber" ?

**Comment by thadius856** [comment]
Btw, looks weird that your red and green versions default to "Blue" in the dropdown.

**Comment by Skemp45** [comment]
Yeah, I just have to add a small piece of code in to make it be set to what the db value is

**Comment by Skemp45** [comment]
and yes, front end will be much more complex

**Comment by Skemp45** [comment]
@JayUnt opinion on this. currently here is what I am doing. 

```
$sql="SELECT configValue FROM config WHERE configName ='".ConfigNames::AdminThemeColor."'";
            $result=mysql_query($sql);
            $stylesheet=mysql_fetch_array($result);
```

and then for the stylesheet

```
<link href="<?php echo $stylesheet['configValue']?>" rel="stylesheet" type="text/css" />
```

can you make this a function? because it has to be put on every page this way.

**Comment by Skemp45** [comment]
and to set the different stylesheets for each color i am doing this. 

```
<?php
        if (isset($_POST['color'])) {
require_once 'includes/functions.php';

// Get values from form 
$color=encode($_POST['color']);

// update data in mysql database
$sql="UPDATE config SET configValue='$color' WHERE configName='adminThemeColor'";
$result=mysql_query($sql);

if ($result){?>
<script>window.location=("themes.php");</script>
<?php
}

}
?>
        <div class="contentbox">
        <a name="columns"></a>

<form method="post" name="color" action="">
    <h2>Select Admin theme Color:</h2>
    <select name="color">
<option value="styles.css"<?php if ($color_select['configValue'] == "styles.css") echo "selected";?>>Blue</option>
  <option value="styles_green.css"<?php if ($color_select['configValue'] == "styles_green.css") echo "selected";?>>Green</option>
  <option value="styles_red.css"<?php if ($color_select['configValue'] == "styles_red.css") echo "selected";?>>Red</option>
</select>
<input type="submit" class="btn" value="Save" />

</form>
```

**Comment by Skemp45** [comment]
```
INSERT INTO `config` VALUES(14, 'adminThemeColor', 'styles.css', 'Admin Color', 0, '2014-02-24 07:18:46', NULL);
```

Here is the db change if you want it

**Comment by thadius856** [comment]
I think youre missing a `NOW ()` on that insert

**Comment by Skemp45** [comment]
Yeah, replace the NULL

**Comment by JayUnt** [comment]
We can/should definitely make that into a function. Create a config_manager.php and have a getByName(configName) function.  

As for the <link href..../>, we should really have a header.php that has all of the generic header stuff, and each page will include that.    It should include the common content as well, like the header bar, and the side bar.   That way the pages, just really have content that is specific to that section.

**Comment by Skemp45** [comment]
ok I like that and im not too familiar with using includes or require how do we make it so the files in the lets just say header.php will pull no matter what directory the file using the header.php is in?

**Comment by Skemp45** [comment]
Hope that makes sense

**Comment by Skemp45** [comment]
Could we just make a file called header.php that looks like this?

```
<?php
require_once __DIR__.'/includes/conn.php';
require_once __DIR__.'includes/configp.php';
require_once __DIR__.'/../includes/config_names.php';
require_once __DIR__.'/includes/html_helper.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/models/beer.php';
require_once __DIR__.'/includes/managers/beer_manager.php';
require_once __DIR__.'/includes/managers/beerStyle_manager.php';
?>
```

**Comment by Skemp45** [comment]
and that would work for anything in the /admin

**Comment by Skemp45** [comment]
Ok here is what I did.
header.php

```
<?php
require_once __DIR__.'/includes/conn.php';
require_once __DIR__.'/../includes/config_names.php';
require_once __DIR__.'/includes/html_helper.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/models/beer.php';
require_once __DIR__.'/includes/managers/beer_manager.php';
require_once __DIR__.'/includes/managers/beerStyle_manager.php';
require_once __DIR__.'/includes/config_manager.php';
require_once 'includes/models/keg.php';
require_once 'includes/models/kegType.php';
require_once 'includes/models/kegStatus.php';
require_once 'includes/managers/keg_manager.php';
require_once 'includes/managers/kegStatus_manager.php';
require_once 'includes/managers/kegType_manager.php';
require_once __DIR__.'/includes/managers/tap_manager.php';
require_once __DIR__.'/includes/configp.php';
?>
```

As you can see I include config_manager.php here is that file.

```
<?php

$sql="SELECT configValue FROM config WHERE configName ='".ConfigNames::AdminThemeColor."'";
            $result=mysql_query($sql);
            $stylesheet=mysql_fetch_array($result);
?>
```

**Comment by Skemp45** [comment]
this broke the personalize page where you can turn on and off columns though so I had to move the require_once **DIR**.'/includes/configp.php'; below the require_once **DIR**.'/includes/config_manager.php'; and it worked. I assume because it gets processed last then

**Comment by Skemp45** [comment]
Ok, I have a good jump on this can someone make a branch called feature-adminthemes and I will update code there

**Comment by JayUnt** [comment]
Yeah.  you can also move actual html into the header.php.  SO you could move the opening html tags, and whatever common code into there.  i would suggest we move this into the header too

```
!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>RaspberryPints</title>
<link href="styles/layout.css" rel="stylesheet" type="text/css" />
<link href="styles/wysiwyg.css" rel="stylesheet" type="text/css" />
    <!-- Theme Start -->
<link href="styles.css" rel="stylesheet" type="text/css" />
    <!-- Theme End -->
<link href='http://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
</head>
```

Then on every page its already there.  If we even want to change the font and use a different google font, we just have to update it in one spot.

**Comment by Skemp45** [comment]
ok I will update all that and if someone can make me that branch I will add files

**Comment by Skemp45** [comment]
BOOM DONE 

so we already had a header.php which was just the top menu, SO i recalled that top_menu.php and updated all the includes calls for it. 
here is the new header.php

```
<?php
session_start();
if(!isset( $_SESSION['myusername'] )){
    header("location:index.php");
}
require_once __DIR__.'/includes/conn.php';
require_once __DIR__.'/../includes/config_names.php';
require_once __DIR__.'/includes/html_helper.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/models/beer.php';
require_once __DIR__.'/includes/managers/beer_manager.php';
require_once __DIR__.'/includes/managers/beerStyle_manager.php';
require_once __DIR__.'/includes/config_manager.php';
require_once 'includes/models/keg.php';
require_once 'includes/models/kegType.php';
require_once 'includes/models/kegStatus.php';
require_once 'includes/managers/keg_manager.php';
require_once 'includes/managers/kegStatus_manager.php';
require_once 'includes/managers/kegType_manager.php';
require_once __DIR__.'/includes/managers/tap_manager.php';

$sql="SELECT configValue FROM config WHERE configName ='".ConfigNames::AdminThemeColor."'";
            $result=mysql_query($sql);
            $stylesheet=mysql_fetch_array($result);

require_once __DIR__.'/includes/configp.php';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>RaspberryPints</title>
<link href="styles/layout.css" rel="stylesheet" type="text/css" />
<link href="styles/wysiwyg.css" rel="stylesheet" type="text/css" />
    <!-- Theme Start -->
<link href="<?php echo $stylesheet['configValue']?>" rel="stylesheet" type="text/css" />
    <!-- Theme End -->
<link href='http://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
</head>
```

**Comment by Skemp45** [comment]
look ok?

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/admin
User: admin
Password: admin
go to theme options under Personalization
play with it. let me know what you think

**Comment by Skemp45** [comment]
closing as this is finished and in the theme branch
