### ISSUE TITLE
Setup Documentation Missing -y Option

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#196]
Could somebody go through and add the -y option to each `sudo apt-get install` instruction?

**Comment by jkurl** [comment]
Rhad I can do it. I just got I to seTtle so it will be about a hour. I will
correct the raspi-config image as well

**Comment by jkurl** [comment]
Thad,

  Got the -y and updated the install for the newer raspi-config.  we can
possibly take out expand file system.  NOOBS automatically does it for
them.  I usually install the OS via cmd line in terminal on my mac so we
can leave it in there incase people install the raspbian image that way.
 look over the changes and let me know what you think.

Jerry

Jerry

**Comment by thadius856** [comment]
Looks awesome.

Yeah, lets lose expand rootfs.

**Comment by jkurl** [comment]
i can take it out then. let me edit it real quick.

**Comment by jkurl** [comment]
all done. give it a look.

**Comment by jkurl** [comment]
does the --kiosk localhost need to be edited as well?

**Comment by jkurl** [comment]
Closed #196
