### ISSUE TITLE
Autosizing and Vertical Centering Within Divs

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#2]
Autosize the vertical direction of and vertically center metrics and graphics within their DIVs.

Affected DIV classes:
- [ ] .HeaderLeft {}
- [ ] .HeaderCenter {}
- [ ] .HeaderRight {}
- [ ] .TitleBarSRM {}
- [ ] .TitleBarIBU {}
- [ ] .TitleBarBeerName {}
- [ ] .TitleBarABV {}
- [ ] .TitleBarKeg {}
- [ ] .OGnumber h3 {}
- [ ] .SRMimage img {}
- [ ] .SRMnumber h2 {}
- [ ] .BUGUnumber h3 {}
- [ ] .IBUimage img {}
- [ ] .IBUnumber h2 {}
- [ ] .BeerName {}
- [ ] .BeerStyle {}
- [ ] .TastingNotes {}
- [ ] .TastingNotes div {}
- [ ] .KCALnumber h3 {}
- [ ] .ABVimage img {}
- [ ] .ABVnumber h2 {}
- [ ] .KegColumn {}
- [ ] .PouredNumber h3 {}
- [ ] .KegImage img {}
- [ ] .LeftNumber h2 {}

**Comment by JayUnt** [comment]
I would suggest that we change the layout from using divs to mimic a table, to just using a table.  We wouldn't need all of these extra classes and it would make the whole site cleaner.

**Comment by thadius856** [comment]
I'll ponder this one today.

**Comment by thesehands** [comment]
I would recommend against using tables for the layout, if you look at my fork all of the classes are unnecessary so I removed most of them. There is quite a bit of redundant CSS code so Im in the process of slimming it down. Table layout are considered deprecated and poor use. It will only cause more trouble down the line with further enhancements.

**Comment by JayUnt** [comment]
I agree with not using tables to create a layout for a whole site, but when you have the content setup as a table, why not use a table. I will look at your changes, but its most likely going to be divs inside divs, with styles to make sure they are fit next to each other and setting the widths.  Using a table would avoid having to add those inline styles by just using trs, and tds.  To me a table a whole lot cleaner than floating divs and having to add a clearfix on every div.

Other than that, your changes definitely look cleaner. The more we can reuse classes the better, especially since there is not much variation in the text styles.

**Comment by JayUnt** [comment]
I just realized i that last comment i talked about how i was going to look at your changes and then later in the comment talk about the changes.  i looked at it half way through and then got too lazy to go back and re-write the beginning. :)

**Comment by thadius856** [comment]
I think I'm with thesehands on this one.

I've followed the table rabbit hole enough times to remember getting bitten in the ass every time.

While I think it is a reasonable consideration, I can't think of a way to turn on/off columns easily using tables without resorting to php hackery. I'm especially against putting html tags within php echoes, because then the CSS doesn't apply to those elements properly.

If we have to nest an additional div within a div to get vertical centering, then so be it. It's only a minor inconvenience. We can always fall back on .Class div {} to keep it readable if need be.

**Comment by JayUnt** [comment]
no problem.  What are your thoughts on using a grid system, like twitter's bootstrap (http://getbootstrap.com/) or 960 (http://960.gs/)?  I'm just trying to avoid having to shove a clearfix on every div tag to make the floating divs fit work.
