### ISSUE TITLE
Kernel Panic on boot after a shutdown -h now

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#202]
I thought I would post this here in case anyone else experiences this as it DROVE ME CRAZY trying to resolve.

On my install of Raspbian when I would do a 

sudo shutdown -h now

to halt the server and power it off, when I went back to boot it (plug it in) I would receive a kernel panic. The kernel wasn't able to find the correct file system.

After some digging, I found the culprit:

dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootfstype=ext4 noatime quiet rootwait loglevel=1 persistent-logs zram.num_devices=2

the part in the config file where its telling the pi to look for root in /dev/mmcblk0p2 is wrong. 

This should be root=/dev/mmcblk0p6

This is not an issue with RaspberryPints, but an issue with the Pi itself. 

If anyone experiences this, the solution is simply:

plug the pi in to your monitor and attach a keyboard.
Boot PI while holding shift to get to the recovery console
Select the Raspbian image (should be the one with an x) and then click or tab to the edit option at the top of the screen

Select the config file (second tab)

Edit the root=/dev/mmcblk0p2 so that it is root=/dev/mmcblk0p6

and save/exit to reboot.

It should boot fine.

**Comment by thadius856** [comment]
I've probably rebooted mine a hundred times. Never got the kernal panic failing to mount a volume.

Installed Arduino.
Rebooted. Fine.
Installed python-serial.
Rebooted. Fine.
Installed Wyolum's Alamode setup.
Rebooted. Kernel panic.

Coincidence? I think not...

**Comment by mcangeli** [comment]
Rebooting it wasn't the problem.

Sudo reboot worked fine and it would come back up. If I did a shutdown and removed the power when I went to boot it back up it would throw a kernel panic.

I made the change and now it boots from a cold boot without issue.

It may not happen to everyone but I figured this would save some headache...

**Comment by thadius856** [comment]
Was throwing panics at me on all boots. :\

**Comment by mcangeli** [comment]
Yea it seems to be fairly picky and the sd card is also a point of issue (talking with Kerber it seems the sd card can be easily corrupted...)

I ended up gluing the card in place (it's a microsd adaptor)

**Comment by mtnbound** [comment]
I just added mcangeli's comment to a Wiki page. I can see myself having this problem, and trying to dig through the currently 200+ issues trying to find this :)

**Comment by kerber** [comment]
Aha! https://github.com/wyolum/alamode/blob/master/alamode-setup/cmdline.txt

So, NOOBS is set up with a bunch of installs on a bunch of partitions. It turns out that this file (run as part of the Alamode setup) is expecting the same partition layout as the default Raspbian install.

**Comment by mcangeli** [comment]
Aha! So I wasn't going crazy.

**Comment by thadius856** [comment]
> Installed Wyolum's Alamode setup.
> Rebooted. Kernel panic.
> 
> Coincidence? I think not...

Aha! So **_I_** wasn't going crazy.

**Comment by mcangeli** [comment]
Maybe we package our own setup script for the alamode that doesn't change the partition...

**Comment by kerber** [comment]
I forked Wyolum's repo and made the necessary changes to the setup script. I submitted a pull request back to her master, so we'll see if he re-releases. Here's an alamode setup that remembers your root settings: https://github.com/kerber/alamode/raw/master/bundles/alamode-setup.tar.gz

**Comment by thadius856** [comment]
Was going to recommend that. Awesome. :)

**Comment by kerber** [comment]
I went ahead and added it to my alamode setup as well
