### ISSUE TITLE
v 1.0.1 has been released. 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#203]
I added a note to backup databases before hand because otherwise idk how they will run the update

thoughts

**Comment by Skemp45** [comment]
because they have to overwrite current files with new files but when they do this that means the config files are not there and the only way to get them is by running the installer but the installer will only overwrite or clear current content. but if they backup their database then can just re import it after reinstall

**Comment by thadius856** [comment]
If you unzip on top of the current install, the config files aren't touched because they don't exist in the zip.

**Comment by thadius856** [comment]
Just a note on releases.

Make sure when we roll out hotfixes that we merge `hotfix-x.x.x` into `master`, then build the release off master. Otherwise, users clicking the ZIP link on our front page will get an older, un-patched version.

I've rolled the hotfix into master. :)

**Comment by Skemp45** [comment]
But dont you overwrite them because the includes folder and the admin/includes folder overwrite the existing ones?

**Comment by thadius856** [comment]
The only file you can't afford to overwrite is /includes/config.php, AFAIK. And it isn't overwritten, because it's not in the release... it's generated by the install scripts.

I'll test in just a moment.

**Comment by Skemp45** [comment]
also you dont want to overwrite admin/includes/conn.php and admin/includes/configp.php

**Comment by thadius856** [comment]
Same case with those files. They're generated by the install script, and not in the release zip. So you can't accidentally overwrite them.

**Comment by thadius856** [comment]
Just tested. Works great, though looks like we jacked up the CSS. _le sigh_

**Comment by Skemp45** [comment]
whats wrong with the css GRRRRRRRRRRRRR

**Comment by thadius856** [comment]
If I were a guessing man...

72e1ea928abb6ce9de3e0c3225d2a5d3a938df73

**Comment by Skemp45** [comment]
what looks different though?

**Comment by Skemp45** [comment]
nvm I see #205

**Comment by Skemp45** [comment]
closing
