### ISSUE TITLE
Front-end Vertical Spacing Expanded

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#205]
The front-end definitely stretched out a bit with that last CSS update.

![untitled](https://f.cloud.github.com/assets/6320180/2253510/fd5514b0-9dbf-11e3-8e79-818e72a57bfc.png)

While a 50 px stretch might seem like not much, it's enough to kick my 10th beer halfway off the monitor. :\

The extra space seems to be above/below the numerical readouts surrounding the infographics.

**Comment by JayUnt** [comment]
Since we are sticking with a non-scrollable screen, what do you think about making the front end page use adjustable heights?  Each row will have a max height, but if the screen in too short, it will shorten the row s til everything fits.

**Comment by mcangeli** [comment]
Or a way to turn off the description and make the images smaller.

**Comment by thadius856** [comment]
Love both ideas. Maybe we need to fix it first though. Look how uneven the vertical centering is.

![untitled](https://f.cloud.github.com/assets/6320180/2257900/d1b41cdc-9e20-11e3-99b3-c7d45e766b65.png)

Seems like this should be three TRs, each of the same class, with a defined top and bottom margin/padding.

Making images smaller might be a bit hard, as we've manually tweaked their positions with padding to get them to line up, but it's not impossible.

For the description: Is there any way to truncate text to a specific number of lines? I know how to truncate to a set number of characters or words or etc... but lines? That's a tough one.

**Comment by shepikoff** [comment]
Fixed height with overflow-y: hidden may work to cut off lines on the bottom of a div.

**Comment by thadius856** [comment]
Tested and fixed. Was pushed out in hotfix 1.0.2. Closing.
