### ISSUE TITLE
Time to get wild!

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#206]
I build a shell script tonight that allows users to backup their database by running one command in command line and it will put a backup into their root directory

**Comment by thadius856** [comment]
Can it add `time()` or some other construct to append a timestamp to the end of the filename?

**Comment by thadius856** [comment]
Off into left field here, but...

...what would you guys think about a `cron` job that fires this shell script daily?

Would require a backups sub-folder, but otherwise, doesn't seem difficult.

**Comment by Skemp45** [comment]
yeah easy to do here check this out

**Comment by Skemp45** [comment]
```
CUR_DB_HOST=localhost
CUR_DB_NAME=raspberrypints
CUR_DB_USER=beers
CUR_DB_PASS=beer
#make MySQL backup filename
BACKUPMYSQLFILE=/var/www/raspberry-$(date +%Y-%m-%d).sql
#export Database
mysqldump -h localhost -u $CUR_DB_USER -p$CUR_DB_PASS $CUR_DB_NAME > $CUR_PATH$BACKUPMYSQLFILE
```

**Comment by thadius856** [comment]
Any chance we could make use of `config.php` since we already have the DB info there?

**Comment by Skemp45** [comment]
we would set the info in the file during install with the install script

but what its doing is making a backup and placing it in their root(we can make a backups folder) and calling it raspberry-exact year, month, day.sql

**Comment by Skemp45** [comment]
I can check if I can include the config info

**Comment by thadius856** [comment]
Sounds good.

Only recommendation is to perhaps poll an external time source. The Pi's lack of a RTC means that often the clock is wrong, especially if an internet connection wasn't available at boot.

**Comment by Skemp45** [comment]
and to run it (if we didn't use a cron) the user would just type

**sudo ./www/var/maintance_scripts/mysql_dump.sh**

**Comment by Skemp45** [comment]
and as for the cron, we can create a crontab that looks like this 

```
00      00      *       *       *       /www/var/maintance_scripts/mysql_dump.sh
```

and that will run every night at midnight. assuming they leave their pi on

**Comment by thadius856** [comment]
No reason not to do both. :) SQL files are small, and most users will have 8gb or larger cards.

Will help sorting a lot if %m and %d have leading zeroes (I'm not intimately familiar, sorry).

**Comment by Skemp45** [comment]
THEN lol

create another script and another cron to run 5 minutes after it, that looks like this

```
find /www/var/backups -type f -mtime +14 -exec rm {} \;
```

this will find the backups directory and only allow 15 backups deleting the oldest. This way the backups dont use all their sd card

**Comment by thadius856** [comment]
~~Fancy!~~

**_Wild!_**

**Comment by Skemp45** [comment]
only problem is would the backups be deleted when we release updates or when you unzip on top of it will it not touch it?

**Comment by Skemp45** [comment]
because in the files we release there will be a backups directory dedicated for storing backups. or would we just tell users in our instructions to mkdir backups that way it would not be touched

**Comment by thadius856** [comment]
You have two questions here.

1) Unzipping over a target folder only overwrites files within the folder that also exist in the zip. It applies the same logic as pasting one folder onto another in Windows. So if the backups don't exist in the repo (they won't), then they won't overwrite the user's backups.

2) If the release contains an empty folder, and the destination contains a folder of the same name, the folder itself will be overwritten. However, the contents will be preserved and not be changed.

**Comment by Skemp45** [comment]
Boom answered them both nice work man. well we have backups figured out then!!!! very easy to do :dancer: I will create and polish these. Can you make a branch called feature-backup so I can upload them and then also a branch called feature-adminthemecolor

**Comment by thadius856** [comment]
To expand a little further, if you were to accidentally package 15 of your own personal backups in the repo, and we didn't notice it during release candidate phase, your backups would be placed in the folder with the user's.

Next time the cron job ran, the newest 15 would stay and the rest would go. I'm guessing the user would still have at least 7 backups (since we lock the rc branch ~7 days out, your backups would be at minimum 7 days old by release day).

**Comment by thadius856** [comment]
Sure. I'll pull them off develop.

**Comment by Skemp45** [comment]
Perfect, ty

**Comment by thadius856** [comment]
Had to roll v1.0.1 into `develop`. Should have done it from `master`, but did it from `hotfix-v1.0.1`. Oh wells.

**Comment by thadius856** [comment]
Slightly different names, same result. Enjoy.

**Comment by JayUnt** [comment]
Can we have the cron job configurable from the admin off the install
script. There is not much data, so I don't think a daily backup is really
necessary. So if we make it configurable, I would be able to change it to
just weekly, or turn it off if I want.

What about just having a backup button in the admin. So I can do it
manually?

**Comment by Skemp45** [comment]
I like the idea of a button in the admin. it will just be known that in order to do a update they have to run a backup

**Comment by Skemp45** [comment]
I have added the backups folder and the maintenance_scripts folder with the script that will run and make a backup of their db and put it into the backups folder.  added all this to feature-database_backups. 
Again the command our users need to run via command is 

```
/var/www/maintenance_scripts/./mysql_dump.sh
```

**Comment by Skemp45** [comment]
@thadius856 I made pull request #208, this is fully functional and tested. If you can push through pull request and then review so we can commit to master or dev because there are some big file structure changes in them and I dont want people making  new features or changes and not using this new structure.

**Comment by Skemp45** [comment]
also I forgot to but once merged into feature-admin_theme_color
I will add 

```
INSERT INTO `config` VALUES(14, 'adminThemeColor', 'styles.css', 'Admin Color', 0, '2014-02-25 08:18:42', '2014-02-25 08:18:39');

```

into the schema.sql as this is needed

**Comment by thadius856** [comment]
Think I resolved all your merge conflicts. Please open a new pull request and it should be able to go right in.

In the future, please make your edits in the branches here. TortoiseGit doesn't support multiple remotes with different origins, from what I can tell.

**Comment by Skemp45** [comment]
Closing
