### ISSUE TITLE
Facebook ads are live

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#216]
I am running a $50 facebook ad right now to see if it can bring RaspberryPints more attention and users!
![untitled](https://f.cloud.github.com/assets/6318869/2279594/1aeb0f34-9f73-11e3-9145-5c4290be4414.png)
![untitled2](https://f.cloud.github.com/assets/6318869/2279595/1c5dc956-9f73-11e3-9db0-1d73f0efca24.png)

**Comment by thadius856** [comment]
:o careful, mang.

**Comment by Skemp45** [comment]
:D No worries, I had a few ad credits sitting around not getting used

**Comment by Skemp45** [comment]
I also switched our website and emails to a new server today to better support the traffic. Jay and Thad you guys got pm's on HBT about the email changes and I posted about the possible downtime on facebook but there should be 0

**Comment by thadius856** [comment]
Can one of you guys work on a WordPress plugin that allows users to suggest AND vote on submitted features?

It would greatly improve our process by letting us know what features are most wanted, instead of whose requesters are most vocal.

**Comment by mcangeli** [comment]
check out http://wordpress.org/plugins/feature-suggest/

**Comment by mcangeli** [comment]
I installed it on my site... http://skypainterbrewing.com/index.php/sample-page/

**Comment by thadius856** [comment]
Love it.

When can we have it implemented?

**Comment by mcangeli** [comment]
Anyone with admin rights to the wordpress can install the plugin.

I checked I don't have the right rights.

**Comment by Skemp45** [comment]
Closing as resolved
