### ISSUE TITLE
Proposed major schema updates for for V2

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#217]
Hey everyone!

JayUnt and I have been toiling away in our virtual workshop and I think we have something ready to share! I'm really excited about this, so I can't wait for everyone to pick it apart ;) We've been working on a pretty big data schema overhaul that will give us a bit more flexibility and some cool new features. 

![alt text](http://i.imgur.com/RPEXRDfl.jpg)

Let's get into the details:
1. Batches: You'll notice that we've broken out the tap info into 'batches'. This presents a really clear way of mapping a specific instance of a beer to the rest of our system. In this way, a tap can easily be linked or unlinked to a keg with a specific beer in it. For those of us who swap out kegs fairly often, it also gives the ability to keep kegs 'on deck' without losing the level data. This also means we can simplify keg status and, instead, use whether or not the keg has a batch of beer in it that's active. Once the keg is kicked (either from user input or a 'keg kicked' flow sensor event), the active status can be changed and it won't appear in the tap selection list. Note that startKg is the initial weight of the keg with beer in it. Given this weight and the weight of the empty keg (already in the kegs table), we can calculate the exact starting volume. All the user has to do is put their keg on their bathroom scale before tapping it.
2. Taps: Now that the been instance info has been relocated, the tap can be simplified down to the vitals. Logically, it only needs to really know it's name, flow sensor address, linked batch, calibration info, and whether it's active. Note that number became name. This allows users to list their taps with identifiers like "Nitro".
3. Pours: A lot of the specifics in here could be calculated on the fly, but it makes just as much sense to store the small amount of data. Flow meter pin address is stored, rather than tap, so that the tap -> pin mapping can change without fubar'ing up historical data. We don't expect this pin mapping to change, but it's a precaution that's easy to take. 
4. Beers and Kegs: These have been largely unchanged, as their current layout works with the proposed changes.
5. Metric: Honestly, calculations are clearer in Metric. At this point, Imperial/Metric just becomes something that the interface checks when a user is storing or fetching data for the UI. Let's rip this band-aid off and just got for it.
6. Pulses, calibration, and pin addresses in the DB/webapp layer: The Arduino is really good at interacting with hardware in a timely and reliable manner. That said, it's WAY easier to deal with things like calibration and address mapping up at the interface.

As you can imagine, there are a lot of Admin UI changes we've been talking about to accompany flow sensors and the new layout, but we'll save those for a separate issue.

**Comment by mcangeli** [comment]
Nice!

**Comment by thadius856** [comment]
> Let's rip this band-aid off and just got for it.

Have fun!

**Comment by JayUnt** [comment]
Well if there are no issues, ill start working on the db alter/migration script this weekend :)

**Comment by kerber** [comment]
@JayUnt, You are my hero.

**Comment by mcangeli** [comment]
Mine too if you two get the flow meters and poured amounts working ;)

**Comment by kerber** [comment]
@mcangeli, We've been hashing out details for the architecture all week. As it will be such a large update, we're making sure we dot the i's. It's going to be a lot of work, but it should be well worth it!

**Comment by mcangeli** [comment]
Let me know if you need someone to argue with... 

or test. My kids will pour water from a tap all day long if I let them.

**Comment by JayUnt** [comment]
I was thinking the same this with you keber. I want to see all of this fire
stuff working, so I'll take the app stuff off your hands. :-)

**Comment by Skemp45** [comment]
Old thread see no current value, if there is valuable info please add as a new issue with a descriptive title
