### ISSUE TITLE
Unlinking 'index.html' throws errors when not present

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#218]
We modified the installer in 1.0.2 to remove `index.html` for the user.

Problem is, when the file doesn't exist, it throws errors that may look scary to the user:

```
 Warning: unlink(../../index.html): No such file or directory in /var/www/install/includes/configprocessor.php on line 212
```

Can we throw an ifexists in there somewhere to check before it attempts?

**Comment by Skemp45** [comment]
Should be able to just add this 

```
$filename = '../../index.html';

if (file_exists($filename))
```

**Comment by thadius856** [comment]
Awesome. Thanks. Just rewrote config_processor.php's section on deleting index.html just for this. :)

**Comment by thadius856** [comment]
c5b3f3d166bef0039a879d6520a376e4c849c0bd
