### ISSUE TITLE
Admin theme Color

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#221]
I downloaded the feature-admin_theme_color branch and installed and fixed all issues, can someone else also install and make sure it works so we can add it to the develop or main. It is ready for our next big release. I just want to add it in so it does not get out dated or left behind

**Comment by Skemp45** [comment]
If someone can please do this so we can add before the framework switch

**Comment by Skemp45** [comment]
@thadius856 which branch do I need to merge this into?

**Comment by thadius856** [comment]
Once it's tested, develop.

If you want to make a release candidate, you'd make an rc-x.x.x branch. But I don't think we have a db patching system worked out, so that's probably off the table.

**Comment by Skemp45** [comment]
Yeah I will just make a pull request to develop and wait on the release candidate

**Comment by thadius856** [comment]
Merged.

Note there was a merge conflict in the admin panel header. Please check that I selected the portions that you wanted.

**Comment by Skemp45** [comment]
thanks. I will download and review

**Comment by Skemp45** [comment]
Downloaded and installed ran through everything FLAWLESS!!!! everything seems to be working without issue
