### ISSUE TITLE
Report bug request feature

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#222]
So now that we changed the url to report a bug to  http://raspberrypints.com/report-bug and request a feature to http://raspberrypints.com/suggestion/ we need to update this in the admin/leftbar.php file because it takes people to a 404 error

**Comment by thadius856** [comment]
Hrm. Wordpress doesn't automagically create redirects? :(

**Comment by thadius856** [comment]
Looks like we both fixed it at the same time.

Created new hotfix branch, updated version to 1.0.3, issued new release.

**Comment by Skemp45** [comment]
Ok, I will blast via email and social media
