### ISSUE TITLE
Website - Font Kerns Two En Dashes to One Em Dash

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#226]
On the website, our font kerns two en dashes to one em dash. That is:

`--` looks identical to `—`. It's throwing people off, thinking there's only one dash, so the commands fail.

Can somebody either change the font of the whole shebang, or the font within the Notice Boxes plugin boxes? I'd do it myself, but barely had enough time to find to write this message. :(

**Comment by shepikoff** [comment]
The source appears to be an actual em dash instead of two dashes. I assume this is for "@chromium –start-fullscreen localhost" on Step5?

**Comment by louking** [comment]
I'm not sure the fullscreen start works anyway.  I'm back to using --kiosk,
and ALT-f4 to get out.

**Comment by thadius856** [comment]
Lou,

Correct. I'm typing and able to see two en dashes on the admin side of the
house. It may be converting to an emdash before presentation... haven't had
time to check yet. Long day. :S

Jeff

**Comment by mcangeli** [comment]
It doesn't seem to matter how its formatted (nbox, blockquote...)

Even if you add a space inbetween the two dashes it still makes one longer and one shorter....

**Comment by raysmithtx** [comment]
This should fix the double dash turning into one dash:
Add this php code to the page. I think the theme will allow header text which should work:
<?php

add_filter( 'the_content' , 'mh_un_en_dash' , 50 );
function mh_un_en_dash( $content ) {
        $content = str_replace( '&#8211;' , '--' , $content );
        return $content;
}

I don't have time today so feel free to change it. Otherwise I'll take a look tomorrow.

**Comment by raysmithtx** [comment]
I was going to look into the double dash problem this morning but cannot get to the menu options screen. I need someone change my user account authorization back to 'Administrator' before I can proceed.

**Comment by Skemp45** [comment]
Added a not eon the page as this is not a issue with nbox but rather how our theme interprets it so I will leave the note there for now as I am not about to change our theme up at least until v2 is released.
