### ISSUE TITLE
Another competitor

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#227]
Looks very similar to ours.

http://philsprojects.wordpress.com/2014/03/10/smart-kegerator/

**Comment by mcangeli** [comment]
That’s pretty cool how he’s using the facial recognition to do the user control.

**Comment by kerber** [comment]
I'm not sure if 'competitor' is the right word. Fellow tinkerer who open sourced his project?

**Comment by JayUnt** [comment]
I'm not calling him a competitor because i want to see him do bad, but we would be competing for users.

**Comment by Boombrewer** [comment]
That's a pretty awesome system.  The facial recognition stuff might be something RPints users would be interested in considering all the discussion about RFID and such.

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task
