### ISSUE TITLE
Lower Resolution Monitors

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#228]
I know that this was originally written with todays screen resolutions in mind, however, I've repurposed an older laptop monitor that seems to want to run at 1280x720 (720x1280 when rotated 90 degrees...) and the images and what not appear huge.

I'd be interested to see if there is a need to work on a "style" for older monitors or larger resolutions. I know that those people who run 10 taps would still need a newer monitor strictly to fit the tap list, but for those people with anything under 4 taps....

Here is the rPi connected to the laptop monitor (its a 17" monitor):
![20140315_171846](https://f.cloud.github.com/assets/6456272/2439789/7dbe1bc4-ae00-11e3-8665-f17877bb3c42.jpg)

and here it is with the tap list up and a beginning housing created for it. If anyone wants info on the board used to hook the laptop monitor up, let me know. It was about $60 shipped from china.

![20140317_130827](https://f.cloud.github.com/assets/6456272/2439797/a0a3a8d4-ae00-11e3-9809-2a9b46b546e7.jpg)

**Comment by thadius856** [comment]
Looks like you'd be better off with a landscape orientation for 4 beers...

**Comment by Boombrewer** [comment]
Yeah, Thad is right.  I only have 4 taps and I've messed around with landscape, portrait, and just about every resolution the pi can do.  Landscape works the best and to be honest, 1080p was the best for me as well.  But I know that depends on what your screen can take as well.

**Comment by mcangeli** [comment]
I'll post another photo in a bit, but I rotated the screen back to landscape.

Edited the code to get as much screen area as possible. Removed (hid) the numbers and adjusted the headers and it actually looks ok at 1280x720 now.

I may resize the rpints logo so it fits in the area left.

**Comment by mcangeli** [comment]
![20140319_121040](https://f.cloud.github.com/assets/6456272/2463532/cdac0776-af8c-11e3-89f1-f90c7037ca43.jpg)
![20140319_121032](https://f.cloud.github.com/assets/6456272/2463534/d0dafcd6-af8c-11e3-8667-41020e993500.jpg)

**Comment by Boombrewer** [comment]
Looks good man! Definitely the way to go with 4 taps.
