### ISSUE TITLE
Tap Display Project

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#229]
Hey guys,

I finally feel like I'm at a point where I can put out a preview of an related side project. Of course I'd like to really easily know the levels in my keg, but I dislike fudging with a monitor when I'm just pouring a beer and want to know the level. I want my kegerator to be smarter. I want it to spring to life and interact with me when I walk by. Why not? It's the future.

![3D Model](http://i.imgur.com/7NoDd8jl.jpg)

<a href="http://www.youtube.com/watch?feature=player_embedded&v=uW5UT9FoLpU
" target="_blank"><img src="http://img.youtube.com/vi/uW5UT9FoLpU/0.jpg" width="480" height="360" border="10" /></a>

The above video is of a 3D printed replacement tap collar that houses a full color display. I'm planning on releasing it as a how-to, printable 3D model, and Arduino Library. It's modular, so integration into existing setups should be possible, given sufficient skills and determination. With an Arduino already in place, I estimate it to cost around $10-$15 per tap.

This will be a moderately advanced project, so adjust expectations accordingly.

More info to follow.

**Comment by mcangeli** [comment]
But thats providing you have access to a 3d printer right? I'd assume its slightly more expensive if you  don't have the materials around...

But thats pretty cool.

**Comment by kerber** [comment]
There are quite a few 3D printing services online and plenty of maker spaces around the country.

**Comment by JayUnt** [comment]
Would the online services print a couple? or do you have to buy in bulk?

**Comment by thadius856** [comment]
3D printing is kind of built around the idea of prototyping and small batches.

It exists partially to alleviate the need for bulk orders.

**Comment by kerber** [comment]
I do admit that it requires some effort to track down a 3D printer and get the prints made. That said, this is intense! Never before has it been easier for schmucks like us to prototype and create plastic parts within such a short period and with as little effort. Freaking awesome.

**Comment by Skemp45** [comment]
This is awesome but I am closing to cleanup the issue board
