### ISSUE TITLE
Caching the untappd data

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#230]
I've managed to work out how to add caching to the untappd data. 

It works like this:
The script checks to see if the bfeed file exists in the cache folder. If it does, it compares the file time to the set cache time (currently 30 minutes). If the cache is with in that 30 minute window, it returns the cached file. 

If its outside of the 30 minutes or if the cached file doesn't exist, the script pulls the data from untappd and creates the cached file and then returns it to the page.

It works similar for the beer img and the rating, however I have those set to 24 hours instead of 30 minutes.

My reasoning for this was if the page refreshes a lot or if you make the tap page public, there could (in theory) be a lot of people polling the page at once or with in a short amount of time. Untappd limits the number of api calls per hour. This lightens the load on the api calls.

Currently, the code is all set to work with the way I have my site/code structured, as soon as we have a stable version of the laravel base working, I will add the code for untappd and the database changes to that base. If anyone would like a sample of my code, I can send it to  you.

**Comment by JayUnt** [comment]
Good idea to cache the data.  i think in the end, when we have polling setup for the keg levels, we can also do polling on untappd. But caching data will be a good idea for then too.
