### ISSUE TITLE
Flow sensor calibration

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#232]
Calibration is really going to be an essential part of the software. Somehow, flow monitoring is going to have to deal with variances between different flow sensors.

**pulses / pulses_per_L = Liters**

For every pour the number of pulses is known, but pulses per liter changes based on the flow meter. If pulses per liter is known, the volume can be accurately calculated. That's a perfect calibration number to store.
- Idea 1 - User enters _pulses per liter_ for each tap in the admin tap list.

Alternatively, **pulses / Liters = pulses_per_L** means that the calibration number can be derived from a pour with a known volume. Pulses per liter can then be stored and used as the calibration for that tap for future pours.
- Idea 2 - The user goes into the admin tap list and hits a 'Calibrate' button. The user then measures a pour, either by volume or weight before & after filling. The pour triggers the admin interface to show a window asking for the measured volume and the tap name from a dropdown (pre-populated with all setup taps).
- Idea 3 - User measures a pour. User then goes to admin interface tap list. They see a list of the last few pours from each tap. The most recent in each list has a 'Calibrate' button next to it. They click the button, enter in the measured volume of the pour and change the tap (if for some reason needed).

Brainstorming demands some wacky ideas, right?
- Idea 4 - Guess pour size from a set of standards. The variances will probably be less than the difference in sizes so that pour volumes will group naturally. Doesn't take into account half pours.

Let's try to keep the conversation positive and see what we come up with!

**EDIT**

Additional Ideas
- @thadius856: Have the user calibrate by entering the weight of the cup before the pour and after. Using the weight of the liquid and FG, we can determine the volume of the pour. This would allow for users who have a kitchen scale, but no accurate volume measure. This could be an option on 2 or 3, like "Calibrate by Pour Volume" and "Calibrate by Pour Weight"

**Comment by thadius856** [comment]
IMO, I think weight is a better measure than volume.

While our scales are rated to 1% accuracy or better (0.5% accuracy, 0.01% precision here), our volumetric vessels are much lower quality in general.

Most brewers have a scale available.

**Comment by Boombrewer** [comment]
I personally like idea 2.  I think it gives the most options to the user and allows for the best calibration.

Thad, I think I know what you're talking about but consider that most brewers that will be doing this will likely be pretty anal about it.  A basic measuring cup from the kitchen will give a calibration that sounds close enough to get keg volume accurate enough for the intent.

Then again, speaking of anal brewers, they'd probably want it as accurate as possible.

What if we give them the option of calibrating it via volume or weight?  Either way its just an equation.

**Comment by thadius856** [comment]
What I mean is, more specifically...

Most of us have, at best, a Pyrex cookingg measuring cup. They're +/- 10%, at best. That's fine for cooking, but for calibration... worthless.

Since we already know the FG, calculating based off weight would likely be more accurate. Weight an empty cup, pour a glass, weigh again. Calculate exact quantity behind-the-scenes. Boom, volume deduced to within a much tighter margin of error.

But if sig. figs. don't matter... _shrug_

**Comment by thadius856** [comment]
Oh, the "Collaborator" tags are new... interesting...

**Comment by kerber** [comment]
That would be a great option and a dead simple addition! All we'd have to do is have "Calibrate by volume" or "Calibrate by weight". Either way, the workflow in the process will be the same.

**Comment by Boombrewer** [comment]
This project is all about options to the users.

**Comment by kerber** [comment]
I really like # 3. It doesn't require the added complexity of the software having to 'react' to a pour. It relies on the user going to choose the pour. # 2 is also pretty good.

After some further thought, I definitely like the option to calibrate by weight.

**Comment by Boombrewer** [comment]
Yeah, the more I think about it, weight is likely the best option.  Most brewers are likely to have a kitchen scale available.

**Comment by kerber** [comment]
Through some research, it seems most pyrex measuring cups fall within 3-5%. While not as accurate as weight, that should be fine for calibration.

It sounds like most people are digging the calibration by measured pour ideas. Since implementing with weight and volume are so similar, both will be included.

What about a variation on 2 where there is just a "Flow Calibrate" page in the admin menu. It just shows the last pour and lets you edit the pre-populated info. This keeps the simplicity of 3, but puts it in a more clear spot than the taps page.

**Comment by mcangeli** [comment]
The math is more straight forward if you do it by the liquid measurement instead of weight….

**Comment by jkurl** [comment]
Agree w/ liquid measurement. Being close to 100% is nice but as long as it
is I. That +- range of 1-3% would be the best.

**Comment by kerber** [comment]
Weight wouldn't be hard. When the page displays, it can just pull the FG for the brews and use the one for whichever tap is selected. It's a bit more involved, but it shouldn't really be an issue.

**Comment by thadius856** [comment]
Why bother buying flow meters with a 1% accuracy if you throw it away on
the calibration stage?

**Comment by Boombrewer** [comment]
Thad, you and your logic. Damn you.

**Comment by mcangeli** [comment]
Because they were cheap when I bought them.

**Comment by kerber** [comment]
@thadius856: As far as I know, these are the only widely available food safe certified flow meters. Accuracy is a plus, but not getting cancer from them has a big draw ;)
