### ISSUE TITLE
Suggestion APP

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#235]
IDK if any of you noticed or not but last week out site had a outage for about 3 hours. Well what happened was the plugin Feature Suggest some how crashed the DB for the website causing the site do go down. I have since brought it back up but after digging through the logs I was able to find it was this plugin that did it. I have resolved any issues with this since but now the feature suggestions are all gone and the page does not display on our site, can whoever setup the plugin reset it up please. We also lost all of the SEO changes I made to the site which has got us to page 1 OF GOOGLE when you search for digital tap list.  I will readd all my seo info so we stay there if whoever did this plugin can re add it

**Comment by thadius856** [comment]
I added it. Working on the plugin now.

**Comment by Skemp45** [comment]
Thank you Thad. sorry for any inconvenience everyone

**Comment by thadius856** [comment]
It's done.

Also fixed some page layout issues, particularly with the menus.

Is our WP lagging today, or is just me?

**Comment by Skemp45** [comment]
I think its that dAMN plugin, it is almost maxing out my I/O limit grrrrrrrrrrr

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task
