### ISSUE TITLE
V2 Pre-Merge Tasks

### ISSUE THREAD

**Issue by kerber** [RaspberryPints/RaspberryPints#236]
The MVC port nearing completion and we've got a few tasks before merging back into dev:
- Install/Upgrade Script
  - Do we want to support upgrades or should we just have people re-enter data? It's a time/feature issue. If someone wants to volunteer to handle the upgrade process and the resulting help requests, it's not an issue.
- Bug Testing
  - The move to Laravel will surely have introduced some 'features'.
- Performance Testing
  - Is everything running well in Laravel? Are there any performance tweaks we can/need to make?
- Feature dev guidelines
  - Some best practices for those wanting to add features. This will save devs having to rewrite when we reject their horrible pull request.

Does anyone have any thoughts or things to add?

**Comment by mcangeli** [comment]
Is this release being called V2? Or is it going to be something akin to V1.5?

People are expecting V2 to have the flow meter support.

**Comment by kerber** [comment]
It's V2. This task list isn't for the release. It's pre-merge to dev.
