### ISSUE TITLE
Testers???

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#237]
Gents, sorry for the unexpected hiatus - work and personal stuff both decided to amplify at the same time.

Where are we at with V2?  I'm not good with much other than heavy lifting and testing but I wasn't sure if anyone needed to put something new through its paces.

**Comment by thadius856** [comment]
Would like a status update as well.

Is the MVC framework changeover still happening? Are we moving forward with features? :\

**Comment by mcangeli** [comment]
The MVC framework is done. I think Jayunt was going to work on porting the installer over to the MVC.

I’m slowly working on a shell script that can be run to make the changes to apache’s config file, grab the files and do the install.

**Comment by JayUnt** [comment]
I thought we were just going to go with a shell script to the new file downloads, apache config updates and db updates.  I can work on the install page, but will it be needed?  If all they have to do is run a command line script and it updates that all for them, i think that would be enough.  Unless we want the update/install page to run this script?

Or were you thinking that the port of the install was for the initial db creation?  We would need the sh to replicate that functionality too.

**Comment by mcangeli** [comment]
I was thinking that the script could handle the initial setup:

Apache

Grab the files

Initialize the DB

From there there would need to be a page they could use to set the passwords for mysql and the user password.

Unless I can figure out how to do that via the script.

Did not have any time to work on it over the weekend. Hope to get to it this weekend.

**Comment by JayUnt** [comment]
I think that would be the best. Let them run the script and then it has some prompts for username/password/whatever.  Keeping all of that contained to one spot. 

This would also help prevent inconsistencies between the db revision and the code revision. Which would be awesome.

**Comment by thadius856** [comment]
So are we at the point where we can start integrating the flow meter support, or are we still at a point prior to that?

**Comment by JayUnt** [comment]
I think we are at a good point for testers work on checking the existing
functionality, and the flow meter stuff going in. With the flow meter
stuff, we are going to try to figure out how to make these new features
modular so the code isn't embedded in the main functionality. But I think
the best way to do it is to just fine right in.

**Comment by Boombrewer** [comment]
Sounds good.  I'm in the process of setting up the hardware.  I was just going to install them in my kegerator but after taking a good look, I'm not sure how I want to do it.  So once I get my bench test setup done, I'll start pulling down code and what-not.

**Comment by beinert** [comment]
I have hardware set up and ready to go. Can't be of much help on the coding side if things but certainly willing to test.

**Comment by Boombrewer** [comment]
Closing this since we've seemed to answer the question....
