### ISSUE TITLE
Move to Laravel bugs

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#239]
If you want these broken up and put into separate issues or another issue, let me know.  I wasn't sure how we were planning on proceeding with these since they pertain to a single branch that hasn't been fully accepted yet.

1) Performance seems to that gone backwards.  Not sure if its my machine or my settings but its taking forever to upload the exact same images I used before for logos and background.  Also, making changes to configurations seems to take longer as well.

2) Ties into #1, need some kind of 'working gif' for "Add a Tap" similar to what's used for updating the taps.  Since it takes a few minutes to the processes to do their thing in the background, I found myself really wanting to click that button a few times until I realized it was just taking a second.  A little icon letting you know its working would be handy.

3) 'Background', 'Image Repeat' needs to be set to 'Yes' by default.  The default background doesn't look as intended if its 'No'.

4) #1 still applies but it seems like 'Brewery Icon' and 'Background' images don't want to upload for me (161kb and 51kb respectively).

5) From the control panel, the gear icon takes you to http://yourIP/admin/personalize which returns a 404.

6) The link for the brewery logo (front side) directs to http://yourIP/admin instead of http://yourIP/index.php/admin which give a 404.

7) Where's the option to change the avatar on the admin side?  It used to be in there but is not gone.  I think I remember a conversation about this but I can't remember where.

8) This ties to #190 as well, but we need a page to calibrate the flow sensors.  Thad had the best idea which was to do it by weight utilizing the final gravity.  Part of this should also be calculating the initial volume in the keg (once again based on weight and final gravity - helps to use the same formula).  That can either go in the batch data (what I'd recommend) or in the tap section (makes less sense to me).

**Comment by Boombrewer** [comment]
Ok, now that I blasted it.  I'm willing to help (in order to develop my own code skills for my own future projects) but I'm guessing I should probably bite off small sections.  So if someone would like to 'mentor' and give me specific stuff to hack through, I'm willing to give it a shot as long as one of you geniuses is checking my work.  For instance, I'm fairly certain I could update the incorrect links.... if I can find them in the code.  Cheers!

**Comment by Boombrewer** [comment]
9) Custom tap names need some format editing as well.
![image](https://cloud.githubusercontent.com/assets/6321429/3169890/bc8376ec-eba9-11e3-98c8-310eb4d61851.png)

**Comment by JayUnt** [comment]
I'm thinking that desperate issues for each bug is the way to go. That way we can assign bugs to ppl and keep track of what is done.

The first one I'll look into is the upload performance bug. When I wrote it, it was on my laptop so there was no issue. Now that my pi is up and running, I'll look too optimize the site for the pi, including the upload.

**Comment by Boombrewer** [comment]
No worries... life happens.  Hopefully guys will re-engage as they find time.  I'll try to take care of the small, easy issues.  I just have to find that sticky to figure out how to do pull requests and such.  I haven't contributed code yet.

**Comment by Boombrewer** [comment]
Closed since issues have been distributed.
