### ISSUE TITLE
Laravel performance

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#240]
1) Performance seems to that gone backwards. Not sure if its my machine or my settings but its taking forever to upload the exact same images I used before for logos and background. Also, making changes to configurations seems to take longer as well.

**Comment by kerber** [comment]
I can confirm. The RPi is not  an overly powerful box,  so the addition of the MVC has caused slowdown. This is a case of a lot of pros, but a couple really big cons.

**Comment by JayUnt** [comment]
I just tested on my pi and it only takes 3 seconds to upload the background image.  Can you post the image you are using, maybe its a larger image than im testing with.  There are also ways to have laravel cache the code for specific classes and functions.  So I will look into this.

**Comment by JayUnt** [comment]
in /app/config/app.php, there is a line `'debug' => true,`.  I set that to false and it reduced my upload time from 3 secs to 2 secs.  

I also ran some optimization commands.  I ran them before but saw that github was ignoring those files.  I removed that ignore so i could commit it.

**Comment by Boombrewer** [comment]
Can someone please remind me how or point me in the direction of the how-to we posted on utilizing github to sync files?  I know it was around here somewhere or we had discussed setting it up.  I really don't want to download a whole new zip and replace all my files to keep testing.  Thanks!

**Comment by JayUnt** [comment]
Is this what you were looking for? _https://github.com/RaspberryPints/RaspberryPints/issues/85_

I don't remember seeing anything about having the pi update the code, except for the bask script we talked about being created.

**Comment by Boombrewer** [comment]
Yeah, I looked at #85 and thought there was more.  I think I'm figuring it out using the GUI.  Now I just have to review the MCV tutorial because I can't find anything in the framework.  Thanks though.
