### ISSUE TITLE
Add icon for "Add a Tap"

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#241]
2) Ties into #240 , need some kind of 'working gif' for "Add a Tap" similar to what's used for updating the taps. Since it takes a few minutes to the processes to do their thing in the background, I found myself really wanting to click that button a few times until I realized it was just taking a second. A little icon letting you know its working would be handy.

**Comment by JayUnt** [comment]
added.  check it out and close if you are happy with the update.

**Comment by Boombrewer** [comment]
Awesome.  Nice touch.
