### ISSUE TITLE
Icon and Background images won't upload

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#243]
4) #240  still applies but it seems like 'Brewery Icon' and 'Background' images don't want to upload for me (161kb and 51kb respectively).

**Comment by Boombrewer** [comment]
Ok, just downloaded the newest set of code.  Still just hangs....
![image](https://cloud.githubusercontent.com/assets/6321429/3189113/d849c0d0-ecc0-11e3-8186-4b17884e5b15.png)
These are the images I'm trying to upload.  Not sure why this is only happening to me.  Maybe a permissions issue?  Most of my folders are 755.  Should we be setting some of them to 777?
![hello sailor 2](https://cloud.githubusercontent.com/assets/6321429/3189138/febcd8ec-ecc0-11e3-8ff2-e6b05df48a34.png)
![background_black](https://cloud.githubusercontent.com/assets/6321429/3189141/021b863c-ecc1-11e3-9431-c8c9fb0cdca2.jpg)

**Comment by Boombrewer** [comment]
Nevermind.  Changed the 'public' folder to 777 and it worked fine.  not sure why it didn't work when I changed all the folders to 777 but whatever.  Closing.

**Comment by JayUnt** [comment]
Should we add that to the instructions? Or the faq or something?

**Comment by Boombrewer** [comment]
We should probably just add it to the steps when installing V2.  Unless someone does an install script and can add it to that.
