### ISSUE TITLE
Steps to setup on server?

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#250]
Does anyone have steps listed on how to install the app now that it is integrated with the mvc, I need to figure it all out so i can start writing some new features, but I am not that verse in larvel.

**Comment by Boombrewer** [comment]
I'm assuming you saw #238 since you commented.  I think I asked every questions possible.  I didn't get a memory issue though.

**Comment by Skemp45** [comment]
:p Yeah
