### ISSUE TITLE
Feature List: Second Release- Reboot

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#252]
Here's what is currently listed in our milestone for Second Release:
- [x] **Flow meters:** Database edits to support flow meters volume recording and calibration.
- [x] **Flow meters:** Support pulse counting and recording in SQL. (_kerber_)

~~\- [ ] **Flow meters:** Provide calibration method in admin panel. (_kerber_)~~
- [x] **Documentation:** Instructions for flow meter wiring
- [x] **Documentation:** Instructions for breakout board assembly.

~~\- [ ] **Documentation:** Instructions for flow meter calibration~~
- [x] **Frontend:** Provide live updates on changes to SQL db using jQuery and AJAX.

~~\- [ ] **Customization:** Provide ability to turn all frontend data/images on/off individually using admin panel. (_thadius856_)~~
~~\- [ ] **Customization:** Provide _preliminary_ support for skinning for later release. (_skemp45_)~~
~~\- [ ] **Customization:** Allow for custom drink colors, other than those available in SRM.~~
~~\- [ ] **BeerXML:** Support import of BeerXML files to `beers` database.~~

**Comment by Skemp45** [comment]
updated v2 list, we are focusing fully on code cleanup and flowmeters for v2, v3 will be the big add on release but we need to get flow meters out there

**Comment by Boombrewer** [comment]
Have we discussed or how we're going to tackle the documentation?  Split into "minimum equipment required, build-your-own" breakout board and then another for alamode?  Are there any other boards that we should address?

**Comment by mcangeli** [comment]
At the moment the only board I'm using besides the pi is the alamode.

**Comment by mcangeli** [comment]
I think we should add basic theming to the V3 release.

**Comment by Skemp45** [comment]
I agree, Like I said lets fully focus on updating code to make sure its up to date and as solid as posible along with the flow meter addon!

**Comment by Skemp45** [comment]
Moved to #268
