### ISSUE TITLE
Auto Refresh options

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#254]
kerber commented on Feb 19

I see three options.
1. The page refreshes on a set interval. This means that the entire page has to refetch data from mysql and rerender every time.
2. We just use jquery's ajax and do long polling, refreshing the data in the page on a set interval. Still requires refetching data from mysql.
3. We use websockets to:

Have the server push all data to the page only when it's updated (possibly complex)
If a more complex update happens, like a beer being updated, the server pushes a message telling the page to do a full refresh. If a simple event happens, like a pour, the server just pushes that to the page and it updated the relevant data.
I'm inclined to # 3, as it's the most dynamic, but it depends on what everyone is most comfortable with.

**Comment by paulcanning** [comment]
Websockets do not work in older Android browsers (seen lots of people use an Android tablet for Prints)

http://caniuse.com/websockets

I'd most probably suggest using ajax

**Comment by mcangeli** [comment]
I've got mine setup so that it updates after a pour has been registered by the flowmeters.

**Comment by mcangeli** [comment]
As I said above, I've currently got the flowmeter script coded so that it updates the attached console automatically after a pour is registered. 

If they're viewing it via a browser on another machine thats a different story.

**Comment by Skemp45** [comment]
Yeah I just read your comment in the flowmeter release and thats perfect. no other reason to refresh except when a pour is made. boom issue closed. nice work @mcangeli
