### ISSUE TITLE
Switching back to old code....

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#255]
Switched back to old code and re-loaded my old DB.  For some reason, the code won't update the DB anymore.  Any ideas?  I've already verified all folder/file permissions of www and subs are 777.  I've tried editing kegs, adding a beer, adding taps.  And for some reason, it reset my taps to none.

**Comment by mcangeli** [comment]
I wonder if the passwords in the old code need to be changed in order to edit the sql. That or the sql permissions for the database need to be updated?

**Comment by Skemp45** [comment]
I would suggest wiping pi and then reloading the https://github.com/RaspberryPints/RaspberryPints/releases/tag/1.0.3.395 
code and installing it. then from there once we are running this code, the same code all of our users are running, we can develop from here. But we need to get moving on this and I am not sure where the code for the flow meters are at and what is needed to get it functional. Once I have this info I can set time aside for making this user useable.

**Comment by mcangeli** [comment]
Boombrewer, I just went through the whole process with a clean pi (I had
pulled the power supply and was getting a kernel panic so I reformatted and
reinstalled).

After I ran apt-get to do a dist-upgrade, then install apache2, php5 and
mysql, I grabbed the code and uploaded it. I made sure to chmod everything
as 777 (yes, I'm aware of the issues) and edit the
/etc/apache2/sites-enabled/000-default file to point it where I wanted it I
pulled it up in a browser and the installer handled everything for me.

Did you run the installer to install the database and did you make sure to
put in the right usernames and passwords? Did the installer give any
errors??

**Comment by Boombrewer** [comment]
No, I had tried to just swap code, dump old db, and re-load previous backup db. Next step was to dump whole install and start over but I figured I'd ask first before going down that road. I was hoping I missed something small. 

I'll wipe and reload this weekend and hopefully be back up and running good code in time to help test the new flowmeter code. 

Thanks for the help tho.

**Comment by mcangeli** [comment]
You should be able to do that as well.

**Comment by Boombrewer** [comment]
Once I get home this weekend I'm going to wipe just the db and the www folder and do a fresh rpints install.  See if that works.  I was really trying to avoid spending the time wiping the SD card and starting from scratch... mainly because I couldn't remember everything I've done at this point (and it takes too many beers and I get drunk before I finish).

**Comment by Skemp45** [comment]
Can i close this up?

**Comment by mcangeli** [comment]
YEa

**Comment by Skemp45** [comment]
closed
