### ISSUE TITLE
Flow Meter Release

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#256]
I'm working on putting together a version with the flowmeter working the way I had it working with the framework version. This will be a very basic version with the minimal code needed to parse the flow meter information and populate the database to update the keg levels on the site. There will be no additional coding done right now for the admin part of things (setting pulse count, etc...)

But this should be done and uploaded to the repo by the weekend for testing.

**Comment by Skemp45** [comment]
Awesome, thanks a ton

**Comment by mcangeli** [comment]
Update on this...

After fighting with my pi alamode I have the meters once again passing information to the python script which then passes that information to a php script to update the database. 

There are two required changes to the taps and the pours tables which add the column for pinId and set it to null (its unused unless you have the flowmeters).

Currently, there is no way other than editing the taps in phpmyadmin to add the pinId to the taps, this will be something I tackle next.

The php script updates the pours table and kicks off an automatic refresh to the chromium browser on the local machine (so that after a pour happens, the browser refreshes to reflect the amount poured automagically).

This works here so far.

I will be typing up instructions on how to wire the alamode, the flowmeters and whatforth as well as the extra packages to add on the pi and how to populate the alamode with the code needed to run the meters.

Thats going to take me the longest.

All of this has been tested on the CURRENT NON FRAMEWORK RELEASE (I also have a version on my repo that is for the frameworked release).

I will say that there were table changes and structure changes that @JayUnt and @kerber had made to the table and the site structure that made a ton of sense, we need to look at getting those changes made to the current release, however I think I've almost got it at a point where we can add a basic flowmeter setup to the release once I get the backend admin stuff (turning it on and off) added and set up.

**Comment by Boombrewer** [comment]
Are you also tackling the meter calibration?  At this point, you are singlehandedly carrying 98% of the version 2 release.  Strong work good sir.  Cheers to you.

**Comment by mcangeli** [comment]
No. There is no meter calibration in this version.

**Comment by Boombrewer** [comment]
Just wondering.  In your opinion, does it need it?  I realize it would obviously be more accurate if the meter was calibrated for every beer that was kegged.  But I also think having a default value that gets it 'close enough' for those not interested in calibrating isn't so bad either.  

Maybe that's another way to approach the calibration... after kegging, select default value or button to enter calibration page?

**Comment by mcangeli** [comment]
I haven't seen that it needs it really... I've pushed water, a stout, and a
couple of ales thru, my black IPA is probably the oilest thing I've pushed
thru and it seems to be on par with the others.

The math does a rather conservative take on it in the code that updates the
pours table based on personal measurement and the manufacturer specs (its
in the middle)

**Comment by Skemp45** [comment]
Alright, I installed the code and checked out the new setup. Lets make a few changes. We need to make the flow meters their own page, For example
 Basic Setup

```
My Beers
My Kegs
My Taps
My FlowMeters
```

The My flow meters page will contain the following,

How many flow meters do you have? [Dropdown]       1-20
Then we will populate the following fields over and over based off of how many flow meters they have

[Here is the flow meter form]
Flow meter Name:
Flow Meter Pin Number: (1-11)<or w/e pins they can use.

That will be it for this page. THEN
on the tap a keg page where pin number is now, we will have a drop down for Which Flow Meter is this attached to, they will select that flow meter then.

Make sense?

**Comment by Skemp45** [comment]
Using the current flow meter code someone kick a keg and try to retap it. let me know if it works for you. its not for me

**Comment by mcangeli** [comment]
What do you mean?

**Comment by Skemp45** [comment]
When I kick a keg and try to tap a new one it just goes back to the page as if I did not try to tap a keg

**Comment by mcangeli** [comment]
At the moment you have to enter a pinID for the tap.

I'm trying to get around that.

**Comment by mcangeli** [comment]
Hit me on Google hangouts

Mcangeli@gmail.com

**Comment by mcangeli** [comment]
I just tested and it tapped a new keg fine for me. I did have to remember
to set the keg I kicked as clean so I could select it.

You _have_ to put a number in the pinID.

**Comment by Skemp45** [comment]
Yeah must be something on my environment, I am using a server to test it as I am not home. no worries
What do you think of the changes I suggested

**Comment by mcangeli** [comment]
I don't think the page is needed. It adds another section that people have
to go to in order to set things up. My plan is to have the radio button in
the config section enable or disable the pinID field in the taps list.

So, click yes to flow meters during the first config, then when you tap all
you have to do is enter the pinID.

Adding a page to specify the number of flow meters doesn't do much except
add another table to the database and another page that people have to go
to to enable them.

If you have 4 taps and 3 of them have the meters you put a 0 in the one
with out and it won't update (as it will never receive any information for
that pin anyways).

**Comment by Skemp45** [comment]
well all that page would be doing is making it easier because all we are doing is allowing someone to give a flow meter a name meter 1 2 3 or left right middle etc. and assign that pin number to that name so they dont have to remember which pin is for which flow meter

**Comment by mcangeli** [comment]
Yea..... hrrrmmmm... I'll think about it. 

:)

On a side note, I have the install back with all my bells and whistles... it automatically posts to untappd for me when I pull a pint. The brewery feed is back in the upper corner and I'm once again pulling the rating and the beer label from untappd. woo.

http://rp.skypainterbrewing.com is my live tap list. I guess I need to put a dev one up with the base code.

**Comment by Skemp45** [comment]
Nice, let's release untapped code in v3 then and I will build out the flow meters page and we can decide how we feel about it

**Comment by Boombrewer** [comment]
@mcangeli Untappd looks awesome.  I definitely think it needs to be added but agree with Skemp that V2 needs to stay flowmeter-centric in order to get it out ASAP.  

I gotta do a little troubleshooting on my setup.  It appears I'm not getting anything from the alamode (or the sensors).  It worked on the bench several months ago so I'm sure its something I did - just gotta figure out what.

**Comment by mcangeli** [comment]
Try the basic blink example and see if you get the blinking LED.

I toyed with the idea of making the led blink in the code for the flow
meters (and I actually did in one version) to see of the alamode was
functioning.

**Comment by Boombrewer** [comment]
Good idea - I was trying to figure out an easy method to troubleshoot.  Thanks.  Maybe tomorrow night.  The harley needs a little TLC tonight.  Too much to do and too little time.

**Comment by Boombrewer** [comment]
@mcangeli You already have pin 13 setup as output for the serial communication and that's the onboard LED.  Were you talking about installing an LED on another digital pin to have it light up as the alamode is 'seeing' flow sensor data?

**Comment by mcangeli** [comment]
Thats how @kerber had it setup.

I was talking about just adding something to the loop in the alamode code
to blink the led on the alamode to ensure that it was still looping.

**Comment by mcangeli** [comment]
I've made  change to the pours.php file that ignores everything if the tap
is not active. I'll update in the morning.
@Skemp45 any chance I can be added as a collaborator so I can push
fixes/changes directly?

**Comment by thadius856** [comment]
Mc: I can make thay happen. Hit me up on GTalk/Hangouts between 5-10 pm PST
tonight.

**Comment by mcangeli** [comment]
Whats your gmail addy?

**Comment by thadius856** [comment]
<--- @gmail.com
