### ISSUE TITLE
RaspberryPints on Tablet over Wifi

### ISSUE THREAD

**Issue by bernerbits** [RaspberryPints/RaspberryPints#257]
I've done a writeup for running RaspberryPints on a tablet over wifi:

http://bernerbits.github.io/ras-pints-without-pi/

It's in draft format and I need a picture of the final setup, but I've gotten it to work using a Mac for the host.

I plan to add some touchscreen support as well.

**Comment by Skemp45** [comment]
Nice writeup, when its all finished I will look at adding this to our website under user addons if that is ok with you

**Comment by bernerbits** [comment]
Cool with me.

**Comment by bernerbits** [comment]
I've made it pretty and added more stuff for completeness. I may add to it in the future - I'll have to contribute my notes for getting set up on Windows or Ubuntu - but I consider this the "1.0" version.

**Comment by Skemp45** [comment]
http://raspberrypints.com/user-add-ons/

its been added to our website

**Comment by Skemp45** [comment]
Nice work @bernerbits  I am going to close this issue to help us keep our issue board clean and easy to manages ;) the more "issues" in this list the more we get stressed out lol

**Comment by bernerbits** [comment]
Thanks! Are you taking pull requests? I may try to work on interactive
touch screen features this weekend.

**Comment by bnairuni** [comment]
I have installed XAMP on my mac and have the following issue after I complete the install page I receive the following error: 

Validating Entries...Success! Checking DB connectivity...Success! Checking config folder permissions...Success!

Cannot write the configuration files. Please check the /includes/ folder permissions. See the RPints Installation page on www.raspberrypints.com. 

Cannot write the configuration files. Please check the /admin/includes/ folder permissions. See the RPints Installation page on www.raspberrypints.com.
Please press the back button on your browser to fix these errors

Any suggestions?

**Comment by thadius856** [comment]
This is a bit late, but... the error message tells you that you don't have write permissions to /includes/ and /admin/includes/.

**Comment by bnairuni** [comment]
Yes that was the problem.  It was a great learning experience.  I just got
a controller for Christmas, now I am ready
