### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by chrisgaines** [RaspberryPints/RaspberryPints#260]
Is there any interest in having a native iOS app for this? I understand it works in the browser. But I am thinking about building myself an app to use this. If there is enough interest I could submit it to the app store for everyone to download.

**Comment by Skemp45** [comment]
There has been a lot of interest for this, we just have not been able to get to it and I have never done an app before. Do you have a functioning app I could see? What will this apps purpose be?

**Comment by chrisgaines** [comment]
I only have one app completed, but the company that I made it for is not publishing it on the app store and just distributing it privately. I can add you to my developer account and set you up with a provisioning profile so you can test it out if you'd like. 

As far as purpose, just give the user another method of viewing the taps and/or updating the tap list. I haven't dug into the backend too much but everything that is done on the website version would be possible through an app, both backend and front end.

**Comment by Skemp45** [comment]
I totally agree with giving people another way to update the tap list on the fly. I would love to check it out just let me know what you need from me.

**Comment by Skemp45** [comment]
Closing to cleanup issue board. If this is going to happen Please open a new issue called Feature/ IOS App and add a version 3 tag to it.

**Comment by thadius856** [comment]
FYI, only Contributor level accounts should be able to tag Issues.
