### ISSUE TITLE
Speed up refresh after pour?

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#265]
Is it possible that we can speed up the refresh following a pour?  It seems inconsistent at best (I think it just depends on how the arduino code is looping) on how quickly the taplist updates following a pour.  Maybe its just my system but thought it was worth discussing as this could be a source of negative comments come time for release.

**Comment by mcangeli** [comment]
I haven't noticed an issue. The python script is polling fairly fast as it
is.

But I'll look.

**Comment by Boombrewer** [comment]
It could just be my setup.  It seems a little buggy and not very reliable.  I need to do some troubleshooting.  If no one else is experiencing the latency, its safe to assume its just mine and not a real issue.  I just thought I'd ask.

**Comment by mcangeli** [comment]
We'll have to see. There are three of us using it total so... The sample size is small.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/15/2014  9:27 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Speed up refresh after pour? (#265) </div><div>
</div>It could just be my setup. It seems a little buggy and not very reliable. I need to do some troubleshooting. If no one else is experiencing the latency, its safe to assume its just mine and not a real issue. I just thought I'd ask.

**Comment by thadius856** [comment]
I'll see if I can get mine up and running this weekend. Lots of events
though. No guarantees.

**Comment by Boombrewer** [comment]
Closing this.  It was clearly my setup.  I think it actually updates pretty well.
