### ISSUE TITLE
RFID and User tracking

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#267]
As part of the enhancements for Untappd that I'm implementing, I'm working on adding an RFID reader as well as user accounts for tracking. As part of this I'll be creating some metrics as well (I hope) such as amounts poured by beer, amounts poured by user, etc.

I'll use this thread as a way to up date people on this. Once I get the rfid reader working and talking to the pints db, I'll post my info and start a new branch with it.

**Comment by Skemp45** [comment]
This is great, Adding a version 3 tag to this

**Comment by mcangeli** [comment]
I took it off V3 as there are many other things to do before this comes out.

**Comment by mcangeli** [comment]
Update: my RFID chip should be here today. I hope to have it wired up and some play time with it to make sure it works ok. Once I know it works with the alamode I'll work on incorporating the code.

**Comment by mcangeli** [comment]
Don't tell my wife (as she'd be pissed I wasn't working on other things) but I have the code reading RFID tags, pours and kicks and putting all of that data in to the database like a good little program. woot. woot!
