### ISSUE TITLE
Whats Left? Release Date for V2?

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#268]
**Whats left?**
- Review code for any bugs
- Review all guides for the version 2 Release to make sure they are accurate 
  ~~Create writeup/documentation for implementing the flow meters for version 2.~~
  ~~Create Documentation for assembling the alamode and the raspberry pi.~~
  ~~stress test code and adjust code for accuracy.~~
  
  ~~Create a upgrade from hotfix 1.0.3 walkthrough~~
  
  ~~Make python script auto start, do not make users run the script everytime~~
  ~~Create a release date~~
  
  ~~Create a v2 release for flowmeter users and NON flowmeter users. We will need to base the non flowmeter branch off of the last release and make just bug updates that users have submitted.~~
  .

~~The Release Date**
What is everyone thinking for this? I was wanting to shoot for late August but before September. 
Making up a date, how about...... August 30th?~~

**Comment by Skemp45** [comment]
@mcangeli  Does a user HAVE to put in a pin number if they are not using flow meters?

**Comment by Skemp45** [comment]
If so we need to make a flow meter code release and a non flow meter code release if we can make it so when you check dont use flow meters it takes aways the pin from the tap form then we can have one version of the code

**Comment by mcangeli** [comment]
I'm working on that. ;)

**Comment by Skemp45** [comment]
Sweet, then they can download one code zip and then follow the new instructions depending on what they want to do. LOVE IT

**Comment by mcangeli** [comment]
Done.

Code is updated on the github. (its much easier now that I can edit
directly).

I've tested it but would of course like someone else to download and test
it as well.

**Comment by Skemp45** [comment]
is the updated code in your branch or the feature flowmeter branch/

**Comment by mcangeli** [comment]
its on the flow meter branch here. Ready to go. I updated the schema.sql file as well

**Comment by Skemp45** [comment]
Do they no longer need to run ALTER TABLE pours ADD pinId INT( 11 ) NULL AFTER tapId;
ALTER TABLE taps ADD pinId INT( 11 ) NULL AFTER tapNumber;
INSERT INTO raspberrypints.config (id, configName, configValue, displayName, showOnPanel, createdDate, modifiedDate) VALUES (NULL, ‘useFlowMeter’, ’0′, ‘Use Flow Monitoring’, ’1′, NOW(), NOW()); then?

**Comment by mcangeli** [comment]
If they're updating from an older version, yes.

If its a new install no.

And actually, there's more to it than just that. They also need to add the
pulsecount and user to the pours table.

**Comment by mcangeli** [comment]
or at least the pulse count. (what ever I sent boombrewer the other night)

**Comment by Skemp45** [comment]
only when updating tho, we will have to write a separate walk through on upgrading from current  version

**Comment by Skemp45** [comment]
![charerror](https://cloud.githubusercontent.com/assets/6318869/3957778/cfa75626-2718-11e4-9a35-59de61b9fcef.png)
Extra } at the top

**Comment by Skemp45** [comment]
`
<?php
if($config[ConfigNames::UseFlowMeter]) {
?>
}
<tr>
<td style="vertical-align:middle;">
<b>Pin Number: <font color="red">*</font></b>
</td>`

**Comment by Skemp45** [comment]
I removed the extra } from my code, updating it in the flow meter branch. @mcangeli When you have it turned off are you able to actually able to put a beer on tap?

**Comment by mcangeli** [comment]
Yes

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Skemp45 notifications@github.com </div><div>Date:08/18/2014  5:02 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Whats Left? Release Date for V2? (#268) </div><div>
</div>I removed the extra } from my code, updating it in the flow meter branch. @mcangeli When you have it turned off are you able to actually able to put a beer on tap?

**Comment by Skemp45** [comment]
@mcangeli  Can I get your
Name
Title
HBT Username and link to profile
Untapped Username and link to profile

**Comment by Skemp45** [comment]
OK, This is running great.  no bugs to note after I fixed the extra } I am going to load this onto the Pi again tonight and this thing will be ready for production once I add a few more pictures to the guide and then once we make the python script run on its own on startup and the upgrade how to we are done for v2. Great work everyone

**Comment by mcangeli** [comment]
HBT - mcangeli - http://www.homebrewtalk.com/members/mcangeli/
Untappd - mcangeli - https://untappd.com/user/mcangeli

**Comment by Skemp45** [comment]
What title do you want to give yourself?

**Comment by Skemp45** [comment]
http://raspberrypints.com/contributors/
example of others

**Comment by mcangeli** [comment]
BAMF?

Hah.

No, I don't care.

**Comment by Skemp45** [comment]
lol alright Then, Application Developer it is

**Comment by Skemp45** [comment]
You are on there. @Boombrewer Lets add you as Quality Assurance

Name you want on here and untapped and hbt username and url

**Comment by Skemp45** [comment]
Anyone want to take point on the update from hotfix 1.0.3 to version 2 walk through?

**Comment by mcangeli** [comment]
@Skemp45 how about the 29th. Its the friday of Labor Day weekend.

**Comment by Boombrewer** [comment]
Name: Casey M.
HBT: boombrewer
untappd: boombrewer

urls are the same as everyone elses just with my username   : )

Thanks.

**Comment by Boombrewer** [comment]
Second to mcangeli's idea!  29th is a perfect day to send people to the garage to drink beer and molest their kegorators.

**Comment by Skemp45** [comment]
@Boombrewer  you have been added and Everyone, Aug 29th is now the official release date for RaspberryPints V2 I will send out an email blast today and a post on the social media!!! LETS GET EXCITED, Also lets crack down and make sure it is ready by then :dancers:

**Comment by Skemp45** [comment]
http://raspberrypints.com/v2/

**Comment by Skemp45** [comment]
*stress test code and adjust code for accuracy.
*Review code for any bugs
*Create a upgrade from hotfix 1.0.3 walkthrough
Thats all thats left and we have 10 days to do it

**Comment by Boombrewer** [comment]
Ok... so I've checked accuracy with water, cleaner, sanitizer, light beer, dark beer, heavy beer, thick beer, thin beer.... it's all pretty darn accurate.  I think its as close as its going to get without giving the option to calibrate the sensor for every type / style of liquid put into a keg.

I've also done quick pours (back to back), short pours (down to ~2oz, couldn't quite make it quick enough to reach a single oz), long pours (out to 56 oz).  Everything works fine.

The only thing I haven't tried is pouring from two taps at the same time (most nights I'm testing by myself after the wife goes to bed and I'm not that coordinated).  I don't think it's that important and suspect it would work fine.

Point being... I don't know how else to 'stress the code'.  Unless someone gives me some ideas, I'm going to say its 'stress tested' and from that perspective, ready for release.

**Comment by thadius856** [comment]
@boombrewer Have you tested with anything highly carbonated? I keep a keg
of soda water on tap all the time, anywhere between 30 and 45 psi.
Somrtimes it sputters on the first ounce or so because of slightly warm
lines. I haven't found time to test (yet) but I'm curious to see how the
meter will react. Think the code will auto kick the keg?

**Comment by mcangeli** [comment]
It will not be marked kicked in the system.

At this time the kicks from the meters do not do anything.

**Comment by Boombrewer** [comment]
@thadius856 I've tested a couple beers on nitrogen (running 30psi) and I've also drained lines and started new kegs with nothing in the line.  All act just fine and don't cause any anomalies with the pour data.  I have poured other stuff under higher pressures but nothing "highly carbonated".

**Comment by Skemp45** [comment]
Alright, we now have 8 days left till launch. Who is doing what to make sure we will be ready for the v2 launch? Lets drop all things not directly related to v2 these next few days to make sure we have a seamless release

**Comment by mcangeli** [comment]
I think things are buttoned down pretty well. The people I've talked to that are using it says it works good.

**Comment by Skemp45** [comment]
Closing this as all that is left is documentation
