### ISSUE TITLE
Updating instructions

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#269]
I will be writing out the new instructions on how to setup RaspberryPints with flow meters, I will be making changes to the site over the next few days but all content will still be accessable. I am going to be splitting the setup process into 2 roads, Setup With Flow Meters or Setup Without Flow Meters.

**Comment by Skemp45** [comment]
http://raspberrypints.com/byo/

Here is the new instructions. Any suggestions or issues let me know. Click on with flow meters to see the new guide.

**Comment by mcangeli** [comment]
Looks good.

**Comment by Skemp45** [comment]
This is Done, if anyone finds or runs into any issues let me know by making a new issue for the issue you find

**Comment by mcangeli** [comment]
The last page needs to be edited to walk people thru enabling the flow meters through the admin (they're off by default) and then enabling them in the tap list via adding the pin id's.

**Comment by Skemp45** [comment]
Just saw that myself I will work on that in a bit. also fixed it so ther eis a list of steps so you dont have to click through each section to get to lets say step 5

http://raspberrypints.com/byo/ 

you can see that by clicking on the buttons

**Comment by Skemp45** [comment]
**Turning ON Flow Meters**
The "Flow Meter" Function will be disabled by default. In order to use the tracking of pours with the flow meters you will need to go the **Personalization >> Show/Hide Columns** section and select the on position for Flow Meters and hit save.

**Putting a Beer on Tap**

When adding a beer on tap you will need to assign a pin number. This pin number should match the pin number you put the digital pin of the flow meter to remember *(Pin2 (middle)-> Any digital pin 2-13. Be sure to set this at the top of the Arduino code). so if you are using flow meter "A" as the flowmeter for your Amazon Pale Ale and flow meter "A" is set to pin 7, you will pit the pin number of 7 in this field.

**Comment by Skemp45** [comment]
Also When and where do you think I should put 

At this point you should be ready to run the python script.
In a terminal window,

pi@raspberrypi ~ $ cd /location/of/raspberrypints/python
pi@raspberrypi ~ $ python flow-meter.py

This will start the script. You will not see anything output until you actually pour a pint. When a pint is poured it passes the pin number and the pulse count
to a php script which then updates the pours table in the database and then refreshes the chromium browser on the localhost.
You should also see output on the terminal window where you started the python script.

**Comment by mcangeli** [comment]
After the pins are setup in the database.

**Comment by Skemp45** [comment]
So of I reboot my pi and then turn it back on I need to startup this script every time?

**Comment by mcangeli** [comment]
No.

Add:

@/usr/bin/python /var/www/python/flow_monitor.py

to your /etc/xdg/lxsession/LXDG/autostart file after the command to launch
the browser.

That appears to run the python script automagically at startup.

**Comment by Skemp45** [comment]
I will add that to the instructions.

**Comment by mcangeli** [comment]
If your install is in a non-standard location, you can always edit the
/var/www part to point to the right location.

The python script currently has ../includes/pours.php I am not sure if that
will work or if it needs to be a hard coded location as well.

**Comment by mcangeli** [comment]
From DrunkleJohn:

Just a FYI, I have been following this project for quite a while. I am stoked about the flow meter addition and the hopefully forthcoming soon V2. One thing I noticed when I was playing around on the main site was that you all updated the Build Your Own section to include V2. I decided to check it out, and appreciate the parts list, though I think you all may have forgotten the part that connects the Swiss Flow meters to the beer line. I believe the part was mentioned earlier in the thread, but figure including it in the parts list would benefit the ordering/setup portion for when people start implementing them. I believe the part was a John Guest PI251208S Stem Barb Connector - 3/8 OD Stem x 1/4 ID Barb.

Thank you and the rest of the developers for all the time and energy and (I am sure) headaches you all have put into this project. I wish I were a good enough coder to help out.

DrunkleJon

**Comment by Skemp45** [comment]
Commend that man, I was racking my brain on what I was forgetting

**Comment by Skemp45** [comment]
· (2 Per Meter) John Guest PI251208S Stem Barb Connector – 3/8 OD Stem x 1/4 ID Barb ($2 Each) — We use these connectors to connect your tap line to your flow meter. They are cheap and work great Get them HERE

**Comment by Skemp45** [comment]
added

**Comment by Skemp45** [comment]
Fixed
