### ISSUE TITLE
SQL Access Method is Unsecured

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#27]
The current username and password for accessing the SQL database is insecure. We need to perform a minimum of hardening so we don't end up putting a ton of devices on the web with default root passwords.

Change config.php to utilize beer///beer.

You'll need to create a new SQL user named beer with the password beer. Grant the user _only_ the "SELECT" privledge, and place the user on the host localhost, _not_ Any (%).

**Comment by Skemp45** [comment]
Who is on this?

**Comment by JayUnt** [comment]
We will have to give "beer" privileges to INSERT, UPDATE and DELETE as well.

**Comment by thadius856** [comment]
I already fixed the insecurity.

The PHP now reads from beer//beer instead of root//<null>. Having root//<null> open like that creates a pretty big vulnerability when you're web-facing.

I don't think user beer needs INSERT, UPDATE, and DELETE. The admin panel shouldn't be editing with the same account.

**Comment by thadius856** [comment]
Closed because the insecurity is fixed, but lets keep going on the beer acct.

Skemp, what account/password does the admin panel use to edit the db? Does it just pass the credentials you provide onto the phpMyAdmin or mySQL server for validation?

**Comment by thesehands** [comment]
This is correc the initial config was written to my local testing machine. There actually be two users one for public access and one for admin. Public access really only needs read privilage.

**Comment by thadius856** [comment]
Sounds great.

I updated the .sql file to reflect using beer//beer and a name db name. Index.php and style.css has been updated to reflect this.

Edit: There's no way to add a user via .sql file, is there?
