### ISSUE TITLE
Plugin to manage requests

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#274]
So the plugin we use to take request for new features etc is killing the server I have it hosted on. Its just a poor plugin. What should we do? just get ride of it?

**Comment by Skemp45** [comment]
We need to atleast disable it on launch week because it is making the site super slow, so that with the addition of hundreds of people on the site will be brutal

**Comment by mcangeli** [comment]
Kill it for now. Say that requests will be reopened after the V2 release has been stablized.

**Comment by Skemp45** [comment]
killed
