### ISSUE TITLE
upgrade path from 1.0.3 to v2.0.0

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#275]
So the upgrade path I think I have worked it out.
Instead of having people patch things up and possibly hacking things to death lets just do this, Have them export the beers table from phpMYadmin then delete the database. Then we will have them follow the install guide for installing version 2 then after they can go in and import the export from the old database to replace the new beers table because other than the beers they added everything else would not be a big inconvenience. they would just have to retap their beers which we want so they set the pin numbers etc. also, readding the kegs is not a big deal.

**Comment by Boombrewer** [comment]
I disagree about the kegs. I have 4 and have had to re-add them multiple times and it sucks. Is there not a way to export the kegs as well?

If not, what I've been doing is printing the kegs screen (from admin view) to a PDF and keeping it so the data is right there.

**Comment by mcangeli** [comment]
Yes, you should be able to keep the kegs and the beers table. The tap,
pours and config tables are the ones with the changes.

**Comment by Skemp45** [comment]
Yeah I don't see why not let's do that then kegs and beers

**Comment by Skemp45** [comment]
http://raspberrypints.com/build-upgrade/

OK check it out guys let me know what you think, the upgrade walkthrough is finished

**Comment by Boombrewer** [comment]
I read through it and it all looks good. I'll run through the process tonight or tomorrow night and see how it goes. So is the flow_monitor branch mostly complete so it'll be a realistic test of the flow monitor version release?

**Comment by Skemp45** [comment]
Yeah
thats the branch i will merge into the version 2 branch and make a release off the version 2 branch

**Comment by Skemp45** [comment]
Please re open this issue if you find any problems with the guide
