### ISSUE TITLE
Flowmeter setup documentation changes

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#276]
Step 9: The picture of the jumper would be better if the jumper was actually in the "ON" position.  I understand it still works, but it might be confusing to some.

**Comment by Boombrewer** [comment]
The rest looks good as far as I can tell.  ^^^^^Pretty minor really.  Good job to the author.

**Comment by Skemp45** [comment]
No that's a good point, I just pulled the best photos from online I could find. I will take better ones with better quality tomorrow

**Comment by mcangeli** [comment]
Also, step nine, in the section about adding the python to the autostart file, add an & after the flow_monitor.py

[code]
@/usr/bin/python /var/www/python/flow_monitor.py &
[/code]

**Comment by Skemp45** [comment]
Done^

**Comment by mcangeli** [comment]
From DrunkleJohn:

Got one more for you. In step 4 installing the LAMP stack, and this was the case with installing V1 as well, it may not hurt to inform installers that during the install, just after they set the DB password that they will be prompted while configuring phpmyadmin, which web serve to reconfigure automatically. The choices are apache2 and lighttpd. I chose apache2 since we were installing it anyway, but some people may appreciate that being mentioned in the install instructions.

**Comment by Skemp45** [comment]
Done^

**Comment by Boombrewer** [comment]
![image](https://cloud.githubusercontent.com/assets/6321429/4022077/1292b48e-2b16-11e4-94d6-eced0fbfcaa6.png)
Might need to put that warning above the command line and make it red or something.  That seems to be a significant risk.

**Comment by Boombrewer** [comment]
Add to Step 10 (for w/ flowmeters) and Step 8 (w/o flowmeters) a link back to upgrade instructions.  It just makes it more convenient.

**Comment by thadius856** [comment]
Why don't we hard code in the directory name to the command? Or use ./\* ?

**Comment by Skemp45** [comment]
because the problem people are worried about is if we have them go into var/www/then run rm -rf ./\* it will remove everything in www and they say they have other stuff in there like brew pi. I think i will just write out a remove that calls just all our files

**Comment by Skemp45** [comment]
Changed it to:
`rm -rf admin img includes install sql LICENSE.md README.md high-res.css index.php pint.ico style.css`

**Comment by Skemp45** [comment]
I added a how to and an image for setting up the flowmeter with the hose barbs. Forgot to add that before woops lol.

**Comment by Skemp45** [comment]
All that is left are the images which now have its own issue closing
