### ISSUE TITLE
Edit Keg page error

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#277]
When I click to edit a keg, the page loads but the "Notes" field is populated with the previously saved "stamped owner" field with deletes the previously saved notes.

![image](https://cloud.githubusercontent.com/assets/6321429/3976880/3c5ac54a-282d-11e4-8d37-d99ab319bf77.png)
![image](https://cloud.githubusercontent.com/assets/6321429/3976884/53d377f8-282d-11e4-9974-cde667a8ee3e.png)

I hope I explained that well enough....

**Comment by Skemp45** [comment]
Ok so the notes are just being erased and loaded with the stamped owner? Most likely just the data we are pulling into the notes field. Echoing the wrong variable. I will check it tomorrow

**Comment by Boombrewer** [comment]
Yeah, seems like the issue.  But if you hit save without looking, you'll overwrite what was in the notes.  For you, likely an easy fix.

**Comment by Skemp45** [comment]
I have fixed this in the flow meter branch 
IT WAS:
`<textarea id="notes" class="text-input textarea" name="notes" style="width:500px;height:100px"><?php echo $keg->get_stampowner() ?></textarea>`

Just had to update to : 
`<textarea id="notes" class="text-input textarea" name="notes" style="width:500px;height:100px"><?php echo $keg->get_notes() ?></textarea>`
