### ISSUE TITLE
Change image paths to be relative

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#28]
Remove leading slash from image paths so the app doesn't have to be on the root to show them.

**Comment by JayUnt** [comment]
tested and committed

**Comment by thadius856** [comment]
Damn you. I _just_ pulled the latest repo. ;)

This is a long process. Deleting contents to /var/www/, download in the newest repo zip, extracting zips, FTPing them to my Pi, unzipping to /var/www/, etc.

How you found a way to have git or that svn thing you mentioned develop, push and pull to/from /var/www/ directly? Or at least something easier than how I'm doing it?

**Comment by JayUnt** [comment]
I use svn to just pull down and commit directly from my web directory. So all I have to do is click update on my folder and it pulls it all down and then I just refresh the page in the browser. Committing us the same thing. When I'm done testing I just click commit in the web folder and it sends it right up. I'm on Windows btw.

**Comment by JayUnt** [comment]
oh yeah, I'm not using a pi just yet. I'm doing this all of my laptop. I don't even have a pi yet.

**Comment by thadius856** [comment]
I'll look into `svn`. I've been developing on my Windows box and have WinSCP set up to automatically FTP over the  file to the Pi every time it sense changes. It usually notices within 1 second of me hitting Save.

Then I preview on my Windows box using Chrome, by just typing the local IP for the Pi. Every 30 minutes or so, I pick up my wireless mini keyboard, hit refresh, and make sure nothing changed on the Pi that broke it.

So far, Chrome (Win) and Chromium (Pi) have showed dead on the exact same thing every time.
