### ISSUE TITLE
Custom Tap "Numbers"

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#281]
So I had a request / idea... what about custom tap labels?  We talked about having a field that you could name the tap anything, but what about being able to assign a picture?

I have some pretty unique tap handles (see below).  I thought it might be cool to take a photo (such as below) and upload it to the tap label so people could associate a picture of the tap handle to the beer being described.  

Is this only useful to me?  What do you guys think?

![image](https://cloud.githubusercontent.com/assets/6321429/4022346/ea661412-2b2c-11e4-97a2-6e609bbd0b69.png)
![image](https://cloud.githubusercontent.com/assets/6321429/4022350/603eed26-2b2d-11e4-88ef-8e0871970579.png)

**Comment by mcangeli** [comment]
That was made before and the change was actually made to the laravel version.

It _shouldn't_ be too hard to do to the regular version but not until the first v2.x release. 

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/23/2014  9:23 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Subject: [RaspberryPints] Custom Tap "Numbers" (#281) </div><div>
</div>So I had a request / idea... what about custom tap labels? We talked about having a field that you could name the tap anything, but what about being able to assign a picture?

I have some pretty unique tap handles (see below). I thought it might be cool to take a photo (such as below) and upload it to the tap label so people could associate a picture of the tap handle to the beer being described.

Is this only useful to me? What do you guys think?

**Comment by Skemp45** [comment]
Agreed

**Comment by Boombrewer** [comment]
Cool.  Thought it might go well with the V3 'skin' / customization ideas.

**Comment by thadius856** [comment]
Would be really cool feature to have if you use pool ball tap handles.

http://www.ebay.com/itm/like/261460027146?item=261460027146&vectorid=229466

There's a keezer on HBT that has 12 of these tap handles in a massive
tower, IIRC.
