### ISSUE TITLE
Needed pictures

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#282]
I need some help with some quality images team. Here is what I need

*The switch set to on, on the alamode so you can power both pi and alamode

*Someones alamode that has multiple flow meters setup on it. 

*A image of someones flowmeter in line so people can see how the barbs work.

**Comment by day-trippr** [comment]
This might work for the barbed adapter setup. I'm using Bevlex-200, fairly generic.
![flow_meter_plumbing](https://cloud.githubusercontent.com/assets/6963379/4038559/91bdad3e-2cb7-11e4-862b-82ac113cbf56.jpg)

Cheers!

**Comment by day-trippr** [comment]
And this is a close-up of P16 in the 5V Link = On position.

![alamode_5v_link_on_01](https://cloud.githubusercontent.com/assets/6963379/4038709/a803e9b6-2cba-11e4-8437-e3a13a3eaa3d.jpg)

Cheers!

**Comment by Boombrewer** [comment]
Here's a pic of my flowmeters hooked up.  Not sure if this is what you're after.
![image](https://cloud.githubusercontent.com/assets/6321429/4038890/445a6520-2cbf-11e4-8b08-42c456b9b039.png)

**Comment by Skemp45** [comment]
All of those are great last one I need is how you have all of them plugged into the aalamode. The wires into the aalamode

**Comment by day-trippr** [comment]
Well...this might be an outlier implementation, but here's something to look at anyway.
The first picture shows my 6 meter harness and patch board with a single meter installed.
The rest show it hooked up to six meters, with the RPi and AlaMode taped up top.

Obviously, it's all temporary. Once the system is fully operational all this stuff will be integrated into the lid with the rest of the stuff that runs my keezer...

Cheers! ("It's gettin' crazy all up in here!" ;) )

![flow_meter_wiring_01](https://cloud.githubusercontent.com/assets/6963379/4039771/06948acc-2cd3-11e4-93a7-008e7661677b.jpg)
![flow_meter_wiring_02](https://cloud.githubusercontent.com/assets/6963379/4039779/3453093e-2cd3-11e4-843c-06f9ae3004e8.jpg)
![flow_meter_wiring_03](https://cloud.githubusercontent.com/assets/6963379/4039780/382d9b32-2cd3-11e4-9ea9-c072ba8178c0.jpg)
![flow_meter_wiring_04](https://cloud.githubusercontent.com/assets/6963379/4039788/862acc2e-2cd3-11e4-8935-3f89d9271173.jpg)

**Comment by Boombrewer** [comment]
And here's couple of pictures of my alamode with multiple flowmeters wired.  Might want to add some arrows showing 5V and GRND connections and make note that I'm using pins 6-9 as opposed to the directions showing 8-11.

![img_0980](https://cloud.githubusercontent.com/assets/6321429/4039868/76ea1c7c-2cd5-11e4-9bbf-f91c90f9eb93.jpg)
![img_0981](https://cloud.githubusercontent.com/assets/6321429/4039869/7c94cbb8-2cd5-11e4-95d4-0b61a7a4fa4c.jpg)

**Comment by Skemp45** [comment]
I am looking for something that will really explain how to hook multiple meters to the vin and aalamode as a whole. These pictures are a bit confusing for a new pints user

**Comment by Boombrewer** [comment]
One of the problems you're going to run into is that its impossible to know what connections they're flowmeters came with.  Mine had female connectors which I swapped for male connectors so I could plug them directly into the headers.  But even if they mounted male headers on the board, they still can't plug flowmeters directly into the board.  I don't know a good way to tell everyone to do it.  At some point, this DIY process is gonna have to incorporate some DIY steps.  I think most people can figure out how to get 5V and GND to the sensors and plug the middle wires into the pins they want to use.
Maybe its good we have lots of examples that we can post to the website (not in the install instructions) of different methods used to connect the sensors to the alamode.  That way it'll give people some ideas and options.

**Comment by Skemp45** [comment]
So there is 1 VIN plug on the alamode why are we having people plug the flow meter into vin?

**Comment by Skemp45** [comment]
What do you think of adding these to the part list http://www.amazon.com/Jumper-female-200mm-length-50pcs/dp/B00AC4NQYG/ref=sr_1_11?s=electronics&ie=UTF8&qid=1409063212&sr=1-11&keywords=female+to+male+header

**Comment by Skemp45** [comment]
PS ty for the pictures, nice work

**Comment by Boombrewer** [comment]
I concur about the Vin.  I see no point in using one Vin pin & and breakout board when you can use the multiple 5V pins that are available.  And it might not hurt to have them cued to some male OR female jumper wires as whatever is required for their setup.  The caution though is that sometimes the jumpers lead to connections issues in my experience which is why I wired my direct.  But I have crimpers already so connectors were a cheap investment for me to have better connections.  Not sure how to help people out on that front.

Has anyone tried the fall back of stripping the sensor wires, adding a little solder to make the wire stiff so it'll plug directly into a female header?

**Comment by Skemp45** [comment]
All set
