### ISSUE TITLE
Release Tomorrow!!

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#284]
Is everything ready for tomorrow launch? I plan on releasing the  launch at 12:00 PM Arizona time.

**Comment by raysmithtx** [comment]
Hopefully others will fair better than me. I have reformated my SD card and blown up my system three times and can never get past the localhost/phpmyadmin. I get the "Cannot start session without errors, please check errors given in your PHP and/or webserver log".

**Comment by day-trippr** [comment]
I'm up and running with 6 kegs tapped and metered.

I completed the Upgrade path, and the only issues not covered previously:

o   importing my saved database brought in the beers and kegs but not the tap list - which we didn't export. No biggie, except when trying to repopulate my tap list the kegs that were Serving can't be tapped (known behavior) so I had to switch them all to Conditioning before I could re-tap those kegs.

o   the upgrade script has the user jump back to the main script for steps 7 - 10 before returning to import the database. But you can't really execute step 10 before the database entries have been restored.

o   the installation should advise the user to not start drinking until the system is on line. I'm sitting here half in the bag, and while that didn't hinder my upgrade effort, I won't be giving the flow meters much of a test tonight :)

Other than those, an observation: any freshly tapped keg will be "Full", regardless of the Start Amount setting. I'll try to remember to add this as a feature request, but it would be more functional to define the Keg Volume and the Start Amount separately, then size the starting keg remaining volume image accordingly, and let the flow meters pick up from there. I'm sure I'm not alone in occasionally switching a partially full keg out for another keg for awhile, then re-tapping it later.

As a work-around I set the Start Amount to a rough guesstimate of what's left in each of six keg, so I should still get some clue that a keg is about to kick.

Anyway, awesome effort by the 'Pints team! Mega kudos!

[edit] Well I spoke too soon. I mustered up the courage to pour one more pint and the "Amount Poured" didn't change. So I tried another tap, same thing. I'll have to dig in to that after work tomorrow...

**Comment by Skemp45** [comment]
:| you have me nervous with your edit!!!!! but Great idea on the starting amount, that will be easy but we will do that in a V2.1.0 or something. as for the guide, another good point on step 10. I will remove 10 from the list and add it to the bottom of the upgrade guide

**Comment by Boombrewer** [comment]
I have a feeling this release is gonna be riddled with questions and problems. It's not so much the code but just the number of variables associated with the flow meters.  It might be worth tossing out the reminder with the release that this is intended to be a DIY project that isn't a commercial off the shelf product. People need to be willing to tinker and troubleshoot.

**Comment by Skemp45** [comment]
I will post that with it when I post it on Twitter, facebook, HBT and when I send out the email blast. You are right, there are 100 times more variables this time and alot more room for user error

**Comment by Skemp45** [comment]
Guide has been updated with the new flow

**Comment by mcangeli** [comment]
@raysmithtx where do you stand at the moment?

Get your raspberry pi reinstalled, enable x and ssh to start on boot. 
Once you have that done, 

sudo rpi-upgrade
sudo apt-get update
sudo apt-get upgrade

Run the rpi-upgrade to see if there is a firmware update (I don't think there is for the B model, only the B+) then run the apt-get update and upgrade. Those will get your system to the latest and greatest.

Let me know when you have that done and we'll take it step by step,

You can either post here or email me directly: mcangeli@gmail.com

**Comment by Skemp45** [comment]
ITS LIVE
