### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#286]
So you know _my_ (I haven't confirmed this with anyone else on the team) roadmap... 

The next "release" will be a hotfix release to fix any issues with the current code base (I may try upping the speed a little bit to see if that helps)
At some point V2.\* will be released with some improvements to the current code (the addition of the centipede)
V3 will come sometime afer that with themes, RFID and Untappd integration, possibly the ability to import beer.xml files and some other functionality.

**Comment by thadius856** [comment]
Do you guys have plans for official support of a motion sensor / monitor
sleeping? I've seen thats a pretty common usage from the v1 thread.

**Comment by Boombrewer** [comment]
@mcangeli 
- what do you mean about upping the speed? Refresh and looping?
- centipede just adds expansion, correct?

@thadius856 
- the PIR support is pretty easy and I think the user DIY is already on the site. Are you just referring to making it configurable in the admin?

**Comment by mcangeli** [comment]
There should be a way to increase the baud rate that the alamode and pi
talk. It's set fairly low at the moment.

That's what I mean.

The code is currently checking every 300 milliseconds so that's fast
enough. The slow down would be on the python end.

We can add the motion sensor. I've also gotten rfid working somewhat on it,
it just needs to be refined.

**Comment by thadius856** [comment]
@boombrewer Aye configurable on the admin page, maybe along with a
recommended model/install instructions.

**Comment by mcangeli** [comment]
I need to sit down and look at the way the pir and the temp probes are
added to the pi.

There may be a simple way to do it all that is configurable, but I also
have to figure out how to pass information along back to the alamode (IE a
set the pins in the rpints admin once and not have to upload your sketch
every time you make a change) but I am not certain....

**Comment by Boombrewer** [comment]
@mcangeli So changing the baud just changes how fast the messaging goes between the Alamode and the Pi? Does it also affect the fidelity of the data sent? I'm curious if we'll start getting garbled data (that makes complete sense in my layman brain - I could've just shown my ignorance).

**Comment by mcangeli** [comment]
From what I can tell yes.

Kerber had it set at 9600 for his code, so I left it. It should be able to handle higher.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/31/2014  2:27 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Roadmap? (#286) </div><div>
</div>@mcangeli So changing the baud just changes how fast the messaging goes between the Alamode and the Pi? Does it also affect the fidelity of the data sent? I'm curious if we'll start getting garbled data (that makes complete sense in my layman brain - I could've just shown my ignorance).

**Comment by day-trippr** [comment]
fwiw, when you program the AVR on the AlaMode using the Arduino IDE, the programming runs at 115200 baud. I've yet to see any indication that "The World's Shortest Serial Link" (what is it - two inches?) has any problem at that speed...

Cheers! ;)

**Comment by Boombrewer** [comment]
Well, I just swapped mine to 115200 and didn't notice any real difference (in the 8oz top off of my beer).  I'll let you guys know if I see any real change in the near future.

**Comment by mcangeli** [comment]
Did you change it in the python script as well?

**Comment by Boombrewer** [comment]
@mcangeli - Yes, I changed both.  But I didn't really 'test' it too much.  If I understand how the serial connection works (which I probably don't really), the baud rate will just change how quickly the few bytes of data are passed and added to the buffer.  I'll take a closer look later to see if there is anything else that can be done.  I noticed when testing that sometimes it updated very quickly and sometimes it took a few seconds.

**Comment by mcangeli** [comment]
Yea, the amount of data we're passing it probably does not matter a whole lot what the serial is communicating at. I'd probably run it lower than that though just for stability's sake.

**Comment by Boombrewer** [comment]
What do you think, 56,000?

**Comment by mcangeli** [comment]
That's pretty much where I was headed.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:09/02/2014  9:08 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Roadmap? (#286) </div><div>
</div>What do you think, 56,000?

**Comment by Boombrewer** [comment]
So I tried different baud rates without much luck.  At 115200 I got one successful pour and that was it.  I also tried 56000 & 11400 and still not much luck.  And to top it off - I had already been experimenting with other serial communications on a different RPi.  Serial comms of strings get really unstable and unpredictable (garbled) if baud rate is increased over 9600.  Please double check my work because I need to learn as well but I didn't have much luck.

**Comment by day-trippr** [comment]
Missed ^that^, Are you running on the prescribed platform (RPi and an AlaMode) or something else?
Also, you can't use AlaMode digital io 0 or 1 for meters (or anything, actually) as those are the uart pins...

Cheers!
