### ISSUE TITLE
Help: Tap List not Updating

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#287]
Received via email. Posting here for additional eyeballs.

```
When I click "Tap a Keg" and select a beer and a keg, click save, then I am sent back to the taplist. Only the taplist did NOT update. The keg shows "serving" but nothing happens...

The taplist still shows "Tap a Keg". The kegs show "serving". The taplist shows "Nothing on tap"

Any ideas? I am sure I messed something up during the install.

Regards,

Matias Gonzales
```

**Comment by thadius856** [comment]
@muhteeus Have you tried a hard refresh on your taplist page? While viewing the taplist, press Ctrl + F5.

**Comment by muhteeus** [comment]
Thadius,

I tried the hard refresh, same result.

**Comment by Skemp45** [comment]
Matias, Go into the personalize page and turn flow monitoring on. Then try to tap a keg and it will ask for a pin number go ahead and just put a random number like 4 in there then try to tap it. Does this now allow you to put a keg on tap? Please let me know

**Comment by muhteeus** [comment]
That worked for me! I hadn't enable flows because I havent purchased the Alamode yet!

Thanks!

**Comment by Skemp45** [comment]
Glad it worked. I will review the code as this seems to be a bug for people who are not using flow meters.

**Comment by Skemp45** [comment]
Closing issue
