### ISSUE TITLE
No Flow No Tap

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#288]
When users are not using flow meters they are running into issues with putting a keg on tap.

**Comment by mcangeli** [comment]
In the sql schema change default null to default 0 for the pin column on the taps table.  That may resolve the issue or more likely we just need to have the sql insert a 0 when it updates. I will look tonight.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Skemp45 notifications@github.com </div><div>Date:09/01/2014  3:17 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Subject: [RaspberryPints] No Flow No Tap (#288) </div><div>
</div>When users are not using flow meters they are running into issues with putting a keg on tap.

**Comment by mcangeli** [comment]
I've corrected the issue in the V2 branch and tested it. 

It now works with or with out the flow meters active the way it should.
