### ISSUE TITLE
Starting flow_monitor.py via init.d

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#290]
Ok, in an effort to clean up the starting of flow_monitor.py at boot, I've gotten the init.d script working.

To install it:
Copy the flowmon file from the python directory to /etc/init.d
<code>
$ sudo cp flowmon /etc/init.d
</code>
Then give it the proper permissions:
<code>
$ sudo chmod a+x /etc/init.d/flowmon
</code>
**IF YOUR INSTALL IS IN /var/www you should be good to go forward. if not, you need to edit the 14th line and set the root dir for your install.

You can test the program by running:
<code>
$ sudo /etc/init.d/flowmon start
$ ps aux | grep flow_monitor.py
</code>
Should return:
<code>
pi        3508  0.0  0.9   8796  4112 ?        S    15:35   0:00 /usr/bin/python /home/pi/raspberrypints/python/flow_monitor.py
pi        3558  0.0  0.1   3548   808 pts/0    S+   15:43   0:00 grep --color=auto flow_monitor.py
</code>

then run:
<code>
$ sudo update-rc.d flowmon defaults
</code>
to ensure it runs at startup.

If you want to create it your self...

**Comment by mcangeli** [comment]
```
#!/bin/sh

### BEGIN INIT INFO
# Provides:          RaspberryPints flow Monitoring
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/var/www/python
DAEMON=$DIR/flow_monitor.py
DAEMON_NAME=RPFlowMon

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=pi

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in


    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
```

**Comment by day-trippr** [comment]
That's brilliant! And just what the doctor ordered! Thank you!

I had started with that same example but got side-tracked before I could finish up, thanks for nailing it!

One typo in your explanification: change the second $ to an & and you're golden...

"You can test the program by running:
 $ sudo /etc/init.d/flowmon start & ps aux | grep flow_monitor.py"

Also, as I assume this will show up in a minor point release, you might want to add a note to remove the flow_monitor.py startup line from /etc/xdg/lxsession/LXDE/autostart if it was added at v2.0.

Cheers! And thanks again - this is the right way to do this!

**Comment by mcangeli** [comment]
No, I wanted those two commands to be on separate lines.

**Comment by Boombrewer** [comment]
@mcangeli 
I did the above changes and commented out the change to LDXE/autostart.  And I downloaded all the new files from the V2 branch.  But now I'm getting a server error.  I even tried running the install again and no love.  Did I miss something?

I got the same error after I tried just copying over just the new index.php to my server to make the recent changes.

**Comment by Boombrewer** [comment]
Also, with the previous files (V2 release) and the new init.d file, I get this for status:
![image](https://cloud.githubusercontent.com/assets/6321429/4129929/66731ae8-332d-11e4-955b-967820e72239.png)
But my pours aren't updating.  It doesn't match your example exactly but everything looks correct from what I can tell.  Any ideas?

I did get this when I tried to update the rc.d defaults
![image](https://cloud.githubusercontent.com/assets/6321429/4129961/0c2f3570-332e-11e4-8400-b57e0cfd0b31.png)
And when I reboot, it shows the "kill" as a fail (no process running) but when it boots, it show the RPFlowMon deamon starting okay.

**Comment by mcangeli** [comment]
What's the server error?

When's the last time you did an apt-get update
Apt-get upgrade on your system?

**Comment by thadius856** [comment]
@boombrewer You do realize that first image is showing that the script
isn't running, right?

**Comment by day-trippr** [comment]
Right - the result of that ps aux command only shows the command itself.
The message about the "mathkernel" script may be normal, I saw the same error at the same point.

Cheers!

**Comment by Boombrewer** [comment]
@mcangeli - too many homebrews last night.... let's get the init.d file running properly and then I'll see if I can re-create the server error. (I didn't get a screenshot, just went back to previous install)  I did run update and upgrade though and the error persisted.

@thadius856 - I realized it wasn't running when I rebooted but I still get this....
![image](https://cloud.githubusercontent.com/assets/6321429/4135192/d5cbb7ec-3373-11e4-96eb-a76456b89533.png)

I'm once again on new terrain.  To me, one says its running and the other says its not running.

**Comment by mcangeli** [comment]
It is running. If you set it up according to the instructions and rebooted
you shouldn't have to do anything.

It's set to run at startup.

The sudo /etc/init.d/flow mon start

Is only if you need to restart it from the cli without a reboot

**Comment by Boombrewer** [comment]
I think it was really the baud rates and changing files that was screwing me up.  I have it working now.

I'll try updating files to the new ones to see if the server error comes back.  Just to make sure I'm using the correct branch, its "Version2" right?

**Comment by mcangeli** [comment]
Yes

**Comment by Boombrewer** [comment]
@mcangeli - This is the server error I'm getting (sorry the picture sucks - best I could do quickly).
![img_0992](https://cloud.githubusercontent.com/assets/6321429/4160162/8c90efd4-34b3-11e4-8179-5c6be38cbeb9.jpg)

**Comment by day-trippr** [comment]
Take a look at the tail of /var/log/apache2/error.log and see if there are any hints there. The last problem I had was exposed therein...

Cheers!

**Comment by Boombrewer** [comment]
Got it working.  Log file showed a PHP parse error with index.php.  I was using GitHub app to pull down files for upload to server and I think some of the files weren't correct.  Downloaded the zip file (as I've always done in the past) and it worked fine.  Weird.

Thanks for the help guys.

**Comment by day-trippr** [comment]
Excellent! Hope you enjoy this as much as I do!

Cheers!
