### ISSUE TITLE
Hotfix V2.0.1

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#292]
@Skemp45 I think the first hotfix for Version 2 (2.0.1?) is ready to be made out of the current version 2 branch.

It corrects the issue with tapping a new keg when you aren't using flow meters and it also corrects the issue with not showing the correct starting volume image if the starting amount is less than the keg volume.

Also included is the flowmon init.d script from: https://github.com/RaspberryPints/RaspberryPints/issues/290

**Comment by day-trippr** [comment]
fwiw, I have all of the latest/greatest components in place and everything has been playing together wonderfully. With the starting volume fixed and the flow monitor script moved to a system service I think 2.0.1 is ready for prime time. 

It really is a great piece of work, folks. Y'all done good! 

Cheers!

**Comment by mcangeli** [comment]
@skemp45 can you push this and update the install directions to include the init.d script and not the change to autostart?

**Comment by day-trippr** [comment]
Ping! 

Could we celebrate the speedy server with the release of v2.0.1?

Cheers!

**Comment by Skemp45** [comment]
LEts give it 2 days till the dns is all resolved then we can sound good?

**Comment by day-trippr** [comment]
That would be just fine, thanks. It'll make bringing up the noobs a lot easier...

Cheers!

**Comment by Skemp45** [comment]
OK, I am going to publish this hot fix, what branch does it need to be made from?

**Comment by Skemp45** [comment]
And what do i need to inform the users of that changes, do any of the instructions need updated with hot fix 2.0.1?

**Comment by day-trippr** [comment]
It's the "Version2" branch. 

And best as I can recall, the one thing that diverged from the original installation instructions is moving pour_monitor.py to a service. But I see Mark put an updated instructions.txt in the Version2 kit. If you can pull those changes into the original V2 installation procedures I think the rest was just "fixing stuff" that doesn't require any changes to the step by step stuff...

Cheers!
