### ISSUE TITLE
Pours table modifiedDate update?

### ISSUE THREAD

**Issue by BillKlineVT** [RaspberryPints/RaspberryPints#294]
So I'm looking at pulling analytics from the pours table in the database and I see the modifiedDate field, but I don't see that being updated when a pour is inserted via the pours.php script.  I know analytics aren't part of version2, but if I update it to pull a time stamp and add it to the pours.php $qry= code ... Am I on the right path here? I'm not new to coding but php and SQL are semi-new to me.

My goal is to pull metrics on how quickly a particular beer is consumed and plot it over time to keep record of which beers were the most popular

**Comment by mcangeli** [comment]
It doesn't really need the modifiedDate field on the pours table as the
pours are not "updated" once made.

**Comment by BillKlineVT** [comment]
Ok good point, then createdDate... Is that field auto-populated on an insert somehow I am not seeing?

**Comment by mcangeli** [comment]
Yes. Its autopopulated by mysql when the pour is entered in to the table.

**Comment by BillKlineVT** [comment]
Awesome, then I should be all set... Sorry I hadn't pulled my actual DB yet to see it, was just trying to follow it in the code.

Has any work on analytics displays been started yet?

Thanks for your fast replies!

**Comment by mcangeli** [comment]
I've started some (as I've implemented users and usertracking with RFID)
but as far as actual metrics to see how popular a beer is, etc... no.

**Comment by BillKlineVT** [comment]
So I checked my DB data and all of my pours have NULL for createdDate and modifiedDate.  If you look at my branch, my latest commit fixes that by updating createdDate in pours.php when an insert occurs.  I'm a github newb so not sure how to propose that get pulled into the Version2 of the original RaspberryPints repository.

**Comment by mcangeli** [comment]
Check the setting on your pours table.

Under the Default field for the CreatedDate field in the table, it should
say CurrentTimeStamp.

**Comment by BillKlineVT** [comment]
it wasn't, it was set to NULL.  I hadn't changed that since the original install of Version2.  Where do the defaults get set?

**Comment by mcangeli** [comment]
It should have been in the original setup of the database. (maybe I made
the switch on mine and forgot to update the code to update the table....)

**Comment by day-trippr** [comment]
I came over to ask the same question - the createdDate is NULL throughout my Pours table.
Can you get to the table settings through phpmyadmin? I can't seem to find them...

Cheers!

[edit] I found the not-quite-obvious thing to click. 
Does changing the table setting persist? Or is there a magical incantation required?
[edit2] It persists! Yay! 

Could this be snuck into v2.0.1 before it's officially released?

**Comment by mcangeli** [comment]
If you click on the table there should be a  link for structure. 

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Day Tripper notifications@github.com </div><div>Date:10/14/2014  11:21 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Pours table modifiedDate update? (#294) </div><div>
</div>I came over to ask the same question - the createdDate is NULL throughout my Pours table.
Can you get to the table settings through phpmyadmin? I can't seem to find them...

Cheers!

**Comment by day-trippr** [comment]
Thanks, I eventually figured it out and the pours table is now inserting the date/time data.

Cheers!
