### ISSUE TITLE
Tracking # of rpints installs.

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#295]
Trying to brainstorm a way to "track" the number of active rpints installs.

Any ideas?

**Comment by Skemp45** [comment]
We can add to the install script a script that writes to a database on one of my shared hosting accounts I don't care about. Make it grab the current count in the database then when a user installs it adds one to that number then reinserts that number into the database..... Just an idea.

**Comment by Skemp45** [comment]
any new ideas on this?
