### ISSUE TITLE
HomeBrewTalk Front Page Article

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#296]
Gents,

I was contacted my an HBT mod asking we'd like to write an article on RPints to be featured on the front page.

Would any of you gyys be interested in this? Seems like a great way to get the word out, especially with v2 stable.

Let me know what you think.

**Comment by Skemp45** [comment]
I could write the article, just pm me shawn@besmartdesigns.com and let 
me know what they are looking for.

**Comment by mcangeli** [comment]
I was going to suggest Skemp45 or Day-trippr

hah, but he beat me to it.

**Comment by thadius856** [comment]
They didn't provide any guidance on what they're looking for, but based on
previous FP articles I would probably go this direction:

. Intro with Wikipedia style first sentence summary + Time and cost.
. Benefits
. Customization / personalization
. Community mods / support
. Outro + link to website + issue challenge to builders/modders

I'll PM you their contact email.

**Comment by Skemp45** [comment]
forgot to send this to the admin Hhahaha I will take care of it
