### ISSUE TITLE
SOLD OUT flow meters

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#298]
Team,

the supplier (ebay user) we were using for flow meters has sold out of all of them. We need to find a new solution ASAP, I have been working with the guys at fresh water solutions for the last few weeks but they are at least a few months out from carrying them. The only other solution I can find is these. http://www.swissflow.com/sf800.html same meters just no plastic end pieces. Any other ideas gents?

**Comment by thadius856** [comment]
The plastics ends are just John Guest fittings screwed on. I'm sure we
could measure our meters and provide the fitting info... users could then
select the tubing opening they wanted. I had to use reducers because I
didnt get the opportunity to pick mine.

**Comment by Skemp45** [comment]
I will keep talking with freshwater systems to see if I can get them to carry the sf-800's and see what discounts they can give our users, otherwise our project just got $40 more per tap :(

**Comment by Skemp45** [comment]
Do you have a link to the fittings so I can provide a solution if they NEED them

**Comment by thadius856** [comment]
Just dozing off, but will see if I can take measurements tomorrow. I know I
posted them previoudly on HBT, but don't feel like digging for that info
all night.
