### ISSUE TITLE
Error when editing tap, keg or beer lists

### ISSUE THREAD

**Issue by bnairuni** [RaspberryPints/RaspberryPints#300]
When I hit attempt to edit any of the my taps, my kegs, or beers, I receive the following error:

Fatal error: Cannot redeclare redirect() (previously declared in /Applications/XAMPP/xamppfiles/htdocs/RaspberryPints/admin/includes/functions.php:2) in /Applications/XAMPP/xamppfiles/htdocs/raspberrypints/admin/includes/functions.php on line 5

I am a PHP newbie, any help would be greatly appreciated.

Thank you in advance

Brent

**Comment by thadius856** [comment]
Never seen this before. I'm pretty sure that XAMPP is the culprit here, but need more info before I can reproduce.
