### ISSUE TITLE
Keg Number is stuck on select one when adding tap

### ISSUE THREAD

**Issue by bnairuni** [RaspberryPints/RaspberryPints#301]
I have updated my number of taps, and entered my two beers and kegs.  When I chose Keg Number, in the tap list/tap form, the select one drop down menu does not show any kegs to select.

This is a new install, 12/28/14

**Comment by bnairuni** [comment]
I figured it out, you can't have a keg in serving status and show in the list

**Comment by Skemp45** [comment]
correct! nice work
