### ISSUE TITLE
Metric Units and other issues 

### ISSUE THREAD

**Issue by Skurk187** [RaspberryPints/RaspberryPints#312]
Good day, I am noob at this and this is my first Raspberry Project so I apologies in advance if my question sounds stupid. 

I am almost done with the Installation, however i run into 2 problems so far 

1) Can i change the units to Metric?
2) When ever i want to add a beer to a keg in the Tap bar then it doesn't load nor display my new added beer. But when you check the keg list it say that the keg is in "serving" mode??

Also apologies if this inst the correct platform for this question.

**Comment by Philusha1983** [comment]
have you managed to make your raspberrypints metric? can you share your solution? @Skemp45
