### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#36]
Continuation of #12.

**Comment by thadius856** [comment]
Skemp, can you create the `Personalize` page?

Checkboxes would be nice for:
- [x] Show tap number column
- [x] Show SRM column
- [x] Show IBU column
- [x] Show ABV column
- [x] Show keg level column

The db entries are all in the `config` table:

showTapNumCol
showSrmCol
showIbuCol
showAbvCol
showKegCol

They're all set to 1 automatically when you import `schema.sql` for the first time.

**Comment by Skemp45** [comment]
Skemp,

You didn't include the users table. So we can't log into our admin panels. :\

If you're having a rough time adding files, you can email them to me.

well shoot, my bad!!! I will add the file here. Also in the includes/config.php and includes/conn.php you need to update with your db info.

**Comment by Skemp45** [comment]
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

---

## 

## -- Table structure for table `Users`

CREATE TABLE `Users` (
  `username` varchar(65) CHARACTER SET utf8 NOT NULL,
  `password` varchar(65) CHARACTER SET utf8 NOT NULL,
  `name` varchar(65) CHARACTER SET utf8 NOT NULL,
  `email` varchar(65) CHARACTER SET utf8 NOT NULL,
  KEY `UserName` (`username`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

**Comment by Skemp45** [comment]
Just run that through sql and then go in to insert and add your user. in the password field dont forget to change the function of the password row to md5

**Comment by thadius856** [comment]
Huh. Uhh...

Think I'll just wait for the next commit. :)

**Comment by Skemp45** [comment]
Thad,

I added to the schema.sql so it will create the Users table and insert a default user of admin with password admin

**Comment by Skemp45** [comment]
Added support for changing header text and deactivating columns tonight

**Comment by thadius856** [comment]
Lots of updates tonight.

Deleted my whole /var/www/ directory contents, re-downloaded everything. Dropped the db, and re-imported both .sql files.

Created a new user in phpMyAdmin (localhost, woot//woot), updated those details into admin/includes/config.php and admin/includes/conn.php. Still no go on logging into the admin panel, either with woot//woot nor admin//admin.

Gotta run, or I'd fiddle more.

**Comment by Skemp45** [comment]
Ok I fixed this issue sorry!!!!!
I would suggest deleting completely and re downloading all files and uploading. I made a ton of changes last night and this morning. I then tested by deleting all my files on my server re downloading them and only making updates to includes/config.php, admin/includes/config.php, admin/includes/conn.php  and imported both sql files and BOOM site loads and works, admin login works everything displays properly. and you can now change header text, brewery logo which updates in both the admin and home page and you can switch columns on and off.

**Comment by Skemp45** [comment]
You can also change background image

**Comment by thadius856** [comment]
Holy mother of fuuuuuuuuuck. You've been busy, looking at the commit list.

Will blow away what I have, re-clone, and test per your instructions. Will let you know shortly. :) I'm probably just being retarded.

**Comment by thadius856** [comment]
Alright man, you're gonna have to add some comments if even I can't get this. Here's what I did.

__includes/config.php__ - enter view-only account name/pw (beer//beer) and db (raspberrypints)
__admin/includes/config.php__ - enter view-only account name/pw (beer//beer) and db (raspberrypints) [again... why twice?]
__admin/includes/conn.php_ - enter read/write account name/pw (woot//woot) and db (raspberrypints)
__Add users__ woot//woot via phpMyAdmin
__Head to tap list.__ Looks great, except logo missing.
__Click brewery logo.__ Log in as woot//woot. "cannot connect to server"

**Comment by thadius856** [comment]
Looks like you removed github//Pa$$w0rd from your hosted version. Not able to test your new features. :\

**Comment by Skemp45** [comment]
Does user admin and password admin log you in?

**Comment by Skemp45** [comment]
what do you mean by why twice?

$host="localhost"; // Host name
$username="TapList45"; // Mysql username
$password=""; // Mysql password
$db_name="TapList45"; // Database name
$tbl_name="Users";

**Comment by thadius856** [comment]
Unsure. Will test admin//admin in the morning.

Had an early morning. Gonna call it an early evening.

**Comment by Skemp45** [comment]
Ok, sorry for any issues man

**Comment by thadius856** [comment]
Ok, wiped _again_ and re-downloaded. Unzipped. Can somebody please tell me what I'm doing wrong here?

Edited includes/config.php. Added the read-only account (beer//beer).
Edited admin/includes/config.php. Added the read/write account (woot//woot).
Edited admin/includes/conn.php. Added the read/write account (woot//woot).

Can clearly see beers in db raspberrypints table beers. Taplist shows the header, but no beers.

Going to admin.php, I see a log-in page. I enter admin//admin, and I get "cannot connect to server".

The hell am I doing wrong here?

**Comment by Skemp45** [comment]
Can you paste the content of the 3 config files minus your password?

**Comment by thadius856** [comment]
includes/config.php:

```
<?php

function db(){
    $link = mysql_connect("localhost", "beer", "beer");
    mysql_select_db("raspberrypints");
}


?>
```

admin/includes/config.php:

```
<?php
 $host="localhost"; // Host name
$username="woot"; // Mysql username
$password="woot"; // Mysql password
$db_name="raspberrypints"; // Database name
$tbl_name="beers";


//Connect to server and select databse.
mysql_connect("$host", "$username", "$password")or die("cannot connect to server");
mysql_select_db("$db_name")or die("cannot select DB");

?>
```

admin/includes/conn.php:

```
<?php
 $host="localhost"; // Host name
$username="woot"; // Mysql username
$password="woot"; // Mysql password
$db_name="raspberrypints"; // Database name
$tbl_name="Users";


//Connect to server and select databse.
mysql_connect("$host", "$username", "$password")or die("cannot connect to server");
mysql_select_db("$db_name")or die("cannot select DB");

?>
```

**Comment by thadius856** [comment]
Dropped the db and re-imported the SQL.

Beers show up now, but still can't log into the admin panel as admin//admin nor woot//woot.

**Comment by Skemp45** [comment]
The only thing I can think of is maybe your db is not called raspberrypints like mine is TapList45

**Comment by Skemp45** [comment]
Ok so open you db and go into the Users table is admin in there? Also check checklogin.php and make sure that looks ok

**Comment by thadius856** [comment]
It is most definitely named raspberrypints.

![untitled](https://f.cloud.github.com/assets/6320180/1937412/ba676dc0-7f23-11e3-81bb-5c93e762131b.png)

**Comment by thadius856** [comment]
Yes, admin is there.

![untitled](https://f.cloud.github.com/assets/6320180/1937426/e60f632e-7f23-11e3-9224-67d4c2a6fe58.png)

**Comment by thadius856** [comment]
Am I supposed to change something in checklogin.php ?

```
<?php
session_start();
$session=session_id();
$time=time();
$time_check=$time-1800; //SET TIME 10 Minute

require 'conn.php';

// username and password sent from form
$myusername=$_POST['myusername'];
$mypassword=md5($_POST['mypassword']);

// To protect MySQL injection (more detail about MySQL injection)
$myusername = stripslashes($myusername);
$mypassword = stripslashes($mypassword);

$myusername = mysql_real_escape_string($myusername);
$mypassword = mysql_real_escape_string($mypassword);


$sql="SELECT * FROM $tbl_name WHERE username='$myusername' and password='$mypassword'";
$result=mysql_query($sql);

// Mysql_num_row is counting table row
$count=mysql_num_rows($result);
// If result matched $myusername and $mypassword, table row must be 1 row
if($count==1){
// Register $myusername, $mypassword and redirect to file "admin.php"
$_SESSION['myusername'] =$myusername;
$_SESSION['mypassword'] =$mypassword;
//session_register("myusername");
//session_register("mypassword");

echo "<script>location.href='../admin.php';</script>";
}
else {

echo "<script>location.href='../index2.php';</script>";
}
?>
```

**Comment by Skemp45** [comment]
Ok go to insert for the users table add a username email password and to the left of password there should be a drops down with options choose md5 then hit go and try to login with that info

**Comment by thadius856** [comment]
Tried inserting 'admin//admin'.

![untitled](https://f.cloud.github.com/assets/6320180/1937810/ca053f60-7f31-11e3-8b08-abb4047f7687.png)

Still, "cannot connect to server". This error seems to indicate to me that it's not even finding the db/table.

**Comment by thadius856** [comment]
Also added woot//woot. No change.

**Comment by Skemp45** [comment]
I think it has something to do with local host. I have 2 different hosting accounts one uses localhost for the databases and another uses hostnames as the db and site are on different servers. my local host is having same issues as you. I cant even get beers to load. Reviewing now

**Comment by Skemp45** [comment]
![errre](https://f.cloud.github.com/assets/6318869/1938140/f9b3f500-7f3e-11e3-9ff9-991ea83989c5.png)

**Comment by Skemp45** [comment]
ERRRRRRRRRRRRRRRRRRRRRRRR wait wait the password you are using.... is it your normal password? I was using Pa$$w0rd and getting same errors as you but then changed it to my normal password and boom do you have any $$ in yourS?

**Comment by Skemp45** [comment]
password for the database user that is

**Comment by Skemp45** [comment]
i set it up 3 more times without issue with the new password

**Comment by thadius856** [comment]
No man, I created a new SQL user for it. Right now, woot//woot.

You saying I need to provide my phpMyAdmin account info to it? I'll try in
this morning.

**Comment by thadius856** [comment]
Changed:

`admin/includes/config.php` to use my phpMyAdmin root login details.
`admin/includes/conn.php` to use my phpMyAdmin root login details.

Now instead of getting `cannot connect to database`, I get `(Wrong Username Or Password)`. That's an improvement, right? :)

Admin//admin and woot//woot are both in table Users. Admin//admin doesn't work, but now woot//woot does now! :dart: 

Question is... why do I need to give my phpMyAdmin user//password in `admin/includes/config.php` and `admin/includes/conn.php`? Seems pretty insecure to have the root pw floating around in plaintext within a sub-folder of www.

**Comment by Skemp45** [comment]
Having the database user inline in a file is no different than Wordpress, joomla, drupal etc.

**Comment by thadius856** [comment]
Looks like we're done here. Closing.
