### ISSUE TITLE
Compatability: Add support for 4k displays (double-height CSS/images)

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#39]
Image sizes (heights) are currently hard-coded in the HTML.

Can we rip the image heights out of the HTML and incorporate them into the CSS?

Edit by Thadius856 18 Jan 2014: Updating title to jive with new issue/milestone tracking scheme.

**Comment by JayUnt** [comment]
Which image height are you talking about? The only heights i can think about that are hard-coded are the full percent ones.  In which case we wouldn't be able to, to get eh precise 22%, but have the say if( height >= 20 && height < 25) class="twenty". and then in the css give the class .twenty{ height: 20%; }.

If its a different image, let me know and ill look at it.

**Comment by thadius856** [comment]
Full height ones, yes.

Here's my thinking. 4k TV's are right around the corner, and will be cheap sooner than later. 4k is 3840x2160, or exactly double 1080p in both directions.

Our currentcurrentayoit would look tiny on a 4k TV, so how could it be fixed?

Alternate CSS with all sizes doubled and double-sized versions of all images.

I can re-export at 200px height for most of these already.

**Comment by thadius856** [comment]
*current layout

**Comment by JayUnt** [comment]
Are we going to have some sort of detector to let us know the size of the screen? or you just want them all to be huge?

**Comment by thadius856** [comment]
Was thinking a simple checkbox in admin panel.
- [ ] 4k monitor

If checked, it uses sytle4k.css instead.

**Comment by JayUnt** [comment]
that works.  thats an easy fix, since all of those height and widths are already in the css file.  The only heights in the html are the calculated percentages to fill the hops/cups.  If we change the height of the containers they will still work.

This new style sheet would only really need the a few rows for overriding the image paths, height and widths and possibly/probably the individual hops positions.

**Comment by JayUnt** [comment]
If you want to export the higher res images and upload them, I can make a new stylesheet that uses them and also add this new item to the config table.

**Comment by Skemp45** [comment]
4k checkbox would be easy to do let me know of you want to go that route I can add that to the admin panel

**Comment by Skemp45** [comment]
I also got it to auto check the check boxes based off what the value for config_value is.

http://zookeeperbrewing.com/admin/df.php

Just need to make it submit the changes to the db now

**Comment by JayUnt** [comment]
i committed the high resolution config row into schema.sql, the name into the config_name file, an untested high res css file and its being included if the config is set.  The high-res.css is just a stripped down style.css with nothing else changed, for now.  Once the Thad uploads the high res images, i can update the url paths and make sure all of the heights, widths, and positioning works.

**Comment by JayUnt** [comment]
Skemp, if you add this as a checkbox into the admin, that would be awesome. thanks

**Comment by Skemp45** [comment]
Current Options view

![options](https://f.cloud.github.com/assets/6318869/1931204/87ba1a2a-7ebb-11e3-8ada-fb743158e309.png)

**Comment by JayUnt** [comment]
There should really only be one submit for the whole form. Not for each individual element.

**Comment by Skemp45** [comment]
Yeah, i am working on that

**Comment by Skemp45** [comment]
![options](https://f.cloud.github.com/assets/6318869/1935338/35e6389a-7ef8-11e3-8b45-3f3a199c36c6.png)

**Comment by JayUnt** [comment]
much better.

On Thu, Jan 16, 2014 at 4:50 PM, Skemp45 notifications@github.com wrote:

> [image: options]https://f.cloud.github.com/assets/6318869/1935338/35e6389a-7ef8-11e3-8b45-3f3a199c36c6.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/39#issuecomment-32550827
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
High res images incoming:

https://www.dropbox.com/s/dyr1rpmkrh41j6w/ibu%200.xcf
https://www.dropbox.com/s/e2oyf5l0kk4cmnj/ibu%2050.xcf
https://www.dropbox.com/s/2eeibbf8xgo1efh/ibu%20100.xcf

https://www.dropbox.com/s/un9mfpq9oycds5e/keg%200.xcf
https://www.dropbox.com/s/9146mfyli7jhzcb/keg%20100.xcf
https://www.dropbox.com/s/1bdqkez49cg8p7x/keg%20-%20blank.xcf

https://www.dropbox.com/s/bmvbu45uy7k4of9/pint.xcf
https://www.dropbox.com/s/9ijr4quphav1bd4/RaspberryPints.xcf

https://www.dropbox.com/s/67ogtfhjjoo3nv1/abv%200.xcf
https://www.dropbox.com/s/r32wp3duuxrbzjk/abv%20100.xcf
https://www.dropbox.com/s/buoi0r1uoc15zlb/abv%20200.xcf
https://www.dropbox.com/s/vty65d18366yfn1/abv%20offthechart%20%282%29.xcf

No SRM image because I plan to ever so slightly tweak the rpint logo to be the new SRM image. Really prefer the nonic pint glass to what we currently have.

**Comment by thadius856** [comment]
Added 4k versions of all of the graphics in Commit 99 -> 2b15b8de26797b68a48600b869b2eec2e88c5ee1
Updated high-res.css and upload 4k version of our logo in Commit 100 -> d62dae638f180137da9d3de7f07e4e00476d4726

Looks like:
- [x] Graphics
- [x] SQL
- [x] CSS
- [x] PHP
- [ ] Admin panel

Are we ready-to-roll other than admin panel?

**Comment by Skemp45** [comment]
I have the button added to admin panel and it enables that CSs sheet so looks like it's all good I just need to commit it

**Comment by thadius856** [comment]
Cool. :)

**Comment by JayUnt** [comment]
I still will need to update the high res css file to use the bees high res images. I'll work on that later tonight.

**Comment by JayUnt** [comment]
Unless, Thad, you did that already.

**Comment by JayUnt** [comment]
Derp, I just saw the commit you made. Nice!

**Comment by thadius856** [comment]
I did update high-res.css to point to the 200px versions of the images.

**Comment by thadius856** [comment]
Yeah, there's some derp in there alright. And I have no idea how to fix it. :\

**Comment by JayUnt** [comment]
I'll do an update tonight and take a look

**Comment by JayUnt** [comment]
The front end is done with the 4k changes.

**Comment by thadius856** [comment]
Very nice. Just tested. 2560x1600 (WUXGA?), so not quite 3840x2160 (4k).

![untitled](https://f.cloud.github.com/assets/6320180/1948822/a1578f10-80b6-11e3-84d7-8dd215a494c5.png)

Stood back 6 feet or so to get a feel for 4k resolution. Insanely tiny pixels. Fonts lookin a bit small at that distance. If we have the fonts set as em, can we just double it?

Also, can we double the header, brewery logo, RPints logo and tap circle heights?

**Comment by JayUnt** [comment]
Yeah we can. I increased the size of the tap circle, but in just looking at
it on my laptop, so it's hard to know a good size. By we can change
whatever sizes we want.

Do you know any css where you can figure out the right font sizes on the
better screen? Or later, I could update them all and commit and you can see
if that is better?

It's about time for me to zone out and watch tv from a long day. But I
could do it tomorrow.  It even set up all of the fonts in 4k, and show you
how to update them.

**Comment by thadius856** [comment]
Sounds good man. Have a good movie.

**Comment by JayUnt** [comment]
I committed a larger font with the 4k stylesheet.  The first item is body and i made the font size larger.  Take a look and adjust it if you think it should be.

You can also update the column widths to make them a bit wider to everything is on the same row and whatnot, like the srm number.

**Comment by thadius856** [comment]
Pulling your commit now.

**Comment by thadius856** [comment]
Not seeing any difference in font sizes.

I put the 4k and standard versions side-by-side. Text is exactly the same size.

**Comment by JayUnt** [comment]
Thats weird.  the style.css the body is using 1em for the font size, and in high-res.css the body is using 2.5 for the font size.  on my computer the one is a lot bigger then the other.

**Comment by thadius856** [comment]
Will nuke my install and try again.

**Comment by thadius856** [comment]
Works now. Go figure.

4k off (1200x1920):

![digital taplist layout v8](https://f.cloud.github.com/assets/6320180/1970463/c2cde32e-8309-11e3-9cca-7ec0a692c167.png)

4k on (1200x1920):

![untitled](https://f.cloud.github.com/assets/6320180/1970465/cf4a3e54-8309-11e3-864f-73562955c531.png)

4k on (2560x1600):

![untitled2](https://f.cloud.github.com/assets/6320180/1970466/d810fabe-8309-11e3-9f17-b09c05cb9147.png)

**Comment by thadius856** [comment]
Though the tap circle alignment is all jacked up. Which is odd, because I see vertical-align: middle; on tap-num.

**Comment by JayUnt** [comment]
Its vertical algined middle for me in both formats.  what browser are you
using?

On Tue, Jan 21, 2014 at 9:12 PM, thadius856 notifications@github.comwrote:

> Though the tap circle alignment is all jacked up. Which is odd, because I
> see vertical-align: middle; on tap-num.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/39#issuecomment-32987385
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Chrome on Win 7 and Chromium on Rasbpian.

**Comment by thadius856** [comment]
Pulled Commit 170 -> 117bc5b5edaf63c7300ff3c43bfa1ce957489475

Tap circles back to vertically centered. So weird. Don't see any appreciable changes to styles.css, outside of admin. Go figure.

**Comment by thadius856** [comment]
```
        <?php if($config[ConfigNames::UseHighResolution]) { ?>
            <link rel="stylesheet" type="text/css" href="high-res.css">
        <?php } ?>
```

Can somebody explain or link me to how this works? I'm not familiar with this function of php.

That is, the open `{` and the close `}`. What do they do? How do they work? Schwaaaaaat?

**Comment by JayUnt** [comment]
The { and } allow you to put multiple lines of code in a conditional.  I tend to always use them to make it clearer as to what you want the conditional to do.  With the following 2 examples, if $a = 2.  The first example will output "second output", since there is no {}, so the conditional only encompases the first line after.  The second example will not output anything.

```
if( $a == 1)
   echo "first output";
   echo "second output";
```

```
if( $a == 1 ){
   echo "first output";
   echo "second output";
}
```

make sense?

**Comment by thadius856** [comment]
Well yes, that makes sense. But wasn't really what I was trying to ask about.

 I totally get:

```
if ($a == b) {
   do a;
   do b;
   }
elseif ($a == $c)
   do c;
```

What I was asking about about is

```
<?php if($a == $b) { ?>
abc
xyz
123
<?php } ?>
```

Does this change the order they're processed in, or is it just for readability for us non-machines?

In other words, if I put:

```
<?php if($a == $b)
   echo "<a href="www.google.com">Google!</a>"
?>
```

The PHP will render the HTML tags as a direct print and not allow the CSS to kick in, so `a` typically won't pull from the `a { }` in the stylesheet. Will it do that with this alternate syntax?

Am I being clear as mud?

**Comment by JayUnt** [comment]
What you have will work just fine, except you would need to escape the quotes around the url.  I just prefer to close the php tag and then do the html so i don't have to escape the quotes and also, so i get the pretty syntax highlighting in my editor.  When its the way you have it, its just a php string and all one color.  With your example its not too bad, but when you go down further where the beers are being looped through, having those all in a php string would suck to write and to debug.

**Comment by thadius856** [comment]
So it's merely presentation? Fair enough.

From research, there also seems to be an alternate syntax for control structures, where you replace `{` with `:`, omit `}`, and use `endif`/`endwhile`/`endfor`/etc.

**Comment by thadius856** [comment]
Just commited (d7ac4b01b353eb0f272160e490d5b53311a31d18) 4k support for the RPints logo and the brewery logo. There's probably better short-hand to do it, but this gets the job done.

Since those were the last remaining objects without 4k support, closing issue as completed.

**Comment by JayUnt** [comment]
yeah I've seen that syntax.  But i'm used to { and } since all of the other languages use it.  I like to use the consistent syntax between the languages, so when there is mixing and matching, its not as confusing.  Like when I have php output javascript, since they both use { and }, i don't start using endif in the js and then it throws an error.
