### ISSUE TITLE
Database: build out all foreseeable tables

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#41]
Taking a look at `schema.sql` and noticed some of the columns for the `beers` table have odd data sizes.

```
CREATE TABLE IF NOT EXISTS `beers` (
  `beerid` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `style` text NOT NULL,
  `notes` text NOT NULL,
  `og` decimal(4,3) NOT NULL,
  `fg` decimal(4,3) NOT NULL,
  `srm` decimal(3,1) NOT NULL,
  `ibu` int(4) NOT NULL,
  `kegstart` decimal(6,1) NOT NULL,
  `kegremain` decimal(6,1) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `tapnumber` int(11) NOT NULL,
```

Correct me if I'm wrong. Does this makes more sense?

```
CREATE TABLE IF NOT EXISTS `beers` (
  `beerid` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `style` text NOT NULL,
  `notes` text NOT NULL,
  `og` decimal(1,3) NOT NULL,
  `fg` decimal(1,3) NOT NULL,
  `srm` decimal(2,1) NOT NULL,
  `ibu` decimal(3,1) NOT NULL,
  `kegstart` decimal(2,6) NOT NULL,
  `kegremain` decimal(2,6) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `tapnumber` int(11) NOT NULL,
```

Note, I left `active` and `tapnumber` for now, but they should really be on the `tap` table.

**Comment by JayUnt** [comment]
I think kegstart should be moved to the taps table and we can get rid of kegremain, since we will be calcuating it from the taps.kegstart - sum(pours.amount)

**Comment by thadius856** [comment]
Woops, totally missed that. But totally agree.

**Comment by thadius856** [comment]
Also og, fg, srm, ibu -> ogEst, fgEst, srmEst, ibuEst. (or similar)

**Comment by JayUnt** [comment]
I just looked at this again because im working finalizing the schema.  You changed the og and fg to be Decimal(1,3),  I had to double check because but i dont think that will work.  The first digit is the total number of digits and the second is the amount of decimal places.  So (1,3) means there is only allowed to be one digit and it had 3 decimal places.  I guess it will default to add 0s before, so it would only allow .000 to .009.  We really want 4 digits with 3 decimal places. 0.000 - 9.999

**Comment by thadius856** [comment]
Damn, good catch. Must have had a few that night.

I see you guys already fixed it. :)

**Comment by thadius856** [comment]
For schema.sql and easy upgrades (patching), what would you guys think about dropping tables if they exist, prior to creating them?

Ex:

``````
DROP TABLE IF EXISTS `beers````
CREATE TABLE IF NOT EXISTS `beers` (
...
``````

**Comment by JayUnt** [comment]
Dropping them would make the user lose all of their information that the put in.  So with the initial release, we can do it, since whoever is already using knows the system is in alpha and this is a risk of using an alpha release. But everything after that should really be updates/alters.

I would hate it if i inputted 50 beers into the system and then there is a patch that drops the table and i have to redo them all.

After the initial release we really should have 2 scripts, 1 thats the schema from scratch for any new users, and 1 thats the table updates / new table queries.

**Comment by thadius856** [comment]
Hrm. I'm on the same page as you now. Version patches will be a pain in the ass though, assuming I write the install instructions to install git and clone to their /var/www/ directory directly.

How about this:

We lock in the schema for each major release (v1.x.x, v2.x.x, etc).

While locked, we can add tables and columns. But no deleting, modifying, or re-formatting tables and columns. If you need to modify a column, create a new one. We'd end up with a couple spare columns, but we'd just yank those back out at the next major release.

That way, we only need to issue a single patch between each major version.

v1.x.x -> v2.x.x
v2.x.x -> v3.x.x
v1.x.x -> v3.x.x

etc

**Comment by thadius856** [comment]
Since we said `srm` is NOT NULL, we should probably have a 0 value just in case. Adding pure-white as 0 SRM.

Also changing `configValue` from longtext to tinyint(1).

**Comment by Skemp45** [comment]
we cant change configVaule to tiny int because now that the logoUrl and headerTest are in the config table their configValue  are admin/img/logo.png    and Beers On Tap

**Comment by thadius856** [comment]
D'oh! Ok, back to longtext. :)

**Comment by Skemp45** [comment]
lol

**Comment by thadius856** [comment]
Commit made. See 176662017a3db07814f0707ee560186bfc5dbd02.

This commit fills the kegTypes table with... a list of keg types.

Somehow, we lost the most important line from schema:

`CREATE DATABASE IF NOT EXISTS `raspberrypints` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;`

I added it back. :)

**Comment by thadius856** [comment]
Heads-up: index.php hasn't been updated for any of these changes. It's pretty well broken by now.

Edit: Taking an ugly stab at it now.

**Comment by JayUnt** [comment]
Yeah, i mentioned that in one of these issues. must have been the other one.  We should really convert index.php to use the taps table now.  So if you are going to update it, i suggest you do that.  Or you can just get it working and then ill make the changes later.

**Comment by thadius856** [comment]
I don't think I can even get it working, to be honest.

Going to dive into the site instead today and try to get the install instructions & FAQ going.

**Comment by JayUnt** [comment]
Ill fix it up tonight.

On Mon, Jan 20, 2014 at 1:22 PM, thadius856 notifications@github.comwrote:

> I don't think I can even get it working, to be honest.
> 
> Going to dive into the site instead today and try to get the install
> instructions & FAQ going.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/41#issuecomment-32784013
> .

## 

Jason Unterman

**Comment by JayUnt** [comment]
as i mentioned in another issue, index.php has been fixed.  I'm thinking we can close this issue now, but ill let you do it.

**Comment by Skemp45** [comment]
I think its resolved as well

**Comment by thadius856** [comment]
Great! Closing.
