### ISSUE TITLE
FAQ: generate images

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#45]
Generate images (mostly screenshots) for use with the FAQ.

**Comment by Skemp45** [comment]
DAMN this FAQ plugin, like to align all images to far right and wont listen when I say stay in place

**Comment by raysmithtx** [comment]
Skemp45,
I have used the Acronix FAQ on a lot of my websites. Each question is a separate post so you aren't limited with image placement, etc.

**Comment by thadius856** [comment]
I'm not particularly partial to any FAQ plugin or another.

I just picked the one we have because was high ranking in the search results. Load any FAQ plugin you prefer.

Skemp, can he do that himself or will he need your assistance (permissions-wise)?

**Comment by Skemp45** [comment]
He should be able to install plugins

**Comment by raysmithtx** [comment]
To give more flexibility in formatting, adding screen shots, etc. to the FAQ I will be moving to a new plugin. I will copy all existing FAQ info so the transition should be smooth. The old FAQ plugin will still be available just in case but will no longer be visible after the transition.

**Comment by thadius856** [comment]
Closing, because the FAQ doesn't really need images.

The install instructions do, and they have a couple already.

**Comment by Skemp45** [comment]
Not Closed. Closing for you
