### ISSUE TITLE
FAQ: proof-read

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#46]
Proof-read the FAQ for errors, inaccuracies and ambiguities.

**Comment by Skemp45** [comment]
I will have my SWMBO Proof read, she is a fantastic writer.

**Comment by Skemp45** [comment]
Added these FAQ
How do I change the brewery logo?
How do I change the header text (Beers On Tap)
How do I add a beer to my recipe database?

**Comment by Boombrewer** [comment]
Other ideas:

How do I manage my kegs? / What do the kick, renew, etc. buttons mean?
What if I want to refill the keg with the same beer?

**Comment by Skemp45** [comment]
Added 
Where can I buy the required flow meters?

**Comment by Skemp45** [comment]
Added 
How do I show/hide columns?
How do I change the background image?

**Comment by Skemp45** [comment]
Added 
How do I restore the default background?

**Comment by mtnbound** [comment]
I can put a lot of that kind of information in the documentation. It might be good to have all of the "how to use" in a single place.

Where do I buy flow meters is a good faq fire sure.

**Comment by Skemp45** [comment]
Yeah, shouldn't hurt having it in our FAQ though

**Comment by thadius856** [comment]
Yeah, I think the install documentation should be clean and to the point.

You're at A, being done is B. Here's how you get there as clearly and quickly as possible.

The FAQ should be for more nitty gritty details. For example, I have a huge FAQ entry on selecting a display. That shouldn't be in the install instructions. But it would be helpful to link to it from the Preparation page of the install instructions.

**Comment by Boombrewer** [comment]
I was going to recommend adding links from the install instructions to the FAQ.

And I have one more FAQ to add for you:

Q:  What if I have a Mac?  Can I still do this?
A:  If you can run Windows, yes.  If no, find a friend with a PC and let him drink beer while you do the setup.  : )

Seriously, not even worth the trouble from what I can see.

**Comment by Skemp45** [comment]
I have ran through the current faq and they look fine. we will create more as people ask us questions but for now this looks closed
