### ISSUE TITLE
Convert Database from CSV to SQL

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#5]
As said in title, convert the database from CSV to SQL.

Assume MySQL and phpMyAdmin will be installed.

**Comment by JayUnt** [comment]
A homebrewer friend from work is interested in joining the project.  He is our DB guy, so he would be a good fit for this task.

**Comment by thadius856** [comment]
Sure, send over or have him send over his username and I'll add/assign.

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/taplist.sql

Here is the link to my sql file I created to fit the database I created.

**Comment by thesehands** [comment]
I have a SQL file that I added to my fork as well, along with an index.php that has it integrated.

**Comment by Skemp45** [comment]
Ok perfect!!! I will check it out

**Comment by thesehands** [comment]
Apologize for the git mess I am still trying to figure this all out

**Comment by Skemp45** [comment]
no worries, its confusing haha

**Comment by JayUnt** [comment]
So multiple people don't work on the same issue, we should try to make it habit to have that issue assigned to you before you start working on it.  And if that issue is assigned to someone else, you can then talk to that person to talk about it/

**Comment by thesehands** [comment]
Sounds good to me, I would like to work on a mobile layout if anyone is interested. Thadius do you want to assign items?

**Comment by thadius856** [comment]
Sure, I can assign items. But I'm getting supremely confused on my end because we have two forks and a branch going.

Trying to merge them back to the master, but having problems with the SQL db not displaying any beers.

Part of my confusion stems from you guys not entering in any notes when committing to your fork. :P

**Comment by thesehands** [comment]
It is likely the connection string in includes/php/config.php there is a function my settings are localhosr root and no password they are likely different for you

**Comment by thadius856** [comment]
Ah yes. Good catch! I had glanced at that, but didn't take a deep enough look.

Not terribly\* sure I enjoy putting root/pw in plaintext. Perhaps I'll have to create a view-only acct. beer//beer or something.

Ready to merge your fork back in. Can you create a pull request?

Edit: Looking twice, the layout stretched quite a bit and the ABV images are no longer updating. Is this intentional?

**Comment by thadius856** [comment]
![untitled](https://f.cloud.github.com/assets/6320180/1865493/edad41ec-7810-11e3-9412-4cbb465a7be0.png)

**Comment by thadius856** [comment]
Also noticed keg fill is inverted, it appears.

5.3 pour is showing as 5.3 remaining in the keg. _shrug_

**Comment by thesehands** [comment]
Yeah that is one of the issues that I am still working on it should be an easy fix just havent had a moment today trying to to get my ethernet enabled temp controller done

**Comment by thadius856** [comment]
Understood.

Your branch has fallen out of sync with the main branch. No worries.

It'll have to manually re-merged. Jay may be up to the task to get us all back on the same branch, but maybe not.

Keep working on your controller. Sounds pretty cool. I'll keep you posted.

**Comment by Skemp45** [comment]
Really sorry if I caused stuff to get out of sync, never really used github before, won't happen again.

**Comment by thadius856** [comment]
Nah man, wasn't your fault. Happens any time multiple people are editing the same file.

Wouldn't have happened if I was around this morning to merge one or the other. Unfortunately, I'm on Active Duty, so I have absolutely no say in what times I want to work. :\

Most of my edits during the weekdays will come around 5-6 am PST or 5-10pm PST.

**Comment by Skemp45** [comment]
:D Thank you for your service

**Comment by thadius856** [comment]
Thank you for the paycheck!

**Comment by Skemp45** [comment]
ok, I updated the kegerface-SQL-SLIM branch, i updated the index.php and the style.css to support and pull in the tap handle column. should be fully updated with my changes along with what ever changes were there when I pulled it at 10:12 PM Arizona time

**Comment by thadius856** [comment]
Hrm. Not seeing any pull requests yet. Will hunt around.

**Comment by Skemp45** [comment]
![taplist](https://f.cloud.github.com/assets/6318869/1866085/4caf5d3c-7826-11e3-87ad-0254c2220388.png)
Here is my current view

**Comment by Skemp45** [comment]
Ok, maybe I did it wrong instead of "pulling" I just went to that branch and clicked edit and put my changed code into the file then at the bottom added my note and hit commit changes

**Comment by thadius856** [comment]
Yep. Just found that version. It's cool, I can still merge. ZIP is downloading for testing right now.

**Comment by Skemp45** [comment]
OK, please let me know.

**Comment by thadius856** [comment]
K, looked over it. I'm seeing what you're seeing, except I only have 3 entries (because I only have 3 entries in my SQL db).

While it opens up a couple new issues, I feel they're minor in comparison to the massive progress made here.

Will merge momentarily and open issues for the minor ones that have popped up.

Note for anybody coming into it at this point: you will need to install mySql, import the kegerface.sql file, and set your db user/pw is (/var/www) /includes/php/config.php.

**Comment by thadius856** [comment]
Reopening because GitHub is being a pain in my ass.

Can't merge the branch back in. Looks like that's a feature of Forks only, not Branches. To merge an out-of-sync branch back in, I'd need to resolve some faults via commandline, and Git is acting up on me.

Can you please create a fork from the current master, apply the changes you made on the SQL-Lite fork, then create a Pull Request? Sorry to have to ask. :\

You changes are here: https://github.com/thadius856/Digital-Taplist/compare/master...kegerface-SQL-SLIM

**Comment by thadius856** [comment]
Ugliest. Merge. Ever.

Sorry about how horrid it looks in the logs. After I manually updated index.php and committed with GitHub Desktop, it allowed me to merge the branches. Go figure.

We're all merged back up. I really need to learn git so this doesn't happen again.
