### ISSUE TITLE
Error handling: make taplist handle zero beers set to active

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#53]
When there's zero taps set to active, the taplist should display an error instead of being completely blank.

How about the following?

```
You don't have any beers added yet.

Would you like to <a href="admin.php">add some</a>?
```

**Comment by thadius856** [comment]
To be clear, what I'm looking for here as something to display on the front end if a user imports schema, but table beers is empty. I think this will come up a LOT otherwise.

**Comment by JayUnt** [comment]
This should show if there are 0 taps set.  If there are any taps set, we should have an empty tap row.  How do we want to show a tap is empty?  THis will also show if you have 3 taps, but only 1 and 3 have a beer attached.

**Comment by thadius856** [comment]
If there are zero rows in beers, there can not be anything in taps.

When a tap is inactive? Hmmm. Ill think on this.

**Comment by JayUnt** [comment]
Yeah, but even if there are beers in the system, you can have the number of tap = 0.  So im thinking we more care about checking that there is a tap number set, when showing this message.

**Comment by thadius856** [comment]
Hrm. I suppose. Just seems a little less intuitive.

How about (thinking in shorthand)

```
select * from table `beers`
if (notexist id = 1) {
     print you havent added any beer recipes.
     print perhaps you'd like to <a>add some</a>? }
elseif (numFaucets = 0) {
     print you don't have any faucets installed.
     print would you like to <a>add some</a>? }
```

For a faucet set to inactive, perhaps hide OG/SRM/BU:GU/IBU/kCal/ABV/poured/remain. Display the SRM, IBU, ABV and keg strokes at 50% opacity. Display "Inactive" for the beername, maybe "Beer faucet" for the style, hide notes entirely. How's that sound?

**Comment by Boombrewer** [comment]
If I understand it as current, it'll only show the 'active taps'.  So if I decide to load Tap 1 and Tap 3, it'll show two rows (labeled 1 and 3).  So if you have nothing on tap, you get no rows.

I think this is easier and ultimately cleaner than always showing 4 taps (in my case) with maybe 3 of them 'grayed' or whatever.  The only hiccup I see is the sizing on the screen.  But ultimately, I don't see that as much of an issue either.  If you want to see your screen full, fill your taps.

**Comment by thadius856** [comment]
Hard to say. This is what I see on my side:

![untitled](https://f.cloud.github.com/assets/6320180/1970742/c07c9044-8312-11e3-992e-45bd4f2d1073.png)

![untitled](https://f.cloud.github.com/assets/6320180/1970744/cd7d4e96-8312-11e3-88eb-679bdf349c83.png)

And that's with 10 beers loaded on a fresh, up-to-date image.

**Comment by Skemp45** [comment]
IDK why your beer_main page is looking like that but the taplsit page thats all there is right now.

**Comment by JayUnt** [comment]
good point boom.  So inactive taps will just not appear in the list.

I don't think there is really a need to do a special call to see if there are any beers in the beer list.  We can have a message if there are not active taps, saying "Hey, put some taps in the system." and when they go to the taps section, and if there are no beers in the system, we tell them to add beers first.

**Comment by JayUnt** [comment]
What is the admin password again?  i know this was mentioned many times, but i cant seem to find it.

**Comment by Skemp45** [comment]
admin admin

**Comment by JayUnt** [comment]
haha should have tried that one

**Comment by Skemp45** [comment]
;)

**Comment by thadius856** [comment]
Rofl.

**Comment by JayUnt** [comment]
I dont know what issues these are for, but i committed a bunch of stuff.  I added the ability to "delete" (aka inactivate) a keg, but only if there is not a active tap associated with it.  

I updated the beer form to match the other form styles, and added a beer listing.  You can also "delete" a beer if its not associated with an active tap.

I updated index.php to show a tap row if there is no tap associated with it.

And a coding change i did, was update a bunch of the includes to use **DIR** because it fixes the annoyance of how included files are considered on the level of the parent file, so if you include them in different levels, all shit hits the fan.  But this fixes that for the 3 listings, 3 form pages and index.php

**Comment by thadius856** [comment]
This issue was merely to show something on index.php if there are zero taps
active (test_data was not loaded). It was intended primarily to be a
preventative to keep us from getting tons of "omg bug help" submissions
from user error.

**Comment by JayUnt** [comment]
Yeah, thats not what i worked on.  i couldn't find the other issue for some
reason.  We can keep this issue open.

On Tue, Jan 28, 2014 at 4:33 PM, thadius856 notifications@github.comwrote:

> This issue was merely to show something on index.php if there are zero taps
> active (test_data was not loaded). It was intended primarily to be a
> preventative to keep us from getting tons of "omg bug help" submissions
> from user error.
> On Jan 28, 2014 1:22 PM, "Jason" notifications@github.com wrote:
> 
> > I dont know what issues these are for, but i committed a bunch of stuff.
> > I
> > added the ability to "delete" (aka inactivate) a keg, but only if there
> > is
> > not a active tap associated with it.
> > 
> > I updated the beer form to match the other form styles, and added a beer
> > listing. You can also "delete" a beer if its not associated with an
> > active
> > tap.
> > 
> > I updated index.php to show a tap row if there is no tap associated with
> > it.
> > 
> > And a coding change i did, was update a bunch of the includes to use
> > _DIR_because it fixes the annoyance of how included files are considered on
> > the
> > level of the parent file, so if you include them in different levels, all
> > shit hits the fan. But this fixes that for the 3 listings, 3 form pages
> > and
> > index.php
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/RaspberryPints/RaspberryPints/issues/53#issuecomment-33527159
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/53#issuecomment-33528564
> .

## 

Jason Unterman

**Comment by JayUnt** [comment]
This has been committed.

I put #53 in the comments of the commit and it linked the commit. how cool.

**Comment by thadius856** [comment]
Yup. It does the reverse too if you paste the SHIA for a comin here.

**Comment by thadius856** [comment]
*SHA

**Comment by thadius856** [comment]
Closing as completed.
