### ISSUE TITLE
Images: replace SRM image set

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#55]
The SRM images were carried over from Kegerface/Kegerface.

They must be re-created or replaced with free versions before we can re-license.

**Comment by Skemp45** [comment]
I might have missed something and you guys may be aware so just let me know but it looks like there is an issue with the srm images.
![srmissue](https://f.cloud.github.com/assets/6318869/1949675/421ebbce-8118-11e3-8968-db70522664c6.png)

**Comment by thadius856** [comment]
Looks fine from here.

![untitled](https://f.cloud.github.com/assets/6320180/1949993/affd857a-812d-11e3-967a-c8115f07f06d.png)

What browser you using?

**Comment by thadius856** [comment]
4k turned off:

![untitled](https://f.cloud.github.com/assets/6320180/1950002/faf77b12-812d-11e3-8c81-203dca79afbe.png)

**Comment by Skemp45** [comment]
chrome, I will look into it

**Comment by thadius856** [comment]
Unable to re-produce this error. The final product looks great on the Pi from here.

Closing as completed.

**Comment by Skemp45** [comment]
No worries,

I was in Firefox doh

**Comment by thadius856** [comment]
Found the answer why it looks like that in Firefox:

```
According to MDN, you can just use mask for Firefox, as of Firefox 3.5:

https://developer.mozilla.org/en/CSS/mask
However, mask requires an SVG image to act as the mask. You might be able to base-64 encode your SVG image into your stylesheet, or you can use an SVG image file.
```

We're using PNGs, with which Firefox does not support using the mask-image: property we have in our CSS.

**Comment by JayUnt** [comment]
I can try to convert the images into svg. I've never done that before but I'm going to assume gimp can do it, it there is an online converter.

**Comment by thadius856** [comment]
I wouldn't bother. Since the install instructions will specify Chromium, it won't make a difference to the end user.

The only people who will see a difference are Firefox users viewing it over the public interwebs. And eventually Firefox will probably be patched to support this anyway.

**Comment by JayUnt** [comment]
works for me :)

On Mon, Jan 20, 2014 at 12:28 PM, thadius856 notifications@github.comwrote:

> I wouldn't bother. Since the install instructions will specify Chromium,
> it won't make a difference to the end user.
> 
> The only people who will see a difference are Firefox users viewing it
> over the public interwebs. And eventually Firefox will probably be patched
> to support this anyway.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/55#issuecomment-32779667
> .

## 

Jason Unterman
