### ISSUE TITLE
Images: replace IBU image set

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#56]
The IBU images were carried over from Kegerface/Kegerface.

They must be re-created or replaced with free versions before we can re-license.

Suggestion: perhaps we just go to a single large hop with % fill like we do for kegs/abv?

**Comment by thadius856** [comment]
Replaced the IBU image. Broke some things. :\

Jay, I'd like the IBU image to return to a single background/single fill instead of the 10 little clusters. I know you probably want to kick me in the nuts because the 10-hop image logic took forever. Can you help me get it back to a single image?

**Comment by JayUnt** [comment]
As in you want one big hop and it fills like the others? Or you want to have to create the little increases over the 100 images?

**Comment by thadius856** [comment]
> As in you want one big hop and it fills like the others?

Yep. One big one. Fill by %.

If $ibu <= 100, height= $ibu px
If $ibu > 100, height=100 px

**Comment by JayUnt** [comment]
Sounds good.  It was a bit of work, but not too crazy.  Ill work on that and fixing up the rest of the 4k images.

**Comment by JayUnt** [comment]
I just committed the front end 4k image changes.  I also made the ibus just a single image, like you wanted.  You changed some of the empty.png files to be stroke.png.  So i went and changed the rest to stay consistent.

**Comment by thadius856** [comment]
Looks great. Closing.

Committed -> 63050626d2c6edd747387db009fdfb3158f0454e
