### ISSUE TITLE
Licensing: re-license under an appropriate free license with attribution and non-commercial use

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#59]
Current license is incompatible.

Once the remaining assets that were carried over from Kegerface/Kegerface have been replaced (#55 + #56), a new license can be applied, as we will have all original assets.

**Comment by Skemp45** [comment]
#55 and #56 have been completed, what can we do with this now?

**Comment by thadius856** [comment]
Re-licensed under GNU GPL v3.0.

To complete re-licensing, we need to change the font of the column headers (easy), change the table borders (easy), and change the default header text (easy). Those should be our last remaining assets.

I'm thinking:

For the headers, Georgia, non-italic, bold.
For the table borders, horizontal only, dotted or dash-dot.
For the header text, "Currently on Tap".

Any input?

**Comment by Skemp45** [comment]
I updated main script for header text and headers font

**Comment by thadius856** [comment]
Success. :)

**Comment by thadius856** [comment]
Now we just need the border changes, and we're done.

**Comment by Skemp45** [comment]
Do we HAVE to change that for this? IDK how I feel about the look
![borders](https://f.cloud.github.com/assets/6318869/2040440/ced14b4e-89b6-11e3-9129-3ba976d3e8a0.png)

**Comment by thadius856** [comment]
Doesnt have to be that specific font, no.

But I also dont want to infringe upon Kegerface.

Open to suggestions.

**Comment by Skemp45** [comment]
I like the font what I was talking about was the table border vertical looks alot better than table border horizontal
Font looks fine to me

**Comment by thadius856** [comment]
Hrm.

I think on alternate solutions today.

**Comment by JayUnt** [comment]
We can look into Google Fonts.  they are open source and are allowed on
private and even commercial projects.  I've used them in the past, where i
just link to Google's url for the font, but we can download the package it
seems too.  I dont know the size of the download, so it might not be great
for the limited size of the pi. But if we are going to assume that the pi
has internet access, we can just link to Google's location.  We can also
have a link to Google's location and also have a backup basic font.

http://www.google.com/fonts#AboutPlace:about

On Thu, Jan 30, 2014 at 9:04 AM, Skemp45 notifications@github.com wrote:

> I like the font what I was talking about was the table border vertical
> looks alot better than table border horizontal
> Font looks fine to me
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/59#issuecomment-33689927
> .

## 

Jason Unterman

**Comment by Skemp45** [comment]
![noborder](https://f.cloud.github.com/assets/6318869/2040535/1c17082a-89b8-11e3-919b-3592ca2e80e3.png)

**Comment by Skemp45** [comment]
Here is a font Idea I had. You cna use google API and include their fonts via stylesheet so no downloading nessary. The whole idea of this is to replace a chalk board, well why dont we still add some chalk board to it!!
![font](https://f.cloud.github.com/assets/6318869/2040654/14c5be52-89ba-11e3-8634-a4453f701cdb.png)

**Comment by JayUnt** [comment]
hahah.  I was just writing up this response when you sent that one Skemp:

One of my friends was saying it could be cool if we made it look like a
chalhboard.  We cuold look for a free chalkboard background and use a chalk
font.  Just a suggestion.

http://www.youthedesigner.com/2013/08/02/20-free-chalkboard-fonts/

On Thu, Jan 30, 2014 at 9:09 AM, Skemp45 notifications@github.com wrote:

> [image: noborder]https://f.cloud.github.com/assets/6318869/2040535/1c17082a-89b8-11e3-919b-3592ca2e80e3.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/59#issuecomment-33690363
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Oh, me no likey that font. Remind me of comic sans. Barf.

Thats a great idea for once we get multiple themes going tho.

**Comment by Skemp45** [comment]
Comic Sans walks into a bar, bartender says, “We don’t serve your type.”

**Comment by thadius856** [comment]
_rimshot_

**Comment by thadius856** [comment]
Closing as completed.

Will re-visit additional layouts in future versions as a new feature.
