### ISSUE TITLE
Add Tap Number Column

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#6]
Simply enough, add a tap number column.

**Comment by Skemp45** [comment]
I forked the project and I have added the Tap # to the screen. It all lines up perfect for me so let me know if ti looks weird to you guys.https://github.com/Skemp45/Digital-Taplist

-------- Original Message --------
Subject: [Digital-Taplist] Add Tap Number Column (#6)

**Comment by JayUnt** [comment]
I didnt pull down the code to see it in the browser but the code looks good
to me.

On Tue, Jan 7, 2014 at 9:07 AM, Skemp45 notifications@github.com wrote:

> I forked the project and I have added the Tap # to the screen. It all
> lines up perfect for me so let me know if ti looks weird to you guys.
> https://github.com/Skemp45/Digital-TaplistShawn KempCEO/ OwnerBe Smart
> Designs(319) 531-2580This e-mail transmission contains information that is
> confidential and may be privileged. It is intended only for the
> addressee(s) named above. If you receive this e-mail in error, please do
> not read, copy or disseminate it in any manner. If you are not the intended
> recipient, any disclosure, copying, distribution or use of the contents of
> this information is prohibited.
> 
> -------- Original Message --------
> Subject: [Digital-Taplist] Add Tap Number Column (#6)
> From: thadius856 notifications@github.com
> Date: Mon, January 06, 2014 9:52 pm
> To: thadius856/Digital-Taplist Digital-Taplist@noreply.github.comSimply
> enough, add a tap number column. —Reply to this email directly or view it
> on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thadius856/Digital-Taplist/issues/6#issuecomment-31739503
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Checked in browser. Some things are breaking. Note, screenshot is on a 1920x1200 monitor, as the Pi did even weirder things at 1920x1080.

![image](https://f.cloud.github.com/assets/6320180/1859910/0166fa90-77ab-11e3-901d-bdcfa8b14356.png)

Spotted a couple things:
- [ ] In index.php and style.css, you use TapNum. In beers.csv, you use TapNumber.
- [ ] Is there any way we could pull the tap number from the existing primary key column (Beer1, Beer2, etc) instead of creating a new manual column in the CSV?
- [ ] Your TapNum div is calling at the very end of the loop, pushing it to the right-most column. I think you meant this div to occur before the the SRMcolumn div?

**Comment by Skemp45** [comment]
Ok I am writing on a screen that is 1280X1024 so thats out problem here as mine looks like this. 
![taplist](https://f.cloud.github.com/assets/6318869/1859979/3e7ecefc-77ac-11e3-96fc-0525234adbfb.png)

**Comment by Skemp45** [comment]
I can move to the front, for some reason I got the idea it was asked to be at the end, my bad. I will look to see if there is any way to pull the tap number based off the position of the beer.

**Comment by thadius856** [comment]
Huh. What browser are you using? It's completely failing to render the HR's
with the CSS modifications. I recommend Chromium for web-kit compatibility.

**Comment by Skemp45** [comment]
^^ that was because I was zoomed out

**Comment by Skemp45** [comment]
![taplist](https://f.cloud.github.com/assets/6318869/1860055/905d3500-77ad-11e3-8a71-73561c0998ba.png)
Here it is moved to front and zoomed back in

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/KEG/

This is the tap id added with thesehands sql version!

**Comment by Skemp45** [comment]
I updated file

**Comment by JayUnt** [comment]
That link is giving me a 404.  Does github give you any sort of hosting for
these repositories, or should we create a dev host somewhere?  Or we can
just hijack zookeeperbrewing.com :)

On Tue, Jan 7, 2014 at 12:57 PM, Skemp45 notifications@github.com wrote:

> I updated file
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thadius856/Digital-Taplist/issues/6#issuecomment-31761369
> .

## 

Jason Unterman

**Comment by Skemp45** [comment]
haha, we can upload to my host if you want, I have lots of diffrent hosting accounts

**Comment by Skemp45** [comment]
also zookeeperbrewing.com here, i moved it when I was working on the box

**Comment by thadius856** [comment]
Completed. See Issue #5  for details.
