### ISSUE TITLE
Offical Release Date

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#62]
Can we put together an offical release date so I can update raspberrypints.com with the right countdown so we can send the followers the link to that also so they can sign up for updates aka our future newsletter

**Comment by thadius856** [comment]
On the issues page, look for the milestone tab.

I meant to bring up this conversation. I selected a random date for the milestone that would allow us to be done by Valentines Day (for the wives sakes).

I havent released any dates yet publicly.

The green progress bar is directly updated my closing issues assigned to that milestone.

Input?

**Comment by Skemp45** [comment]
I feel to really make sure everything works right and we don't release a ton of bugs we should shoot more for mid February. plus the longer the wait (not too long) will help build anticipation.

**Comment by Skemp45** [comment]
feb 20th??

**Comment by thadius856** [comment]
Release on Thursday Feb 20 sounds good. That gives peoples a chance to install Friday, identify some issues (you know they will!), and then we can use the weekend to fix them.

If we're going to stretch it out this long, I think it would be worth it to cut off development at ~ Feb 13. Then spend that entire week trying to tighten up everything we have for extensibility and efficiency.

**Comment by Boombrewer** [comment]
If you guys want, I'll volunteer the hours to start poking and prodding at it to work out what I can.  Just let me know when and how you think it best and I'll try to break it.  : )

After all, I'm usually pretty good at breaking things... like its my job.

**Comment by thadius856** [comment]
It's always welcome.

If you're a novice and have a Pi, I'll soon be at the point where I could use testers for my instructions. What may seem clear to me or an experienced user, may not be at all to a novice.

**Comment by Boombrewer** [comment]
I do have a Pi and I am a novice.  So I'd say I'm a perfect fit.  And I used to write procedure / work packages for others so I have a little experience with this kind of thing.  More so than coding - for sure.

**Comment by thadius856** [comment]
If you get bored, I've gotten part of the instructions done. :)

http://raspberrypints.com/site/

**Comment by Skemp45** [comment]
ok, countdown is set http://raspberrypints.com/
If you want to post that in the form thread to get people excited!

**Comment by thadius856** [comment]
Going to consider this completed. Release date set for 20 Feb 14.
