### ISSUE TITLE
Private Bug Tracking

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#64]
http://raspberrypints.com/bug/

I have put together a way for us to Bug Track or organize issues for when we release the product. you all have usernames. 

They Are

ethan- ejordan
jay- JayUnt
thad- thadius856
mine- skemp

Your passwords were set ny default but in all of your emails I sent password reset links so you can go in them and reset it to gain access. 
ethan- ethan@raspberrypints.com
jay- jay@
thad- thad@
mine- shawn@

this is a great issues tracking tool with all kinds of things we can do. Like, when we make tickets if it is a common issue we are seeing we can link tickets together and address them all at once when we fix the bug. 
Select if it is certain platforms, add attachments etc. 

Let me know what you guys think. I feel this will really help us get organized and solve the issues we will discover after release and manage this like a real project.

**Comment by Skemp45** [comment]
I have created one example ticket in there just while I was playing around in it./ feel free to create a few and mess around

**Comment by thadius856** [comment]
I haven't had a change to dig in and play yet.

What's your vision for this?

Will it integrate with the "Submit a Bug" page on the admin panel? Will we manually create bugs as we receive them?

**Comment by Skemp45** [comment]
Yeah, 

Users can email to issues@ and it will add as an issue in our tracker. Yes The form on our website both the add a feature and report a bug can be send into this tracker if I set it that way

**Comment by Skemp45** [comment]
Updated feedback.php and report_bug.php to submit right into this tracker this way we can all see them and make notes etc. on steps we took to resolve

**Comment by Skemp45** [comment]
We decided to use github to track and fix bugs. closing this ticket
