### ISSUE TITLE
Admin Panel: Create "About" Page

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#66]
Initial release is currently in 25 days.

We should really have an "About" page in the admin panel. I can write the generic mission statement BS you'd expect to see there.

Is there anything special you guys would like to see there?

**Comment by Skemp45** [comment]
nothing I can think of

**Comment by thadius856** [comment]
Will leave this open for another day. If no inputs, I'll remove as a release requirement and delete it from the admin panel.

**Comment by Skemp45** [comment]
Bump

**Comment by Boombrewer** [comment]
I recommend deletion based on lack of interest.

**Comment by thadius856** [comment]
Second.

**Comment by EmDubeu** [comment]
Nobody reads the about page anyway.  To hell with About.

**Comment by Skemp45** [comment]
Removing from the left_bar.php in the dev branch and closing as this is not needed
