### ISSUE TITLE
Admin Panel: Create "Licensing" Page

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#67]
Initial release is in 25 days. We need to create a "Licensing" page.

We've been working under a CC-by-SA 3.0 unported license thus far, IIRC. Does anybody have a specific license they prefer?

I'd like to make this as free as possible for home use, while preventing three things:
1. A commercial entity from coming along, swiping our code, and re-selling. (e.g., Frostwire -> Limewire)
2. A business from installing in their premises and pretending it's their product.
3. A business from getting lawsuit happy if it breaks on them.

If no preferences, I'll choose something that fits these the closest.

**Comment by Skemp45** [comment]
1. I agree
2. I think business should be able to use for free but should have a rule in there that states that they cannot alter the original source code, so they cant remove the powered by logo.
3. THIS THIS THIS THIS lol

**Comment by thadius856** [comment]
After much thinking and a couple beers in IRC last night, decided this didn't need to be in the admin panel. All of our DYNAMIC content should be on our site, and we should be linking externally to it.

Created a WP page for licensing, then updated the link to it from the admin panel.

d55a7de5907a318649627cfb9820f42fd2c03dad

Closing as completed, as I can't see how ugly the site is until we go live.

**Comment by JayUnt** [comment]
agreed.

On Wed, Feb 12, 2014 at 8:53 PM, thadius856 notifications@github.comwrote:

> After much thinking and a couple beers in IRC last night, decided this
> didn't need to be in the admin panel. All of our DYNAMIC content should be
> on our site, and we should be linking externally to it.
> 
> Created a WP page for licensing, then updated the link to it from the
> admin panel.
> 
> d55a7dehttps://github.com/RaspberryPints/RaspberryPints/commit/d55a7de5907a318649627cfb9820f42fd2c03dad
> 
> Closing as completed, as I can't see how ugly the site is until we go live.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/67#issuecomment-34940629
> .

## 

Jason Unterman

**Comment by EmDubeu** [comment]
Agreed,  squared.

**Comment by kerber** [comment]
Sounds good.
