### ISSUE TITLE
Create "Contributors" Page

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#68]
Initial release is in 25 days. We should create a Contributors page in the admin panel to give ourselves a little credit.

Making the page is easy enough, but what shall we call ourselves by title? I think we should be able to come up with our own titles (within reason). And I'm thinking something along the lines of "Project Manager" for myself.

What title would you guys want next to your name?

Would you want a First M. Last, or a F. Last, or First L., or a pseudonym, or nothing at all?

**Comment by Skemp45** [comment]
First last picture? Lol

**Comment by JayUnt** [comment]
I'm fine with having my full name in there, Jason Unterman.  You can throw my middle initial in if that is the format we are going, S..

As for title, ill go with Application Developer, or just plain one President of Awesomeness. 

We should put our HBT usernames too, since that is where we met and started the project.

**Comment by Skemp45** [comment]
I agree first middle initial last name and what ever title then our HBT usernames I like that

**Comment by Skemp45** [comment]
Starting this

**Comment by Skemp45** [comment]
Created page and added an example, we can spruce it up and make it look nice but you get the idea

**Comment by Skemp45** [comment]
Who all needs to be on this page?

**Comment by thadius856** [comment]
Well, hate to say it, but add everybody you can think of.

If we miss anybody, they can chime in here.

Maybe for the non-bold people we could spell out exactly what they contributed to (like for tx, the website layout). I don't want to bother listing everything the three of us slaved over.

**Comment by Skemp45** [comment]
Ok, 

Here is how this is going to work. 

If you contributed to this project post your name here First middle Initial Last name or whatever you feel comfortable with. and next to your name list what you did to contribute to the project. Also if you are on home brew talk post your username so I can add it here. 

if you are not listed in the contributes page it will only be because you did not post here so please do if you helped.

**Comment by JayUnt** [comment]
I was thinking about adding my Untappd account too. What do you guys think?  Are any of you going to add yours?

**Comment by mtnbound** [comment]
Not sure how you see it working, and I'm not sure who, but someone posted an idea of scrolling your Untappd "brewery" RSS feed at the bottom.

Thought that sounded like a great idea.

On Monday, January 27, 2014 9:07 PM, Jason notifications@github.com wrote:

I was thinking about adding my Untappd account too. What do you guys think?  Are any of you going to add yours?

**Comment by JayUnt** [comment]
I was just thinking my username, so people can friend me of they want.
Nothing fancy :-)

**Comment by mtnbound** [comment]
Guess I should have looked at the thread name first :) Just noticed it was the contributors thread.

Maybe the other one is a feature request for V2 or V3.

On Monday, January 27, 2014 9:35 PM, Jason notifications@github.com wrote:

I was just thinking my username, so people can friend me of they want. 
Nothing fancy :-)

**Comment by Skemp45** [comment]
Jay,
If you want that let's make it happen!!
I'm cool with it

**Comment by Skemp45** [comment]
Whats your untappd usernames?

**Comment by JayUnt** [comment]
Lets see if you can guess it.  :)

**Comment by Skemp45** [comment]
hahaha check the page I just updated I found yours

**Comment by thadius856** [comment]
Good luck with mine. Its a real brain buster. ;)

Lets go with Thadius D. Miller. Not sure I'm real big into tying every pour
to my real name.

**Comment by JayUnt** [comment]
I searched for Skemp45 when i was making sure my username was JayUnt, but it wasnt there.  Was ShawnKemp was taken on HBT already?

We aren't posting anything to Untappd, just a place for ppl to see our usernames, and friend us if they want.  

Should we put this contributors page on the website too?

**Comment by Skemp45** [comment]
Yeah, I will add this to the website also, and I always use skemp45 but i connected to untappd with my Facebook profile, so I guess thats the username it gave me : \

**Comment by thadius856** [comment]
Added sloeschler (mtnbound) and raysmithtx to the contributors page. Created a second table, to separate project staff and contributors.

**Comment by thadius856** [comment]
Let me know if I forgot anybody.

If no response to that effect, close issue in 3 days.

**Comment by kerber** [comment]
While I've not committed anything to the codebase yet, I'm very actively developing the SF800 integration. I'll be more active in the discussion when it's time for it to communicate with the rest of the system.

**Comment by kerber** [comment]
I also plan on doing documentation of any modifications needed to make the 'slice of pi' expandable to multiple MCP23017 chips. I may do a custom board design as well.

**Comment by mtnbound** [comment]
Thad,

If you need it, my info is

Name - Scott Loescher
HBT - sloescher
untappd - sloescher

Thanks!

**Comment by thadius856** [comment]
Kerb,

Just wanted to make sure you were still here before I added ya. ;)

The Slice of PI/O is daisychainable to 8 units IIRC, for a total of 128 IO. Theres some pads you connect with on the backside, and you select the board number by bridging solder pads.

http://openmicros.org/index.php/articles/94-ciseco-product-documentation/raspberry-pi/223-slice-of-pio

**Comment by kerber** [comment]
Thad,

Yeah! The only problem is that there is no simple physical connection to daisy chain them. I was thinking of seeing about replacing the GPIO headers with extended stackable headers. This would allow someone to just stack the boards together after changing the address pads. It would greatly improve ease of use.

**Comment by thadius856** [comment]
I think stacked two high, you bump into css height restrictions.

I can't even close my case with a single Pi and PI/O, though. :\

**Comment by raysmithtx** [comment]
Ray Smith
HBT: raysmithtx
Untappd: raysmithtx

**Comment by sevlabs** [comment]
Hi All,
I Just came on board today to look at the ABV tweaks. I'm still feeling my way around but wanted to give you my info, just in case.

Seven Johnson
HBT: Seven
Untappd: SevenXXX

**Comment by kerber** [comment]
Most RPi cases don't handle any kind of daughter board well. It certainly won't fit in a case if we daisy chain, anyways. If someone has a setup that needs more than 1 IO expansion board, they will have enough invested in the process to figure out a bigger case.

**Comment by thadius856** [comment]
Closing as created.

Will update to add people who aren't already on the page once they submit code (or for the non-coders, once they complete their lane).
