### ISSUE TITLE
Admin panel: place beers on taplist

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#69]
Old thread #40

**Comment by Skemp45** [comment]
Thad,

if you want all these pages for 
header text background img  let me know I will split them up. 

But i feel we should have one page for all of them. I just really don't want to make it too complex and too many pages etc.

**Comment by Skemp45** [comment]
Ok Thad, 

Talk me down man lol, these menus are bothering me. I just feel like there is way to many sections and options now. You think we can reduce these? I hope your on today otherwise im not going to be able to sleep lol

**Comment by Skemp45** [comment]
What are you guys looking for on the beer recipes page for deleting domain? Do we want it to just set the beer to inactive but stay in db for statistics purposes? or fully remove beer from database

**Comment by thadius856** [comment]
For a delete page?

A view-only table, with a Delete button at the end of each row.

Delete sets binary 'inactiveRecipe' or somesuch on `beers` table to 1.

**Comment by thadius856** [comment]
> Talk me down man lol, 

Relax man, it'll be ok. ;)

> these menus are bothering me. I just feel like there is way to many sections and options now. You think we can reduce these? I hope your on today otherwise im not going to be able to sleep lol

Just trying to plan out where things will be in the future. We can set them to hide for now, but honestly that's probably about how many features we'll probably accumulated by v3.0.0.

For the existing options (the four on one page), you can split them if you like, but I don't think there's enough content on those pages for it to look good if you do. Just trying to plant the seed of the idea in the users head that they can change these settings.

**Comment by Skemp45** [comment]
Right on, I totally understand that users wont know they can do something unless there is a tab telling them to lol!

**Comment by Skemp45** [comment]
What i will do is create anchors to each section
this way when they click change background it jumps down to that section on the personalize page

**Comment by thadius856** [comment]
Broke the SQL trying to add tables last night.

Now it errors when when importing, somewhere near the InnoDB portion of the taps table.

Double-header AG brew day today, though. We'll see if I can find time.

**Comment by Skemp45** [comment]
GOOD luck with the brew, im brewing a Gluten Free chocolate coffee stout this afternoon

**Comment by JayUnt** [comment]
Yeah we shouldn't delete any rows from the database. Of we did, we would have to delete any associated tap rows and also the pour rows. It should really be an inactive button, which would remove that beer from the beer recipe dropdown in the taps from. We could add a reactivate button, so they can undo it.  But no delete IMO.

**Comment by JayUnt** [comment]
And the button can be on the beer listing page, right next to the edit button. We should have a confirm pop-up to make sure they know what they are doing.

**Comment by Skemp45** [comment]
I Like it

**Comment by JayUnt** [comment]
I see a numberOfKegs was added to the config.  Is this necessary?  To be kegs is more like beers, which is just a list of however many you want.  Where taps is more a specific amount where you can fill up to that number but not more.

**Comment by JayUnt** [comment]
And i fixed the kegs table creation in shema.  There was an extra comma at the end, and instead of kegs pointing to kegStatus.Status, it now points to kegStatus.Id.

**Comment by Skemp45** [comment]
Did you commit it>

**Comment by Skemp45** [comment]
Jay, 

on the tap_list page when I hit Tap a Keg I am getting 

Warning: Cannot modify header information - headers already sent by (output started at /home/content/78/10666578/html/admin/includes/conn.php:1) in /home/content/78/10666578/html/admin/tap_list.php on line 25

You aware of this? I imagine you just have not got to it yet

**Comment by JayUnt** [comment]
I'm pretty sure I committed, let me check. I used to use tortoisesvn, but I
kept getting errors. So I'm switching to tortoisegit to see if that will
fix it. More I have to get used to using tortoisegit.

**Comment by JayUnt** [comment]
Ok it looks like its committed now.  im going back between using the git gui and the tortoisegit. trying to figure out which one i like better.

Ill look into the header issue.

**Comment by JayUnt** [comment]
I wasn't getting that, but i but i committed a fix that should fix it for you.  I guess the conn.php was outputting a header, which messed with the header redirect.  I changed it to use js to redirect, and it still works for me, and hopefully will fix it for you.  I dont know why yours wasn't working like mine is, but thats what i gathered from the error message you gave me.

**Comment by Skemp45** [comment]
right on, I will review

**Comment by Skemp45** [comment]
Weird, the schema keeps dieing on import for me. I am going to import table by table and see which is causing the issue.

**Comment by Skemp45** [comment]
Jay,

for the Keg table you said

**Comment by Skemp45** [comment]
```
FOREIGN KEY (`kegStatusId`) REFERENCES kegStatuses(`status`) ON DELETE CASCADE
needs to be changed to 
FOREIGN KEY (`kegStatusId`) REFERENCES kegStatuses(`id`) ON DELETE CASCADE 
```

right?

**Comment by Skemp45** [comment]
EDIT: I resolved this one by doing 

```
echo "<script>window.location = 'tap_list.php';</script>";
```

I also think you need to do the same to tap_form.php as you did to tap_list.php

Warning: Cannot modify header information - headers already sent by (output started at /home/content/78/10666578/html/admin/includes/conn.php:1) in /home/content/78/10666578/html/admin/tap_form.php on line 28

got this when on tap_form.php

**Comment by JayUnt** [comment]
That is correct about the (status) to (id) change..

I turned the js redirect into a php function that i put in a new functions.php file.  I didnt make it a helper class for now, like the html_helper is, but we might want to do that.  But for now, it works.

**Comment by JayUnt** [comment]
let me know if you are still having problems with the schema.  I just ran it full on a new database and it went all the way for me. Was it just that FK issue that was breaking it?  That was a casualty of my switch to tortoisegit.

**Comment by Skemp45** [comment]
After I fixed that in the schema it went in but the test data kept giving error on the keg dump, something with the structure not matching up, I will have to look again

**Comment by thadius856** [comment]
I probably have a column mismatch somewhere in the kegs table.

First brew in boil, second brew mashing. Will look later (I hope)

**Comment by Skemp45** [comment]
Yeah its weird I just tried to take info and insert manually but got this 

```
SQL query: Edit

INSERT INTO  `TapList45`.`kegs` (

`id` ,
`kegLabel` ,
`kegTypeId` ,
`kegMake` ,
`kegModel` ,
`kegSerial` ,
`kegStampedOwner` ,
`kegStampedLoc` ,
`kegNotes` ,
`kegStatusId` ,
`beerId` ,
`createdDate` ,
`modifiedDate`
)
VALUES (
NULL ,  '1',  '1',  'Cornelius',  'Super Champion',  '016530387',  'Johnstown Production Center',  '',  'One hanndle cracked',  '4',  '', NOW( ) , NOW( )
)
MySQL said: Documentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`TapList45`.`kegs`, CONSTRAINT `kegs_ibfk_1` FOREIGN KEY (`beerId`) REFERENCES `beers` (`id`) ON DELETE CASCADE) 
```

**Comment by thadius856** [comment]
Oh. That makes sense.

Foreign keys are like filters. In that response, it's saying "you said we have to input a valid `beerId` (from `id` column on `beers table`), but the input you gave us (`''`) is not a valid beerId."

Here's the kick in the ass. Even if it was a valid beerId, it would still error. That's because we haven't loaded the beers themselves yet, they're still waiting in `test_data.sql`.

Delete the foreign key line from table `kegs` that references `beerId`. Since we've decided we're never deleting beers, it won't be an issue anyway.

**Comment by JayUnt** [comment]
Yeah kegs doesn't need to link to kegs, instead taps will have a kegId instead of the kegStyleId.

I feel like i am done with the taps stuff, minus the styling.  If someone else wants to style it, i can go onto making the new kegs listing/add/edit/inactivate.  Then i will come back to the taps, and change the kegType to pull from kegs instead.  I can style it, but you guys seem to have more of an eye for styling then i do, im more of a "you give me a style and ill match it."

**Comment by JayUnt** [comment]
Another thing that i see, all of the fields in the table start with keg (kegLabel, kegNotes, kegSerial, etc...).  They all are columns of the kegs table, so there is no need to repeat the keg part.  You should know ts a label for the keg because of the table.  KegTypeId and KegStatusId should still keep the keg part since they are FKs to those tables.

**Comment by thadius856** [comment]
> Yeah kegs doesn't need to link to kegs, instead taps will have a kegId instead of the kegStyleId.

Just fixed, but haven't committed.

> Another thing that i see, all of the fields in the table start with keg (kegLabel, kegNotes, kegSerial, etc...). They all are columns of the kegs table, so there is no need to repeat the keg part. You should know ts a label for the keg because of the table. KegTypeId and KegStatusId should still keep the keg part since they are FKs to those tables.

Fixing this now.

**Comment by JayUnt** [comment]
thanks!  Im working on the listing page as we speak.

**Comment by thadius856** [comment]
Committed -> 03e411de4464b865bd50ff4f6985a96b51b1741e

**Comment by thadius856** [comment]
Tested twice, imports without complaint.

**Comment by JayUnt** [comment]
Hey,  With KegStatus, are we going to automatically change a keg's kegStatus to serving when a keg is added to a tap?  What happens when they kick a keg? Do we change it to needs cleaning?  Or should we put all of these statuses on the user to update?

If we are going to do these automatic updates, we might want to give the table a unique code (which could replace the auto increment int id as the PK.  This would make it easier for us to set these values.  We could also change the status property to name, since that is what we call it in the other tables.  Just my 2 cents.

**Comment by thadius856** [comment]
T'would be nice to auto-update.

Tap a keg? kegStatusId = 1 (serving)
Kick a keg? kegStatusId = 5 (flooded)

> If we are going to do these automatic updates, we might want to give the
> table a unique code (which could replace the auto increment int id as the
> PK. This would make it easier for us to set these values. We could also
> change the status property to name, since that is what we call it in the
> other tables. Just my 2 cents.

Way over my head. If it needs doing, go for it.

**Comment by JayUnt** [comment]
Will do.  The reason i think we need to make them codes (like SERVING, BROKEN, etc) is that we cant really just assume id 1 is serving, since its auto-incremental number.  If for some reason a person went in and added a couple of status before running our status inserts, our #1 wouldnt be #1.  

Also, when a tap is started, setting it to status with id = 1 isnt very descriptive.  But setting it to status with code = SERVING makes perfect sense.  

Ill make these changes.

**Comment by Skemp45** [comment]
Brew session went well last night, My lady can not have gluten as of recently so we have been struggling to find her a good gluten free beer. I have been working on this recipe for awhile now, and it turned out well last night. 

I also think it named itself lastnight, ( Yin and Yang)
![gfstout](https://f.cloud.github.com/assets/6318869/2009452/6416cdb0-875e-11e3-90c7-fb02b2569127.jpg)

**Comment by Skemp45** [comment]
I edited the admin/beer_main.php and admin/includes/insert.php so you can now add beers from beer_main.php
I also added the section where we can list beers in view only so users can remove them. we just need to add the php to list them. 

Jay,

If you want to convert my add to database feature into a function thats cool!!

**Comment by JayUnt** [comment]
Sounds good to me. Once I'm done with the kegs stuff (should be soon) I'll
convert the beer stuff over to match.

**Comment by Skemp45** [comment]
YAYYY I found a big... Maybe

I added a beer, here it is in the database
![issue3](https://f.cloud.github.com/assets/6318869/2011617/4f641df4-877d-11e3-8560-09b1e9f1b4e0.png)

Then I see it on the  tap lsit page when I added it
![issue1](https://f.cloud.github.com/assets/6318869/2011619/580532b8-877d-11e3-962c-ea4533c57611.png)

But when i click edit tap list info, it updated the ibus to what the srm is set to... any ideas why
![issue2](https://f.cloud.github.com/assets/6318869/2011623/6a988772-877d-11e3-813b-144c25a861f7.png)

**Comment by Skemp45** [comment]
Found the problem

```
            <tr>
                <td>
                    SRM:
                </td>
                <td>
                    <input type="text" id="srm" name="srm" value="<?php echo $tap->get_srm() ?>" />
                </td>
            </tr>
            <tr>
                <td>
                    IBU:
                </td>
                <td>
                    <input type="text" id="ibu" name="ibu" value="<?php echo $tap->get_srm() ?>" />
                </td>
            </tr>
```

**Comment by Skemp45** [comment]
changing to 

```
            <tr>
                <td>
                    SRM:
                </td>
                <td>
                    <input type="text" id="srm" name="srm" value="<?php echo $tap->get_srm() ?>" />
                </td>
            </tr>
            <tr>
                <td>
                    IBU:
                </td>
                <td>
                    <input type="text" id="ibu" name="ibu" value="<?php echo $tap->get_ibu() ?>" />
                </td>
            </tr>

```

**Comment by JayUnt** [comment]
nice catch

On Mon, Jan 27, 2014 at 1:06 PM, Skemp45 notifications@github.com wrote:

> changing to
> 
> ```
>         <tr>
>             <td>
>                 SRM:
>             </td>
>             <td>
>                 <input type="text" id="srm" name="srm" value="<?php echo $tap->get_srm() ?>" />
>             </td>
>         </tr>
>         <tr>
>             <td>
>                 IBU:
>             </td>
>             <td>
>                 <input type="text" id="ibu" name="ibu" value="<?php echo $tap->get_ibu() ?>" />
>             </td>
>         </tr>
> ```
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/69#issuecomment-33402564
> .

## 

Jason Unterman

**Comment by JayUnt** [comment]
I committed the new keg listing/form.  I also updated the taps to be linked to keg instead of kegType.  There have been schema / test_data changes.  I will look into altering the beer list/form so it is more consistent with the keg and tap stuff.  Shouldn't be much, just tedious.  But i feel like most of the stuff was already made by Skemp and me with working on the other sections.  I dont think ill get to it tonight, but ill probably get it done tomorrow.

**Comment by Skemp45** [comment]
VERY VERY VERY nice Jay. 
one thing i saw is on the tap_form when adding a beer if you hit cancel it does not go back anymore, all the fields just light up red.

**Comment by Skemp45** [comment]
I also think we need to add a delete button on the kegs page. Incase someone gets rid of it or it breaks. With this I dont think it should remove it from the database but rather render it inactive for stats reasons.

**Comment by thadius856** [comment]
So, we need an inactive beers column, an inactive kegs column, and... an inactive taps column?

**Comment by JayUnt** [comment]
well this is the thread i was looking for but couldnt find.  I just commented on #53 with the changes i just committed.  I added these columns to the db and also updated the code so you can "delete" aka inactivate kegs and beers.  I also made the beer listing page, and updated the beer form page to match to the other forms.

I didn't really style too much, so someone else can jump in and do that.  Just basic styling.

I also updated the frontend to show an empty tap but the name is "Nothing on tap" which we can change. I just wanted to set it all up.

**Comment by Skemp45** [comment]
Nice work Jay, I will clean up style when i get home on those forms

**Comment by JayUnt** [comment]
Thanks and sounds good.

On Tue, Jan 28, 2014 at 4:36 PM, Skemp45 notifications@github.com wrote:

> Nice work Jay, I will clean up style when i get home on those forms
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/69#issuecomment-33528836
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Looks like we just introduced something bad in schema:

```
MySQL said:
#1052 - Column 'active' in where clause is ambiguous 
```

Undefined variable?

**Comment by JayUnt** [comment]
Damn. I knew I should have terrain the while she's gone again. I did it a
couple of times with no issue and then changed one small thing. And of
course it broke because I didn't test it again.

I'm assuming it's within the active tap view. The tap had an active
property, as does the beer table now. We will just have to specify that the
active we are conditioning on is for the tap.  The only problem is I don't
have my laptop home, so I can't make the change. I can look into it and
post the change for you to commit though.

**Comment by JayUnt** [comment]
Line 695

WHERE active = true

Should be

WHERE t.active = true

**Comment by thadius856** [comment]
Fixed

**Comment by Skemp45** [comment]
Did I miss a change? looks like our shadowing switched. Did we want this?
![shadowing](https://f.cloud.github.com/assets/6318869/2026607/39110842-8899-11e3-98f2-e5dda4c3c81c.png)

**Comment by Skemp45** [comment]
If not I will switch it back but just let me know

**Comment by JayUnt** [comment]
Yeah. I changed it from looping through the active taps, to showing
1-number of Taos. So now it will show a row for a tap that doesn't have an
active beer. You can make that Fox your the background shadowing.

**Comment by Skemp45** [comment]
ok cool. 

I also went through and updated the style for all the forms.

**Comment by Skemp45** [comment]
Thoughts on verbiage to clear things up/

After thinking about it Why are we naming the list of beers the beer recipes, its not really a recipe but rather a list of all beers. so Beer List, Beers, My Beers Etc might be more suiting 

thoughts?

**Comment by Boombrewer** [comment]
That definitely makes more sense to this 'non-computer guy'

Or was Thad thinking about the future and potentially being able to store your recipes in the database????  He's crafty like that.

**Comment by thadius856** [comment]
Because I'll probably incorporate BeerXML parsing, so you can import your BeerSmith or ProMash recipes directly in.

**Comment by thadius856** [comment]
Also plan to make a list of the top 100 beer recipes in the HBT database, as ranked by reply count.

**Comment by Boombrewer** [comment]
does no one else use iBrewMaster?  

Were you planning on being able to import the whole top 100?

I do like the idea of being able to pull in a whole recipe though.

**Comment by thadius856** [comment]
Don't think I've ever used a piece of software starting with 'i' that I enjoyed.

**Comment by Boombrewer** [comment]
i suppose i had that one coming.

**Comment by thadius856** [comment]
> Were you planning on being able to import the whole top 100?

Also, yes. Not by default, but included with the install files should they decide to.

**Comment by Skemp45** [comment]
I like the idea of importing but maybe we should have a seprate page for importing xml recipies and call that page beer list. I just feel like beer list is clearer to an end user

**Comment by thadius856** [comment]
Fair enough on the confusion, but I think they'll confuse that name too (with Thadius856 fromt end, haha). ;)

My Beers? List Beers? BEERS BEERS BEERS?

**Comment by Skemp45** [comment]
Beers and Beyond hahah

**Comment by Skemp45** [comment]
What about My Beers

**Comment by thadius856** [comment]
Beers and Body Works

**Comment by thadius856** [comment]
Sure man, whatever you like.

**Comment by JayUnt** [comment]
I was also thinking about the beer style.  We currently are giving the
users a textbox to set their beer style.  What about giving them a dropdown
instead for them to choose from?  We would need a list of beer styles to
import into a new beerStyles table.

On Wed, Jan 29, 2014 at 8:37 AM, thadius856 notifications@github.comwrote:

> Sure man, whatever you like.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/69#issuecomment-33584642
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Ok, but it'd have to be extensible by the user. We'd surely miss categories
or have different conceptions of what's a style and what isn't.

Vegetal?
Smoke?
Cascadian?
Gluten free?

See?

Would it be easier to provide BJCP Categories and leave the fill-in style
box?

**Comment by JayUnt** [comment]
I was just looking at to how BrewToad does it, and they just have a set list.  That way they can show the appropriate ranges for OG, FG, etc.  We could just have an Other, which would encompass all of those.  

And Gluten Free isn't really a style.  You would brew a Gluten Free IPA, but its really an IPA made without gluten.

We could maybe make it a set list now, but then in the next release give them a listing/edit/add section.

If you didn't realize yet, this would make some cool analytics if we were able to group all of the user's IPAs, ESBs, etc together.

**Comment by Skemp45** [comment]
I would be cool with doing a set list for first release as long as we give options for self entry in the next release!

**Comment by Skemp45** [comment]
1. LIGHT LAGER
2. PILSNER
3. EUROPEAN AMBER LAGER
4. DARK LAGER
5. BOCK
6. LIGHT HYBRID BEER
7. AMBER HYBRID BEER
8. ENGLISH PALE ALE
9. SCOTTISH AND IRISH ALE
10. AMERICAN ALE
11. ENGLISH BROWN ALE
12. PORTER
13. STOUT
14. INDIA PALE ALE (IPA)
15. GERMAN WHEAT AND RYE BEER
16. BELGIAN AND FRENCH ALE
17. SOUR ALE
18. BELGIAN STRONG ALE
19. STRONG ALE
20. FRUIT BEER
21. SPICE / HERB / VEGETABLE BEER
22. SMOKE-FLAVORED AND WOOD-AGED BEER
23. SPECIALTY BEER
24. TRADITIONAL MEAD
25. MELOMEL (FRUIT MEAD)
26. OTHER MEAD
27. STANDARD CIDER AND PERRY
28. SPECIALTY CIDER AND PERRY
29. OTHER

**Comment by JayUnt** [comment]
1. SODA
2. SELTZER

**Comment by Skemp45** [comment]
Feels good to know people are excited. Look at all these subscribers!!! Thad, you want to write a email blast I can sent to all of them? Something like just a heads up our Target date is coming up in 3 weeks. Something fun to give them a update/
![subs](https://f.cloud.github.com/assets/6318869/2030340/64b02440-88f5-11e3-8a54-17582d2d20ec.png)

**Comment by thadius856** [comment]
Sure thing man. Can you toss it here before you send it? Maybe a couple paragraphs like:

Salutation,

Para 1 - thanks for interest
Para 2 - here's where we're at with status
Page 3 - thanks for patience + release teaser

Closing

**Comment by thadius856** [comment]
Ill probably ask the mods to close our current HBT thread so I can make a new one tonight.

**Comment by Skemp45** [comment]
If you want to write it up im cool with that LOL

**Comment by thadius856** [comment]
Ok, I will. :)

Do I send it to any particular distro?

**Comment by Skemp45** [comment]
If you want to post it here I can send it out to all of them from the support@raspberrypints.com email address

**Comment by JayUnt** [comment]
What is the verdict of the beer styles as a table? Should I work on it?

**Comment by thadius856** [comment]
Sure, why not.

**Comment by JayUnt** [comment]
:thumbsup:

**Comment by thadius856** [comment]
Skemp, here's your message to send to the distro. Everything below the image.

http://www.homebrewtalk.com/f51/initial-release-raspberrypints-digital-taplist-solution-456809/#post5866685

Please post a subscriber # once your spam it out.

**Comment by Skemp45** [comment]
22 total recipients not including us 3

**Comment by Skemp45** [comment]
Sent it out YAYYYYY

**Comment by JayUnt** [comment]
:+1:

**Comment by JayUnt** [comment]
Hey @Skemp45, You probably should have put everyone in the bcc.  That way the whole list of emails is not visible to everyone else on the list.   Next time :)

**Comment by Skemp45** [comment]
Jay,
Hey your right my bad lol

**Comment by Skemp45** [comment]
This issue seems to be good to go now, Should we close?

**Comment by thadius856** [comment]
If somebody has tested successfully, and we've styled, please do.

**Comment by Skemp45** [comment]
Tested all links and functions of the taplist section and they work without issue. Closing issue

**Comment by Boombrewer** [comment]
Any idea why I would get 'cannot connect to server' with this in the address bar "http://localhost:8888/admin/includes/checklogin.php"

I have the latest set of files.  When I check the 'includes' folder, there is no checklogin.php so I understand what's happening but you guys don't seem to have that problem.... what did I do (or not doing)?
