### ISSUE TITLE
Options! Options Options!

### ISSUE THREAD

**Issue by thesehands** [RaspberryPints/RaspberryPints#7]
I was pondering as we get thing tied up and get a base for future enhancements what are everyone's ideas on add-ons.

Since I do not use flow meters I was thinking and option for qr codes instead so people have direct access to my beers on untappd. 

Figured I'd start a thread for this so we can discuss, just idea sharing that's all.

**Comment by JayUnt** [comment]
I like QR codes, even in conjunction with flow meters.  So you can track who gets the beer.  I would like it even in the end, to have to scan a qr code in order to get a beer.  That way when my daughters are older, they cant get the beer.

If you didn't use a flow meter, would you assume that 12 oz was poured each time? Or would you ask to estimate the pour size?

**Comment by thesehands** [comment]
From my perspective it was a change of rows, instead of poured/remaining I just have QT codes that channel back to untappd.

**Comment by thadius856** [comment]
I know what QR codes are, but not the context here.

What do QT codes have to do with unTapped?

Do you scan a barcode with your smartphone to post a brew to a Facebook-esque feed?

**Comment by thesehands** [comment]
The QR just holds a url the url points to my homebrewery on untappd so that way people can scan code off the monitor and check in when they try my beer.

**Comment by thadius856** [comment]
Oh, that sounds pretty easy. And cool.

So, like replace the clock with the QR code? Or place it next to the Brewery Logo or something?

Or do you need to generate a separate QR code for each beer?

**Comment by thesehands** [comment]
You could in theory tag it to the brewery but I have QR for each beer that I have loaded. You would have to hang generate them, but it doesn't take that long.

**Comment by thadius856** [comment]
Sounds really cool.

Lets hold off on implementing until we get merged back up. But once we're there, why the hell not? :)

**Comment by thadius856** [comment]
Aaaaaand we're merged back up.

**Comment by thadius856** [comment]
Added QR codes to the milestones for 3.0.0+. Closing.
