### ISSUE TITLE
Website: Complete the "Build Your Own" Section

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#71]
Just adding this for the thread. I'm sure we'll have a few questions for everyone as we work on this, so I thought it would be best to try and organize all the questions in one place.

**Comment by thadius856** [comment]
Wow. No idea how I missed this.

**Comment by mtnbound** [comment]
Couple of quick questions and thoughts. I downloaded and installed the new version, and I just wanted to run a couple of things past everyone to keep things simple for the users. It looks GREAT btw. I've been out of town for a week or so, and just got back to it and love the direction.

Questions:
Why is tomcat install? Is it needed somewhere I haven't seen yet?
Is vstftpd needed? I copied all the files and wrote the install docs using SCP, but is FTP needed somewhere else?
Do we need/want users to have to install phpMyAdmin? Unless it's needed for config, I'm not sure it's worth installing for users. It looks like everything is created using the schema, so I'm not sure if it's necessary.

Thoughts:
Any thought of just doing a drop down and table for the styles rather than free text? More flexibilty with the free text, but eliminates potential errors with a drop down.

Just some thoughts...

**Comment by thadius856** [comment]
Tomcat and vsftpd are installed because they're pretty standard fare on the Debian LAMP stack. But no, they don't have a use yet.

phpMyAdmin, yes. They need to create a user with an md5 hashed password. We could try command line direct to mySQL if you're confident the average user could execute the command.

**Comment by thadius856** [comment]
Only reason I'd consider adding a dropdown for style is for distributed stats. But we don't even have standard ol' stats up yet. :)

**Comment by mtnbound** [comment]
The schema adds an "admin", "admin" user by default, so they would only use it if they wanted to change the default admin username and password, or add another admin account. Not sure if you guys are thinking about a User management screen, or a "Change Password" screen.

On Monday, January 27, 2014 12:04 AM, thadius856 notifications@github.com wrote:

Tomcat and vsftpd are installed because they're pretty standard fare on the Debian LAMP stack. But no, they don't have a use yet.
phpMyAdmin, yes. They need to create a user with an md5 hashed password. We could try command line direct to mySQL if you're confident the average user could execute the command.

**Comment by Skemp45** [comment]
Deff will be making a user management section, we don't want everyone who uses this to know everyone's admin password

**Comment by thadius856** [comment]
admin//admin is inherently insecure, especially when place public-facing in the DMZ of a router, or when port forwarding of unsolicited port 80 is set to the Pi.

**Comment by mtnbound** [comment]
I completely agree. I just mentioned that since if you were going to do a "change password" or management screen, we could eliminate phpMyAdmin, unless we us it elsewhere. Could just have them login as admin and then change their password right after logging in.

On Monday, January 27, 2014 12:27 AM, thadius856 notifications@github.com wrote:

admin//admin is inherently insecure, especially when place public-facing in the DMZ of a router, or when port forwarding of unsolicited port 80 is set to the Pi.

**Comment by JayUnt** [comment]
I agree with not having the user add their own user right into the db.  Even having them run schema is not really even ideal.  What we should do is what WordPress does. When you download the side and upload it to your server, there is an install folder.  

The user goes there and shows a form that asks for your database connection information.  That get saved and saved to the connection file.  Before we ask, we could check the file to see if already is there, in which case we could assume this is an update not a new install.  

The next step sees if the raspberrypints database exists and if the tables exist inside it. If not, we run schema for them.  If it does, we can check the config for the current version # and then run the appropriate update scripts to get them to the most recent version.

The next step checks to see if there are any users.  if not we allow them to give a username/password for their initial user.  We add it and then shoot them over to the admin login page.

It is a lot more work for us, but it will make it cleaner for the user.  Maybe we want to push this off to another release, but I would like it to be clean for the user.

**Comment by Skemp45** [comment]
#72

**Comment by Boombrewer** [comment]
Since I'm just sitting here waiting for Raspbian to install...  I've noticed a couple things that could be a little clearer in the BYO write-up.  Please don't judge the village idiot.

Hardware Assembly page:
- connect USB keyboard (if you chose the recommended, make sure you connect the wifi received not the USB cable)  **AND DO NOT disconnect the keyboard during the OS install
- connect WiFi adapter (i.e. the Edimax or your equivalent)

Minor stuff but stuff that might help another idiot (or someone else multiple beers deep).  : )

**Comment by thadius856** [comment]
> Since I'm just sitting here waiting for Raspbian to install... I've noticed a couple things that could be a little clearer in the BYO write-up. Please don't judge the village idiot.

Sloe (mtn), you catch this post?

**Comment by mtnbound** [comment]
Yes, I'll take a look at that tonight or tomorrow. 

It might be worth getting a few beta testers from the people that have subscribed.

What seems clear to us might be really confusing for newcomers.

**Comment by EmDubeu** [comment]
Sign me up to beta test. I'm on the subscriber list. I have a background in
software quality assurance and software product management.  I also drink
the beer I brew! Cheers.

Mike

**Comment by Boombrewer** [comment]
I'm still working through the install / setup process....  Don't worry, I'm taking notes.

**Comment by thadius856** [comment]
QA. _scowl_

Jk.

**Comment by Boombrewer** [comment]
Ok.  I'm to the point of actually setting up the page on the RPi.  I have all the most recent files copied over but I'm guessing this is where the writeup is considerably behind the recent modifications.  Any help?  I was trying to setup users but I don't think the steps were working right.

**Comment by mtnbound** [comment]
Wow, you guys move fast. One mention of Beta testers, and it looks like 2 started! That's great.

Yes, quite a bit has changed after the "copy the code" part. I'm going to make the updates probably today, so any comments before and including the "copy your code" section would be great.

**Comment by thadius856** [comment]
Ok, so.

Copy files to /var/www
Import schema.sql
Import test_data.sql (optional)
If imported test_data.sql, edit admin//admin login.
If not imported test_data.sql, insert a user with MD5 pw into table users.

Customize in admin panel as desired. Suggest you have them add their first beer, keg and tap, then put a beer on tap.

**Comment by thadius856** [comment]
Dont forget to edit the 3 config files, and make/create MySQL user accts.

**Comment by raysmithtx** [comment]
I'll be glad to be a beta tester. Put me in coach.

**Comment by mtnbound** [comment]
Thad - That's all built into the installation scripts now, so I'm going to edit the "build your own" section to reflect that now.

The user shouldn't have to worry about any of the back end stuff now once they run the install.

**Comment by thadius856** [comment]
K. Hadn't tests its functionality, so didnt want to speak to something I was unfamiliar with.

You guys are far too active for 5:39 am btw :P

**Comment by mtnbound** [comment]
I started a new section on the site called "Documentation". I thought that the "Build your own" is different than the day to day use and administration.

I didn't put anything behind it yet, just started with the page to see if that made sense to do it that way.

**Comment by thadius856** [comment]
I figured we should be building a product where the day-to-day interface is intuitive enough to not require a Documentation section. Anything we want to expound upon, seemed like would work in the FAQ.

Anybody else have input?

**Comment by Boombrewer** [comment]
I agree.  Everything so far is pretty straight forward.  You should need anything other than install / setup instructions and some FAQ's so cover the outliers.

**Comment by raysmithtx** [comment]
I put info that I 'think" users may want to know in the widgets at the bottom of the homepage. If you want them deleted, just let know.

**Comment by mtnbound** [comment]
I went through this section in detail yesterday after wiping my Pi and starting from scratch.

I made some small edits, and some larger ones near the end of the website, but I think it's pretty straightforward now to install.

I also uploaded the latest Install screens this morning, so it should probably be worth a test or two before releasing it to some beta testers, but I know that Boom and ray have volunteered for at least an Alpha test. Just remember, I started it on Tuesday never using PHP before, so be gentile :)

Also, I'm a back end and middle tier developer, so I SUCK at design, and didn't even try. If anyone wants to pretty up the index.php page let me know. I'm more than happy for some ideas.

I need to change some permissions before releasing it, since I'm using 777 for a few steps that can probably be reduced, but it's a start. I also probably need some better error handling and checking, but It's probably good for a test or two.

**Comment by thadius856** [comment]
I'll create a pull request for you. Please review carefully.

I notice some changes on index.php. Did you intend to remove these
sections? Or is it a version mis-match we need to correct?

**Comment by mtnbound** [comment]
I made some changes to the /admin/index.php page, but not the main one. Other than the sql schema, I didn't change anything outside of the /admin folder.

Also, the config files will need to be removed from the master branch for the install scripts to know it's a new installation. The one in the /include folder and the 2 in the /admin/include folder.

**Comment by thadius856** [comment]
Pull request created, then merged back into master.

Now you're saying you want me to delete some files from the repository?

**Comment by mtnbound** [comment]
No, everything looks right based on the request it just sent me.

**Comment by mtnbound** [comment]
Yes, the config files do need to be deleted. I didn't do it since I didn't want to mess with code outside of the /install folder.

**Comment by thadius856** [comment]
It wouldn't have messed with anything.

Which files, specifically?

**Comment by mtnbound** [comment]
/includes/config.php
/admin/includes/configp.php
/admin/includes/conn.php

All 3 get created with the install page, so they shouldn't be part of the release.

**Comment by thadius856** [comment]
Whew. Those are big items to delete. Will delete, test, and commit if it works.

**Comment by Boombrewer** [comment]
Setting up the static wifi:

Mine looks like this:
![image](https://f.cloud.github.com/assets/6321429/2061042/8effb2d2-8c3e-11e3-83a2-ff67b37889b3.jpg)

Do I replace all? Perhaps a before and after pic in this section would be better.

**Comment by thadius856** [comment]
If you were using the ethernet port, you'd change `iface eth0 inet dhcp` to `iface eth0 inet static`. For WiFi, you do the same, but change the `wlan0` line instead. Then you'd add the details:

```
address 192.168.100.1
netmask 255.255.255.0
network 192.168.100.0
broadcast 192.168.100.255
gateway 192.168.100.254
```

`Address` is the IP you want to assign.
`netmask` is the desires subnet mask (leave default if that doesn't make sense to you).
`network` is the netmask applied to the address (if you kept the netmask default, the first 3 groups should match the `address`, and the 4th group should be `0`).
`broadcast` is where it'll broadcast its presence (leave default if that doesn't make sense to you).
`gateway` is the address of your router.

**Comment by thadius856** [comment]
The complexity here is why I recommended applying the IP in your router using Static DHCP.

It's much, much easier, IMO.

**Comment by thadius856** [comment]
Does this make sense? Do you need more help? Just let me know.

**Comment by Boombrewer** [comment]
Yeah, static ip via the router was much easier to setup.  This mostly makes sense.

If I have the static ip still set up on the router, do I even need to do this step or can I skip it?
If I can, I think it should be listed as an option in the BYO instructions

**Comment by thadius856** [comment]
Adding the MAC of the Wi-Fi card to the router's Static DHCP table means that any time that card requests an IP, your router will always issue it that IP. Raspbian is set to DHCP by default, so you can safely skip editing that file.

The beauty of Static DHCP is that if you pull that Wi-Fi adapter and place it in a different Pi, it takes the IP with it. On the same token, if you nuke Raspbian and re-install, it still retains the IP as well.

The only time you should need to edit that file is when the user has no admin access to their router AND their router allows the device to pick its own IP. This is a pretty rare scenario with Wi-Fi.

**Comment by Boombrewer** [comment]
But when I leave that file alone and ping google, I still get unknown host.  So something isn't right and it's not connecting.  I'll start the GUI and see if I can figure it out from that side.

**Comment by thadius856** [comment]
Use the desktop shortcut to configure the Wi-Fi the first time.

I'm assuming you haven't told it which network to connect to, your WPA pass key, etc. Your results are to be expected.

**Comment by Boombrewer** [comment]
```
 Use the desktop shortcut to configure the Wi-Fi the first time.
```

I did use the GUI to configure.

Well, right now even the GUI is just showing status: Scanning and WPS-AP-AVAILABLE.  So I have other issues.  When I scan the network shows up fine but for some reason it won't connect.

On another note, the BYO instructions imply changing wlan0 to your network name after setting up the wifi via the GUI.  Is that required?

**Comment by Boombrewer** [comment]
Haha.. I'm an idiot.  Wrong encryption selected.  Maybe I should put down the bloody mary, have the wife stir the wort, and work on just one thing.

**Comment by thadius856** [comment]
Negative. You shouldn't need to update `/etc/network/interfaces` at all.

Notice it calls on `wpa-conf`, which is written by `wpa_supplicant` (the back end of the GUI you're using).

Hence, when you set up a network using the GUI, it writes your details to `/etc/wpa_supplicant/wpa_supplicant.conf` for you. Mine looks like:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
        ssid="Thadius"
        psk="youdidntreallythinkidpostmypskdidyou"
        proto=RSN
        key_mgmt=WPA-PSK
        pairwise=CCMP
        auth_alg=OPEN
}








                               [ Read 11 lines ]
^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Page ^K Cut Text  ^C Cur Pos
^X Exit      ^J Justify   ^W Where Is  ^V Next Page ^U UnCut Text^T To Spell
```

**Comment by thadius856** [comment]
Ahhh. Good to hear. :)

If you made the mistake, others will too. That'd be a good NB to have in the install instructions. _nudge nudge_

Who's writing those, again?

**Comment by Boombrewer** [comment]
Ok.  So it all works pretty well except the wifi set up.  I'd definitely recommend Thad's suggestion of doing the static IP via the router.

The only other note is that once install is complete, what are the steps to actually display the tap list on the Pi?

**Comment by thadius856** [comment]
As in, after you install the package into /var/www? That one's pretty easy (assuming you already have Chromium installed)

`sudo nano /home/pi/.bashrc`

Add `chromium-browser --kiosk localhost`

`sudo reboot`

**Comment by thadius856** [comment]
I'm assuming you're already run the install script by this point.

**Comment by Boombrewer** [comment]
Well, along those lines we can assume chromium is not installed because we didn't tell "Joe" to install it.  So I think we should add the Chromium install to the BYO.

**Comment by thadius856** [comment]
Yup. Who's writing the BYO?

Boom, I knew you were a tester.
Ray, I think you're site layout.
But who's BYO? Sloe?

**Comment by Skemp45** [comment]
I added target="_blank" to all the amazon links on the hardware page so they open in new pages. having to reload back to site is annoying and this will make shopping easier.

**Comment by thadius856** [comment]
Woops. Thanks. Totally forgot to test that.

I middle-click out of force of habit.

**Comment by raysmithtx** [comment]
My hardware order should be here on Wednesday so I can begin testing. Should I just use the BYO section on the website to run my first 'beta/alpha' test or do I need to download files from somewhere else?

**Comment by thadius856** [comment]
Click `Download Zip` on the main page here.

The instructions will have you download a couple other things along the way. Just follow along and take good notes.

**Comment by EmDubeu** [comment]
Dumb question, but where are the installation instructions?

On Mon, Feb 3, 2014 at 5:22 PM, thadius856 notifications@github.com wrote:

> Click Download Zip on the main page here.
> 
> The instructions will have you download a couple other things along the
> way. Just follow along and take good notes.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34021513
> .

## 

Mike Wright

**Comment by thadius856** [comment]
On our official website. They're hidden unless you're logged in and Skemp has added you as a user on the project.

**Comment by EmDubeu** [comment]
What do you say, Skemp? I have my hardware, zip files from Github, and I'm
ready to test.

On Mon, Feb 3, 2014 at 5:56 PM, thadius856 notifications@github.com wrote:

> On our official website. They're hidden unless you're logged in and Skemp
> has added you as a user on the project.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34023384
> .

## 

Mike Wright

**Comment by thadius856** [comment]
While you're waiting for a reply, I suggest you start by downloading NOOBS. Google around, you'll find it.

**Comment by EmDubeu** [comment]
i forgot to say, please. Please.

On Mon, Feb 3, 2014 at 5:58 PM, Mike Wright emdubeu@gmail.com wrote:

> What do you say, Skemp? I have my hardware, zip files from Github, and I'm
> ready to test.
> 
> On Mon, Feb 3, 2014 at 5:56 PM, thadius856 notifications@github.comwrote:
> 
> > On our official website. They're hidden unless you're logged in and Skemp
> > has added you as a user on the project.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34023384
> > .
> 
> ## 
> 
> Mike Wright

## 

Mike Wright

**Comment by EmDubeu** [comment]
Done. It's already running on my Pi and the pi connected to my flat screen.

On Mon, Feb 3, 2014 at 6:00 PM, thadius856 notifications@github.com wrote:

> While you're waiting for a reply, I suggest you start by downloading
> NOOBS. Google around, you'll find it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34023559
> .

## 

Mike Wright

**Comment by thadius856** [comment]
He's probably busy. What's your WP username?

**Comment by thadius856** [comment]
Ray, I changed the website background back from the beer glass. I have a 30" monitor in front of me with amazing color. That said, when I view our site on it, 60% of the screen is background. That's a whole lot of yellow burning holes in my retinas.

I'm not against the idea of beer as a background. Just perhaps a little muted. The one you had up was very "loud". Perhaps we can dim it down a bit? Or make it semi-transparent? Or...?

**Comment by EmDubeu** [comment]
Wekim

**Comment by raysmithtx** [comment]
I didn't like the bright background either just left it there as a placeholder of sorts. Once the RP system is done, I'm hoping to grab a nice image from there and use that as a background. Based on what I've seen so far, that will provide a nice dark background.

**Comment by thadius856** [comment]
The bg image from RPints? Thats what I have up now.

**Comment by raysmithtx** [comment]
I'm hoping to get a screenshot with more variation than just the black background. I will be looking for a good image as I go through the installation process starting tomorrow.

**Comment by Boombrewer** [comment]
@thadius856 

> As in, after you install the package into /var/www? That one's pretty easy (assuming you already have Chromium installed)
> 
> sudo nano /home/pi/.bashrc
> 
> Add chromium-browser --kiosk localhost
> 
> sudo reboot

So I installed Chromium per RPi and did the above but when I rebooted I got the following line:
(Chromium:2935): Gtk-WARNING **: cannot open display:

I goggled it but didn't understand the fix. I originally had the .bashrc add all the way at the bottom and now moved it up to just below the first comments. That's the extent of my troubleshooting capabilities.

**Comment by thadius856** [comment]
Can you sterilize your .Bashir file and post the contents here?
Troubleshooting on my phone from the gym is difficult.

**Comment by Boombrewer** [comment]
I'll try later tonight when I get home from work. 

Troubleshooting, phone, gym .... You crazy man.

**Comment by thadius856** [comment]
Sorry, I steered you totally off course. Undo your changes to `/home/pi/bash.rc`. Try this instead:

`sudo nano /etc/re.local`

Insert this just before `exit 0`:

`su -l root -c 'xinit chromium-browser --kiosk http://127.0.0.1`

Alternatively, you can replace `http://127.0.0.1` with `localhost`, but I haven't tested for ill side-effects.

**Comment by jkurl** [comment]
thad,

  I have a word doc almost ready to go with what i found during the install.  i need to recharge my keyboard and will perform the kiosk edit since this was one of my questions about how are they going to display the tap list from the cmd line. 

Jerry

**Comment by thadius856** [comment]
Jerry, the Pi will boot to Raspbian by default if they follow the NOOBS installation instructions.

The Kiosk edit above just opens Chromium in full-screen mode on boot. :)

Please post the contents of your findings here once you're done.

**Comment by jkurl** [comment]
Thad never mind about getting chromium into kiosk mode. i got it working by editing the LXDE autostart session.

**Comment by jkurl** [comment]
Here is what I found when I went through the install. this is the second time I have done the install. the first time I already had Raspbian installed on the SD card.  I used the GUI the first time to setup the entire install and configuration.  The second time I did it all from the cmd line outside of the GUI except for putting chromium in kiosk mode. 

Operating System Installation:
1.  When picking Raspbian at the bottom of the screen the install allows you to pick US as language and once you us as language it will change the Keyboard to US as well

Operating System Configuration:
1.  After reboot from changing display settings they will need to login back into the pi.  User: pi and whatever they changed their password to.
2.  If language and keyboard are set at the OS selection screen, changing the keyboard locale will not need to be done. It can be checked incase it didn’t take during the install.  Having them check the keyboard config wouldn’t hurt but this step could possibly be eliminated
3.  When selecting logging out of the GUI you can use the power button on the left side of the screen. This maybe easier for them to see and it is something they are used to seeing as a standard symbol for logging out in a GUI.  I would just have them do everything in the GUI.
4.  Network interface edit looks different than what you have on the doc. Do you have to add the lines in for the ip, subnet and gateway once you change it to static ip? (Already addressed in Github issue #71 but not clarified on instructions)

Package Installation:
1.  This section was pretty straightforward. No issues or confusion should happen during this install. 
2.  If chromium is going to be used or other browsers that need to be installed this would be a perfect time to add the cmd line code to install them since ttf –mscorefonts are being installed.

Package Configuration:
1.  When doing the chmod of the /var/www folder it looks like it does nothing and goes right back to the cmd prompt. Might want to put a note in that if you get anything else you did something wrong such as a typo.

RPints Installation:
1.  This is for windows only.   People that use a mac or Linux most likely know how to SFTP into a pi or another machine, but for those that don’t instructions should be included. FileZilla is a free easy to use program for mac. I can do a quick write up to provide instructions for people using macs. I don’t have access to a Linux computer not counting the pi.
    

RPints Configuration:
1.  When you get the install is a success and it provides the links to tap list and admin page, a not should be written to remind them to save the links in their favorites as they can be edited at anytime if something was to change.  This will provide them quick access to the each portion without having to remember link and type it in.

Documentation:
1.  Is this where the instructions on how to setup the tap list is going to go or is that not planned and have them load the test data to see how the system is setup?
2.  Once the pi and tap list is all set are they going to hook their monitor into the pi and go into the GUI to use the web browser to display the tap list all the time or will they access it from the cmd line interface? (Already addressed in Github issue #71 but not added in the instructions anywhere)

**Comment by thadius856** [comment]
> When selecting logging out of the GUI you can use the power button on the left side of the screen. This maybe easier for them to see and it is something they are used to seeing as a standard symbol for logging out in a GUI. I would just have them do everything in the GUI.

I really agree with this one. @mtnbound, any particular reason you're having the user dump out of the GUI to edit `/etc/network/interfaces` when LX Terminal is right there?

**Comment by thadius856** [comment]
Jerry, my take on your stuff above...

OS Install
1. Good catch. I'll add this.   Update: Done.

OS Config:
1. Shouldn't NOOBS have added the l/p to `/etc/passwd/` and `/etc/shadow/` already?
2. True, but couldn't hurt to do. Takes only seconds. :)
3. Addressed above.
4. Yep, I noticed this too. Just fixed it on the site before I read your message.

Package Install:
1. Cool!
2. Oops. Did we forget Chromium here? :o

Package Config:
1. Ah, yes. Good idear. I think I'll put this tidbit much earlier, like on the first time they use LX Terminal. I'd do -v, but it spams on a folder this large.

RPints Installation:
1. I'll take a look and fix as necessary.

RPint Config:
1. Good idear.

Docs:
1. Don't know why it's there, honestly. Test data and tap setup should go in Customization or something.
2. My vision is that once users setup this thing, they shouldn't need to use a terminal unless they're upgrading between versions or instructed to do so by us. But yeah, I'll look into it.

**Comment by jkurl** [comment]
i am in the process now of just adding some random beers and trying to test
thing like boom is doing.

**Comment by jkurl** [comment]
Thad,

   In the kiosk mode the screensaver keeps coming on. here is what i edited

sudo nano /etc/xdg/lxsession/LXDE/autostart

#@xscreensaver -no-splash

then added this

@xset s off

@xset -dpms

@xset s noblank

saved, rebooted then added

@chromium --kiosk --incognito http://192.168.1.106/index.php

what do I need to do to keep the screensaver from coming on? well the
screen just goes blank

Jerry

**Comment by thadius856** [comment]
Hrm. Odd. I think I may have missed a few steps in the instructions.

So it works now for you?

If you don't have these packages, you should install them with `apt-get`:

`dpkg --get-selections | grep x11-xserver-utils`
`dpkg --get-selections | grep unclutter`

**Comment by jkurl** [comment]
I am gonna try something first I think I have it now. if this doesn't fix
it i will install the dependancies above

**Comment by thadius856** [comment]
Ok. You probably want `unclutter` anyway, as it hides the mouse after 5
seconds of inactivity.

**Comment by jkurl** [comment]
Sounds good. Will put that here soon.

**Comment by jkurl** [comment]
just installed them as the last test did not work. testing again after a
reboot

**Comment by jkurl** [comment]
Thad,

   Thanks for the fix with installing those packages. that fixed my
problem. no screensaver, blank screen or mouse pointer.

Jerry

**Comment by Boombrewer** [comment]
I'm getting a URL not found error trying to get to phpMyAdmin.  What did I miss on the install?

**Comment by thadius856** [comment]
Hrrmmrmrmrmrm... run:

`dpkg --get-selection | grep php`

Lets see the output.

**Comment by thadius856** [comment]
If you don't see phpmyadmin towards the bottom of the short list:

`sudo apt-get install phpmyadmin`

**Comment by Boombrewer** [comment]
yeah, somehow I guess I missed the install on that one.  Weird.  Thanks though.

**Comment by Boombrewer** [comment]
Well, spoke too soon.  Still getting the 404.  I even 'removed' and installed it again.  Still no go via my laptop or directly on the pi.

It is just:  MY_URL/phpmyadmin   ???  or on the pi:  localhost/phpmyadmin  ???  Google better not have lied to me!

**Comment by thadius856** [comment]
It didn't lie.

URLs are case sensitive.

/phpMyAdmin :)

**Comment by EmDubeu** [comment]
Boom, you need to use /phpMyAdmin. URLs be case sensitive.

On Sun, Feb 9, 2014 at 11:14 PM, Boombrewer notifications@github.comwrote:

> Well, spoke too soon. Still getting the 404. I even 'removed' and
> installed it again. Still no go via my laptop or directly on the pi.
> 
> It is just: MY_URL/phpmyadmin ??? or on the pi: localhost/phpmyadmin ???
> Google better not have lied to me!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34605477
> .

## 

Mike Wright

**Comment by Boombrewer** [comment]
I did use localhost/phpMyAdmin (I was just being lazy on here I guess).  Still got the 404.

**Comment by EmDubeu** [comment]
You may need to run an install of phpmyadmin. The install instructions for
LAMP left off the phpmyadmin command.

**Comment by Boombrewer** [comment]
Already did.  And removed it.  And re-installed it.  And when configuring, I chose Apache as the server.  But when I removed and re-installed, it didn't give me the option on the second go'round.  I'm toast for tonight.  I'll work at it again tomorrow.  Its not the end of the world - I've been managing just fine without it for this long.  Thanks for the help guys.

**Comment by EmDubeu** [comment]
You'll also need to reboot the pi after the sudo apt-get install phpmyadmin
command.

**Comment by EmDubeu** [comment]
Also,  when you run sudo apt-get install phpmyadmin make sure you choose
mysql as your db.
On Feb 9, 2014 11:41 PM, emdubeu@gmail.com wrote:

You'll also need to reboot the pi after the sudo apt-get install phpmyadmin
command.
On Feb 9, 2014 11:39 PM, "Mike Wright" emdubeu@gmail.com wrote:

You may need to run an install of phpmyadmin. The install instructions for
LAMP left off the phpmyadmin command.

**Comment by Boombrewer** [comment]
Finally figured it out.  Just had to add the Include in the apache.conf.  Its all good now.  Thanks.

**Comment by jkurl** [comment]
I had the same issue with entering in localhost/phpMyAdmin last but I was
able to use http://192.168.1.106/phpmyadmin to get in. Will look to edit
mine today

**Comment by Boombrewer** [comment]
@thadius856 - I think these are pretty good at this point.  Should we consider the BYO section complete and just do tweaks from here on out?

**Comment by thadius856** [comment]
I'm thinking we might want to add `-y` after `sudo apt-get install` each time we use it.

It auto-answers yes each time you're queried if you want to use extra disk space.

**Comment by EmDubeu** [comment]
-y, I agree.  That's an annoying prompt.  Let's do away with annoying
prompts. Reply with a yes if you agree. ..

**Comment by jkurl** [comment]
Yes plus it will save sometime for everyone.

**Comment by Boombrewer** [comment]
x2 on the yes and the -y

**Comment by Skemp45** [comment]
Meh... I don't like 777 it's lucky in Vegas but shouts come get me on the inter webs

**Comment by jkurl** [comment]
Guys I am gonna wipe my entire install tomorrow and go through the install
instructions once more to see if we need to fine tune anything, add it
delete. The better and easier the install instructions are the less
headaches you guys will have. The natives are already getting restless and
started downloading the master.zip from the github and trying to install
it. Please let me
Know if there is one area you would like me to focus on.

**Comment by EmDubeu** [comment]
I just changed my admin and includes folder to 705 and tested the brewery
logos. Looks like 705 works.

On Mon, Feb 10, 2014 at 8:13 PM, Skemp45 notifications@github.com wrote:

> Meh... I don't like 777 it's lucky in Vegas but shouts come get me on the
> inter webs
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/71#issuecomment-34725118
> .

## 

Mike Wright

**Comment by thadius856** [comment]
Is 705 any better?

Lets break it down.

The account Pi still has the same privs.

Users in the group Pi... don't matter, because there are none.

Everybody else gets read/write. So they can't execute... so what? We don't have any scripts or binaries, do we?

**Comment by jkurl** [comment]
hey guys I noticed this is still part of the install instructions.

Select the first option 'Raspbian' and click 'Install'.

Once the install has completed, Raspbian will automatically boot to the desktop. That's all there is to it!

I think we want them to pick boot to scratch.  if you select Raspbian that will take them to the raspi-config and not the GUI. plus rootfs is automatically expanded w/ the NOOB install. 

so do we want them to boot right into scratch or boot into raspi-config?

**Comment by thadius856** [comment]
I had planned for raspi-config. Because I did, I deleted all the sections on setting locales, timezones, etc etc.

Why scratch? I personally loathe it.

**Comment by jkurl** [comment]
ok nevermind about scratch. I was thinking scratch was the GUI.  i borked that one. lesson learned on that one.

**Comment by jkurl** [comment]
ok guys here is a few suggestions for the install instructions. rough night for me tonight going through these. screwed several things up missed stuff in the install instructions. basically got cocky and it bit me in the ass. lesson learned now enough bashing myself here is the suggestions.
1.  If they do forget to set their language and keyboard to US they can do it from the raspi-config page
2.  for locale you must hit space bar on US local to select and then tab to select ok and then on the next screen select US and then OK
3.  recommend moving chmod 777 /var/www ahead of the transfer of files.
4.  @chromium --kiosk --incognito http://192.168.1.xxx/index.php worked for me to get my pi into kiosk mode. 

the last issue could be something I did or was not doing but this worked for me to get into kiosk mode so i went with it. @xset chromium --kiosk localhost just would not work. i think i even replaced localhost w/  http://192.168.1.xxx/index.php and still a no go so like i said it could be me.

**Comment by Boombrewer** [comment]
I was hoping to have time to do the same thing but I'm just running out.  We're headed out of town tomorrow and I'm already way behind on the important stuff like packing.

My .02:
1. Good note but recommend linking it to a FAQ.
2. I think the file transfer has to be first (I'm pretty sure that's what I was messing up on my second install)
3. If this is going to be in the install instructions, we need to explain it as an option and leave it up to the user.  for instance:
   If you'd like you RPi to boot directly to RPints, do this...
   If you'd like to start RPints manually after boot, this is how...

I used the @xset chromium and it worked fine.  But I might have done something else first.  I think there was a couple other install items that were needed to make that work - not sure though.

**Comment by raysmithtx** [comment]
As a new RPI user it took me 2 days to figure out the "Operating System Configuration" page on the website should say "display_rotate" and not "rotate_display". Now if I can only figure out why I can't get WIFI. Still working through the BYO section.

**Comment by jkurl** [comment]
I had issues with my wifi at first what I had to do was change it from ccmp
to tkip for security. For some reason on ccmp it would loop over and over
again trying to connect. I also changedybrouter to accept ccmp + tkip.
Haven't had a problem since.

**Comment by jkurl** [comment]
Hey guys do you think we should meet up on Wednesday night some time online to discuss the launch day and go over support for the launch.

**Comment by Skemp45** [comment]
Yeah chatting about it will be good. its Arizona beer week through so I have a ton going on this week,

**Comment by Skemp45** [comment]
also, is this issue all done and fixeD?

**Comment by jkurl** [comment]
I think so not much if anything needed to be changed instruction wise. Just
the links you mentioned

**Comment by Skemp45** [comment]
SCHWEET. we are getting so close 1 day and 9 hours, so I am trying to get all the needs to be done pre v1 finished up here

**Comment by Skemp45** [comment]
Actually, what was talked about in #137 needs to be added yet, can someone please do that. we need to link to how to enable mb_strlen() and php short tags, or we can just tell them how to do it. All they need to do is add the following lines in their php.ini

```
extension=php_mbstring.dll
short_open_tag = on
```

and then reboot^

***_please let me know when this is done.**_*

**Comment by thadius856** [comment]
Added. Closing as completed.
