### ISSUE TITLE
V1 Release 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#74]
Should I host the .zip of all the files so users can download them directly from the website or do you want to leave it hosted on github?

**Comment by Skemp45** [comment]
The problem with hosting it on github is it can be changed and not all users would be getting the same files. the download file link goes to https://github.com/RaspberryPints/RaspberryPints/archive/master.zip which is changing as we develop so users might download it in between releases while we are working on v2

**Comment by JayUnt** [comment]
Thad and i talk about this last night.  Github allows you to create releases, which are like snapshots of the code at a given time.  So whenever we do a release, we create one of these and its saved. Then we can continue on with our development for the next release.

https://help.github.com/articles/about-releases

**Comment by thadius856** [comment]
Yep. We just set the most recent stable release and away it goes. :)

**Comment by Skemp45** [comment]
Problem solved then, thats what we will do. Save me bandwidth!

**Comment by Skemp45** [comment]
We will use Github to host release versions

**Comment by thadius856** [comment]
Yup!

**Comment by JayUnt** [comment]
Does anyone know of a way to download a release and re-commit to that specific release?  The reason i ask is if we make a release and then start working on new code, but then we get a major bug for that release.  We will want to fix it on that release and re-release just that bug fix.

**Comment by thadius856** [comment]
Haven't fiddled yet, sorry.

**Comment by Skemp45** [comment]
Me either I will try to look into it

**Comment by kerber** [comment]
At this point we're getting into release workflows. The image at this link (https://community.kde.org/index.php?title=File:Kde-git-workflow.svg&page=1) shows a sample of how you handle feature additions, releases, tags, etc.

The important part here is the 'release branch'. We'll branch off the codebase that we want to release, then do testing and bugfixes. Any fixes will be made to the branch and merged back to master. That way, we can do all feature development away from our more stable release code.

There are definitely more complex workflows we could adopt, but this is simple and handles most cases.
