### ISSUE TITLE
untappd Brewery feed

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#75]
I've gotten code working that uses the untappd API to pull the 5 most recent checkins to a brewery and displays the user and what they were drinking. 

I'm going to clean up the code and create a way to install it as a "plugin" so that it updates the base sql schema for the configuration and it incorporates the "css style" of the main base.

When you create the admin panel, are the fields for settings hard coded or are they generated based on the fields in the database?

You can see it in action at the bottom of the page on:
http://rp.skypainterbrewing.com

You do have to have your homebrewery established as a brewery with untappd and then you have to request access to the API to obtain a secret and id.

**Comment by Skemp45** [comment]
```
When you create the admin panel, are the fields for settings hard coded or are they generated based on the fields in the database?
```

Which settings? 
like the beers on tap etc.? if so those pull from the database

**Comment by mcangeli** [comment]
The config settings.

If I wanted to add three fields to the configuration page somewhere so that the user is able to add their client secret, client id and brewery id

Would that be handled simply by the database or would I have to edit one of the configuration pages

**Comment by Skemp45** [comment]
You would want that to be handled through the database. 
I assume like most API's they give you the client secret, client id and brewery id
so we could have a Untappd settings page where it has
Client Secret:
Client ID:
Brewery ID:
[Save]   [Cancel]

and this form would submit to the database where these value would be stored

**Comment by mcangeli** [comment]
Yes, thats how it works. Once you setup your brewery you have the brewery id.

Then you apply for the api keys (and two weeks later you get them).

Need an easy way to update that information in the database so that the script can pull the settings.

**Comment by Skemp45** [comment]
Yeah in the config table we could prolly add 
these values. 
and have the form just echo these into inputs. 

@JayUnt @thadius856 
you think it would be a problem in the next release to incorporate this?

**Comment by JayUnt** [comment]
Works for me.  We will just have to figure out the best place to show the feed. Whether its at the bottom, or maybe make a side bar.  If it stays ate the bottom, it might get pushed off the screen.  We could also set up an ajax polling to auto-update the feed every X minutes.

Adding the config items to the db is as simple as inserts, and then we will need to update the admin config to allow it to be easily editable.

**Comment by Skemp45** [comment]
What about if we used ajax to like every 5 minutes pop up like a ad on a website and it has an update on whos drinking what?

**Comment by mcangeli** [comment]
I would just leave it at the bottom. I was planning on adding a meta refresh to the index.php page so that it refreshes every 5 minutes anyways to get updated keg qty.

**Comment by JayUnt** [comment]
What happens if you have 10 taps and they just fit on the screen.  i think we could afford some shrinking of the name/notes column, to get a small column on the right.  kinda look like facebook's updates/whos online right column.

i don't think the popup will work because it seems like most people aren't going to have a mouse/keyboard always hooked up to the pi. so if its a popup and they want to see whats on tap, it might get annoying.

**Comment by Skemp45** [comment]
Well, once launch day has come and passed lets play with some layouts and include this in v2

Sound good to you guys?

**Comment by JayUnt** [comment]
Sounds good

**Comment by thadius856** [comment]
v2, definitely.

**Comment by thadius856** [comment]
> What happens if you have 10 taps and they just fit on the screen. i think we could afford some shrinking of the name/notes column, to get a small column on the right. kinda look like facebook's updates/whos online right column.

Perhaps in v2.0.0, we should be thinking about giving the users the ability to define their own row height. They could enable as many taps and features as they like, then tweak to fit how they want it.

**Comment by mcangeli** [comment]
The admin section to add the ClientID, Secret and Brewery ID for the brewery feed has been done.

Need to add a field to the beers list/form called untID that is the beer ID from untappd.

**Comment by Skemp45** [comment]
screen shot?? I would love to see how this feature is turning out

**Comment by mcangeli** [comment]
http://rp.skypainterbrewing.com

username: mcangeli
password: Apples

**Comment by Skemp45** [comment]
Looks great, Make sure you go into your config table in your database and set their showOnPanel to 0 so these dont show up. 
![untapped](https://f.cloud.github.com/assets/6318869/2218886/c3a792f0-9a37-11e3-954c-bbf67f0155d6.png)

**Comment by mcangeli** [comment]
Yea, I had had those set to 1 to see what they did... ;)

**Comment by Skemp45** [comment]
:dancer:

**Comment by mcangeli** [comment]
Ok, I think the brewery feed and the rating are done for the most part. The only thing left to do is add the field in the beer list form to add the beer id.

That I need help with.

**Comment by thadius856** [comment]
K, writing this up for you now.

**Comment by thadius856** [comment]
In `admin/beer_form.php` line 134, add:

```
            <tr>
                <td>
                    <b>BLAH BLAH BLAH BLAH:</b>
                </td>
                <td>
                    <textarea type="text" id="BLAH" class="text-input textarea" style="smallbox" name="BLAH"><?php echo $beer->get_BLAH() ?></textarea>
                </td>
            </tr>
```

Depending on how long you want the box, your options for the style are:
xsmallbox
smallbox
mediumbox
longbox
xlongbox

Repeat for each input box you want. Make sure that BLAH is unique.

In `admin/includes/models/beer.php` line 15, define your new variable:

`private $_BLAH;`

Again, repeat for as many BLAHs as you want.

At line 46, create your new function:

```
    public function get_BLAH(){ return $this->_BLAH; }
    public function set_BLAH($_BLAH){ $this->_BLAH = $_BLAH; }
```

Make sure you get all six BLAH's. They all need to be the identical within those two lines, and they're case-sensitive, so match the rest of the file. ...and repeat for each BLAH.

At line 125, add your if statement:

```
        if( isset($postArr['BLAH']) )
            $this->set_BLAH($postArr['BLAH']);
        else
            $this->set_BLAH(null);
```

Note, this assumes you have it set to NULL in the schema (optional field).

**Comment by JayUnt** [comment]
Yes, make sure it's muscle in the database. This should not be a required
field.

Another cool feature we should add, now that we have the untappd beer id.
Add an optional column that will show a qr code that is a link to the
untappd beer page. I looked it up and untappd supports this. So you can
scan the code on your phone and it will open untappd directly to the beer,
so you can check it in.

We would just need a way to make the code. I think there is a php library
that can do it for us. I can look for the qr stuff if you can't find it.  I
think I even added it to an issue way back.

**Comment by JayUnt** [comment]
Oh and make sure BLAH is following the same case convention add the other
properties. Thad just made then all caps so it's easier the find all
instances.

**Comment by mcangeli** [comment]
Ok, I think this can be closed. Its in the version I created the merge request for today to the development branch.

It has the front and admin sections complete and working on it.

**Comment by Skemp45** [comment]
Closing
