### ISSUE TITLE
Alphabetize Beers List in tap_form Dropdown List

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#77]
A list ordered by beerId will quickly become unmanagable as it grows past 10-20 beers.

![untitled](https://f.cloud.github.com/assets/6320180/2047359/5cbaa84c-8a1b-11e3-89b1-2598f9d3dfff.png)

This list should really be sorted alpha.

**Comment by JayUnt** [comment]
Committed. I also ordered the kegs, keg statuses and keg types

**Comment by thadius856** [comment]
Closing as completed.
