### ISSUE TITLE
Turn beer.style into beerType

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#78]
Add new table for beerType. Update beer table to have FK to new beerType table instead of a style free text.

**Comment by JayUnt** [comment]
i created a beerType table and added the values that we talked about in #69.

I update the test_data.sql to use the new beerTypeId, but i just gave them all id 1.  If someone want to update the test_data to be real data, go for it.

Can someone confirm it all works and then close out this issue?

Thanks

**Comment by thadius856** [comment]
Style vs type. Hrm.

"Style" seels more appropriate, doesn't it? When we add BeerXML later, they
also use style.

Type feels like... ale vs lager. Or even traditional vs non-alcoholic.

No?

**Comment by JayUnt** [comment]
I can change it. I did type because we have kegType.  No problem.

**Comment by JayUnt** [comment]
done and done.
