### ISSUE TITLE
Do we care about keg status?

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#79]
Do we want to make make it so the users have to update their keg's status in order to us it in the taps?  The problem i see is that as of now, it is possible for all of the person's taps to be using the same keg.  

Do we want the tap form to limit the kegs in that dropdown to anything that is not SERVING? 

I updated the code so that when a keg is tapped we change it to SERVING and when its kicked we changed it to NEEDS_CLEANING.  So if ppl dont want to manually change the keg's status, it will still work fine.

Thoughts?

**Comment by thadius856** [comment]
> Do we want to make make it so the users have to update their keg's status in order to us it in the taps? The problem i see is that as of now, it is possible for all of the person's taps to be using the same keg.

Can you be more specific? I'm not sure what you're tasking.

> Do we want the tap form to limit the kegs in that dropdown to anything that is not SERVING?

Probably shouldn't be dirty, flooded, or broken either. They don't make a whole lot of sense as choices.

> I updated the code so that when a keg is tapped we change it to SERVING and when its kicked we changed it to NEEDS_CLEANING. So if ppl dont want to manually change the keg's status, it will still work fine.

Cool! :)

**Comment by JayUnt** [comment]
Right now when you create a tap, we dont take the kegs that are already tapped out of the dropdown.  So i can tap 3 beers with the same keg.  Which isnt physically possible.  But do we care enough to prevent this?  Should we leave it on the user to know that they selected the same 3 times.  If we take all of the SERVING kegs out of the dropdown, this will take care of that, except for the test_data that is, since we always choose the first keg.

So we want to take SERVING, BROKEN and FLOODED out of the dropdown list?  I can do that.

**Comment by thadius856** [comment]
Oh. Sure you can hook a keg to multiple taps. Just use a Tee or Wye in the line.

I'm guessing bars do this. I can't imagine their 5 Budweiser taps all go to different kegs.

**Comment by JayUnt** [comment]
So we don't want to take SERVING kegs out if the tap form, keg dropdown?

**Comment by thadius856** [comment]
Well, I suppose they'd only list a beer once on their taplist, regardless of how many taps they had it on. So, sure, why not. Remove away.

**Comment by JayUnt** [comment]
I was referring to the physical kegs, not beers. I think beers can be
multiple because you can fill two kegs with the same beer. But if you think
people have 2 taps hooked up to 1 keg, we don't have to take that keg out
of the tap form if it's already on use.

I figured it would make the keg list shorter, to take them out.

**Comment by thadius856** [comment]
Two taps on a single keg is probably unlikely at home. But even if you did so in a bar, the taplist is for the benefit of the customer, not the bartender.

**Comment by JayUnt** [comment]
So for a home keezer its unlikely, so we can take it out. And for a bar the customer doesnt care about the actual number of taps with the same beer, they just care about what beers they can get.  So we can take it out for bar sake too.

So the consensus is that we can take kegs off the list if they are SERVING. Right? or just forget i ever said anything and let them put the same keg on multiple taps?

**Comment by thadius856** [comment]
Yes, take kegs off the list if they are serving.

I'm agreeing with you here. :P

**Comment by JayUnt** [comment]
yeah, i knew you were agreeing but then i started to convince myself it wasn't needed.  But i did it anyway.  commit b4917ce

**Comment by JayUnt** [comment]
Do you know of any other coding issues i should work on? I looked through the issues and only saw ones for the website FAQ, and the install scripts (which mtnbound is working on) and whatnot.

Issues #53, #77, #78 and #79 are all ready for testing/closing.  But other than fixing any bugs that pop up with those, I think I might be done for this release.

**Comment by thadius856** [comment]
If you want things to do, of course I can find some more. ;) If you're
tired, enjoy some well deserved rest.

I have planned today to dig thru what you've done to try to understand the
logic and conditional loops better.

**Comment by JayUnt** [comment]
Sounds good. I think with what we have planned for the first release, I'm
good. If you need me to clarify anything for you, key me know.

I just got a side project to work on. So I'll spend more time in that, so I
can order up my pi and sensors and all the fun stuff.

**Comment by Skemp45** [comment]
I would like to take a second to say great work everyone. It is rare that a few strangers can come together and selflessly work together to create something like this. It's been a blast working with you all.

**Comment by JayUnt** [comment]
I'll cheers to that. Good job everyone. This is a fun project and I just
see it getting better.

**Comment by thadius856** [comment]
Sure is getting better. Working on some edits myself right meow. :)

While most of the coding is done (good job, guys!), it's now time for our testers to go find bugs and our documentation guys (including me) to get writing content.

**Comment by Boombrewer** [comment]
Truly nice work gents. Looks great and it's super high quality for any paid product let alone a free one. I'll do my best to break it and find the bugs but something tells me there won't be many. 

Cheers!

**Comment by thadius856** [comment]
See 360979e54e80bc930e43e5d1a6a6fa5f736a80c6.

Changed "Broken" to "Needs Parts". Added "Needs Repairs" and "Dry Hopping".
Removed "Needs Repairs" and "Flooded" and "Sanitized" from Tap a Keg list.
