### ISSUE TITLE
Design Mobile Layout

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#8]
A mobile layout is required.

Specific requests:
- [ ] Be prepared to re-apply the diff should I overwrite the master while cleaning up the GitMess.
- [ ] Provide a 'Full version' or 'Desktop version' or similar link to override mobile layout.
- [ ] Use new fork.

**Comment by thadius856** [comment]
Why closed?

**Comment by JayUnt** [comment]
sorry about that. didn't mean to close it.

**Comment by thadius856** [comment]
Adding mobile layout as a feature request for version 3.0.0+. Closing this issue.
