### ISSUE TITLE
Keg List page sorts incorrectly

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#80]
On the Kegs List page, we currently have odd sorting:

```
1
10
11
12
...
2
20
21
...
3
4
...
```

I looked around for ways to fix this sorting, but couldn't find what I was looking for. Probably because I don't know the term for this.

**Comment by JayUnt** [comment]
This is because those numbers are the labels of the keg and are stirrings.
So the sort is an alphanumeric sort and "10" comes before "2".

It's really a problem with the test data. When you create a keg and make
the keg's label "converted pin lock with green handles", it will look right.

And just to let you know, the label and id are different, but the test data
has them the same.

**Comment by thadius856** [comment]
Hrm. Figured this was probably the case.

Looks like the easy fix is to make column `label` datatype `int(11)`.

**Comment by thadius856** [comment]
Yep. Tested, works. Will push correction to the schema with next commit.

Was trying to give people the option to label `A, b, c` or even `α, β, γ`, but oh wells. Not worth it.

**Comment by JayUnt** [comment]
I don't think we want that. We really want to fix the test_data.sql to have
real names for the kegs. With the release we probably won't be giving them
that test_data.sql so it doesn't matter too much. Which in why I didn't fix
it.

**Comment by JayUnt** [comment]
Label is more like a description for the keg.

**Comment by thadius856** [comment]
Oh.

When I created the label field, I meant it to hold the value of what you sharpied or stickered on the keg.

Is there a better name for this?

**Comment by JayUnt** [comment]
Thats what i thought about it too. But you are making the assumption that they are going to mark all of their kegs with numbers.  What if i wanted to make my kegs after the X-Men?  THats why i thought label would be text and not int.

**Comment by JayUnt** [comment]
We could output the keg's id and change label to description if you want.  the id is def an it, but it will be automatically generated by us, which could be a negative.

**Comment by thadius856** [comment]
Right, the ID only works for keg numbers if they're entered in the exact sequence you label them. And then never retire or replace one.

**Comment by thadius856** [comment]
And if you wanted to label your kegs with X-Men, why not just put that in the `notes` column?

**Comment by JayUnt** [comment]
Ok so label is like a user's id for the keg, which would be different then our internal.  You think if they have a keg retire, the will give its label to another keg?

My thoughts was to give the keg a label of "Wolverine" but then in the notes do the green handle thing, like is in the test_data.  I actually forgot there was a notes column when i gave the "converted pin lock with green handles" label example.

I thinking making the label an int is limiting what the user can do, but it really does make the most sense that the label will be int.  Ill change the keg form to validate that it will be an int.

**Comment by thadius856** [comment]
I've already made the changes, don't bother. I'll commit... soooooon. :)

**Comment by thadius856** [comment]
Wait... keg_form? Nvm, haven't dove into that pool just yet.

**Comment by JayUnt** [comment]
haha its all good.  Its just updating some js.  you can look at the change
that i made with my commit.

Do we want to change the name from label to something that is more number
oriented, like id (even though that could get confusing for us).  label
number? or something like that?

On Sat, Feb 1, 2014 at 4:14 PM, thadius856 notifications@github.com wrote:

> I've already made the changes, don't bother. I'll commit... soooooon. :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/80#issuecomment-33883646
> .

## 

Jason Unterman

On Sat, Feb 1, 2014 at 4:15 PM, thadius856 notifications@github.com wrote:

> Wait... keg_form? Nvm, haven't dove into that pool just yet.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/80#issuecomment-33883665
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Don't want to confuse us. Maybe keep it label on the back-end, and if
somebody complains it's confusing at release, we can just change the
keg_list table header and keg_form field.

**Comment by JayUnt** [comment]
works for me

On Sat, Feb 1, 2014 at 4:20 PM, thadius856 notifications@github.com wrote:

> Don't want to confuse us. Maybe keep it label on the back-end, and if
> somebody complains it's confusing at release, we can just change the
> keg_list table header and keg_form field.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/80#issuecomment-33883771
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
Closing as fixed.
