### ISSUE TITLE
4K option missing

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#82]
Did we remove the option to enable and disable support for 4k monitors for a reason?
Are we waiting to have this option on a later release?

**Comment by thadius856** [comment]
Huh. No, it was definitely there.

Is it missing from the config page or index or both?

**Comment by thadius856** [comment]
I see the option on personalize.php. Turning it on, it appears that it works.

**Comment by Skemp45** [comment]
I redownloaded this morning and its not there humm just seems the option was removed from the personalize page

**Comment by thadius856** [comment]
I'm looking at Commit #265, and it's still there (lines 51-57).

```
<?php
    foreach($result as $row) {
    echo '<h3>' . $row['displayName'] . ":" . '</h3>' . 
        'On<input type="radio" ' . ($row['configValue']?'checked':'') . ' name="' . str_replace(' ','',$row['id']) . '" value="1">' .
        'Off<input type="radio" ' . (!$row['configValue']?'checked':'') . ' name="' . str_replace(' ','',$row['id']) . '" value="0"><br>' .
        '<br>';
} ?>
```

If you're not seeing it, then you're probably missing the `config` table value.

Just confirmed it's still in the schema:

```
INSERT INTO `config` ( configName, configValue, displayName, createdDate, modifiedDate ) VALUES ( 'useHighResolution', '0', '4k Monitor Support', NOW(), NOW() );
```

**Comment by Skemp45** [comment]
I have all of it in the config table and the for each relies on the configp.php where it is told to 

```
$stmt = $conn->prepare('SELECT * FROM config WHERE id <= 6');
```

**Comment by thadius856** [comment]
Ohhhhh, I see then. Version was added, and it's now id 1, which makes your useHighResolution id 7.

Fixing now. Gimme a sec to commit.

**Comment by Skemp45** [comment]
and the problem is when Version was added it was set to id of 1 so kicking useHighResolution to id 7 so now version is set with an on and off section. so I need to change it

**Comment by Skemp45** [comment]
lol Yep

**Comment by thadius856** [comment]
Fix is committed. See above.

**Comment by mtnbound** [comment]
Just as a quick comment, if we're using a name value pair table for the config, we should probably be selecting it in code with the name rather than an id.

**Comment by thadius856** [comment]
Agreed. Unfortunately, I'm not sure I can make that change with my current skill set.
