### ISSUE TITLE
Frontend is pulling logo from admin/img/logo.png

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#84]
Attempted to change the front-page logo.

Changed img/logo.png.
Refreshed.
Nothing changes.

Turns out, it's pulling from admin/img/logo.png. Looking at the PHP, it's clearly pulling from the `config` table.

```
INSERT INTO `config` ( configName, configValue, displayName, createdDate, modifiedDate ) VALUES ( 'logoUrl', 'admin/img/logo.png', 'Logo Url', NOW(), NOW() );
```

Skemp: If I fix this, is it going to break your admin panel?

**Comment by Skemp45** [comment]
yeah so I figured they should have the same logo for both admin and front end no need to have 2 diffrent ones

**Comment by Skemp45** [comment]
logoUrl is whats in the config table telling it where the url is. I can create another form for them to change the front end logo also and we can store it as fosLogoUrl or something

**Comment by thadius856** [comment]
How about we change the existing `logoUrl` to point to img/logo.png, and append a new `adminLogoUrl`?

It does make sense to have two different logos, since the backgrounds are different colors. Joe may not understand how to work with PNG transparency. It might be easier for him to make 2 versions with solid bg colors.

Edit: They're also different shapes/sizes, so it makes even more sense.

**Comment by Skemp45** [comment]
Ok this is done I will commit

**Comment by thadius856** [comment]
Wow. Are you manually updating files using the website?

**Comment by Skemp45** [comment]
Yeah..... I am at work :\ :-1:

**Comment by thadius856** [comment]
Ohhhhhh.

Welp, we broke something. Frontend isn't loading anymore. :\ Blank page, doesn't even let me view source.

**Comment by Skemp45** [comment]
Checking

**Comment by Skemp45** [comment]
I see the config files are no longer in includes and /admin/includes are yours therE?

**Comment by Skemp45** [comment]
there was a error in the schema When I changed it I fixed this. then deleted my whole install redoanloaded and installed and everything worked.

**Comment by Skemp45** [comment]
This has been fixed can we close?

**Comment by thadius856** [comment]
Testing. Sec.

**Comment by thadius856** [comment]
> I see the config files are no longer in includes and /admin/includes are yours therE?

Ah, you just jogged my memory.

We made them auto-generate from install, so we removed them from the repo.

Everything looks great. Sorry, was just me being boneheaded.

**Comment by Skemp45** [comment]
No problem I was worried myself like WHAT DID I DO haha.

**Comment by thadius856** [comment]
Me too! :P
