### ISSUE TITLE
How To: Working with TortoiseGit

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#85]
**PART 1: CLONING A REPOSITORY**

So you want to edit your branch easily using the Windows GUI and your favorite flavor of text editor. But how? Here's how.

Install TortoiseGit. You'll probably need to reboot after to get the shell extensions to update.

Create a new folder where ever you like, name it whatever you like. I prefer mine on my Desktop, named "var www".

![untitled](https://f.cloud.github.com/assets/6320180/2060870/510b1354-8c34-11e3-94b3-c8b18fcde2cb.png)

Right click the folder, select Git Clone.

![untitled](https://f.cloud.github.com/assets/6320180/2060872/8aa56bbe-8c34-11e3-8d30-21396580d379.png)

Copy the `URL:` field to match what I have in the picture. (You do not need Contributor permissions to the master branch to do this.)

If you want multiple repositories or branches in a single folder, leave the `Directory:` field as-is. I prefer a separate desktop folder for each repo, so I'll be deleting the text within the red box. Click Ok when done.

![untitled](https://f.cloud.github.com/assets/6320180/2060888/540b8a06-8c35-11e3-8647-942e01d9b707.png)

The repository downloads.

![untitled](https://f.cloud.github.com/assets/6320180/2060881/ffb541e0-8c34-11e3-86af-f50030d214d7.png)

If you get "Checking connectivity... done. Success", then it was successful. If you get "did not exit cleanly (error 1)", then you're lacking write permissions to the folder. Fix it and re-attempt the Clone step.

![untitled](https://f.cloud.github.com/assets/6320180/2060884/2a04c0d8-8c35-11e3-9a85-2637dc5772c2.png)

We can see that the folder now has files, and the green checkmark indicates that there have been no changes to the repository since you last committed.

![untitled](https://f.cloud.github.com/assets/6320180/2060890/964bbd78-8c35-11e3-8a5d-5efe1d6caf49.png)

And opening the folder, we can see that there are files inside. Clearly, the files you see will be different.

![untitled](https://f.cloud.github.com/assets/6320180/2060893/b98369a8-8c35-11e3-87f2-a3ca436e0b48.png)

_This concludes Part 1, Cloning a Repository. Stay tuned for Part 2._

**Comment by thadius856** [comment]
**PART 2: BRANCHING A REPOSITORY, COMMITTING, AND PUSHING**

_Note: Branching is limited to users with Contributor-level access to the GitHub project. There should be no more than a handful of highly trusted users with this access level. Users without this permission should use Forks instead, which will be covered in a later part._

All edits are applied to a branch of a repository. The default branch is `master`, which is like the trunk of the tree. Branches are splits off of the `master`; they may be identical to the master or they may have differences from the master. Branches can even be created from other branches, ad infinitum.

On small projects with few contributors, it's fine to edit the `master` directly. On projects with a reasonable amount of contributors and production releases (such as this one), it's extremely poor form to do so. We'll create a branch in this tutorial so we can make edits without disturbing other contributors.

We cloned the master branch in Part 1. Now we'll create a new branch, `test123`.

Right click your repository folder, and select `TortoiseGit` > `Create Branch`.

![untitled](https://f.cloud.github.com/assets/6320180/2060917/407a1b36-8c37-11e3-87eb-bbfdd33ebc7b.png)

Enter the name you want to give the branch in the `Branch:` field. Click 'Ok' when done.

![untitled](https://f.cloud.github.com/assets/6320180/2060918/6b580688-8c37-11e3-912a-a87aa64acd11.png)

The branch is now created locally and is identical to the master. However, we're still viewing the `master` branch.. We need to switch to our new branch to be able to view it. Right click the repository, then select `TortoiseGit` > `Switch/Checkout`.

![untitled](https://f.cloud.github.com/assets/6320180/2060921/ac6a1b48-8c37-11e3-9ed8-408a12f17cdc.png)

Select the new branch from the `Branch:` dropdown list, then click Ok.

![untitled](https://f.cloud.github.com/assets/6320180/2060931/ffacd192-8c37-11e3-9ce7-2e2046847d68.png)

TortoiseGit confirms that we've switched branches successfully.

![untitled](https://f.cloud.github.com/assets/6320180/2060932/127fb5d2-8c38-11e3-9e1b-437d379db86c.png)

The files in the repository folder will automatically update to reflect the branch you're working on. Since they're still identical, we won't see a difference just yet. Let's go ahead and make some changes to demonstrate.

Delete `pints.ico` from the folder. The icon updates to let us know we have uncommitted changes.

![untitled](https://f.cloud.github.com/assets/6320180/2060998/907f7df2-8c3b-11e3-941e-91d6e9b52993.png)

Now we'll tell TortoiseGit that we want to commit the changes and apply a commit number. Right click the repository, then select `Git Commit -> "test123"`. 

![untitled](https://f.cloud.github.com/assets/6320180/2060999/b2d42164-8c3b-11e3-94d7-f907361248c0.png)

TortoiseGit shows us the changes we've made in the bottom pane. We can see that it recognizes we deleted `pint.ico`. Enter anything into the `Message:` field, then click Ok.

![untitled](https://f.cloud.github.com/assets/6320180/2061003/04e99f2e-8c3c-11e3-9ff2-c3703110b2ab.png)

We have successfully committed our branch. It still only exists locally in Git, so we need to push the new branch and our changes to GitHub's servers. Click the 'Push' button.

![untitled](https://f.cloud.github.com/assets/6320180/2061011/391cc8f2-8c3c-11e3-8a97-d1ff86febfcb.png)

Ensure that our test branch is selected in the `Local:` dropdown menu, then click Ok. When prompted for your GitHub username and password, enter them. TortoiseGit confirms everything completed successfully, and that our local `test123` branch was used to create a remote `test123` branch on GitHub.

![untitled](https://f.cloud.github.com/assets/6320180/2061013/7d0ee626-8c3c-11e3-88f4-f3eeb1d214a5.png)

When we look on GitHub, we can see that the new branch exists and is different from master by 3 commits. Note in the image that we're 1 commit ahead because we deleted pints.ico. We're also 2 commits behind because another user committed the master branch twice while I was creating this tutorial.

![untitled](https://f.cloud.github.com/assets/6320180/2061015/afeb3edc-8c3c-11e3-90a5-005e6841dedd.png)

**Update:** Please see #121 for more information on the branch scheme we use before creating new branches.

_This concludes Part 2, Branching a Repository, Committing, and Pushing. Stay tuned for Part 3._

**Comment by thadius856** [comment]
**PART 3: PULLING CHANGES TO A REPOSITORY**

It's important to understand the difference between local and remote repositories. A local repository is one that exists on a workstation. A remote repository is one that exists on GitHub or other collaboration server. In most cases, every repository will have one remote (on the server) and several locals (on each contributor's computer).

If Joe makes a commit to his local repository, then pushes it to the remote repository, our local repository is now out of date. If Joe pushed 2 commits, we're behind by two commits. So how do we get our local back in sync?

We Pull. Pulling grabs all new commits from a remote and applies the changes to our local. Right click the repository, then click `TortoiseGit` > `Pull`.

![untitled](https://f.cloud.github.com/assets/6320180/2061066/1d4a4e66-8c40-11e3-9eec-84f4c0dda865.png)

The Pull dialog appears. In the `Branch:` dropdown menu, select the branch you want to Pull changes to. We want to ensure the `Remote:` dropdown menu is set to `origin`, which is shorthand for "whatever server you originally cloned it from". ;)

![untitled](https://f.cloud.github.com/assets/6320180/2061070/452f25dc-8c40-11e3-9750-5acff339888e.png)

Any changes are pulled down and applied. The window shows you details of what files were updated. In this image, there's no changes as I'm already up-to-date.

![untitled](https://f.cloud.github.com/assets/6320180/2061076/737fd918-8c40-11e3-9b72-6ae9a50f8c9e.png)

It's a best practice to Pull before you Push to GitHub so that you don't accidentally overwrite previous contributors' code. Your workflow should generally look like:

`Make your edits` -> `Commit` -> `Pull` -> `Push`

In fact, most times, Git will check for newer versions when you attempt to Push as a failsafe. If you haven't already Pulled them down and addressed them, the Push will fail out. More on that in the next part.

_This concludes Part 3, Pulling Changes to a Repository. Stay tuned for Part 4._

**Comment by thadius856** [comment]
**PART 4: REVIEWING DIFFS AND RESOLVING CONFLICTS**

You can view the `Diff` or difference between what you have now and the last commit made by right-clicking the respository, then selecting `TortoiseGit` > `Diff`.

![untitled](https://f.cloud.github.com/assets/6320180/2061083/3b9f339e-8c41-11e3-98a4-e441224661cc.png)

Since I have no changes, I've selected `TortoiseGit` > `Diff from previous version` instead to show the difference between the current commit and the previous commit.

![untitled](https://f.cloud.github.com/assets/6320180/2061085/5e4572aa-8c41-11e3-8d71-24c83dc27e17.png)

We can see that the previous commit message was `Support to have 2 different logos` and that the SHA hash (version number) of that commit was `a5c93d7f`. Here we can see that the difference is 1 line was added to `sql/schema.sql` and 1 line was also removed from it. This usually means that 1 line was changed -- Git isn't smart enough to understand the difference between deleting/re-adding a line and modifying a line.

Usually know that a file was changed isn't enough. We want to see what the change was. We'll double-click on the `sql/schema.sql` to display the differences in `Working Tree`. If you are a Wikipedia editor, this may look familiar. We can see that the number `10` was changed to the number `0` in this edit.

![untitled](https://f.cloud.github.com/assets/6320180/2061108/f6fa2c02-8c41-11e3-9016-407c9d0f271b.png)

If you were notified of a conflict during a Pull or a Push, you'd be presented with the opportunity to manually review the changes in `Working Tree`, just like we are now.

For example, if Joe edited `sql/schema.sql` and pushed it to the server, then I edited the same file locally before pulling down his changes, we now have a conflict because the changes did not occur in a linearly. Git doesn't know which version is the correct one because it relies on a linear timeline, so it'll prompt you to choose which edits should be kept and which should be discarded.

When I right-click Joe's version (the left half of the screen), I get this dialog:

![untitled](https://f.cloud.github.com/assets/6320180/2061122/b1275686-8c42-11e3-972a-60a79401fbd2.png)

If I select `Use this text block`, I'm telling Git that Joe's version is the correct one. The same can be done when right-clicking my version (the right half of the screen). Selecting `Use this whole file` would tell Git that the entire file Joe worked on is better and to discard all of my changes. Or we can do the same for my version.

You typically won't select `Use both text blocks (this one first)` or `Use both text blocks (this one last)`, because that would be telling Git that you want to keep both lines of code one after the other, and you're specifying which order you want them to appear in.

If you were only viewing a `Diff` for fun, you can simply close the `Working Tree` window at any time.

If you were correcting conflicts, you should click the `Save` button once all conflicts are resolved, then you may close the window. You'll need to Commit for your changes to be reflected, at which point you can safely reattempt the Push or Pull. If you missed any conflicts, you'll be presented with them again and asked to repeat the process for those that you missed.

_This concludes Part 4, Reviewing Diffs and Resolving Conflicts. Stay tuned for Part 5._

**Comment by thadius856** [comment]
**PART 5: MERGING BRANCHES USING PULL REQUESTS**

Up until now, you've been editing your own branch. But what happens when you're done making changes on your branch? You create a Pull Request. A Pull Request is essentially presenting your changes to a Contributor for review and asking that they be added to (typically) the `master` branch. I personally think Merge Request` would have been a more apt name, but I wasn't asked when Git was written. ;)

You can create a Pull Request from the confirmation window after successfully Pushing. However, it's also very easy to use GitHub's interface to accomplish this.

To create a Pull Request, first visit the page of the `master` branch.

![untitled](https://f.cloud.github.com/assets/6320180/2061302/dcbe5ea4-8c4a-11e3-9016-f410528f78f1.png)

If you do not have Contributor permissions (likely you don't), you will not see the green buttons -- this is perfectly normal. Pull down the `branch` dialog box and select your branch.

![untitled](https://f.cloud.github.com/assets/6320180/2061296/a6d9d606-8c4a-11e3-9c33-0d08bc5d247f.png)

Notice that the `branch` dialog updates.

![untitled](https://f.cloud.github.com/assets/6320180/2061288/86d9b556-8c4a-11e3-916b-d68cbc6aa1fd.png)

Click the `Pull Request` button.

![untitled](https://f.cloud.github.com/assets/6320180/2061304/025a850c-8c4b-11e3-9b3b-04c92d93f191.png)

Enter a _descriptive_ summary of the changes, then click `Send pull request`. If the button is greyed out, you either have unaddressed conflicts, or you're forgotten to Commit & Push after fixing them.

![untitled](https://f.cloud.github.com/assets/6320180/2061327/1a5deb98-8c4c-11e3-978a-a84d8c83748b.png)

This is what the reviewing Contributor will see. We'll browse the commits, check out your changes, and add comments as necessary.

![untitled](https://f.cloud.github.com/assets/6320180/2061330/3b46d680-8c4c-11e3-94e4-b80da0fcb85e.png)

Once the Contributor is happy with what they see, they will click `Merge pull request` and your changes will be applied to the master. The Contributor may have you make several Commits to get everything where we need it to be. Please be patient and responsive.

_This concludes Part 5, Merging Branches Using Pull Requests_.

**Comment by Skemp45** [comment]
closing and linking to in wiki page
