### ISSUE TITLE
Test Data still in Tap List drop down

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#87]
So if the test data is loaded and then all the beers are inactivated, they still show up in the beer drop down on the Tap List page.

**Comment by thadius856** [comment]
Innnnnnteresting. Looking now.

**Comment by thadius856** [comment]
Yeeeep. This is way above me.

**Comment by mtnbound** [comment]
I'll take a look after the game.

Sent from Yahoo Mail on Android

**Comment by thadius856** [comment]
Also, when I put a keg on tap, it doesn't set it as SERVING, so I can put the same keg on tap multiple times.

**Comment by JayUnt** [comment]
You should make a bug for that last one Thad

**Comment by thadius856** [comment]
Tested. This bug looks quashed. Closing.
