### ISSUE TITLE
Admin Panel Login Page - Gain Focus

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#89]
The admin panel login page currently does not request focus of the cursor on page load.

It should attempt to place the cursor in the username box, as that's what the user is going to do 99% of the time anyway.

**Comment by Skemp45** [comment]
autofocus="autofocus"

DONE

**Comment by thadius856** [comment]
![download](https://f.cloud.github.com/assets/6320180/2065244/c1054a18-8cdd-11e3-987d-facb7a8a6d59.jpg)

Closing as completed then.
