### ISSUE TITLE
Editing a tap, the tap's keg is not in the list

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#91]
When you update a tap's info, its previously selected keg is not in the keg dropdown.  This is because the keg's status is SERVING.  We need to add the current keg item to the list of available.

I will work on it, but i just wanted to track this.  I also just did a sync and got the install stuff, so i have to run through that to get my site working.

**Comment by Boombrewer** [comment]
I thought we were changing the 'available' kegs to not be dependent on its status? If I'm behind on conversation please disregard.

**Comment by JayUnt** [comment]
I think the idea was that we would prevent broken and serving would be taken out, but the rest would stay in.  If we don't take any out, this bug would be fixed.  But if its already in use with another tap, it would be cleaner to take it out of the list, especially if you have a bunch of kegs.

**Comment by thadius856** [comment]
> But if its already in use with another tap, it would be cleaner to take it out of the list, especially if you have a bunch of kegs.

Agreed.
