### ISSUE TITLE
My Beers Page

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#93]
Where is this info being pulled from and when was this added, I missed something!!!!!
Yeast/Water/etc Hop Additions
Aloha Morning

Light Lager
(BJCP 1A - Light Lager)

Yeast: Fermentis S-04
Water: Sacramento, CA
More: Info Here...
More: Info Here...
1.42 oz Northern Brewer (6.8%) @ 60 min
2.14 oz Nelson Sauvin (9.1%) @ 30 min
2.41 oz Columbus/Tomahawk (8.6%) @ 15 min
1.24 oz East Kent Goldings (2.1%) @ 0 min

**Comment by Skemp45** [comment]
![ing](https://f.cloud.github.com/assets/6318869/2076577/efbc62a2-8da4-11e3-8129-75c5bcd54d38.png)

**Comment by thadius856** [comment]
Test data for layout design. Not being pulled from anywhere -- hardcover
while I style.

**Comment by Skemp45** [comment]
AHH ok, that will be in 2.0 not 1.0 right?

**Comment by thadius856** [comment]
Ill prolly write the pho now, with if statements to hide if null so nobody
will see them anyway

**Comment by Skemp45** [comment]
cool

**Comment by Skemp45** [comment]
Closing
