### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#96]
So I saw it mentioned on here and people are asking for it on homebrewtalk, 

whats the plan for this, I say we make a decision on it and stick with it but thoughts??? It would help for paying for needed domain hosting and emails as well as development for future add ons and testing

**Comment by thadius856** [comment]
WTH. Why am I no longer getting any email updates from HBT? Gahhhh...

I'll ask a mod if that's cool if our website has a donate button AND we link to the front page from HBT.

**Comment by thadius856** [comment]
If so, what did the domain cost you? How much is the hosting? Do you have any other cash outlays yet?

**Comment by Skemp45** [comment]
Domain is $8 a year with my discount... dont ask and hosting costs me $25 a year and email is just part of another plan I have so I would pay for it anyways.

**Comment by Skemp45** [comment]
I can also include the donate button in the email blasts I send out

**Comment by Skemp45** [comment]
just about 60 subscribers now

**Comment by thadius856** [comment]
Sent TxBrew a PM. We'll see what he says.

**Comment by thadius856** [comment]
Oops.

**Comment by Skemp45** [comment]
;) let me know and get me the code from the paypal account so I can add it to the coming soon. Also if you can write up a email giving people the url for the hardware so they can get it early and I w ill add the donate button there too

**Comment by kerber** [comment]
I'd rather leave off the hardware for flow monitoring at this point. We still haven't nailed that part of it down.

**Comment by thadius856** [comment]
Yeah, I was going to leave it at "test equipment" or somesuch.

**Comment by kerber** [comment]
Perfect :)

**Comment by thadius856** [comment]
Closing.

Final ruling from TxBrew was we cannot have a donate button on our website if we want any meaningful presence on HBT.
