### ISSUE TITLE
Install Script Errors

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#98]
![screen shot 2014-02-04 at 10 24 49 pm](https://f.cloud.github.com/assets/6321429/2084735/8076f8d2-8e2e-11e3-8d89-a2e115f140e5.png)

Nuked my install - deleted all files.  Got the above when I did my 'fresh' install.  Front page (index) doesn't load.  Admin page loads but goes to blank nothing when I log in using my admin account. (address bar hangs on /admin/includes/checklogin.php)

Is this operator error or a bug?

**Comment by mtnbound** [comment]
There is a new step in the instructions right after copying all your files to the Pi, to change permissions on the folders /includes and /admin/includes folders to 777.

I'll put a pre processing check into the scripts today to check the permissions before trying to run, and if it fails to write some instructions to the screen.

**Comment by thadius856** [comment]
If you're going to add `chmod 777`, you may as well add `chown pi:pi`.

777 scares me when public-facing. Does 755 work? Something less?

**Comment by mtnbound** [comment]
I agree with reducing 777. I was going to experiment with reducing the permissions, but just haven't had time, unless one of our testers wants to take a look at the lowest security permissions for those folders.

**Comment by Boombrewer** [comment]
I'll try adjusting the permissions again.  I had already done that on the previous install and since I was just deleting the files inside that folder I didn't think it would change the folder permissions.  I'll toy with it later to see if it helps.

Thanks guys.  If you want, I can toy around with lower levels of permissions (755 and whatever other codes you send me).  But I won't be able to do it till after work today.

**Comment by thadius856** [comment]
Us developing on Windows (NTFS) for a Debian product (XFS) probably doesn't
help.

But I sure as hell aint doing all my coding directly on the Pi! :P

**Comment by Boombrewer** [comment]
ran the change permission (line below) and also deleted and re-transferred all the files.
sudo chmod 777 /var/www
Now I get the following:
![image](https://f.cloud.github.com/assets/6321429/2095599/bfadb66e-8eea-11e3-983c-7c66dfb58187.png)
I was going to run through the config steps again but the website won't navigate away from the Preparation page.  What am I missing here?

**Comment by thadius856** [comment]
You're missing the proper command.

`sudo chmod 777 /var/www` changes the permissions of that folder (/var/www) only.

You want `sudo chmod -R 777 /var/www` so it recurses.

**Comment by Boombrewer** [comment]
Did I need a reboot after that?  Because now I got:
![image](https://f.cloud.github.com/assets/6321429/2095642/d1632794-8eeb-11e3-9bd1-e9c93b8fa778.png)

I'm about to just nuke the whole thing and start over with a fresh OS.  So frustrating!

**Comment by thadius856** [comment]
Hehe no. You don't need to reboot.

If an install fails, you need to drop db raspberrypints before you try again.

Otherwise, you get conflicting data and... that error.

**Comment by mtnbound** [comment]
I added a check in the install scripts earlier today that checks for proper permissions before it even starts. If you don't have the right permissions, it fails with an error message about why.

Pushed to the install branch.

**Comment by thadius856** [comment]
See, that's what I'm talkin' bout! Unnnhhhhh.

**Comment by mtnbound** [comment]
BTW Boom: Welcome to beta (actually Alpha really) testing :)

Thanks for helping though!! Would have never added that check without you testing it.

**Comment by thadius856** [comment]
Merged `Install` back into `master` to take advantage of those checks.

83ba0416b91a1f84d6b28f82dc2cea9aec954945

**Comment by Boombrewer** [comment]
yeah, being a guinea pig isn't always fun.  How's the latest repository?  I was gonna download the full zip and try the newest stuff since I was deep inside gutting everything....

**Comment by thadius856** [comment]
Blowing away and re-installing now. Will let ya know in a minute.

**Comment by thadius856** [comment]
```
Validating Entries...Success!
Checking DB connectivity...Success!
Checking config folder permissions...Success!

Cannot write the configuration files. Please check the /includes/ folder permissions. See the RPints Installation page on www.raspberrypints.com.
Cannot write the configuration files. Please check the /admin/includes/ folder permissions. See the RPints Installation page on www.raspberrypints.com.

Please press the back button on your browser to fix these errors
```

That's a good sign.

**Comment by thadius856** [comment]
Looks really good, except for the unicode bug I just opened.

**Comment by Boombrewer** [comment]
![image](https://f.cloud.github.com/assets/6321429/2095729/a68249bc-8eee-11e3-83de-c6631aa28242.png)
Ok.  I deleted all the files in my /var/www folder.  Rebooted my pi.  Ran the permission code from Thad.  Installed all new files (that Thad just installed).  Got the above errors.  What am I missing?  Does the db raspberrypints get deposited somewhere else besides the /var/www folder?

Thad, I was messing with the .bashrc file trying to get chromium to boot, would something in there be causing this.  I don't think I did anything but add the line for chromium and then delete it but who knows as this point.

**Comment by mtnbound** [comment]
Did you run the permissions command after you copied your code to the Pi, or before? The command should be run after you copy the files.

**Comment by thadius856** [comment]
Nah, has nothing to do with Chromium or `.bashrc`.

If you had all new files, you'd be getting the error I had above. Not the one in the picture.

`sudo rm -R /var/www/*`

Drop the raspberrypints table. Download new zip. Unzip to `/var/www`.

`sudo chmod -R 777 /var/www`

Run install. What happens?

**Comment by Boombrewer** [comment]
![image](https://f.cloud.github.com/assets/6321429/2095807/f6392258-8ef0-11e3-96cb-79a08a70043d.png)
Permissions thing seems to be fixed.  But now I got the above.  Its worth noting that I've been running the install this whole time without checking the box for test data.

**Comment by Boombrewer** [comment]
Everything loads and works fine so far - I just have no data (which is to be expected).  But I didn't get any kind of confirmation or direction.

Am I sensing a new 'bug' for the install code?

BTW, thanks for the help guys.  Sequencing is a bitch.

**Comment by mtnbound** [comment]
No, actually there's a bug in the schema.sql file it looks like. Let me take a look.

**Comment by thadius856** [comment]
I've literally dropped the tables and reloaded it 3 times in the last 20 minutes. No errors over here.

**Comment by mtnbound** [comment]
Yea. I'm going to take that back. I just copied the schema directly from the master branch, and it installed fine.

**Comment by Boombrewer** [comment]
Maybe its just me.  That is a distinct possibility.  If you guys can't replicate it, then I'd say it doesn't really exist.

**Comment by thadius856** [comment]
Sleep on it and try again. Helps more than I'd care to admit.

**Comment by JayUnt** [comment]
Im getting the same error as Boombrewer.  

I'm at a standstill trying to fix bugs because i cant get the site up and running because of this.  I think im going to just try to run everything manually just to get my site up.

**Comment by JayUnt** [comment]
I got past that error by manually deleting my existing raspberrypints db and then running it again. 

I got a different error after that though.  Ill look into that a bit.

```
Validating Entries...Success!
Checking DB connectivity...Success!
Checking config folder permissions...Success!
Update config files...Success!
Update admin config files...Success!
Creating RPints database user...Success!
Running Database Script...
Fatal error: Maximum execution time of 30 seconds exceeded in C:\Projects\GitHub\RaspberryPints\install\includes\configprocessor.php on line 175
```

**Comment by JayUnt** [comment]
Ok well i ran the install again, and this time it had a dropdown on the top about upgrading.  it seemed to work now.

**Comment by thadius856** [comment]
PHP is timing out trying to execute the script.

Need to raise your max time in php.ini.

**Comment by Boombrewer** [comment]
Ok.  I get the same error again.  See below:
![image](https://f.cloud.github.com/assets/6321429/2099737/2875dadc-8f40-11e3-958e-0e7f8790c511.png)

This is how I'm re-creating this: delete everything from /var/www folder.  Unzip and extract new files to the /var/www folder.  Change the permissions on the folder to 777.  Run the install but DO NOT check the text data box.  Which makes sense to be because there isn't any data to run a query on if I'm understanding the code correctly.  Its not really a bug, just some fine tuning for the guys who won't load the test data.  Seems like if statement to skip the queries when the test data box isn't checked and direct them to where raspberry pints is at just like the other install.  The install still works great!

**Comment by mtnbound** [comment]
Can you send me your sql/schema.sql file? Your file has an error somewhere, but I don't get the same issue here. I want to see if it's a version thing or something else. Not sure how you send files in git, but if you need to my email is: sloescher at (the major company with a Y logo) dot com. (Don't want to put my email in a format to be scraped)

**Comment by thadius856** [comment]
Boom,

Your theory that leaving the sample data box unchecked imports no data is
wrong.

It imports ~590 items.

Sample data adds another 25 or so.

**Comment by Boombrewer** [comment]
Well, that's what "Joe" gets for thinking he's learning a little something.

Mtn, I'll send you the file when I get home.

**Comment by thadius856** [comment]
Here, here.

Contstantly reminded while staring at this code every night that I have no
idea what I'm doing.

**Comment by mtnbound** [comment]
Boom,

I just cleared my Pi of all the code, and DB. When I downloaded the latest zip from the master branch, I didn't have any issues installing it.

If you get a chance can you try deleting everything in the var/www directory and dropping the DB. Once it's all cleared, can you download the master branch again just to make sure.

Also, if you get a moment to send your schema file, I can check to see what's failing.

**Comment by thadius856** [comment]
I'm pretty convinced it's a versioning issue. It _has_ to be.

Boom, are you absolutely sure you're not re-installing old versions accidentally? It's really really easy to do.

**Comment by Boombrewer** [comment]
I'm pretty sure I'm not but anything is possible late at night.

You guys keep mentioning dropping the db as well as nuking the /var/www folder.  Is it saved in a different location?

(that might have just explained things for you guys, huh?)

**Comment by thadius856** [comment]
If you're dropping the db and emptying /var/www, then that's all there is.

My concern is that maybe you're FTPing in old files or using an old ZIP or something.

**Comment by mtnbound** [comment]
Boom,

I think we found it. It doesn't sound like your dropping the DB as a part of the clearing process. I have that built into the install scripts, but it needs to see a config file first which you don't have due to the permissions issue. I'll send you the commands to drop the DB manually in just a second.

**Comment by jkurl** [comment]
Thad,

I would like to help be a beta tester. If you got enough no worries.
Basically I am itching to load this up on my pi. It is sitting in my room
all lonely.

Jerry

**Comment by mtnbound** [comment]
From your Pi enter the following:
mysql -uroot -p
Enter your root password

from the mysql> prompt enter:
drop database raspberrypints;

Then "exit" mysql. Delete everything in the /var/www folder and copy the latest files and you should be ready to go

**Comment by thadius856** [comment]
Jerry, create a WordPress account if you don't already have one and post your username here.

**Comment by jkurl** [comment]
Username is klinklotus

Don't ask weird ass name I came up for spore

**Comment by thadius856** [comment]
> Username is klinklotus

Oops, sorry. I need an email addy too.

**Comment by jkurl** [comment]
Klinklotus@gmail.com

**Comment by thadius856** [comment]
Check your email. Set your password. Then visit:

http://raspberrypints.com/site/wp-admin/

Click "Pages". Those are the install instructions, in order.

**Comment by jkurl** [comment]
When I click the link and log in and then go to the site it will not let me
past the preparation page.

**Comment by thadius856** [comment]
Right. Because they're hidden from the public.

Go back to the Pages page. You need to view them one at a time from there.

**Comment by jkurl** [comment]
All I have is dashboard, profile and the ability to visit the site. Not
seeing any pages

**Comment by thadius856** [comment]
Fixed. Try again.

**Comment by jkurl** [comment]
Crap man this is killing me not your fault. For some reason it shows 14
pages in the at a Glance but will not let me click on the nor is it showing
anything on the tool bar in the left side. I can see the faqs. Sorry to be
pain the butt.

**Comment by thadius856** [comment]
No probs. I'm new to this. Try again now.

**Comment by jkurl** [comment]
Ok one step closer I now have media and can see all the images.

**Comment by thadius856** [comment]
Yeesh, ok, now you've got all I have.

Don't mess things up. This is temporary. :P

**Comment by jkurl** [comment]
Awesome thanks Thad. When are you making your way done to Travis next?

**Comment by thadius856** [comment]
Last time was for surgery.

Hopefully next time is to visit AFOSI.

**Comment by thadius856** [comment]
Aaaand, I'm going to call it bedtime. Got a 5k to run at 0645. :runner:

**Comment by jkurl** [comment]
for the install part where you have SFTP in I did it using a mac. wasn't to hard. we could add that to the write and I can even download several different programs to get either a wide variety to use or we can pick one and go with that. the one I used was cyberduck which is in the mac store but costs $23.99.  I will scour the web to find some good free ones to use. cyberduck was pretty easy to use but i don't want people to have to pay $23 for it. let me know what you guys think.

**Comment by Skemp45** [comment]
FileZilla

**Comment by jkurl** [comment]
I saw that when I did a web search but everyone said cyber duck was the
best. I will give FileZilla a try. Do you need me to write something up for
the Mac people?

**Comment by jkurl** [comment]
Holy crap that was easy to use. Thanks Skemp45. Well guess I get to explain
that $23 purschase to the wife.

**Comment by Skemp45** [comment]
Haha yeah!! I tell all my clients to use it. Great program

**Comment by Boombrewer** [comment]
@mtnbound - yep, that fixed it.  And I'm once again reminded I really have no idea what I'm doing...

![image](https://f.cloud.github.com/assets/6321429/2110915/58c2216c-900a-11e3-8e92-6012e4a5ec31.png)

**Comment by mtnbound** [comment]
Great news. I'll close this for now. If you see anything else, feel free to open a new issue.

**Comment by jkurl** [comment]
Boomerbrew,

   did you change the permissions on the folder when you SFTP it to the pi?

Jerry

**Comment by Boombrewer** [comment]
Yeah, that was only one of my problems. Mtn got me straightened out. Working like a champ now. Thanks.
