### ISSUE TITLE
Import BeerXML

### ISSUE THREAD

**Issue by mtnbound** [RaspberryPints/RaspberryPints#99]
Needed to learn PHP XML, so I started working on this, and created a V2 branch.

No major additions yet, just started the framework.

**Comment by thadius856** [comment]
Schweet.

I had planned to update the styles last night, but pushed that back to tonight.

How fortuitous.

**Comment by Skemp45** [comment]
I added a version 2 Label for all issues that are actually dealing with version 2 not the first release.

**Comment by thadius856** [comment]
There's already a Milestone for v2, but you're welcome to use this label if it helps.

**Comment by thadius856** [comment]
Just updated the beerStyles table in preparation for this.

Most data will go unseen by the user for now.

**Comment by mtnbound** [comment]
I'm not sure who wrote the admin screens, but I have a quick question.

I'm in the process of modifying the V2 code and models to support more recipe fields. I understand the basics of what's been done already, and have added additional fields to the beer.php model, and have pushed the new fields down to the screen and DB, so I feel like I understand the basics of the one to one model.

My question is this: Now I want to add a few one to many relationship to the model. For example: One header (OG, Rating, Name, etc), to many fermentables (grain, DME, etc).

Should that be done in the model, or create a new model for the fermentables, and then just link them together in the display code? There will also be a one to many relationship to the hops and misc ingredients as well.

I'm very new to PHP, but it's pretty straightforward to learn, and I've enjoyed the process.

**Comment by thadius856** [comment]
@mtnbound @JayUnt 

I want to add extra columns to `beers` before we lock down the codebase here in a couple days.

The basic stuff is easy. Yeast, water, etc. They're all one-to-one.

But BeerXML's (obviously) extensible nature makes the other ones difficult. There's no limit to how many fermentables, hops, finings, etc. I can have in BeerXM recipe.

Obviously I could create fermentables1, fermentables2, fermentables3, etc. But that seems like a hack.

What's the better way to do this?

**Comment by thadius856** [comment]
> My question is this: Now I want to add a few one to many relationship to the model. For example: One header (OG, Rating, Name, etc), to many fermentables (grain, DME, etc).
> 
> Should that be done in the model, or create a new model for the fermentables, and then just link them together in the display code? There will also be a one to many relationship to the hops and misc ingredients as well.

Damn, you beat me to the same question by 3 days.

**Comment by mtnbound** [comment]
I built a lot of this including the db structure already. I just created new models for fermentables, etc.

I'll upload my code in a few days, when I very back home. Doing brewery tours today.

**Comment by thadius856** [comment]
Cool beans. :)

When you, be sure to make the `develop` branch local, branch of a `feature-xml` branch, put in your files.

Alternatively, if you already have a branch, you can just rebase it to `develop`.

**Comment by JayUnt** [comment]
Sorry, i didnt see my mention in this until now. But it looks like @mtnbound has it covered. nice!

**Comment by thadius856** [comment]
@mtnbound 

Do you expect you'll have the schema changes good-to-go by the codebase lockdown for V1.0.0? Or will the schema be V2.0.0 as well?

**Comment by mtnbound** [comment]
I would wait until V2. It's a very simple upgrade to the DB to support this feature. A couple of new tables, and some new columns. Won't affect any of the current schema.

BTW: I just got back into town, and geez there's been a lot of activity on the project. Looks great! I feel like I missed all kinds of things..

**Comment by thadius856** [comment]
You didn't really.

**Comment by Skemp45** [comment]
Should we postpone this till v3 and focus fully on flowmeters and cleaning up the code a bit for v2?

**Comment by mcangeli** [comment]
Yes.

**Comment by Skemp45** [comment]
Adding v3 tag

**Comment by jksnetwork** [comment]
I wouldn't mind helping out on this.  I have experience with a beerxml wordpress plugin I've contributed to.  The code to parse the beerxml is already there.  It would just be a matter of grabbing what we wanted to store in the DB.
